import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        setTaskFunction(runScreenTask)
        ' Needed to circumvent a Roku bug with callFunc
        m.containerNode = createObject("roSGNode", "Node")
    end sub)
end sub


function runScreenTask(options = {})
    screenVariables = top().screenVariables
    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Screen) %>", variables: screenVariables }, headers: "<%- o(CONFIG.Headers) %>"})

    if rodash.isEmpty(response.text) then return true

    screenModel = returnScreenModel(parseJSON(response.text))

    ' Needed to circumvent a Roku bug with callFunc
    m.containerNode.appendChild(screenModel)

    if rodash.isNode(screenModel)
        publish(events.SCREEN_DATA_RECEIVED, {
            content: m.containerNode
        })
    end if

    return true
end function


function returnScreenModel(options = {})
    data = options.data ?? {}
    screenData = data.screen ?? {}
    ' carouselsData = screenData.carousels ?? []
    ' carouselsData =  [screenData.carousels[3], screenData.carousels[4], screenData.carousels[5]]
    carouselsData =  [screenData.carousels[0]]
    updateObjArray = []

    for each carousel in carouselsData
        carouselModel = createObject("roSGNode", "Collection")
        thumbnailType = carousel.thumbnailType ?? "LANDSCAPE"

        updateObject = {
            carouselTitle: carousel.carouselTitle,
            carouselType: carousel.carouselType,
            documentId: carousel.documentId,
            id: carousel.documentId,
            thumbnailType: thumbnailType
        }

        configKey = thumbnailType = "LANDSCAPE" ? "LandscapeCarousel" : "PortraitCarousel"
        carouselConfig = liveConfig({ field: "config", keyPath: configKey }, carouselModel)

        updateObject.children = []

        ' Load initial carousel items
        ' for loading animation
        for x = 0 to carouselConfig.visibleTiles
            updateObject.children.push({
                description: "",
                hydrated: false,
                logoImageUri: "",
                subtype: "ContentModel",
                thumbnailImageUri: ""
            })
        end for

        carouselModel.update(updateObject, true)

        updateObjArray.push(carouselModel)
    end for

    updateObject = {
        slug: screenData.slug
    }

    model = createObject("roSGNode", "Model")
    model.appendChildren(updateObjArray)
    model.update(updateObject, true)

    return model
end function
