import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        setTaskFunction(runScreenTask)
        ' Needed to circumvent a Roku bug with callFunc
        m.containerNode = createObject("roSGNode", "Node")
    end sub)
end sub


function runScreenTask(options = {})
    options = top().options ?? {}
    if not rodash.isNonEmptyAA(options) then return true

    collection = options.collection
    if not rodash.isNode(collection) then return true

    variables = exec("getVariables", {}, collection)
    if rodash.isEmpty(variables) then return true

    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Screen) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>"})

    if rodash.isEmpty(response.text) then return true

    updateObject = returnUpdateObject(parseJSON(response.text))
    collection.update(updateObject, true)
    collection.totalCount = collection.getChildCount()

    publish(events.SCREEN_DATA_RECEIVED, {
        content: collection
    })

    return true
end function


function returnUpdateObject(options = {})
    data = options.data ?? {}
    screenData = data.screen ?? {}
    carouselsData = screenData.carousels ?? []
    ' carouselsData =  [screenData.carousels[3], screenData.carousels[4], screenData.carousels[5]]
    ' carouselsData =  [screenData.carousels[0], screenData.carousels[2]]
    updateObjArray = []

    for each carousel in carouselsData
        carouselModel = createObject("roSGNode", "Collection")

        if not rodash.isNode(carouselModel) then continue for

        updateObject = {
            carouselTitle: carousel.carouselTitle,
            carouselType: carousel.carouselType ?? "INDEX",
            documentId: carousel.documentId,
            id: carousel.documentId,
            thumbnailType: carousel.thumbnailType ?? "LANDSCAPE"
        }

        carouselModel.update(updateObject, true)

        generateDefaultModels(carouselModel)
        exec("generateCarouselCollection", {}, carouselModel)

        updateObjArray.push(carouselModel)
    end for

    updateObject = {
        canPaginate: not rodash.isEmpty(updateObjArray),
        children: updateObjArray,
        documentId: screenData.documentId,
        slug: screenData.slug,
        paginating: false
    }

    return updateObject
end function


sub generateDefaultModels(carouselModel)
    if not rodash.isNode(carouselModel) then return

    initialPagination = exec("returnInitialPagination", {}, carouselModel)

    ' Load initial carousel items
    ' for loading animation
    for x = 0 to initialPagination.pageSize - 1
        updateObject = {
            description: "",
            hydrated: false,
            logoImageUri: "",
            thumbnailImageUri: ""
        }
        model = createObject("roSGNode", "ContentModel")
        model.update(updateObject, true)
        exec("generateCarouselModel", { thumbnailType: carouselModel.thumbnailType }, model)

        carouselModel.appendChild(model)
    end for
end sub
