import "pkg:/components/_ord/wrappers.bs"
import "pkg:/components/tasks/shared/carousels.bs"
import "pkg:/components/tasks/shared/content.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runScreenTask)
    end sub)
end sub


function runScreenTask(options = {})
    options = top().options ?? {}
    if not rodash.isNonEmptyAA(options) then return true

    collection = options.collection
    if not rodash.isNode(collection) then return true

    variables = options.variables ?? {}
    if rodash.isEmpty(variables) then return true

    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Screen) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>"})
    responseJSON = response.json ?? {}

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return true
    end if

    data = responseJSON.data ?? {}
    screenData = data.screen ?? {}
    carouselsArray = screenData.carousels ?? []
    ' carouselsArray =  [screenData.carousels[0]]
    ' carouselsArray =  [screenData.carousels[0], screenData.carousels[2]]
    updateObject = returnCarouselsArray(carouselsArray)
    updateObject.append({
        id: screenData.documentId,
        slug: screenData.slug
    })

    publish(events.SCREEN_DATA_RECEIVED, {
        content: collection,
        updateObject: updateObject
    })

    return true
end function
