import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runConfigsTask)
    end sub)
end sub


function runConfigsTask(_options = {})
    response = rokurequests_Requests().get("<%- s(CONFIG.ENV.LOCAL_DEV_SERVER) %>" + "/configs.json")
    responseJSON = response.json ?? {}

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return true
    end if

    dispatch(events.CONFIGS_UPDATE, responseJSON)

    return true
end function
