import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.pill = top().findNode("pill")
        m.ratingText = top().findNode("ratingText")
        safeObserve("text", onTextSet)
    end sub)
end sub


sub onTextSet(options = {})
    if not rodash.isNonEmptyAA(options) then return

    rating = options.data
    m.ratingText.text = ucase("Rated " + rating.replace("_", "-"))
    stackChildren({ node: m.pill, direction: "horizontal" })
end sub
