sub azLog(thingsToPrint = [], location = "")
    logMessage = ""
    logMessage += chr(10)
    logMessage += "+-+-+-+-+-+-+-+-+-+-+-+-+-+"
    logMessage += chr(10)
    logMessage += chr(10)

    titleText = "Logged from: "
    bodyText = ""

    if rodash.isNonEmptyString(location) then titleText += location

    for each item in thingsToPrint
        bodyText += formatJSON(item, 512)
        bodyText += chr(10)
        bodyText += chr(10)
    end for

    logMessage += "Logged at: "
    logMessage += rodash.now().toStr()
    logMessage += chr(10)

    logMessage += titleText
    logMessage += chr(10)

    logMessage += bodyText

    logMessage += "-+-+-+-+-+-+-+-+-+-+-+-+-+-"
    logMessage += chr(10)

    ?logMessage
end sub
