import "pkg:/components/_ord/wrappers.bs"
import "pkg:/components/tasks/shared/carousels.bs"
import "pkg:/components/tasks/shared/content.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runContentTask)
    end sub)
end sub


function runContentTask(options = {})
    options = top().options ?? {}
    if not rodash.isNonEmptyAA(options) then return true

    model = options.content
    if not rodash.isNode(model) then return true

    documentId = model.id

    variables = {}
    variables.setModeCaseSensitive()
    variables = {
        "documentId": documentId
    }
    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.ContentScreen) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>" })
    responseJSON = parseJSON(response.text)
    responseData = responseJSON.data ?? {}
    content = responseData.content ?? {}

    updateObject = getContentData({ data: content })

    carouselsArray = content.carousels ?? []
    updateObject.append(returnCarouselsArray(carouselsArray))

    publish(events.CONTENT_DATA_RECEIVED, {
        content: model,
        updateObject: updateObject
    })
    return true
end function
