import "pkg:/components/_ord/init.bs"
import "pkg:/components/tasks/shared/carousels.bs"
import "pkg:/components/tasks/shared/content.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runContentTask)
    end sub)
end sub


function runContentTask(options = {})
    options = top().options ?? {}
    variables = options.variables ?? {}

    detailsHydrated = options.detailsHydrated ?? false
    updateObject = {}

    if not detailsHydrated
        response = rokurequests_Requests().post("{{%- s(CONFIG.ENV.GRAPHQL_SERVER) %}}", { json: { query: "{{%- s(QUERY.ContentScreen) %}}", variables: variables }, headers: "{{%- o(CONFIG.Headers) %}}" })
        responseJSON = response.json ?? {}

        if not response.ok
            onError({
                failureReason: response.getfailurereason,
                errors: (responseJSON ?? {}).errors
            })
            return true
        end if

        responseData = responseJSON.data ?? {}
        content = responseData.content ?? {}

        updateObject.append(getContentData({ data: content }))

        carouselsArray = content.carousels ?? []
        updateObject.append(returnCarouselsArray(carouselsArray))
        updateObject.append({ detailsHydrated: true, hydrated: true })
    end if

    publish(events.CONTENT_DATA_RECEIVED, {
        content: options.content,
        updateObject: updateObject
    })
    return true
end function
