import "pkg:/components/_ord/wrappers.bs"
import "pkg:/components/tasks/shared/carousels.bs"
import "pkg:/components/tasks/shared/content.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runContentTask)
    end sub)
end sub


function runContentTask(options = {})
    options = top().options ?? {}
    if not rodash.isNonEmptyAA(options) then return true

    model = options.content
    if not rodash.isNode(model) then return true

    variables = options.variables ?? {}
    if not rodash.isNonEmptyAA(variables) then return true

    detailsHydrated = options.detailsHydrated ?? false
    updateObject = {}

    if not detailsHydrated
        response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.ContentScreen) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>" })
        responseJSON = response.json ?? {}

        if not response.ok
            onError({
                failureReason: response.getfailurereason,
                errors: (responseJSON ?? {}).errors
            })
            return true
        end if

        responseData = responseJSON.data ?? {}
        content = responseData.content ?? {}

        updateObject.append(getContentData({ data: content }))

        carouselsArray = content.carousels ?? []
        updateObject.append(returnCarouselsArray(carouselsArray))
        updateObject.append({ detailsHydrated: true })
    end if

    publish(events.CONTENT_DATA_RECEIVED, {
        content: model,
        updateObject: updateObject
    })
    return true
end function
