import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub()
        setupItem()
    end sub)
end sub


sub setupItem()
    m.label = m.top.findNode("label")
    m.icon = m.top.findNode("icon")
    m.container = m.top.findNode("textContainer")
    m.background = top().findNode("background")
    m.highlight = top().findNode("highlight")
    m.parentList = top().getParent()
    m.flexList = m.parentList.getParent()

    if m.flexList.id = "topbarList"
        addClass("topbar")
    end if

    safeObserve("focusPercent", onFocusPercentChange)
    safeObserve("itemContent", itemContentChanged)
    safeObserve("currRect", onCurrRectChange)
    safeObserve("groupHasFocus", onGroupFocusChange)
    safeObserve("focusPercent", onGroupFocusPercentChange, m.parentList)
    safeObserve("itemSelected", onListItemSelected, m.parentList)
end sub


sub onGroupFocusChange(options = {})
    setColors()
end sub


sub onListItemSelected(options = {})
    setColors()
end sub


sub itemContentChanged(options = {})
    content = options.data
    m.label.text = ucase(content.title)
    m.icon.text = content.iconText
    dynamicWidth = content.dynamicWidth ?? false

    listContent = content.getParent()
    totalItemCount = listContent.totalCount

    setColors()

    set({ dynamicWidth: dynamicWidth, totalItemCount: totalItemCount})
    onTextChange()
end sub


sub onTextChange(options = {})
    stackChildren({ node: m.container, horizontal: true })
    m.container.width = m.container.boundingRect().width
    m.container.height = m.container.boundingRect().height

    exec("registerChildRect", {
        smallSquare: getUnFocusedRectSize(),
        bigSquare: getFocusedRectSize(),
        index: m.top.index
    }, top().getParent().getParent())

    if get("dynamicWidth") then m.label.clippingRect = [0,0,0,0]
end sub


function getFocusedRectSize(options = {})
    if not rodash.isNode(m.label) then return [0,0]

    m.label.text = ucase(top().itemContent.title)
    labelSquare = [getVisibleWidth(m.label), getVisibleHeight(m.label)]
    set({ "labelSquare": labelSquare })

    stackChildren({ node: m.container, horizontal: true })
    return [getVisibleWidth(m.container), getVisibleHeight(m.container)]
end function


function getUnfocusedRectSize(options = {})
    if not rodash.isNode(m.label) then return [0,0]

    if get("dynamicWidth")
        m.label.width = 0
        m.label.text = ""
    end if

    stackChildren({ node: m.container, horizontal: true })
    return [getVisibleWidth(m.container), getVisibleHeight(m.container)]
end function


sub onCurrRectChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    rect = options.data
    m.background.width = rect.width
    m.background.height = rect.height
end sub


sub onGroupFocusPercentChange(options = {})
    labelSquare = get("labelSquare") ?? [0, 0]
    labelWidth = labelSquare[0]
    labelHeight = labelSquare[1]

    if get("dynamicWidth")
        m.label.clippingRect = [0, 0, labelWidth * options.data, labelHeight]
    end if

    percentageOffset = getCenteredPercentage(options.data ?? 0)

    if top().groupHasFocus
        delayMS = top().index * 33
    else
        totalItemCount = get("totalItemCount") ?? 0
        delayMS =  (totalItemCount - top().index) * 33
    end if

    rodash.delay(sub(args)
        node = args[0]
        percentageOffset = args[1]
        node.opacity = percentageOffset
    end sub, delayMS, [m.highlight, percentageOffset])
end sub


sub onFocusPercentChange(options = {})
    focusPercentage = options.data ?? {}
    maxOpacity = top().groupHasFocus ? 0.20 : 0

    if m.flexList.itemSelected = top().index
        maxOpacity = 1
    end if

    m.background.opacity = focusPercentage * maxOpacity
end sub


function getCenteredPercentage(value = 0)
    if not rodash.isNumber(value) then return 0

    clampedValue = value
    if clampedValue < 0 then clampedValue = 0
    if clampedValue > 1 then clampedValue = 1

    return 1 - abs((clampedValue * 2) - 1)
end function


sub setColors()
    activeItem = m.flexList.itemSelected <> -1 and m.parentList.itemSelected = top().index
    selectedItem = m.parentList.itemFocused = top().index
    groupHasFocus = top().groupHasFocus

    m.label.color = "#BBBBBB"
    m.icon.color = "#BBBBBB"
    m.background.opacity = 0

    if activeItem
        m.label.color = "#9ca56c"
        m.icon.color = "#9ca56c"
        m.background.opacity = 1
    else if selectedItem and groupHasFocus
        m.background.opacity = 0.2
    end if
end sub
