import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runQueue)
    end sub)
end sub


function runQueue(_options = {})
    messagePort = createObject("roMessagePort")
    top().ready = safeObserve("eventData", messagePort)

    while true
        msg = wait(0, messagePort)
        if msg = invalid then continue while

        messageData = msg.getData()
        publish(messageData.id, messageData.options)
    end while

    return true
end function
