import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        setupItem()
    end sub)
end sub


sub setupItem()
    m.label = top().findNode("label")
    m.icon = top().findNode("icon")
    m.container = top().findNode("textContainer")
    m.background = top().findNode("background")
    m.highlightTop = top().findNode("highlightTop")
    m.highlightBottom = top().findNode("highlightBottom")
    m.colorFieldInterpolator = top().findNode("focusColorInterpolator")
    parentList = top().getParent()

    safeObserve("focusPercent", onFocusPercentChange)
    safeObserve("itemContent", itemContentChanged, top())
    safeObserve("currRect", onCurrRectChange, top())

    if rodash.isNode(parentList) then safeObserve("focusPercent", onGroupFocusPercentChange, parentList)
end sub


function getTitleText()
    if not rodash.isNode(top().itemContent) then return ""
    active = top().itemContent.active ?? false
    title = active ? top().itemContent.activeTitle : top().itemContent.title
    return ucase(title)
end function


sub itemContentChanged(options = {})
    content = options.data
    m.label.text = getTitleText()

    setIconInfo(content)

    dynamicWidth = content.dynamicWidth ?? false
    set({ "dynamicWidth": dynamicWidth })
    onTextChange()
end sub


sub setIconInfo(content)
    if not rodash.isNode(content) then return
    m.icon.text = content.iconText

    ctaType = content.id
    if rodash.isEmptyString(ctaType) then return

    if ctaType <> userItemsTypes.WATCHLIST and ctaType <> userItemsTypes.FAVORITE then return

    if content.active ?? false
        addClass("active", m.icon)
    else
        removeClass("active", m.icon)
    end if
end sub


sub onTextChange(_options = {})
    labelSquare = get("labelSquare") ?? [0,0]
    clipPercentage = labelSquare[0] > 0 ? m.label.clippingRect.width / labelSquare[0] : 0

    stackChildren({ direction: "horizontal" }, m.container)
    m.container.width = m.container.boundingRect().width
    m.container.height = m.container.boundingRect().height

    if get("dynamicWidth")
        labelSquare = get("labelSquare") ?? [0,0]
        m.label.clippingRect = [0, 0, labelSquare[0] * clipPercentage, labelSquare[1]]
    end if

    parentList = top().getParent()
    if not rodash.isNode(parentList) then return
    flexList = parentList.getParent()
    if not rodash.isNode(flexList) then return

    exec("registerChildRect", {
        smallSquare: getUnFocusedRectSize(),
        bigSquare: getFocusedRectSize(),
        index: top().index
    }, flexList)
end sub


sub onCurrRectChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    rect = options.data

    for each node in [m.background, m.highlightTop, m.highlightBottom]
        node.width = rect.width
        node.height = node.id = "highlightTop" ? (rect.height / 3) * 2 : rect.height
    end for
end sub


sub onGroupFocusPercentChange(options = {})
    percentage = options.data ?? {}
    labelSquare = get("labelSquare") ?? [0,0]
    labelWidth = labelSquare[0]
    labelHeight = labelSquare[1]
    parentList = top().getParent()
    if not rodash.isNode(parentList) then return

    if parentList.itemFocused = top().index then m.colorFieldInterpolator.fraction = percentage

    if parentList.itemFocused = top().index and get("dynamicWidth")
        m.label.clippingRect = [0, 0, labelWidth * percentage, labelHeight]
    end if
end sub


sub onFocusPercentChange(options = {})
    percentage = options.data ?? {}
    runFocusTransformation(percentage)
end sub


function getFocusedRectSize(_options = {})
    if not rodash.isNode(m.label) then return [0,0]

    m.label.text = getTitleText()
    m.label.visible = true

    if get("dynamicWidth") then m.label.clippingRect = [0,0,0,0]
    labelSquare = [getVisibleWidth(m.label), getVisibleHeight(m.label)]
    set({ "labelSquare": labelSquare })

    stackChildren({ direction: "horizontal" }, m.container)
    return [getVisibleWidth(m.container), getVisibleHeight(m.container)]
end function


sub runFocusTransformation(percentage)
    labelSquare = get("labelSquare") ?? [0,0]
    labelWidth = labelSquare[0]
    labelHeight = labelSquare[1]

    if top().groupHasFocus then m.colorFieldInterpolator.fraction = percentage

    if get("dynamicWidth")
        m.label.clippingRect = [0, 0, labelWidth * percentage, labelHeight]
    end if
end sub


function getUnfocusedRectSize(_options = {})
    if not rodash.isNode(m.label) then return [0,0]

    if get("dynamicWidth")
        m.label.width = 0
        m.label.text = ""
        m.label.visible = false
    end if

    stackChildren({ direction: "horizontal" }, m.container)
    return [getVisibleWidth(m.container), getVisibleHeight(m.container)]
end function
