import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        safeObserve("loading", onLoadingChange)
        m.animationId = ""
    end sub)
end sub


sub onLoadingChange(options = {})
    loading = options.data ?? false
    if loading then startLoadingAnimation()
end sub


sub startLoadingAnimation(_options = {})
    m.animationId = fadeIn(top(), { callback: onFadedIn })
end sub


sub onFadedOut(_options = {})
    if not top().loading
        if rodash.isNonEmptyString(m.animationId) then removeAnimation(m.animationId)
        safeUnobserve("loading")
        return
    end if

    startLoadingAnimation()
end sub


sub onFadedIn(_options = {})
    fadeOut(top(), { callback: onFadedOut })
end sub
