sub init()
   updateObjArray = []

    for each item in getItems()
        updateObject = { subtype: "ContentNode"}
        updateObject.append(item)
        updateObjArray.push(updateObject)
    end for

    m.top.update(updateObjArray, true)
    m.top.totalCount = m.top.getChildCount()
end sub


function getItems() as object
    return [
        {
            title: "Home"
        },
        {
            title: "Live Channels"
        },
        {
            title: "Documentaries"
        },
        {
            title: "TV Shows"
        },
        {
            title: "Movies"
        },
        {
            title: "Sports"
        },
        {
            title: "News"
        },
        {
            title: "Favorites"
        },
        {
            title: "Settings"
        },
        {
            title: "Account"
        },
        {
            title: "Terms of Service"
        }
    ]
end function
