import "pkg:/source/helpers/dateTime.bs"

function setInterval(func, args, timeout)
    return setTimeout(func, args, timeout, true)
end function

function setTimeout(func, args, timeout, repeat = false)
    if m.timeouts = invalid then m.timeouts = {}
    if m.delayedFunctions = invalid then m.delayedFunctions = {}

    currentTime = DateTime_getTimestamp(true)
    newTimeout = createObject("roSGNode", "Timer")
    newTimeout.duration = timeout / 1000
    newTimeout.id = currentTime
    newTimeout.repeat = repeat
    newTimeout.observeField("fire", "onTimeoutFinished")

    m.timeouts[currentTime] = newTimeout
    m.delayedFunctions[currentTime] = {
        args: args
        func: func
    }

    newTimeout.control = "start"
    return currentTime
end function

sub onTimeoutFinished(event)
    timerNode = event.getROSGNode()
    timeoutId = timerNode.id

    func = (m.delayedFunctions[timeoutId] ?? {}).func
    args = (m.delayedFunctions[timeoutId] ?? {}).args

    if type(func) <> "roFunction" then return
    func(args)

    if not timerNode.repeat
        clearTimeout(timeoutId)
    end if
end sub

sub clearTimeout(timeoutId)
    m.delayedFunctions[timeoutId] = invalid
    m.timeouts[timeoutId] = invalid
end sub

