' requires /source/helpers/typeGuard.bs
import "pkg:/source/helpers/typeGuard.bs"



' CommonUtils_arrayToMap: turns array to json map using a field key
'
' @param {dynamic} array to convert to json map
' @return {object} key to set as
'''''''''
function CommonUtils_arrayToMap(array as dynamic, fieldKey as string, fieldValue = "" as string) as object
    map = {}
    hasFieldValue = TypeGuard_isStringNotEmpty(fieldValue)
    for each item in array
        if TypeGuard_isValid(item) and TypeGuard_isStringNotEmpty(item[fieldKey])
            map[item[fieldKey]] = hasFieldValue ? item[fieldValue] ?? item : item
        end if
    end for
    return map
end function


'''''''''
' CommonUtils_mapToQueryString: turns assoc array to query params string
'
' @param {object} map - a hashmap, key-value associative array
'                       IF value is an AA, it will be formatted to String using FormatJSON
'                       otherwise value must be string
' @return {string} uri-encoded query params
'''''''''
function CommonUtils_mapToQueryString(map as object, encodeValue = true) as string
    queryParts = []

    for each key in map
        v = map[key]
        if TypeGuard_isValid(v)
            k = key.encodeUriComponent()

            v = TypeGuard_isAssocArray(v) ? FormatJSON(v) : v
            v = encodeValue ? v.encodeUriComponent() : v

            queryParts.push(k + "=" + v)
        end if
    end for

    return queryParts.join("&")
end function


'''''''''
' CommonUtils_queryStringToAA: turns assoc array to query params string
'
' @param {object} map - a hashmap, key-value associative array
' @return {string} uri-encoded query params
'''''''''
function CommonUtils_queryStringToAA(str as string) as object
    unescaped = str.decodeURIComponent()
    unescapedArray = unescaped.split("&")
    urlObject = {}

    for each kvp in unescapedArray
        splitKVP = kvp.split("=")
        urlObject[splitKVP[0]] = splitKVP[1]
    end for

    return urlObject
end function


'''''''''
' CommonUtils_flat: Creates an array with all the elements of the sub-arrays until the specified depth
' @param {array} array of items
' @param {depht} [default=1] depht of sub-arrays to be flatten
' @return {object} flatten array to the specified depth
'''''''''
function CommonUtils_flat(array as dynamic, depht = 1 as integer) as object
    if not TypeGuard_isIterable(array) then return invalid
    flattenArr = []
    nextArray = []

    for each item in array
        if TypeGuard_implementsArray(item)
            nextArray = item
            if depht = 1
                for each item in nextArray
                    flattenArr.push(item)
                end for
            else
                for each item in CommonUtils_flat(nextArray, depht-1)
                    flattenArr.push(item)
                end for
            end if
        else
            flattenArr.push(item)
        end if
    end for

    return flattenArr
end function


'''''''''
' CommonUtils_get: is used to get the value at path of object
'
' @param {object} obj The object to query.
' @param {string} path The path of the property to get.
' @param {dynamic} [default=invalid] optional value in case no match.
' @return {dynamic}
'''''''''
function CommonUtils_get(obj as object, path as string, default = invalid as dynamic) as dynamic
    if not TypeGuard_isIterable(obj) then return default
    segments = CommonUtils_pathAsArray(path)
    if TypeGuard_isInvalid(segments) then return default
    result = invalid
    while segments.count() > 0
        key = segments.shift()
        value = obj[key]
        if TypeGuard_isInvalid(value)
            exit while
        end if
        if segments.count() = 0
            result = value
            exit while
        end if
        if not TypeGuard_isIterable(value)
            exit while
        end if
        obj = value
    end while
    if TypeGuard_isInvalid(result) then return default
    return result
end function


'''''''''
' CommonUtils_map: creates an array of values by running each element in collection through the iteratee
'
' @param {object} obj The iterable array to iterate over.
' @param {dynamic} iteratee The function invoked per iteration.
' @param {dynamic} [ctx=invalid] Optional params to use in iteratee.
' @return {dynamic}
'''''''''
function CommonUtils_map(obj as object, iteratee as dynamic, ctx = invalid) as dynamic
    if TypeGuard_isString(iteratee)
        ctx = iteratee
        iteratee = function(x, prop)
            return x[prop]
        end function
    end if

    if not TypeGuard_isFunction(iteratee)
        iteratee = function(x, ctx)
            return x
        end function
    end if

    if TypeGuard_implementsArray(obj)
        result = []
        for each o in obj
            result.push(iteratee(o, ctx))
        end for
        return result
    else
        return []
    end if
end function


'''''''''
' CommonUtils_pathAsArray: split a string path into its parts in an array
'
' @param {dynamic} path separated by dots
' @return {object} array with path segments
'''''''''
function CommonUtils_pathAsArray(path as dynamic) as object
    pathRE = CreateObject("roRegex", "\[([0-9]+)\]", "i")
    segments = []
    if TypeGuard_isString(path)
        dottedPath = pathRE.replaceAll(path, ".\1")
        stringSegments = dottedPath.tokenize(".")
        for each s in stringSegments
            if (Asc(s) >= 48) and (Asc(s) <= 57)
                segments.push(s.toInt())
            else
                segments.push(s)
            end if
        end for
    else if TypeGuard_implementsArray(path)
        stringPath = ""
        for each s in path
            stringPath = stringPath + "." + Box(s).toStr()
        end for
        segments = CommonUtils_pathAsArray(stringPath)
    else
        segments = invalid
    end if
    return segments
end function


'''''''''
' CommonUtils_slice: takes a portion of an array and returns it
' source: https://github.com/juliomalves/roku-libs
' @param {object} arr array of items
' @param {integer} fromIndex index at which to start slicing
' @param {dynamic} toIndex index or invalid of where to stop slicing
' @return {object} array of sliced items
'''''''''
function CommonUtils_slice(arr as object, fromIndex=0 as integer, toIndex=invalid as dynamic) as object
    if not TypeGuard_isArray(arr) then return invalid

    size = arr.count()
    lastIndex = size - 1
    slicedArr = []

    if fromIndex < 0 then fromIndex = size + fromIndex
    if toIndex = invalid then toIndex = lastIndex
    if toIndex < 0 then toIndex = size + toIndex
    if toIndex >= size then toIndex = lastIndex

    if fromIndex >= size or fromIndex > toIndex then return slicedArr

    for i = fromIndex to toIndex
        slicedArr.push(arr[i])
    end for
    return slicedArr
end function


'''''''''
' CommonUtils_3n: takes a number and returns the closest number divisible by 3
' @param {dynamic} value as integer or float
' @return {integer} value as integer divisible by 3
'''''''''
function CommonUtils_3n(value as dynamic) as integer
    if not TypeGuard_isNumber(value) then return 0
    return int(value / 3) * 3
end function

'''''''''
' CommonUtils_filter: Filters array through a function and arguments provided
' @param {arr} as object -- array of items
' @param {func} as function - comparator function
' @param {args} as object - arguments to use in the function
' @return {mappedArr} value as object - array of filtered items
'''''''''
function CommonUtils_filter(arr as object, func as function, args as object) as object
    if not TypeGuard_isArray(arr) then return []

    size = arr.count()
    mappedArr = []

    if size = 0 then return mappedArr

    for i = 0 to size - 1
        if func(arr[i], i, arr, args)
            mappedArr.push(arr[i])
        end if
    end for

    return mappedArr
end function


'''''''''
' CommonUtils_find: looks through an array and finds an item
' @param {arr} as object - array of items
' @param {func} as function - comparator function
' @param {args} as object - arguments to use in the function
' @return {} as object - object containing found item
'''''''''
function CommonUtils_find(arr as object, func as function, args as object, findLast = false) as object
    if not TypeGuard_isArray(arr) then return {}

    size = arr.count()

    if size = 0 then return {}

    found = []

    for i = 0 to size - 1
        if func(arr[i], i, arr, args)
            if findLast
                found.push(arr[i])
            else
                return arr[i]
            end if
        end if
    end for

    if found.count() > 0 then return found.peek()

    return invalid
end function


'''''''''
' CommonUtils_reduce: array reduce method
' @param {arr} as object - array of items
' @param {func} as function - reduction function
' @param {args} as object - arguments to use in the function
' @param {initialValue} as dynamic - initial value to use in the reducer
' @return {} as dynamic - returns accumulated value
'''''''''
function CommonUtils_reduce(arr as object, func as function, args as object, initialValue=invalid as dynamic) as dynamic
    if not TypeGuard_isArray(arr) then return invalid

    size = arr.count()
    startAt = 0
    accumulator = initialValue

    if size = 0 then return accumulator

    if accumulator = invalid
        accumulator = arr[0]
        startAt = 1
    end if

    for i = startAt to size - 1
        accumulator = func(accumulator, arr[i], i, arr, args)
    end for

    return accumulator
end function


'''''''''
' CommonUtils_titleize:
' @param {text} as string - string to titleize
' @return {str} as string - string with every word capitalized
'''''''''
function CommonUtils_titleize(text as string) as string
    if TypeGuard_isStringEmpty(text) then return ""

    strArray = lcase(text).split(" ")
    newArray = []

    for each substr in strArray
        newArray.push(substitute("{0}{1}", ucase(left(substr, 1)), right(substr, len(substr) - 1)))
    end for

    return newArray.join(" ")
end function


'''''''''
' CommonUtils_trTitleize:
' @param {text} as string - translation key
' @return {str} as string - titleized and translated key
'''''''''
function CommonUtils_trTitleize(key as string) as string
    if left(key, 5) <> "TKEY_" then key = "TKEY_" + key
    return CommonUtils_titleize(tr(key))
end function


'''''''''
' CommonUtils_indexOf: returns the index position of an element in an array
' @param {dynamic} arr to search in
' @param {dynamic} el the element to search for
' @return {integer} the index position of el in arr, or -1 if not found
'''''''''
function CommonUtils_indexOf(arr as dynamic, el as dynamic) as integer
    if TypeGuard_isArray(arr)
        for i = 0 to arr.count() - 1
            if TypeGuard_isNode(el) and arr[i].isSameNode(el)
                return i
            else if not TypeGuard_isNode(el) and arr[i] = el
                return i
            end if
        end for
    end if

    return -1
end function


'''''''''
' CommonUtils_isLowendDevice: check whether user device is low end or not
' @return {boolean} true if low end device, false if not
'''''''''
function CommonUtils_isLowendDevice() as boolean
    lowEndModels = ["2400X", "2450X", "2500X", "2700X", "2710X", "2720X", "3000X", "3050X", "3100X", "3400X", "3420X", "3500X", "3500R", "3700X", "3710X"]
    di = CreateObject("roDeviceInfo")
    return (CommonUtils_indexOf(lowEndModels, di.getModel()) > -1)
end function


'''''''''
' CommonUtils_letterSpacing: adding letterSpacing to text
' @param {targetString} as string  - string to add letterSpacing to
' @return {format} as string - final date string
'''''''''
function CommonUtils_letterSpacing(targetString as string) as string
    stringArr = targetString.split(" ")
    newStringArr = []
    for each subString in stringArr
        ' for future: other spacings can be 8201, 8239
        newStringArr.push(subString.split("").join(chr(8202)))
    end for
    ' for future: other space sizes can be 8191, 8193
    return newStringArr.join(chr(8194))
end function

'''''''''
' CommonUtils_letterDeaccent: changes all accented letters in a text to their unaccented one
' @param {string} string to be checked
' @return {string} unaccented string
'''''''''
function CommonUtils_letterUnaccent(targetString as string) as string
    unaccentedString = targetString
    map = {
        "[àáâãäå]": "a"
        "[çčć]": "c"
        "[èéêë]": "e"
        "[ìíîï]": "i"
        "[ñ]": "n"
        "[òóôõöø]": "o"
        "[ß]": "s"
        "[ùúûü]": "u"
        "[ÿ]": "y"
        "[æ]": "ae"
    }

    for each item in map.items()
        r = CreateObject("roRegex", "(" + item.key +")", "g")
        unaccentedString = r.replaceAll(unaccentedString, item.value)
    end for

    return unaccentedString
end function

'''''''''
' CommonUtils_letterAccent: changes all unicode of accented letter of a text to an accented letter
' @param {string} string to be checked
' @return {string} accented string
'''''''''
function CommonUtils_letterAccent(targetString as string) as string
    accentedString = targetString
    map = {
        "\\u00([Ee])1": "á"
        "\\u00([Cc])1": "Á"
        "\\u00([Ee])9": "é"
        "\\u00([Cc])9": "É"
        "\\u00([Ee])([Dd])": "í"
        "\\u00([Cc])([Dd])": "Í"
        "\\u00([Ff])3": "ó"
        "\\u00([Dd])3": "Ó"
        "\\u00([Ff])([Aa])": "ú"
        "\\u00([Dd])([Aa])": "Ú"
    }

    for each item in map.items()
        r = CreateObject("roRegex", "(" + item.key +")", "g")
        accentedString = r.replaceAll(accentedString, item.value)
    end for

    return accentedString
end function

'''''''''
' CommonUtils_overrideError: updates the error field of a given service's ClientApi if valid
' @param {object} service service of which we wish to override its error if present.
' @param {dynamic} message to override
' @param {dynamic} title to override
' @param {dynamic} internalCode to override
'''''''''
function CommonUtils_overrideError(service as object) as object
    error = CommonUtils_get(service, "clientApi.error", {})

    if TypeGuard_isValid(error)

        title = CommonUtils_get(error, "title", tr("TKEY_GENERIC_ERROR_TITLE"))

        internalCode = CommonUtils_get(error, "internalCode")

        message = CommonUtils_get(error, "internalErrorMessage", substitute(tr("TKEY_GENERIC_ERROR"), chr(10)))

        error.append({
            "title": title,
            "internalErrorMessage": message,
            "internalCode": internalCode
        })
    end if

    return error
end function

function CommonUtils_test() as object
    try
        oops = -1 / 0
    catch e
        ?"OOOPS " e.backtrace.Peek()
        return {}
    end try

    return { oops: oops }
end function


'''''''''
' CommonUtils_printableJSON: takes data  and creates a printable string representation of data
' @param {dynamic} obj
' @return {string}
'''''''''
function CommonUtils_printableJSON(obj as dynamic) as string
    if TypeGuard_isEmptyAssocArray(obj) then return "{}"

    dataString = formatJSON(obj, 256)
    indentation = 0
    finalString = ""
    lineBreakKeys = ["{", "[", ",", "}", "]"]
    indentKeys = ["{", "["]
    outDentKeys = ["}", "]"]

    for each character in dataString.split("")
        if CommonUtils_indexOf(lineBreakKeys, character) <> -1
            if CommonUtils_indexOf(indentKeys, character) <> -1
                finalString += character
                finalString += chr(10)
                indentation += 1
                finalString += String(indentation, chr(8195) + chr(8195))
            else if CommonUtils_indexOf(outDentKeys, character) <> -1
                finalString += chr(10)
                indentation -= 1
                finalString += String(indentation, chr(8195) + chr(8195))
                finalString += character
            else
                finalString += character
                finalString += chr(10)
                finalString += String(indentation, chr(8195) + chr(8195))
            end if
        else
            finalString += character
        end if
    end for

    return TypeGuard_isStringEmpty(finalString) ? "{}" : finalString
end function


'''''''''
' CommonUtils_newNode: helper to create a new node
' @param {assocarray} fields - fields to add to the new node
' @param {dynamic} subType - the node's subType
' @return {node} the new node
'''''''''
function CommonUtils_newNode(fields = {} as object, subType = "ContentNode" as string) as object
    node = CreateObject("roSgNode", subType)
    node.update(fields, true)
    return node
end function


'''''''''
' CommonUtils_leadingCharacter: adds a leading 0 to a string
' @param {dynamic} target - string or int to add the 0 to
' @param {string} character - character to add
' @return {string} targetStr
'''''''''
function CommonUtils_leadingCharacter(target as dynamic, character as string) as string
    if TypeGuard_isInvalid(target) or TypeGuard_isInvalid(character) or TypeGuard_isIterable(target) or TypeGuard_isIterable(character) then return ""
    targetStr = target.toStr()
    if Len(targetStr) < 2
        targetStr = character+targetStr
    end if
    return targetStr
end function


'''''''''
' CommonUtils_floatMOD: Mod function that supports floats
' @param {dynamic} number - first number
' @param {dynamic} number - last number
' @return {dynamic} remainder
'''''''''
function CommonUtils_floatMOD(x as dynamic, y as dynamic) as dynamic
    if y = 0 then return 0
    a = abs(x)
    b = abs(y)
    remainder = a - (int(a/b) * b)
    return remainder * sgn(x)
end function


'''''''''
' CommonUtils_observe: Observe helper which allows passing of function references instead of just function names
' @param {node} node - node to attach the observer
' @param {field} string - field which to observe
' @param {func} dynamic - function reference or name
' @param {toggle} bool - togle to observe or unobserve
'''''''''
sub CommonUtils_observe(node as object, field as string, func as dynamic, toggle = true as boolean)
    if TypeGuard_isString(func)
        functionName = func
    else
        functionName = func.toStr().tokenize(" ").peek()
    end if

    if toggle
        node.observeField(field, functionName)
    else
        node.unobserveField(field)
    end if
end sub


'''''''''
' CommonUtils_observeScoped: Observe helper which allows passing of function references instead of just function names
' @param {node} node - node to attach the observer
' @param {field} string - field which to observe
' @param {func} dynamic - function reference or name
' @param {toggle} bool - togle to observe or unobserve
'''''''''
sub CommonUtils_observeScoped(node as object, field as string, func as dynamic, toggle = true as boolean)
    if not TypeGuard_isNode(node) then return
    if TypeGuard_isString(func)
        functionName = func
    else
        functionName = func.toStr().tokenize(" ").peek()
    end if

    if toggle
        node.observeFieldScoped(field, functionName)
    else
        node.unobserveFieldScoped(field)
    end if
end sub


'''''''''
' CommonUtils_logger: Print timestamp and log message if is dev mode
' @param {string} msg - the message to be printed
'''''''''
sub CommonUtils_logger(m1 = "", m2 = "", m3 = "", m4 = "", m5 = "", m6 = "", m7 = "", m8 = "", m9 = "", m10 = "")
    appInfo = CreateObject("roAppInfo")
    if appInfo.isDev()
        time = CreateObject("roDateTime")
        stamp = "[" + time.toISOString().replace("T", " ").replace("Z", ".") + time.GetMilliSeconds().toStr() + "Z]"
        ' bs:disable-next-line
        ? stamp m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 ' eslint-disable-line
    end if
end sub


'''''''''
' CommonUtils_trace: Print the backtrace without crashing the app
' @param {string} msg - the message to identify the trace in the logs
'''''''''
sub CommonUtils_trace(msg as string)
    try
        throw msg
    catch e
        CommonUtils_logger(`TRACE FOR ${msg}: `, FormatJSON(e.backtrace))
    end try
end sub

function CommonUtils_getIntToString(intValue as dynamic) as string
    value = ""
    if TypeGuard_isValid(intValue)
        if TypeGuard_isString(intValue) then return intValue.trim()
        if TypeGuard_isInteger(intValue) then return str(intValue).trim()
    end if
    return value
end function

function CommonUtils_getInteger(value as dynamic) as integer
    if TypeGuard_isInteger(value) then return value
    if TypeGuard_isFloat(value) then return cint(value)
    if TypeGuard_isString(value) then return value.toInt()
    return 0
end function


'''''''''
' CommonUtils_findFocusedChild: Iterates down the focusedChild chain to find the actual focused child
' @param {node} topNode - starting node
' @return {node} focusedChild - node that is focused
'''''''''
function CommonUtils_findFocusedChild(topNode) as object
    lastSubtype = topNode.subType()
    lastId = topNode.id
    focusedChild = topNode.focusedChild
    if focusedChild.subType() = lastSubtype and focusedChild.id = lastId
        return topNode
    else
        return CommonUtils_findFocusedChild(focusedChild)
    end if
end function

function CommonUtils_getPositionPercentage(position as float, duration as integer) as float
    ' avoid dividing by zero
    if duration = 0 then return 0
    percentage = position ' default to assume it is stored as percentage
    if position > 1
        ' only true with the new method of storing position not percentage

        ' getting the position as percentage 0 - 1, with only 2 decimal points
        percentage = (int((position / duration) * 1000)) / 1000
    end if
    return percentage
end function

'''''''''
' CommonUtils_uniq: Returns an array of unique items from a given array
' @param {array} array - array to uniq
'''''''''
function CommonUtils_uniq(array) as object
    uniqArray = []

    for each item in array
        if CommonUtils_indexOf(uniqArray, item) = -1
            uniqArray.push(item)
        end if
    end for

    return uniqArray
end function

'''''''''
' CommonUtils_deeplinkId: Returns query string for deeplink
'''''''''
function CommonUtils_deeplinkId(options = {} as object, returnType = "string" as string) as dynamic
    stringArray = []

    for each kvp in (options.metaData ?? {}).items()
        stringArray.push(`${kvp.key}=${kvp.value}`)
    end for

    contentId = stringArray.join("|")

    returnObj = {
        mediaType: options.mediaType
        contentId: contentId
    }

    if returnType = "string"
        return CommonUtils_mapToQueryString(returnObj)
    else
        return returnObj
    end if
end function


'''''''''
' CommonUtils_stringReplace: uses a regex pattern to replace a srting in a string and returns it
' source: https://github.com/juliomalves/roku-libs
' @param {str} string to put replacements into
' @param {pattern} regex pattern to find
' @param {replacement} string to use as replacement for found string
' @return {string} final string with replacements as apprporiate
'''''''''
function CommonUtils_stringReplace(str = "" as String, pattern = "" as String, replacement = "" as String) as String
    regexObj = createObject("roRegex", pattern, "")
    return regexObj.replaceAll(str, replacement)
end function

'''''''''
' CommonUtils_formatPaywallCopies: transforms paywal styles into html tags for MultiStyleLabels
' @param format {
'   {textArray} array of objects containig text and styles keys
'   {sourceLabel} label set in the paywall response
'   {targetLabel} label set in the multi style label property
' }
' @return {string} final string with replacements as appropiate
'''''''''
function CommonUtils_formatPaywallCopies(format = {} as object) as String
    if TypeGuard_isEmptyAssocArray(format) then return ""

    textArray = format.textArray ?? []
    addNewLine = format.addNewLine ?? false
    sourceLabel = format.sourceLabel ?? "strong"
    targetLabel = format.targetLabel ?? "highlight"

    if not TypeGuard_isArray(textArray) or TypeGuard_isArrayEmpty(textArray) then return ""

    targetLabelOpeningTag = ["<", targetLabel, ">"].join("")
    targetLabelClosingTag = ["</", targetLabel, ">"].join("")

    textLineArr = []
    itemIndex = 0
    for each item in textArray
        text = (item.text ?? "").trim() ?? ""
        styles = item.styles ?? [""]
        style = styles[0] ?? ""
        textArray = [text]

        if lCase(style) = sourceLabel
            textArray.unshift(targetLabelOpeningTag)
            textArray.push(" ")
            textArray.push(targetLabelClosingTag)
        else
            textArray.push(" ")
        end if
        text = textArray.join("")

        itemIndex++
        textLineArr.push(text)
        if addNewLine then textLineArr.push(chr(10))
    end for

    finalText = textLineArr.join("")
    return CommonUtils_stringReplace(finalText, "<br ?/?>", chr(10))
end function

'''''''''
' CommonUtils_recast: recasts numbers as a specified type
' @param {value} value to be recast
' @param {type} type to recast to
' @return {type specified} final value in a specified type
'''''''''
function CommonUtils_recast(value, fieldType) as dynamic
    if not TypeGuard_isNumber(value) then return value
    if TypeGuard_isStringEmpty(fieldType) then return value

    lcType = lcase(fieldType)

    if lcType = "integer"
        typedValue% = value
        value = typedValue%
    else if lcType = "float"
        typedValue! = value
        value = typedValue!
    else if lcType = "double"
        typedValue# = value
        value = typedValue#
    else if lcType = "longinteger"
        typedValue& = value
        value = typedValue&
    end if

    return value
end function

'''''''''
' CommonUtils_gridReduction: Used on Fixed TargetGrids due to not having trackingId field
' to create a new element, so, use the node Id plus an extra pseudo random number (salt)
' thus we avoid elements that are not created by repetitions in the TargetGrid
'''''''''
function CommonUtils_gridReduction(acc, cv, index, arr, args)
    salt = rnd(0)
    newRow = false
    node = cv.node ?? cv
    cursor = cv.cursor ?? ""
    itemsToRender = args.itemsToRender ?? 3
    if index = 0 or index mod itemsToRender = 0
        rowObject = {
            contents: {
                edges: []
            }
            moduleType: "{{%- s(CONST.VOD.moduleTypes.fixedGridCarousel) %}}"
            title: ""
            id: `${node.id}|${salt}`
            itemsToRender: itemsToRender
            trackingId: ""
            treatment: "LANDSCAPE"
        }
        newRow = true
    else
        rowObject = acc.peek()
    end if
    rowObject.contents.edges.push({
        node: node
        cursor: cursor
    })
    if newRow then acc.push(rowObject)
    return acc
end function

function CommonUtils_booleanToString(val as object) as String
    if not TypeGuard_isBoolean(val) then return "false"

    return val.toStr()
end function

function CommonUtils_stringToBoolean(val as object) as Boolean
    if TypeGuard_isStringEmpty(val) then return false

    return lCase(val).trim() = "true"
end function

function CommonUtils_getQuadruple(val as dynamic) as object
    top = 0
    right = 0
    bottom = 0
    left = 0

    if TypeGuard_isInvalid(val) then return [top, right, bottom, left]

    if TypeGuard_isNumber(val)
        top = val
        right = val
        bottom = val
        left = val
    else if TypeGuard_isStringNotEmpty(val)
        top = val.toInt()
        right = val.toInt()
        bottom = val.toInt()
        left = val.toInt()
    else if TypeGuard_isArrayNotEmpty(val)
        if val.count() = 1
            top = val[0]
            right = val[0]
            bottom = val[0]
            left = val[0]
        else if val.count() = 2
            right = val[0]
            left = val[0]
            top = val[1]
            bottom = val[1]
        else
            top = val[0]
            right = val[1]
            bottom = val[2]
            left = val[3]
        end if
    end if

    return [top, right, bottom, left]
end function

function CommonUtils_chunk(array, chunkSize = 2 as integer) as object
    if TypeGuard_isArrayEmpty(array) then return []

    returnArray = [[]]

    for each item in array
        lastArray = returnArray[returnArray.count() - 1]

        if lastArray.count() >= chunkSize
            lastArray = []
            returnArray.push(lastArray)
        end if

        lastArray.push(item)
    end for

    return returnArray
end function

namespace CommonUtils
    function min(l as dynamic, r as dynamic) as dynamic
        return  l <= r ? l : r
    end function

    function max(l as dynamic, r as dynamic) as dynamic
        return  l >= r ? l : r
    end function

    ' function filtered()
    ' end function
end namespace

function parseObj(obj, depth = 0) as object
    if TypeGuard_isNode(obj) then return parseNode(obj, depth)

    returnObj = {}

    for each field in obj.items()
        fieldName = field.key
        fieldValue = field.value

        if type(fieldValue) = "roSGNode"
            returnObj[fieldName] = parseNode(fieldValue, depth + 1)
        else if type(fieldValue) = "roAssociativeArray"
            returnObj[fieldName] = parseObj(fieldValue, depth + 1)
        else
            returnObj[fieldName] = fieldValue
        end if
    end for

    return returnObj
end function

function parseNode(node, depth = 0) as object
    if not TypeGuard_isNode(node) then return {}
    allowedFieldTypes = ["array", "associativeArray", "boolean", "color", "float", "node", "rect2d", "string", "uri", "vector2d"]

    fieldTypes = node.getFieldTypes()
    returnObj = {}

    for each field in fieldTypes.items()
        fieldName = field.key
        fieldType = field.value

        if CommonUtils_indexOf(allowedFieldTypes, fieldType) <> -1
            if fieldType = "node"
                if depth < 4
                    returnObj[fieldName] = parseNode(node[fieldName], depth + 1)
                else
                    returnObj[fieldName] = `<Node: ${node.subType()}>`
                end if
            else if fieldType = "associativeArray"
                returnObj[fieldName] = parseObj(node[fieldName], depth + 1)
            else
                returnObj[fieldName] = node[fieldName]
            end if
        end if
    end for

    return returnObj
end function
