function TypeGuard_isInvalid(val as dynamic) as boolean
    valType = type(val)
    return valType = "Invalid" or valType = "roInvalid"
end function

function TypeGuard_isValid(val as dynamic) as boolean
    return not TypeGuard_isInvalid(val)
end function


function TypeGuard_isInitialized(val as dynamic) as boolean
    valType = lCase(type(val))
    return not valType = "<uninitialized>"
end function


function TypeGuard_isInteger(val as dynamic) as boolean
    valType = type(val)
    return valType = "Integer" or valType = "roInt" or valType = "roInteger"
end function


function TypeGuard_isString(val as dynamic) as boolean
    valType = type(val)
    return valType = "String" or valType = "roString"
end function


function TypeGuard_isStringNotEmpty(val as dynamic) as boolean
    if not TypeGuard_isString(val) then return false
    return val.trim() <> ""
end function


function TypeGuard_isStringEmpty(val as dynamic) as boolean
    return not TypeGuard_isStringNotEmpty(val)
end function


function TypeGuard_isLongInteger(val as dynamic) as boolean
    valType = type(val)
    return valType = "LongInteger" or valType = "roLongInteger"
end function


function TypeGuard_isFloat(val as dynamic) as boolean
    valType = type(val)
    return valType = "Float" or valType = "roFloat"
end function


function TypeGuard_isDouble(val as dynamic) as boolean
    valType = type(val)
    return valType = "Double" or valType = "roDouble"
end function


function TypeGuard_isNumber(val as dynamic) as boolean
    return TypeGuard_isInteger(val) or TypeGuard_isLongInteger(val) or TypeGuard_isFloat(val) or TypeGuard_isDouble(val)
end function


function TypeGuard_isBoolean(val as dynamic) as boolean
    valType = type(val)
    return valType = "Boolean" or valType = "roBoolean"
end function


function TypeGuard_isArray(val as dynamic) as boolean
    valType = type(val)
    return valType = "roArray"
end function


function TypeGuard_isArrayEmpty(val as dynamic) as boolean
    valType = type(val)
    return valType = "roArray" and val.count() = 0
end function


function TypeGuard_isArrayNotEmpty(val as dynamic) as boolean
    valType = type(val)
    return valType = "roArray" and val.count() > 0
end function

function TypeGuard_isListNotEmpty(val as dynamic) as boolean
    valType = type(val)
    return valType = "roList" and val.count() > 0
end function

function TypeGuard_isAssocArray(val as dynamic) as boolean
    valType = type(val)
    return valType = "roAssociativeArray"
end function

function TypeGuard_isEmptyAssocArray(val as dynamic) as boolean
    if not TypeGuard_isAssocArray(val) then return true
    ' removing possible name clashes
    if val.doesExist("count")
        val._count = val.count
        val.delete("count")
    end if

    return val.count() = 0
end function


function TypeGuard_isFunction(val as dynamic) as boolean
    valType = type(val)
    return valType = "Function" or valType = "roFunction"
end function


function TypeGuard_isNode(val as dynamic, subtype = "" as string) as boolean
    return type(val) = "roSGNode" and (subtype = "" or ucase(val.subtype()) = ucase(subtype))
end function


function TypeGuard_isEvent(val as dynamic) as boolean
    return type(val) = "roSGNodeEvent"
end function


function TypeGuard_isEqual(val1 as dynamic, val2 as dynamic) as boolean
    if type(val1) <> type(val2) then return false
    if TypeGuard_isAssocArray(val1) or TypeGuard_isArray(val1)
        return formatJson(val1) = formatJson(val2)
    else
        return val1 = val2
    end if
end function


function TypeGuard_implementsAssocArray(obj as dynamic) as boolean
    return TypeGuard_isValid(obj) and (getInterface(obj, "ifAssociativeArray") <> invalid)
end function


function TypeGuard_implementsArray(obj as dynamic) as boolean
    return TypeGuard_isValid(obj) and (getInterface(obj, "ifArray") <> invalid)
end function


function TypeGuard_isIterable(obj as dynamic) as boolean
    return TypeGuard_implementsAssocArray(obj) or TypeGuard_implementsArray(obj)
end function


function TypeGuard_isJSONable(value as dynamic) as boolean
    if TypeGuard_isInvalid(value) then return false
    jsonStr = formatJSON(value)
    ' an invalid formatJSON op is the only case that will return
    ' an actual empty string
    return len(jsonStr) > 0
end function


function TypeGuard_isNil(value as dynamic) as boolean
    return TypeGuard_isInvalid(value) or not TypeGuard_isInitialized(value)
end function


function TypeGuard_isFalsey(value as dynamic) as boolean
    if TypeGuard_isNumber(value) then return value = 0
    if TypeGuard_isString(value) then return value = ""
    if TypeGuard_isBoolean(value) then return not value
    return TypeGuard_isNil(value)
end function


function TypeGuard_isTruthy(value as dynamic) as boolean
    return not TypeGuard_isFalsey(value)
end function

function TypeGuard_isErrorNode(value as dynamic) as boolean
    return TypeGuard_isNode(value, "ERROR")
end function

function TypeGuard_isSameNode(node1 as dynamic, node2 as dynamic) as boolean
    if node1 = invalid and node2 = invalid
        return true
    end if

    if TypeGuard_isNode(node1) and TypeGuard_isNode(node2)
        return node1.isSameNode(node2)
    end if

    return false
end function

function TypeGuard_isDatetime(obj as object) as boolean
    if obj = invalid then return false

    if type(obj) = "roDateTime" then return true

    return false
end function

function TypeGuard_Stringify(obj) as string
    if TypeGuard_isEmptyAssocArray(obj) then return ""

    returnObj = {}

    for each field in obj.items()
        returnObj[field.key] = TypeGuard_isNode(field.value) ? `<Node: ${field.value.subType()}>` : field.value
    end for

    returnStr = formatJSON(returnObj)

    ' newStr = ""

    ' r = CreateObject("roRegex", "{", "i")
    ' replaceStr = `{`
    ' staticTkx = r.replaceAll(returnStr, "")

    return returnStr
end function

' function parseObj(obj, index = 0) as string
'     returnStr = ""

'     fieldTypes = obj.getFieldTypes()

'     for each field in obj.items()

'     end for

'     return returnStr
' end function

