import "pkg:/components/_ord/azat.bs"

function asdFunc()
    ?"ASADASDASDADASDAD"
end function


class NodeFunctions
    sub onInit(options = {})
        top().someArray = ["one", "two"]
    end sub


    function onTheNose(options = {})
        return { result: options.name + " failure" }
    end function


    function regularFunc(options = {})
        return { result: "safe count is: " + options.data.count().toStr()}
    end function
end class
