import "pkg:/components/_ord/wrappers.bs"


sub init()
    exec(function ()
        safeFunctions({
            nodeTest: nodeTest
            onTheNose: onTheNose
        })

        top().setField("someArray", ["asd","123"])

        safeObserve("data", onDataChange, m.top)

    end function)
end sub


sub onDataChange(options = {})
    ?"onDataChange " options.data
end sub


sub nodeTest()
    ?"!!!!!!!!!!!!!!!!!!!!"
    ?"nodeTest " m.top
end sub


function onTheNose(options = {})
    return { result: options.name + " failure" }
end function
