import "pkg:/components/_ord/wrappers.bs"
import "pkg:/source/roku_modules/promises/promises.brs"

sub init()
    exec(sub(options = {})
        m.scrollGroup = top().findNode("scrollGroup")
        m.scrollGroup.config = {
            direction: "vertical",
            flushEnd: true,
            scrollbarPosition: "top",
            showScrollbar: true
        }

        rodash.delay(sub(node)
            newRect = createObject("roSGNode", "Rectangle")
            newRect.width = 1650
            newRect.height = 400
            newRect.color = "#0000FFFF"

            newRect2 = createObject("roSGNode", "Rectangle")
            newRect2.width = 1650
            newRect2.height = 200
            newRect2.color = "#FF00FFFF"
            node.appendChildren([newRect, newRect2])
            ' node.appendChild(newRect)
        end sub, 3000, m.scrollGroup)
    end sub)
end sub


function handleFocus(options = {})
    return exec(function(options = {})
        m.scrollGroup.setFocus(true)
        return true
    end function)
end function
