import "pkg:/source/roku_modules/rodash/rodash.brs"
import "pkg:/source/roku_modules/sgrouter/router.brs"
' This component is used as a route guard that checks a keyPath against an expected value
' If the value at the keyPath does not match the expected value, it can show a deny dialog and/or redirect to another route
sub setGuardConfig(guard as Object)
end sub
' This function is called to determine if the route can be activated
function canActivate(currentRequest = {} as Object) as Dynamic
end function
