import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub()
        setupItem()
    end sub)
end sub


sub setupItem()
    m.indexLabel = m.top.findNode("label")
    m.container = m.top.findNode("container")
    m.container.opacity = 0.5
    safeObserve("focusPercent", onFocusPercentChange)
end sub


sub itemContentChanged(event)
    content = event.getData()
    m.indexLabel.text = content.title
    stackChildren({ node: m.container, horizontal: true })
    m.container.width = m.container.boundingRect().width
    m.container.height = m.container.boundingRect().height
    exec("registerChildRect", {
        smallSquare: [m.container.width, m.container.height],
        bigSquare: [m.container.width, m.container.height],
        index: m.top.index
    }, top().getParent().getParent())
end sub


sub onFocusPercentChange(options = {})
    focusPercentage = options.data ?? {}
    opacityPercentage = (0.5 * focusPercentage) * focusPercentage + 0.5
    m.container.opacity = opacityPercentage
end sub


sub stackChildren(options = {})
    node = options.node ?? m.top
    children = node.getChildren(-1, 0)
    totalHeight = 0
    totalWidth = 0
    horizontal = options.horizontal ?? false

    for each child in children
        if child.subType() <> "Animation" and child.subType() <> "Timer"
            childMargins = quadrupleMargins(child.margin)

            topMargin = childMargins.top
            rightMargin = childMargins.right
            bottomMargin = childMargins.bottom
            leftMargin = childMargins.left

            childHeight = child.boundingRect().height
            childWidth = child.boundingRect().width

            if horizontal
                child.translation = [totalWidth + leftMargin, child.translation[1]]

                totalWidth += leftMargin
                totalWidth += childWidth
                totalWidth += rightMargin
            else
                child.translation = [child.translation[0], totalHeight + topMargin]

                totalHeight += topMargin
                totalHeight += childHeight
                totalHeight += bottomMargin
            end if
        end if
    end for

    minWidth = node.minWidth ?? 0
    node.width = totalWidth > minWidth ? totalWidth : minWidth
end sub


function quadrupleMargins(margin)
    returnObj = {
        "left": 0,
        "top": 0,
        "right": 0,
        "bottom": 0
    }

    if margin.count() = 1
        returnObj["left"] = margin[0]
        returnObj["top"] = margin[0]
        returnObj["right"] = margin[0]
        returnObj["bottom"] = margin[0]
    else if margin.count() = 2 or margin.count() = 3
        returnObj["left"] = margin[0]
        returnObj["top"] = margin[1]
        returnObj["right"] = margin[0]
        returnObj["bottom"] = margin[1]
    else if margin.count() = 4
        returnObj["left"] = margin[3]
        returnObj["top"] = margin[0]
        returnObj["right"] = margin[1]
        returnObj["bottom"] = margin[2]
    end if

    return returnObj
end function
