import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub()
        setupItem()
    end sub)
end sub


sub setupItem()
    m.indexLabel = m.top.findNode("label")
    m.container = m.top.findNode("container")
    m.container.opacity = 0.5
    safeObserve("focusPercent", onFocusPercentChange)
end sub


sub itemContentChanged(event)
    content = event.getData()
    m.indexLabel.text = content.title
    stackChildren({ node: m.container, horizontal: true })
    m.container.width = m.container.boundingRect().width
    m.container.height = m.container.boundingRect().height
    exec("registerChildRect", {
        smallSquare: [m.container.width, m.container.height],
        bigSquare: [m.container.width, m.container.height],
        index: m.top.index
    }, top().getParent().getParent())
end sub


sub onFocusPercentChange(options = {})
    focusPercentage = options.data ?? {}
    opacityPercentage = (0.5 * focusPercentage) * focusPercentage + 0.5
    m.container.opacity = opacityPercentage
end sub
