import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub()
        setupItem()
    end sub)
end sub


sub setupItem()
    m.indexLabel = m.top.findNode("label")
    m.container = m.top.findNode("container")
    m.parentList = top().getParent()
    m.flexList = m.parentList.getParent()
    m.colorFieldInterpolator = top().findNode("focusColorInterpolator")
    safeObserve("focusPercent", onFocusPercentChange)
    safeObserve("focusPercent", onGroupFocusPercentChange, m.parentList)
end sub


sub itemContentChanged(event)
    content = event.getData()
    m.indexLabel.text = content.title
    stackChildren({ node: m.container, direction: "horizontal" })
    m.container.width = m.container.boundingRect().width
    m.container.height = m.container.boundingRect().height
    exec("registerChildRect", {
        smallSquare: [m.container.width, m.container.height],
        bigSquare: [m.container.width, m.container.height],
        index: m.top.index
    }, top().getParent().getParent())
end sub


sub onFocusPercentChange(options = {})
    if not top().groupHasFocus then return
    percentage = options.data ?? {}
    m.colorFieldInterpolator.fraction = percentage
end sub


sub onGroupFocusPercentChange(options = {})
    percentage = options.data ?? {}
    if m.parentList.itemFocused = top().index then m.colorFieldInterpolator.fraction = percentage
end sub
