import "pkg:/source/helpers/appUtils.bs"
import "pkg:/source/helpers/timestamps.bs"
import "pkg:/source/plugins/stateable.bs"
import "pkg:/source/plugins/safeable.bs"
import "pkg:/source/roBoilerplate.bs"
import "pkg:/source/wrapperFunctions.bs"
import "pkg:/components/constants.bs"


sub init()
    initFramework(privateFunctions)
    exec("onInit")
end sub


sub runBenchmark(name = "")
    benchmark = createObject("roSGNode", "Benchmark")
    benchmark.run = [name, { top: benchmark }]
end sub


class privateFunctions extends privates
    function onInit(options = {})

        subscribe({
            "TEST_EVENT": "onTestEvent"
        })

        m.top.appendChild(createObject("roSGNode", "NodeTest"))

        m.task = createObject("roSGNode", "TestNode")

        setTimeout(sub(m)
            m.task.control = "run"
        end sub, m, 500)

        ' loadList()
        ' loadPlugin()
        ' runBenchmark("DataSending")
    end function


    function testFunction(options = {})
        ?"testFunction " options
    end function

    function onTheNose(options = {})
        ?"ALMOST PUNCHED " options.name
        return { result: "success" }
    end function
end class


sub onTestEvent(data, msgInfo)
    ?"onTestEvent2 " data
    result = exec("onTheNose", { name: "test" })
    ?"result " result
end sub


function add()
    return "add"
end function


sub loadList()
    rectConfig = {
        "autoclip": true,
        "bigSquare": [251, 321],
        "defaultVisibleIndex": 1,
        "direction": "horizontal",
        "duration": 0.5,
        "flushFocus": false,
        "focusType": "floating",
        "gutterWidth": 0,
        "itemComponentName": "TestItem",
        "margin": [9, 0],
        "smallSquare": [212, 273],
        "visibleTiles": 4,
        "wrap": true
    }

    list = createObject("roSGNode", "MagicList")
    m.top.appendChild(list)

    testModel = createObject("roSGNode", "ContentNode")
    testModel.appendChild(createObject("roSGNode", "ContentNode"))
    testModel.appendChild(createObject("roSGNode", "ContentNode"))
    testModel.appendChild(createObject("roSGNode", "ContentNode"))
    testModel.appendChild(createObject("roSGNode", "ContentNode"))
    testModel.appendChild(createObject("roSGNode", "ContentNode"))
    testModel.appendChild(createObject("roSGNode", "ContentNode"))
    testModel.appendChild(createObject("roSGNode", "ContentNode"))
    testModel.appendChild(createObject("roSGNode", "ContentNode"))

    list.content = testModel
    list.rectConfig = rectconfig
    list.color = "#FFFFFF00"
    list.translation = [399,198]
    list.setFocus(true)
end sub


sub fooFunction(options = {})
    ?"foofFunction " options
end sub
