import "pkg:/components/_ord/wrappers.bs"


sub init()
    exec(sub(_options = {})
        top().backExitsScene = false

        subscribe({
            [events.EVENT_TASK_READY]: onEventTaskReady
        })

        m.layout = top().findNode("layout")

        setFocusMap({
            "onFocus": top().findNode("layout"),
            "onKey": {
                "default": true
            }
        })

        registerControllers([
            "ConfigsController",
            "LayoutController",
            "PlayerController",
            "SocketController",
            "StylesController",
            "UserController"
        ])

        setFocus(m.layout)
    end sub)
end sub


sub onEventTaskReady(_options = {})
    dispatch(events.APP_STARTED)
end sub
