import "pkg:/components/_ord/wrappers.bs"
import "testdata.bs"


sub init()
    exec(sub()
        ?"INIT " m.top.subtype()
        ' m.secondNode = createObject("roSGNode", "SecondNode")

        ' m.secondNode.data = {
        '     azat: "is cool"
        ' }

        ' localResult = onTheNose({ name: "Azat" })
        ' remoteResult = exec("onTheNose", { name: "Azat" }, m.secondNode)
        ' ?"localResult " localResult
        ' ?"remoteResult " remoteResult

        ' set({
        '     "food": "burrito"
        '     "drink": "diet dr pepper"
        ' })

        ' ?"get self " get("food")
        ' ?"get self 2" get(["food", "drink"])
        ' ?"get self 3 " top().drink

        ' set({
        '     "food": "pizza"
        ' }, m.secondNode)

        ' ?"get remote " get("food", m.secondNode)
        ' res2 = get(["food", "someArray"], m.secondNode)
        ' ?"get remote 2 " res2 res2.someArray

        registerControllers([
            "SocketController"
            "StylesController"
        ])

        top().setFocus(true)
        loadList()
        loadSecondList()
        ' loadThirdList()
    end sub)
end sub


sub loadList(options = {})
    list = createObject("roSGNode", "_ord_flexList")
    list.id = "first_list"
    top().appendChild(list)

    testModel = returnModel({ number: 8 })
    testModel.addField("rectConfig", "assocarray", true)
    testModel.addField("totalCount", "integer", false)

    testModel.rectConfig = {
        direction: "horizontal",
        animationDuration: 0.3,
        ' horizAlign: "right",
        ' vertAlign: "top",
        clip: true,
        defaultVisibleIndex: 0,
        focusType: "floating",
        itemComponentName: "TestItem",
        visibleTiles: 4,
        wrap: true,
        flushFocus: false,
        bigSquare: [252, 321],
        gutterSize: 0,
        smallSquare: [213, 273],
        squareMargins: [0]
    }

    testModel.id = "flexCarousel_model"
    testModel.totalCount = testModel.getChildCount()

    list.data = {
        content: testModel
    }

    m.firstList = list
    ' m.firstList.setFocus(true)
end sub


sub loadSecondList(options = {})
    list = createObject("roSGNode", "_ord_flexList")
    list.id = "second_list"
    top().appendChild(list)

    testModel = returnModel({ number: 8 })
    testModel.addField("rectConfig", "assocarray", true)
    testModel.addField("totalCount", "integer", false)

    testModel.rectConfig = {
        direction: "horizontal",
        animationDuration: 0.3,
        ' horizAlign: "right",
        ' vertAlign: "top",
        clip: true,
        defaultVisibleIndex: 0,
        focusType: "floating",
        itemComponentName: "TestItem",
        visibleTiles: 4,
        wrap: true,
        flushFocus: true,
        bigSquare: [252, 321],
        gutterSize: 0,
        smallSquare: [213, 273],
        squareMargins: [0]
    }

    testModel.id = "flexCarousel_model"
    testModel.totalCount = testModel.getChildCount()

    list.data = {
        content: testModel
    }

    m.secondList = list
    m.secondList.setFocus(true)
end sub


sub loadThirdList(options = {})
    list = createObject("roSGNode", "_ord_flexList")
    list.id = "third_list"
    top().appendChild(list)

    testModel = returnDynamicWidthModel()
    testModel.addField("rectConfig", "assocarray", true)
    testModel.addField("totalCount", "integer", false)

    testModel.id = "flexDynamicCarousel_model"
    testModel.totalCount = testModel.getChildCount()

    testModel.rectConfig = {
        direction: "horizontal",
        animationDuration: 0.1,
        ' horizAlign: "right",
        ' vertAlign: "top",
        clip: false,
        defaultVisibleIndex: 0,
        dynamicWidth: true,
        focusType: "floating",
        itemComponentName: "DynamicItem",
        visibleTiles: 6,
        wrap: true,
        flushFocus: true,
        bigSquare: [200, 100],
        gutterSize: 0,
        smallSquare: [200, 100],
        squareMargins: [8]
    }

    list.data = {
        content: testModel
    }

    m.thirdList = list
    ' m.thirdList.setFocus(true)
end sub


function returnModel(options = {})
    numberOfModels = options.number
    testModel = createObject("roSGNode", "ContentNode")
    for i = 1 to numberOfModels
        testModel.appendChild(createObject("roSGNode", "ContentNode"))
    end for
    return testModel
end function


function returnDynamicWidthModel()
    testModel = createObject("roSGNode", "ContentNode")
    titles = ["Home", "Live Channels", "Documentaries", "TV Shows", "Account", "Movies"]
    for each item in titles
        childModel = createObject("roSGNode", "ContentNode")
        childModel.title = item
        testModel.appendChild(childModel)
    end for

    return testModel
end function


function onTheNose(options = {})
    return { result: options.name + " success"  }
end function


function onKeyEvent(key as string, press as boolean) as boolean
    return exec(function(options = {})
        key = options.key
        press = options.press
        m = getGlobalAA()
        if not press then return true

        if key = "down" then m.secondList.setFocus(true)
        if key = "up" then m.firstList.setFocus(true)

        return true
    end function, { key: key, press: press })
end function
