namespace events
    const APP_STARTED = "APP_STARTED"
    const CATALOG_HERO_FOCUSED = "CATALOG_HERO_FOCUSED"
    const CAROUSEL_FOCUSED = "CAROUSEL_FOCUSED"
    const CAROUSEL_ITEM_FOCUSED = "CAROUSEL_ITEM_FOCUSED"
    const CONFIGS_UPDATE = "CONFIGS_UPDATE"
    const CONTENT_DATA_RECEIVED = "CONTENT_DATA_RECEIVED"
    const EVENT_TASK_READY = "EVENT_TASK_READY"
    const GET_CATALOG_DATA = "GET_CATALOG_DATA"
    const GET_CONTENT_DATA = "GET_CONTENT_DATA"
    const GET_SIDEBAR = "GET_SIDEBAR"
    const GET_TOPBAR = "GET_TOPBAR"
    const GET_USER_CAROUSELS = "GET_USER_CAROUSELS"
    const HERO_ITEM_FOCUSED = "HERO_ITEM_FOCUSED"
    const NAVIGATE_TO = "NAVIGATE_TO"
    const PAGINATE_CAROUSEL = "PAGINATE_CAROUSEL"
    const PAGINATE_SCREEN = "PAGINATE_SCREEN"
    const PLAY_VIDEO = "PLAY_VIDEO"
    const SCREEN_DATA_RECEIVED = "SCREEN_DATA_RECEIVED"
    const SIDEBAR_RECEIVED = "SIDEBAR_RECEIVED"
    const TOPBAR_RECEIVED = "TOPBAR_RECEIVED"
    const USER_CAROUSELS_RECEIVED = "USER_CAROUSELS_RECEIVED"
    const REQUEST_STYLES = "REQUEST_STYLES"
    const SCROLL_GROUP_FOCUSED = "SCROLL_GROUP_FOCUSED"
    const SHOW_CATALOG_UI = "SHOW_CATALOG_UI"
    const SHOW_CONTENT_UI = "SHOW_CONTENT_UI"
    const STYLES_UPDATE = "STYLES_UPDATE"
    const REQUEST_CONFIGS = "REQUEST_CONFIGS"
    const TOGGLE_FAVORITE = "TOGGLE_FAVORITE"
    const TOGGLE_WATCHLIST = "TOGGLE_WATCHLIST"
    const USER_LOGGED_IN = "USER_LOGGED_IN"
    const VIDEO_PLAYING = "VIDEO_PLAYING"
    const VIDEO_RESTARTING = "VIDEO_RESTARTING"
    const VIDEO_PAUSED = "VIDEO_PAUSED"
    const VIDEO_ERROR = "VIDEO_ERROR"
    const VIDEO_BUFFERING = "VIDEO_BUFFERING"
    const VIDEO_POSITION_CHANGE = "VIDEO_POSITION_CHANGE"
    const VIDEO_FINISHED = "VIDEO_FINISHED"
    const VIDEO_STOPPED = "VIDEO_STOPPED"
end namespace


namespace carouselTypes
    const CHANNEL = "CHANNEL"
    const CONTINUE_WATCHING = "CONTINUE_WATCHING"
    const EPISODES = "EPISODES"
    const EXTRAS = "EXTRAS"
    const FAVORITES = "FAVORITES"
    const GRID = "GRID"
    const HERO = "HERO"
    const INDEX = "INDEX"
    const RELATED = "RELATED"
    const WATCHLIST = "WATCHLIST"
end namespace


namespace userItemsTypes
    const CWITEM = "CWITEM"
    const FAVORITE = "FAVORITE"
    const WATCHLIST = "WATCHLIST"
end namespace


namespace sections
    const CAROUSEL = "CAROUSEL"
    const HERO = "HERO"
    const CONTENT_HERO = "CONTENT_HERO"
end namespace


namespace sounds
    const SELECT = "select"
    const NAVSINGLE = "navsingle"
    const NAVMULTI = "navmulti"
    const DEADEND = "deadend"
end namespace


enum Icons
    arrowDown = "2"
    arrowLeft = "4"
    arrowRight = "3"
    arrowUp = "1"
    caretDown = "D"
    caretLeft = "L"
    caretRight = "R"
    caretUp = "U"
    cc = "6"
    documentaries = "d"
    ellipsisV = "E"
    ellipsisH = "e"
    favorites = "f"
    genres = "g"
    home = "h"
    info = "I"
    liveTV = "t"
    movies = "m"
    pause = "P"
    play = ">"
    playSquare = "C"
    podcasts = "p"
    remote = "r"
    replay = "@"
    search = "s"
    seekFF = "B"
    seekRW = "A"
    shows = "a"
    sports = "b"
    settings = "S"
    user = "u"
    watchLater = "l"
    watchlist = "w"
end enum
