import "pkg:/components/constants.bs"


sub init()
    ' integerTest = m.top.integerTest
    ' longintegerTest = m.top.longintegerTest
    ' floatTest = m.top.floatTest
    ' stringTest = m.top.stringTest
    ' booleanTest = m.top.booleanTest
    ' vector2dTest = m.top.vector2dTest
    ' colorTest = m.top.colorTest
    ' vector2dTest = m.top.vector2dTest
    ' timeTest = m.top.timeTest
    ' uriTest = m.top.uriTest
    ' nodeTest = m.top.nodeTest
    ' floatarrayTest = m.top.floatarrayTest
    ' intarrayTest = m.top.intarrayTest
    ' boolarrayTest = m.top.boolarrayTest
    ' stringarrayTest = m.top.stringarrayTest
    ' vector2darrayTest = m.top.vector2darrayTest
    ' colorarrayTest = m.top.colorarrayTest
    ' timearrayTest = m.top.timearrayTest
    ' nodearrayTest = m.top.nodearrayTest
    ' assocarrayTest = m.top.assocarrayTest
    ' arrayTest = m.top.arrayTest
    ' rect2dTest = m.top.rect2dTest
    ' rect2darrayTest = m.top.rect2darrayTest

    ' ?"integerTest " integerTest
    ' ?"longintegerTest " longintegerTest
    ' ?"floatTest " floatTest
    ' ?"stringTest " stringTest
    ' ?"booleanTest " booleanTest
    ' ?"vector2dTest " vector2dTest
    ' ?"colorTest " colorTest
    ' ?"timeTest " timeTest
    ' ?"uriTest " uriTest
    ' ?"nodeTest " nodeTest
    ' ?"floatarrayTest " floatarrayTest
    ' ?"intarrayTest " intarrayTest
    ' ?"boolarrayTest " boolarrayTest
    ' ?"stringarrayTest " stringarrayTest
    ' ?"vector2darrayTest " vector2darrayTest
    ' ?"colorarrayTest " colorarrayTest
    ' ?"timearrayTest " timearrayTest
    ' ?"nodearrayTest " nodearrayTest
    ' ?"assocarrayTest " assocarrayTest
    ' ?"arrayTest " arrayTest
    ' ?"rect2dTest " rect2dTest
    ' ?"rect2darrayTest " rect2darrayTest

    test = createObject("roSGNode", "SocketController")

    asd = "sad"
    foo = {}
    bar = []
    baz = m.top
    ?"----------------------------------"
    ?type(asd)
    ?type(foo)
    ?type(bar)
    ?type(baz)
    ?"m.top.get " m.top.getFieldType("assocarrayTest")
    ?"m.top.get " m.top.getFieldType("stringTest")
    ?"m.top.get " m.top.getFieldType("stringTest") = lcase(type(asd))
    ?"m.top.get " m.top.getFieldType("assocarrayTest") = type(foo)
    ?"m.top.get " m.top.getFieldType("arrayTest") = type(bar)
    m.top.arrayTest = foo
end sub

sub anotherFunc()
    ?"anotherFunc "
end sub
