import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.carouselTitle = top().findNode("carouselTitle")
        m.carouselList = top().findNode("carouselList")
        m.titleContainer = top().findNode("titleContainer")
        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)
        setFocusMap({
            "default": m.carouselList
        })
        styleHooks({
            after: afterStyling
        })
    end sub)
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if rodash.isNode(m.content) then return

    data = options.data
    content = data.content
    m.content = content
    m.carouselTitle.text = content.carouselTitle
    m.carouselList.data = data
    thumbnailType = content.thumbnailType

    if rodash.isNonEmptyString(thumbnailType) then addClass(lcase(thumbnailType))

    afterStyling()
    dispatch(events.PAGINATE_CAROUSEL, { collection: content })
end sub


sub afterStyling(options = {})
    stackChildren({ node: m.top, direction: "vertical" })
end sub

