import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.carouselTitle = top().findNode("carouselTitle")
        m.carouselList = top().findNode("carouselList")
        m.titleContainer = top().findNode("titleContainer")
        safeObserve("data", onDataSet)
        safeObserve("itemFocused", onCarouselItemFocused, m.carouselList)
        safeObserve("itemSelected", onCarouselItemSelected, m.carouselList)
        set({
            "hydrated": false
        })
        setFocusMap({
            "onFocus": focusCarousel
        })
        styleHooks({
            "after": afterStyling
        })
    end sub)
end sub


sub focusCarousel(_options = {})
    if not get("hydrated") or not top().hasFocus() then return
    setFocus(m.carouselList)
end sub


sub onCarouselItemFocused(options = {})
    carouselItemFocused = options.data ?? -1
    if carouselItemFocused = -1 then return
    itemModel = m.content.getChild(carouselItemFocused)
    if not rodash.isNode(itemModel) then return
    if m.content.carouselType = carouselTypes.INDEX then dispatch(events.CAROUSEL_ITEM_FOCUSED, { content: itemModel })
    if exec("needsToPaginate", { itemFocused: options.data }, m.content) then dispatch(events.PAGINATE_CAROUSEL, { collection: m.content })
end sub


sub onCarouselItemSelected(options = {})
    selectedChild = options.data
    itemContent = m.content.getChild(selectedChild)
    if not rodash.isNode(itemContent) then return

    if itemContent.type = contentTypes.EPISODE
        dispatch(events.PLAY_VIDEO, { content: itemContent })
    else
        dispatch(events.NAVIGATE_TO, { slug: `/content/${itemContent.id}`, context: { content: itemContent }})
    end if
end sub


sub onDataSet(options = {})
    data = options.data
    content = data.content

    exec("generateDefaultModels", {}, content)

    m.content = content
    m.carouselTitle.text = content.carouselTitle
    m.carouselList.data = { content: content }

    thumbnailType = content.thumbnailType
    if rodash.isNonEmptyString(thumbnailType) then addClass(lcase(thumbnailType))

    afterStyling()
    dispatch(events.PAGINATE_CAROUSEL, { collection: content })

    if content.hydrated ?? false
        onHydrated()
    else
        safeObserve("hydrated", onHydrated, content)
    end if
end sub


sub onHydrated(_options = {})
    set({ "hydrated": true })
end sub


sub afterStyling(_options = {})
    stackChildren({ direction: "vertical" })
end sub
