import "pkg:/components/_ord/init.bs"


sub init()
    exec(sub(_options = {})
        subscribe({
            [events.PLAY_VIDEO]: playVideo,
            [events.VIDEO_BUFFERING]: onVideoBuffering,
            [events.VIDEO_ERROR]: onVideoError,
            [events.VIDEO_FINISHED]: onVideoFinished,
            [events.VIDEO_PAUSED]: onVideoPaused,
            [events.VIDEO_PLAYING]: onVideoPlaying,
            [events.VIDEO_RESTARTING]: onVideoRestarting,
            [events.VIDEO_STOPPED]: onVideoStopped
        })
    end sub)
end sub


sub onVideoBuffering(_options = {})
    ' ?"onVideoBuffering " rodash.now()
end sub


sub onVideoError(_options = {})
    ' ?"onVideoError " rodash.now()
end sub


sub onVideoFinished(_options = {})
    ' ?"onVideoFinished " rodash.now()
end sub


sub onVideoPaused(_options = {})
    ' ?"onVideoPaused " rodash.now()
end sub


sub onVideoPlaying(_options = {})
    ' ?"onVideoPlaying " rodash.now()
end sub


sub onVideoRestarting(_options = {})
    ' ?"onVideoRestarting " rodash.now()
end sub


sub onVideoStopped(_options = {})
    ' ?"onVideoStopped " rodash.now()
end sub


sub playVideo(options = {})
    if not rodash.isNonEmptyAA(options) then return
    content = options.content
    if not rodash.isNode(content) then return

    if content.type = contentTypes.SHOW
        episodeContent = exec("findShowEpisode", {}, content)
        if not rodash.isNode(episodeContent) then return
        exec("playVideo", { content: episodeContent }, layout())
    else
        exec("playVideo", options, layout())
    end if
end sub


function layout()
    return app().findNode("layout")
end function
