sub init()
    m.top.observeFieldScoped("fieldData", "onFieldDataChange")
    m.top.observeFieldScoped("dataArray", "onDataArrayChange")
    m.top.observeFieldScoped("dataRef", "onDataRefChange")
end sub


sub dataFunc(options = {})
    data = options.data
end sub


sub onDataArrayChange(event)
    data = event.getData()
end sub


sub onFieldDataChange(event)
    data = event.getData()
end sub


sub refFunc()
    data = m.top.getRef("dataRef")
end sub


sub onDataRefChange()
    ?"onDataRefChange "
end sub
