import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        setupItem()
        styleHooks({
            after: afterStyling
        })
    end sub)
end sub


sub afterStyling(_options = {})
    onTextChange()
end sub


sub setupItem()
    m.label = top().findNode("label")
    m.icon = top().findNode("icon")
    m.container = top().findNode("textContainer")
    m.tabBackground = top().findNode("tabBackground")
    m.tabTop = top().findNode("tabTop")
    m.tabBottom = top().findNode("tabBottom")
    m.parentList = top().getParent()
    m.flexList = m.parentList.getParent()

    safeObserve("focusPercent", onFocusPercentChange)
    safeObserve("itemContent", itemContentChanged, top())
    safeObserve("currRect", onCurrRectChange, top())
    safeObserve("width", onCurrRectChange, top())
    safeObserve("height", onCurrRectChange, top())
    if rodash.isNode(m.parentList) then safeObserve("focusPercent", onGroupFocusPercentChange, m.parentList)
end sub


sub itemContentChanged(options = {})
    content = options.data
    m.label.text = ucase(content.title)
    m.icon.text = content.iconText ?? ""
    if not rodash.isEmpty(m.icon.text)
        m.icon.visible = true
    end if

    onTextChange()

    if not rodash.isNode(m.parentList) then return

    if top().index = m.parentList.itemFocused then addClass("active", top())
end sub


sub onTextChange(_options = {})
    stackChildren({ node: m.container, direction: "horizontal" })
    tabWidth = m.container.boundingRect().width
    tabHeight = m.container.boundingRect().height
    m.container.width = tabWidth
    m.container.height = tabHeight
    top().width = tabWidth
    top().height = tabHeight

    if not rodash.isNode(m.parentList) then return

    exec("registerChildRect", {
        smallSquare: getFocusedRectSize(),
        bigSquare: getFocusedRectSize(),
        index: top().index
    }, m.parentList.getParent())
end sub


function getFocusedRectSize(_options = {})
    if not rodash.isNode(m.container) then return [0,0]
    return [getVisibleWidth(m.container), getVisibleHeight(m.container)]
end function


sub onCurrRectChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    field = options.field
    if field = "currRect"
        rect = options.data
    else
        rect = top()
    end if

    for each node in [m.container, m.tabTop, m.tabBottom]
        node.width = rect.width
        node.height = rect.height
    end for
end sub


sub onGroupFocusPercentChange(options = {})
    if not m.parentList.itemFocused = top().index then return
    percentage = options.data ?? 0
    m.tabBackground.opacity = 0.5 + (percentage * (0.9 - 0.5))
end sub


sub onFocusPercentChange(options = {})
    percentage = options.data ?? 0
    if not top().groupHasFocus then return
    m.tabBackground.opacity = percentage * 0.9
end sub
