query UserCarousels($documentId: ID!, $sort: [String], $pagination: PaginationArg) {
  usersPermissionsUser(documentId: $documentId) {
    user_carousels {
      documentId
      type
      user_items(sort: $sort, pagination: $pagination) {
        type
        position
        contentId
        content {
          complimentaryColor
          copyrightYear
          description
          documentId
          duration
          v2genres {
            name
          }
          rating
          title
          type
          images {
            imageType
            data {
              url
            }
          }
        }
      }
    }
  }
}
