import "pkg:/components/_ord/wrappers.bs"


sub init()
    exec(sub()
        top().color = "#00000000"
        m.carousel = top().findNode("carousel")
        m.carousel.advancing = true
        m.carousel.reversing = true
        m.carousel.easeFunction = "linear"
        m.carousel.update({ focusPercent: 0.0 }, true)
        m.rectSizes = []
        ' m.carousel.showTargetRects = true

        safeObserve("itemSelected", onItemSelected, m.carousel)
        safeObserve("itemFocused", onItemFocused, m.carousel)
        safeObserve("itemUnfocused", onItemUnfocused, m.carousel)
        safeObserve("focusedChild", onCarouselFocusedChildChange, m.carousel)

        m.initialFocus = m.carousel

        set({ defaultConfig: {
            animationDuration: 0.1,
            bigSquare: [0, 0],
            carouselType: "default",
            clip: true,
            debugClippingRect: false,
            defaultVisibleIndex: 0,
            ' lastIndex: 2,
            direction: "horizontal",
            focusType: "floating",
            gutterSize: 0,
            horizAlign: "center",
            itemComponentName: "",
            maxHeight: 0,
            maxWidth: 0,
            smallSquare: [0, 0],
            squareMargins: [0, 0],
            squareTotalArea: [0, 0],
            startingPositionOffsets: [0],
            uniformCrossAxisSize: false,
            useUnfocusedTargetSet: false,
            vertAlign: "center",
            visibleTiles: 0,
            wrap: false
        }})

        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)

        safeFunctions({
            registerChildRect: registerChildRect
        })

        m.focusTimer = getFloatFieldInterpolator(m.carousel.getChildren(-1, 0))
    end sub)
end sub


function getFloatFieldInterpolator(children = [])
    for each child in children
        if child.subType() = "FloatFieldInterpolator" then return child
        return getFloatFieldInterpolator(child.getChildren(-1, 0))
    end for
    return invalid
end function


sub onCarouselFocusedChildChange(options = {})
    if not rodash.isNode(m.focusTimer) then return
    safeUnobserve("fraction", m.focusTimer)
    safeObserve("fraction", onTestTimerFired, m.focusTimer)
end sub


sub onTestTimerFired(options = {})
    fraction = options.data

    if rodash.isNode(m.focusTimer) and (fraction = 0 or fraction = 1) then safeUnobserve("fraction", m.focusTimer)


    percentage = m.carousel.isInFocusChain() ? fraction : 1 - fraction
    m.carousel.focusPercent = percentage

    ' There is a 100ms delay before
    ' TargetGroup animation starts
    rodash.delay(sub(percentage)
        applyClippingRect({ percentage: percentage })
    end sub, 100, percentage)
end sub


function onKeyEvent(key as string, press as boolean) as boolean
    return exec(function(options = {})
        carousel = options.carousel
        key = options.key
        press = options.press

        if not press then return true
        if not rodash.isArray(m.focusedTargetSetArray) then return true
        if not rodash.isNode(carousel) then return true

        if calculate.floatMOD(carousel.currFocusItemIndex, 1) <> 0 then return true
        if key <> top().advanceKey and key <> top().reverseKey then return false

        direction = key = top().reverseKey ? -1 : 1
        currentIndex = top().focusedContentIndex
        lastFocusableIndex = get("lastFocusableIndex")
        nextIndex = currentIndex + direction
        currentTargetSetIndex = top().focusedTargetsetIndex
        nextTargetSetIndex = currentTargetSetIndex + direction

        if nextTargetSetIndex <= 0 then nextTargetSetIndex = 0
        if nextTargetSetIndex >= lastFocusableIndex then nextTargetSetIndex = lastFocusableIndex

        if carousel.content.getChild(nextIndex) = invalid
            if not get("wrap") then return false

            if direction = 1
                nextIndex = 0
                nextTargetSetIndex = 0
            else
                profilesCollection = carousel.content
                if not rodash.isNode(profilesCollection) then return true
                nextIndex = profilesCollection.getChildCount() - 1
                nextTargetSetIndex = m.focusedTargetSetArray.count() - 1
            end if
        end if

        nextTargetSet = m.focusedTargetSetArray[nextTargetSetIndex]

        if nextTargetSet <> invalid and carousel.currTargetSet <> invalid and nextTargetSet.focusIndex <> carousel.currTargetSet.focusIndex
            carousel.animateToTargetSet = nextTargetSet
            top().focusedTargetsetIndex = nextTargetSetIndex
        end if

        carousel.animateToItem = nextIndex
        top().focusedContentIndex = nextIndex

        return true
    end function, { carousel: m.carousel, key: key, press: press })
end function


sub applyClippingRect(options = {})
    if not get("clip") then return

    percentage = options.percentage
    percentage = percentage < 0 ? 0 : percentage
    percentage = percentage > 1 ? 1 : percentage
    direction = get("direction") ?? "horizontal"
    horizontal = direction = "horizontal"
    focusedClippingRect = get("focusedClippingRect")
    unfocusedClippingRect = get("unfocusedClippingRect")

    if focusedClippingRect = invalid then return
    if unfocusedClippingRect = invalid then return

    deltaX = focusedClippingRect[0] - unfocusedClippingRect[0]
    deltaY = focusedClippingRect[1] - unfocusedClippingRect[1]
    deltaWidth = focusedClippingRect[2] - unfocusedClippingRect[2]
    deltaHeight = focusedClippingRect[3] - unfocusedClippingRect[3]

    newClippingRect = [
        deltaX * percentage + unfocusedClippingRect[0],
        deltaY * percentage + unfocusedClippingRect[1],
        deltaWidth * percentage + unfocusedClippingRect[2],
        deltaHeight * percentage + unfocusedClippingRect[3]
    ]

    if horizontal
        newClippingRect[2] -= (deltaX * percentage + unfocusedClippingRect[0])
    else
        newClippingRect[3] -= (deltaY * percentage + unfocusedClippingRect[1])
    end if

    if get("debugClippingRect")
        if m.clippingRectOutline = invalid
            m.clippingRectOutline = top().findNode("clippingRectOutline")
            m.clippingRectOutline.visible = true
        end if
        m.clippingRectOutline.width = newClippingRect[2]
        m.clippingRectOutline.height = newClippingRect[3]
        m.clippingRectOutline.translation = [newClippingRect[0], newClippingRect[1]]
    end if

    top().width = newClippingRect[2]
    top().height = newClippingRect[3]
    top().clippingRect = newClippingRect
end sub


function applyGutters(options = {})
    if not rodash.isNonEmptyAA(options) then return [0,0,0,0]
    clippingRect = options.clippingRect ?? [0,0,0,0]
    direction = options.direction ?? "horizontal"
    horizontal = direction = "horizontal"
    gutters = options.gutters ?? calculate.quadruple({ value: 0 })

    clippingRect[0] -= gutters.left
    clippingRect[1] -= gutters.top
    clippingRect[2] += gutters.right
    clippingRect[3] += gutters.bottom

    if horizontal
        clippingRect[3] += gutters.top
    else
        clippingRect[2] += gutters.left
    end if

    return clippingRect
end function


sub setClippingRects(options = {})
    if not rodash.isNonEmptyAA(options) then return
    clippingRects = options.clippingRects ?? {}
    direction = options.direction
    dynamicSize = options.dynamicSize ?? false
    gutters = options.gutters
    horizontal = direction = "horizontal"
    maxHeight = options.maxHeight ?? 0
    maxWidth = options.maxWidth ?? 0
    index = horizontal ? 2 : 3
    maxPrimarySize = horizontal ? maxWidth : maxHeight

    unfocusedClippingRect = clippingRects.shift()
    focusedClippingRect = clippingRects[0]

    if dynamicSize
        focusedClippingRect[index] = focusedClippingRect[index] > maxPrimarySize ? maxPrimarySize : focusedClippingRect[index]
        unfocusedClippingRect[index] = unfocusedClippingRect[index] > maxPrimarySize ? maxPrimarySize : unfocusedClippingRect[index]
    end if

    set({
        unfocusedClippingRect: applyGutters({
            clippingRect: unfocusedClippingRect,
            direction: direction,
            gutters: gutters
        })
    })

    for each clippingRect in clippingRects
        if clippingRect[2] > focusedClippingRect[2] then focusedClippingRect[2] = clippingRect[2]
    end for

    set({
        focusedClippingRect: applyGutters({
            clippingRect: focusedClippingRect,
            direction: direction,
            gutters: options.gutters
        })
    })
end sub


sub onFocusedChildChange(options = {})
    node = options.data
    currentIndex = top().focusedContentIndex
    if m.content = invalid then return

    unfocused = node = invalid or not node.isSameNode(m.top) and not top().isInFocusChain()

    if not rodash.isNode(m.carousel.targetSet) then return

    if unfocused
        dynamicSize = get("dynamicSize") ?? false
        useUnfocusedTargetSet = get("useUnfocusedTargetSet") ?? false

        if m.unFocusedTargetSet = invalid then return
        unFocusedTargetSet = dynamicSize and not useUnfocusedTargetSet ? m.carousel.targetSet : m.unFocusedTargetSet

        unFocusedTargetSet.focusIndex = m.carousel.targetSet.focusIndex
        rodash.delay(sub(args)
            args[0].animateToTargetSet = args[1]
        end sub, 100, [m.carousel, unFocusedTargetSet])
        m.carousel.animateToItem = currentIndex
        return
    end if

    if not rodash.isArray(m.focusedTargetSetArray) then return

    currentTargetSet = m.focusedTargetSetArray[top().focusedTargetsetIndex]
    m.carousel.animateToItem = currentIndex

    rodash.delay(sub(args)
        args[0].animateToTargetSet = args[1]
    end sub, 100, [m.carousel, currentTargetSet])

    m.carousel.setFocus(true)
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return

    data = options.data ?? {}
    content = data.content
    if not rodash.isNode(content) then return

    safeObserve("totalCount", onTotalCountChange, content)
    safeObserve("rectConfig", processConfig, content)

    m.content = content
    m.carousel.content = content
    m.carousel.itemComponentName = content.rectConfig.itemComponentName

    if content.rectConfig.carouselType = "dynamicSize"
        rects = []
        for x = 0 to m.content.getChildCount() -1
            rects.push({
                height: 1,
                width: 1,
                x: 0,
                y: 0
            })
        end for
        unFocusedTargetSet = createTargetSet({
            focusIndex: 0,
            targetRects: rects
        })
        m.carousel.targetSet = unFocusedTargetSet
    else
        processConfig({ data: content.rectConfig })
    end if
end sub


sub onTotalCountChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    totalCarouselItems = options.data
    if rodash.isNumber(totalCarouselItems) then set({ totalCarouselItems: totalCarouselItems })
    processConfig()
end sub


sub onItemFocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    m.top.itemFocused = options.data
end sub


sub onItemSelected(options = {})
    if not rodash.isNonEmptyAA(options) then return
    m.top.itemSelected = options.data
end sub


sub onItemUnfocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    m.top.itemUnfocused = options.data
end sub


sub processConfig(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.content) then return

    defaultConfig = get("defaultConfig")
    config = {}
    config.append(defaultConfig)
    config.append(options.data ?? {})

    dynamicSize = config.carouselType = "dynamicSize"
    flushFocus = config.carouselType = "flushFocus"
    totalCarouselItems = m.content.totalCount ?? 0
    margins = calculate.quadruple({ value: config.squareMargins })
    gutters = calculate.quadruple({ value: config.gutterSize })

    rectSizes = processRectSizes({
        bigSquare: config.bigSquare,
        margins: margins,
        smallSquare: config.smallSquare
    })

    extraRects = calculate.extraRectNumber({
        direction: config.direction,
        dynamicSize: dynamicSize,
        gutters: gutters,
        rectSizes: rectSizes
    })
    visibleWindow = calculate.visibleWindow({
        defaultVisibleIndex: config.defaultVisibleIndex ?? 0,
        extraRects: extraRects,
        totalCarouselItems: totalCarouselItems,
        visibleTiles: config.visibleTiles
    })
    totalRects = calculate.totalCarouselRects({
        extraRects: extraRects,
        visibleTiles: visibleWindow.visibleTiles
    })

    focusableIndexArray = visibleWindow.focusableIndexArray
    firstFocusableIndex = visibleWindow.firstFocusableIndex
    lastFocusableIndex = visibleWindow.lastFocusableIndex

    generateRects({
        carouselType: config.carouselType,
        defaultVisibleIndex: config.defaultVisibleIndex,
        direction: config.direction,
        dynamicSize: dynamicSize,
        extraRects: extraRects,
        firstFocusableIndex: firstFocusableIndex,
        flushFocus: flushFocus,
        focusType: config.focusType,
        gutters: gutters,
        horizAlign: config.horizAlign,
        lastFocusableIndex: lastFocusableIndex,
        margins: margins,
        maxHeight: config.maxHeight,
        maxWidth: config.maxWidth,
        rectSizes: rectSizes,
        startingPositionOffsets: config.startingPositionOffsets,
        uniformCrossAxisSize: config.uniformCrossAxisSize,
        totalRects: totalRects,
        vertAlign: config.vertAlign
    })

    setListContent({
        animationDuration: config.animationDuration,
        itemComponentName: config.itemComponentName
    })

    if config.direction = "vertical"
        top().reverseKey = "up"
        top().advanceKey = "down"
    else
        top().reverseKey = "left"
        top().advanceKey = "right"
    end if

    set({
        clip: config.clip,
        debugClippingRect: config.debugClippingRect,
        direction: config.direction,
        dynamicSize: dynamicSize,
        extraRects: extraRects,
        focusableIndexArray: focusableIndexArray,
        gutters: gutters,
        lastFocusableIndex: lastFocusableIndex,
        useUnfocusedTargetSet: config.useUnfocusedTargetSet,
        wrap: config.wrap
    })

    applyClippingRect({ percentage: 0 })
end sub


function processRectSizes(options = {})
    bigSquare = options.bigSquare
    margins = options.margins
    smallSquare = options.smallSquare
    rectSizes = m.rectSizes ?? []

    if not rodash.isNonEmptyArray(rectSizes)
        rectSizes = [{
            bigSquare: bigSquare,
            smallSquare: smallSquare
        }]
    end if

    for each rectSet in rectSizes
        rectSet.totalArea = calculate.squareTotalArea({
            bigSquare: rectSet.bigSquare,
            margins: margins
        })
    end for

    return rectSizes
end function


sub registerChildRect(options = {})
    m.rectSizes[options.index] = {
        smallSquare: options.smallSquare,
        bigSquare: options.bigSquare
    }
    if m.rectSizes.count() = m.content.getChildCount()
        processConfig({ data: m.content.rectConfig })
    end if
end sub


sub setListContent(options = {})
    m.carousel.content = m.content
    m.carousel.itemComponentName = options.itemComponentName
    m.carousel.duration = options.animationDuration ?? 0.3
end sub


sub generateRects(options = {})
    carouselType = options.carouselType
    defaultVisibleIndex = options.defaultVisibleIndex
    direction = options.direction
    dynamicSize = options.dynamicSize
    extraRects = options.extraRects
    firstFocusableIndex = options.firstFocusableIndex
    flushFocus = options.flushFocus
    focusType = options.focusType
    gutters = options.gutters
    lastFocusableIndex = options.lastFocusableIndex
    maxHeight = options.maxHeight ?? 0
    maxWidth = options.maxWidth ?? 0

    if carouselType = "flushFocus"
        rects = returnFlushRects({
            direction: direction,
            extraRects: extraRects,
            horizAlign: options.horizAlign,
            margins: options.margins,
            rectSizes: options.rectSizes,
            startingPositionOffsets: options.startingPositionOffsets,
            totalRects: options.totalRects,
            vertAlign: options.vertAlign
        })
    else if carouselType = "dynamicSize"
        rects = returnDynamicRects({
            direction: direction,
            extraRects: extraRects,
            gutters: gutters,
            horizAlign: options.horizAlign,
            margins: options.margins,
            maxHeight: maxHeight,
            maxWidth: maxWidth,
            rectSizes: options.rectSizes,
            startingPositionOffsets: options.startingPositionOffsets,
            totalRects: options.totalRects,
            uniformCrossAxisSize: options.uniformCrossAxisSize,
            vertAlign: options.vertAlign
        })
    else
        rects = returnDefaultRects({
            direction: direction,
            extraRects: extraRects,
            horizAlign: options.horizAlign,
            margins: options.margins,
            rectSizes: options.rectSizes,
            startingPositionOffsets: options.startingPositionOffsets,
            totalRects: options.totalRects,
            vertAlign: options.vertAlign
        })
    end if

    targetsetRects = rects.targetsetRects
    clippingRects = rects.clippingRects

    unfocusedRects = targetsetRects.shift()
    setUnfocusedTargetSet({
        defaultVisibleIndex: defaultVisibleIndex,
        dynamicSize: dynamicSize,
        extraRects: extraRects,
        flushFocus: flushFocus,
        unfocusedRects: unfocusedRects
    })

    setClippingRects({
        clippingRects: clippingRects,
        direction: direction,
        dynamicSize: dynamicSize,
        gutters: gutters,
        maxHeight: maxHeight,
        maxWidth: maxWidth
    })
    ' Array of targetsets for each focused position in the list.
    m.focusedTargetSetArray = []

    if focusType = "fixed"
        index = defaultVisibleIndex + extraRects
        focusedTargetSet = createTargetSet({
            focusIndex: index,
            targetRects: targetsetRects[index]
        })
        m.focusedTargetSetArray.push(focusedTargetSet)
    else
        for index = 0 to targetsetRects.count() - 1
            focusedTargetSet = createObject("roSGNode", "TargetSet")

            if index >= firstFocusableIndex and index <= lastFocusableIndex
                focusedTargetSet = createTargetSet({
                    focusIndex: index,
                    targetRects: targetsetRects[index]
                })
                m.focusedTargetSetArray.push(focusedTargetSet)
            end if
        end for
    end if

    m.targetsetRects = targetsetRects
end sub


sub setUnfocusedTargetSet(options = {})
    defaultVisibleIndex = options.defaultVisibleIndex
    dynamicSize = options.dynamicSize
    extraRects = options.extraRects
    unfocusedRects = options.unfocusedRects

    if dynamicSize or not rodash.isNode(m.carousel.targetSet)
        ' Peel off the first array, which should always be for unfocused targetset
        unFocusedTargetSet = createTargetSet({
            focusIndex: defaultVisibleIndex + extraRects,
            targetRects: unfocusedRects
        })
        ' Set the initial targetset of the list to the unfocused one
        m.carousel.targetSet = unFocusedTargetSet
        m.unFocusedTargetSet = unFocusedTargetSet
    end if
end sub


function createTargetset(options = {})
    targetSet = createObject("roSGNode", "TargetSet")
    targetSet.update(options)
    return targetSet
end function


function returnDefaultRects(options = {})
    direction = options.direction
    extraRects = options.extraRects
    horizAlign = options.horizAlign
    margins = options.margins
    rectSizes = options.rectSizes
    startingPositionOffsets = options.startingPositionOffsets
    totalRects = options.totalRects
    vertAlign = options.vertAlign
    horizontal = direction = "horizontal"
    targetRectIndex = horizontal ? 0 : 1

    clippingRects = []
    targetsetRects = []

    for y = -1 to totalRects - 1
        focusedTile = y
        targetRects = []
        clippingRect = [0, 0, 0, 0]
        startingPosition = 0

        for x = 0 to totalRects - 1
            rectSize = rectSizes[x] ?? rectSizes[0]
            bigSquare = rectSize.bigSquare
            smallSquare = rectSize.smallSquare
            totalArea = rectSize.totalArea
            lastVisibleIndex = totalRects - (extraRects * 2)
            adjustedIndex = x + extraRects * -1
            startingPositionOffset = startingPositionOffsets[adjustedIndex]
            if rodash.isNumber(startingPositionOffset) then startingPosition += startingPositionOffset

            adjustedPosition = startingPosition - (extraRects * totalArea[targetRectIndex])
            deltaArray = calculate.alignmentOffsets({
                bigSquare: bigSquare,
                horizAlign: horizAlign,
                smallSquare: smallSquare,
                vertAlign: vertAlign
            })
            square = x = focusedTile ? bigSquare : smallSquare

            containerPosition = [0, 0]
            containerPosition[targetRectIndex] = adjustedPosition

            offsetX = x = focusedTile ? margins.left : deltaArray[0] + margins.left
            offsetY = x = focusedTile ? margins.top : deltaArray[1] + margins.top

            targetRect = {
                x: containerPosition[0] + offsetX,
                y: containerPosition[1] + offsetY,
                width: square[0],
                height: square[1]
            }
            targetRects.push(targetRect)

            clippingRect = calculate.extendLinearClippingRect({
                existingClippingRect: clippingRect,
                horizontal: horizontal,
                lastVisibleIndex: lastVisibleIndex,
                rectIndex: x,
                startingPosition: startingPosition,
                totalArea: totalArea
            })

            startingPosition += totalArea[targetRectIndex]
        end for

        targetsetRects.push(targetRects)
        clippingRects.push(clippingRect)
    end for

    return {
        "targetsetRects": targetsetRects,
        "clippingRects": clippingRects
    }
end function


function returnFlushRects(options = {})
    direction = options.direction
    extraRects = options.extraRects
    horizAlign = options.horizAlign
    margins = options.margins
    rectSizes = options.rectSizes
    startingPositionOffsets = options.startingPositionOffsets
    totalRects = options.totalRects
    vertAlign = options.vertAlign

    horizontal = direction = "horizontal"
    primaryArrayIndex = horizontal ? 0 : 1
    primaryLeadingMargin = horizontal ? margins.left : margins.top
    primaryMarginSize = horizontal ? margins.left + margins.right : margins.top + margins.bottom
    secondaryArrayIndex = horizontal ? 1 : 0
    targetRectIndex = horizontal ? 0 : 1

    clippingRects = []
    targetsetRects = []

    for y = -1 to totalRects - 1
        focusedTile = y
        targetRects = []
        clippingRect = [0, 0, 0, 0]
        startingPosition = 0

        for x = 0 to totalRects - 1
            adjustedIndex = x + extraRects * -1
            startingPositionOffset = startingPositionOffsets[adjustedIndex]
            if rodash.isNumber(startingPositionOffset) then startingPosition += startingPositionOffset

            rectSize = rectSizes[x] ?? rectSizes[0]
            bigSquare = rectSize.bigSquare
            smallSquare = rectSize.smallSquare
            deltaArray = calculate.alignmentOffsets({
                bigSquare: bigSquare,
                horizAlign: horizAlign,
                smallSquare: smallSquare,
                vertAlign: vertAlign
            })
            square = x = focusedTile ? bigSquare : smallSquare

            adjustedPosition = startingPosition - (extraRects * (smallSquare[targetRectIndex] + primaryMarginSize))

            containerPosition = [0, 0]

            containerPosition[primaryArrayIndex] = adjustedPosition + primaryLeadingMargin
            containerPosition[secondaryArrayIndex] = deltaArray[secondaryArrayIndex]

            if focusedTile = -1
                containerPosition[primaryArrayIndex] += deltaArray[primaryArrayIndex] / 2
            else if x = focusedTile
                containerPosition[secondaryArrayIndex] = 0
            end if

            targetRect = {
                x: containerPosition[0],
                y: containerPosition[1],
                width: square[0],
                height: square[1]
            }

            targetRects.push(targetRect)

            startingPosition += square[targetRectIndex] + primaryMarginSize

            clippingRect = calculate.dynamicClippingRect({
                existingClippingRect: clippingRect,
                firstVisibleIndex: extraRects,
                horizontal: horizontal,
                lastVisibleIndex: totalRects - extraRects - 1,
                rectIndex: x,
                targetRect: targetRect,
                targetSetIndex: y
            })
        end for

        clippingRects.push(clippingRect)
        targetsetRects.push(targetRects)
    end for

    return {
        "targetsetRects": targetsetRects,
        "clippingRects": clippingRects
    }
end function


function returnDynamicRects(options = {})
    direction = options.direction
    extraRects = options.extraRects
    gutters = options.gutters
    horizAlign = options.horizAlign
    margins = options.margins
    maxHeight = options.maxHeight ?? 0
    maxWidth = options.maxWidth ?? 0
    rectSizes = options.rectSizes
    startingPositionOffsets = options.startingPositionOffsets
    totalRects = options.totalRects
    uniformCrossAxisSize = options.uniformCrossAxisSize ?? false
    vertAlign = options.vertAlign

    targetsetRects = []
    clippingRects = []

    horizontal = direction = "horizontal"
    crossAxisIndex = horizontal ? 1 : 0
    maxCrossAxisSize = 0
    targetRectIndex = horizontal ? 0 : 1
    targetAxis = horizontal ? "x" : "y"
    targetDimension = horizontal ? "width" : "height"
    targetCrossDimension = horizontal ? "height" : "width"

    for each rectSize in rectSizes
        if rodash.isNonEmptyAA(rectSize)
            bigSquare = rectSize.bigSquare ?? [0, 0]
            smallSquare = rectSize.smallSquare ?? [0, 0]

            if bigSquare[crossAxisIndex] > maxCrossAxisSize then maxCrossAxisSize = bigSquare[crossAxisIndex]
            if smallSquare[crossAxisIndex] > maxCrossAxisSize then maxCrossAxisSize = smallSquare[crossAxisIndex]
        end if
    end for

    ' -1 because we want to generate the unfocused state as first array
    for y = -1 to totalRects - 1
        targetRects = []
        clippingRect = [0, 0, 0, 0]
        startingPosition = 0

        for x = 0 to totalRects - 1
            rectSize = rectSizes[x] ?? rectSizes[0]
            totalArea = rectSize.totalArea
            adjustedIndex = x + extraRects * -1
            rect = rectSizes[adjustedIndex]
            lastVisibleIndex = totalRects - (extraRects * 2)
            startingPositionOffset = startingPositionOffsets[adjustedIndex]
            if rodash.isNumber(startingPositionOffset) then startingPosition += startingPositionOffset

            if not rodash.isNonEmptyAA(rect) then rect = {
                bigSquare: [0, 0],
                smallSquare: [0, 0]
            }

            square = x <> y or y = -1 ? rect.smallSquare : rect.bigSquare

            containerPosition = [0, 0]
            alignmentBounds = horizontal ? [square[0], maxCrossAxisSize] : [maxCrossAxisSize, square[1]]
            deltaArray = calculate.alignmentOffsets({
                bigSquare: alignmentBounds,
                horizAlign: horizAlign,
                smallSquare: square,
                vertAlign: vertAlign
            })

            if horizontal
                containerPosition[1] = deltaArray[1]
            else
                containerPosition[0] = deltaArray[0]
            end if

            if horizontal
                containerPosition[targetRectIndex] = startingPosition + margins.left + margins.right
            else
                containerPosition[targetRectIndex] = startingPosition + margins.top + margins.bottom
            end if

            targetRect = {
                height: square[1] ?? 0,
                width: square[0] ?? 0,
                x: containerPosition[0],
                y: containerPosition[1]
            }

            if y <> -1 and uniformCrossAxisSize
                targetRect[targetCrossDimension] = maxCrossAxisSize
            end if

            targetRects.push(targetRect)
            startingPosition = targetRect[targetAxis] + targetRect[targetDimension]

            clippingRect = calculate.extendLinearClippingRect({
                existingClippingRect: clippingRect,
                horizontal: horizontal,
                lastVisibleIndex: lastVisibleIndex,
                rectIndex: x,
                startingPosition: startingPosition,
                totalArea: y = -1 ? square : totalArea
            })
        end for

        if y <> -1
            if horizontal
                clippingRect[3] = maxCrossAxisSize
            else
                clippingRect[2] = maxCrossAxisSize
            end if
        end if

        clippingRects.push(clippingRect)

        targetRects = calculate.adjustedDynamicRects({
            direction: direction,
            gutters: gutters,
            maxHeight: maxHeight,
            maxWidth: maxWidth,
            targetRects: targetRects,
            targetSetIndex: y
        })

        targetsetRects.push(targetRects)
    end for

    return {
        "targetsetRects": targetsetRects,
        "clippingRects": clippingRects
    }
end function


namespace calculate
    function adjustedDynamicRects(options = {})
        direction = options.direction
        gutters = options.gutters
        horizontal = direction = "horizontal"
        maxHeight = options.maxHeight ?? 0
        maxWidth = options.maxWidth ?? 0
        maxPrimarySize = horizontal ? maxWidth : maxHeight
        targetRects = options.targetRects ?? {}
        targetSetIndex = options.targetSetIndex ?? {}
        targetAxis = horizontal ? "x" : "y"
        targetDimension = horizontal ? "width" : "height"
        guttersKey = horizontal ? "right" : "bottom"

        if targetSetIndex = -1 then return targetRects
        if maxPrimarySize <= 0 then return targetRects

        itemThreshold = targetRects[targetSetIndex][targetAxis] + targetRects[targetSetIndex][targetDimension]

        adjustedRects = []

        if itemThreshold < maxPrimarySize then return targetRects

        sizeDelta = maxPrimarySize - itemThreshold
        sizeDelta -= gutters[guttersKey]

        for each rect in targetRects
            newRect = {}
            newRect.append(rect)
            newRect[targetAxis] += sizeDelta
            adjustedRects.push(newRect)
        end for

        return adjustedRects
    end function


    function alignmentOffsets(options = {})
        bigSquare = options.bigSquare ?? [0, 0]
        horizAlign = options.horizAlign ?? "center"
        smallSquare = options.smallSquare ?? [0, 0]
        vertAlign = options.vertAlign ?? "center"

        if horizAlign = "left"
            deltaX = 0
        else if horizAlign = "right"
            deltaX = bigSquare[0] - smallSquare[0]
        else
            deltaX = (bigSquare[0] - smallSquare[0]) / 2
        end if

        if vertAlign = "top"
            deltaY = 0
        else if vertAlign = "bottom"
            deltaY = bigSquare[1] - smallSquare[1]
        else
            deltaY = (bigSquare[1] - smallSquare[1]) / 2
        end if

        return [deltaX, deltaY]
    end function


    function dynamicClippingRect(options = {})
        clippingRect = options.existingClippingRect
        firstVisibleIndex = options.firstVisibleIndex
        horizontal = options.horizontal
        lastVisibleIndex = options.lastVisibleIndex
        rectIndex = options.rectIndex
        targetRect = options.targetRect
        targetSetIndex = options.targetSetIndex

        ' clippingRect = [0, 0, 0, 0]

        if targetSetIndex = -1
            if rectIndex = firstVisibleIndex
                if targetRect.x >= 0 and targetRect.x > clippingRect[0] then clippingRect[0] = targetRect.x
                if targetRect.y >= 0 and targetRect.y > clippingRect[1] then clippingRect[1] = targetRect.y
            end if

            if rectIndex <= lastVisibleIndex
                if horizontal
                    rectsLastX = targetRect.width + targetRect.x
                else
                    rectsLastX = targetRect.width
                end if

                if clippingRect[2] < rectsLastX then clippingRect[2] = rectsLastX

                if horizontal
                    rectsLastY = targetRect.height
                else
                    rectsLastY = targetRect.height + targetRect.y
                end if

                if clippingRect[3] < rectsLastY then clippingRect[3] = rectsLastY
            end if
        else if targetSetIndex <> -1 and rectIndex <= lastVisibleIndex
            clippingRect[0] = 0
            clippingRect[1] = 0

            if horizontal
                rectsLastX = targetRect.width + targetRect.x
            else
                rectsLastX = targetRect.width
            end if

            if clippingRect[2] < rectsLastX then clippingRect[2] = rectsLastX

            if horizontal
                rectsLastY = targetRect.height
            else
                rectsLastY = targetRect.y + targetRect.height
            end if

            if clippingRect[3] < rectsLastY then clippingRect[3] = rectsLastY
        end if

        return clippingRect
    end function


    function extendLinearClippingRect(options = {})
        clippingRect = options.existingClippingRect ?? [0, 0, 0, 0]
        horizontal = options.horizontal ?? false
        lastVisibleIndex = options.lastVisibleIndex ?? -1
        rectIndex = options.rectIndex ?? -1
        startingPosition = options.startingPosition ?? 0
        totalArea = options.totalArea ?? [0, 0]

        if rectIndex > lastVisibleIndex then return clippingRect

        if horizontal
            clippingRect[2] = startingPosition
            clippingRect[3] = totalArea[1]
        else
            clippingRect[2] = totalArea[0]
            clippingRect[3] = startingPosition
        end if

        return clippingRect
    end function


    ' Get the number of extra hidden rects
    ' for *each side* of the carousel
    ' meaning ultimately it will be n*2
    function extraRectNumber(options = {})
        if not rodash.isNonEmptyAA(options) then return 0

        direction = options.direction
        dynamicSize = options.dynamicSize ?? false
        gutters = options.gutters
        horizontal = direction = "horizontal"
        rectSizes = options.rectSizes
        squareArea = rectSizes[0].totalArea ?? [0, 0]
        defaultExtraRect = 1
        if not rodash.isNonEmptyArray(squareArea) then return 0
        if dynamicSize then return 1
        ' If there is a gutter, meaning partially visible rects
        ' on each side of the carousel,
        ' then we need to add an extra rects
        ' in order to smoothly load the partially visible rect.

        gutterSize = 0

        if horizontal
            gutterSize = gutters.left > gutters.right ? gutters.left : gutters.right
        else
            gutterSize = gutters.top > gutters.bottom ? gutters.top : gutters.bottom
        end if

        if gutterSize <= 0 then return defaultExtraRect

        rectSize = squareArea[horizontal ? 0 : 1]
        percentageOfSquareAsGutter = gutterSize / rectSize
        numberOfVisibleGutterSquares = int(percentageOfSquareAsGutter) + 1

        return numberOfVisibleGutterSquares + defaultExtraRect
    end function


    function floatMod(x as dynamic, y as dynamic)
        if y = 0 then return 0
        a = abs(x)
        b = abs(y)
        remainder = a - (int(a/b) * b)
        return remainder * sgn(x)
    end function


    function quadruple(options = {})
        returnObj = {
            "left": 0,
            "top": 0,
            "right": 0,
            "bottom": 0
        }
        if not rodash.isNonEmptyAA(options) then return returnObj

        if rodash.isNumber(options.value)
            value = [options.value]
        else
            value = options.value ?? [0]
        end if

        if value.count() = 1
            returnObj["left"] = value[0]
            returnObj["top"] = value[0]
            returnObj["right"] = value[0]
            returnObj["bottom"] = value[0]
        else if value.count() = 2 or value.count() = 3
            returnObj["left"] = value[0]
            returnObj["top"] = value[1]
            returnObj["right"] = value[0]
            returnObj["bottom"] = value[1]
        else if value.count() = 4
            returnObj["left"] = value[3]
            returnObj["top"] = value[0]
            returnObj["right"] = value[1]
            returnObj["bottom"] = value[2]
        end if

        return returnObj
    end function


    function rectStartingPosition(options = {})
        coordinates = [0, 0]
        if not rodash.isNonEmptyAA(options) then return coordinates

        ' Because some of the tiles will be hidden
        extraRects = options.extraRects
        horizontal = options.horizontal ?? false
        index = options.index ?? 0
        rect = options.square ?? {}
        ' We need to adjust the index based on the extraRects
        adjustedIndex = index + extraRects * -1

        if rodash.isEmpty(rect) then return coordinates

        if horizontal
            coordinates[0] = adjustedIndex * rect.width
        else
            coordinates[1] = adjustedIndex * rect.height
        end if

        return coordinates
    end function


    function squareTotalArea(options = {})
        if not rodash.isNonEmptyAA(options) then return 0

        bigSquare = options.bigSquare
        squareMargins = options.margins

        return [
            bigSquare[0] + squareMargins.left + squareMargins.right,
            bigSquare[1] + squareMargins.top + squareMargins.bottom
        ]
    end function


    function totalCarouselRects(options = {})
        if not rodash.isNonEmptyAA(options) then return 0
        extraRects = options.extraRects ?? 0
        visibleTiles = options.visibleTiles ?? {}
        return visibleTiles + (extraRects * 2)
    end function


    function visibleWindow(options = {})
        if not rodash.isNonEmptyAA(options) then return {
            firstFocusableIndex: 0,
            focusableIndexArray: [0, 0],
            lastFocusableIndex: 0,
            visibleTiles: 0
        }

        defaultVisibleIndex = options.defaultVisibleIndex ?? 0
        extraRects = options.extraRects ?? 0
        configMaxTiles = options.visibleTiles ?? 0
        totalCarouselItems = options.totalCarouselItems ?? 0
        visibleTiles = totalCarouselItems < configMaxTiles ? totalCarouselItems : configMaxTiles

        firstFocusableIndex = defaultVisibleIndex + extraRects
        lastFocusableIndex = visibleTiles - 1 + extraRects

        return {
            firstFocusableIndex: firstFocusableIndex,
            focusableIndexArray: [firstFocusableIndex, lastFocusableIndex],
            lastFocusableIndex: lastFocusableIndex,
            visibleTiles: visibleTiles
        }
    end function
end namespace
