import "pkg:/components/_ord/wrappers.bs"


sub init()
    exec(sub()
        m.carousel = top().findNode("carousel")
        m.carousel.advancing = true
        m.carousel.reversing = true
        m.carousel.easeFunction = "linear"
        m.rectSizes = []
        ' m.carousel.showTargetRects = true

        safeObserve("itemSelected", onItemSelected, m.carousel)
        safeObserve("itemFocused", onItemFocused, m.carousel)
        safeObserve("itemUnfocused", onItemUnfocused, m.carousel)
        getGlobalAA().initialFocusNode = m.carousel

        defaultConfig = {
            animationDuration: 0.3,
            clip: true,
            componentName: "",
            defaultVisibleIndex: 0,
            ' lastIndex: 2,
            direction: "horizontal",
            dynamicWidth: false,
            focusType: "floating",
            flushFocus: false,
            gutterSize: 0,
            horizAlign: "center",
            maxHeight: 0,
            maxWidth: 0,
            vertAlign: "center",
            visibleTiles: 0,
            wrap: false,
            bigSquare: [0, 0],
            smallSquare: [0, 0],
            squareMargins: [0, 0],
            squareTotalArea: [0, 0]
        }

        set({ defaultConfig: defaultConfig })
        set(defaultConfig)

        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)

        safeFunctions({
            registerChildRect: registerChildRect
        })

        m.focusTimer = top().findNode("focusTimer")
        m.focusTimer.update({
            finishTime: rodash.now(),
            focused: false,
            startTime: rodash.now()
        }, true)

        m.focusTimer.duration = 0.016
        m.focusTimer.repeat = true
        safeObserve("fire", onFocusTimerFired)
    end sub)
end sub


function onKeyEvent(key as string, press as boolean) as boolean
    return exec(function(options = {})
        key = options.key
        press = options.press
        carousel = options.carousel

        if not press then return true
        if not rodash.isArray(m.targetSetArray) then return true
        if calculate.floatMOD(carousel.currFocusItemIndex, 1) <> 0 then return true
        if key <> top().advanceKey and key <> top().reverseKey then return false

        direction = key = top().reverseKey ? -1 : 1
        currentIndex = top().focusedContentIndex
        lastVisibleIndex = get("lastVisibleIndex")
        nextIndex = currentIndex + direction
        currentTargetSetIndex = top().focusedTargetsetIndex
        nextTargetSetIndex = currentTargetSetIndex + direction

        if nextTargetSetIndex <= 0 then nextTargetSetIndex = 0
        if nextTargetSetIndex >= lastVisibleIndex then nextTargetSetIndex = lastVisibleIndex

        if carousel.content.getChild(nextIndex) = invalid
            if not get("wrap") then return false

            if direction = 1
                nextIndex = 0
                nextTargetSetIndex = 0
            else
                profilesCollection = carousel.content
                if not rodash.isNode(profilesCollection) then return true
                nextIndex = profilesCollection.getChildCount() - 1
                nextTargetSetIndex = m.targetSetArray.count() - 1
            end if
        end if

        nextTargetSet = m.targetSetArray[nextTargetSetIndex]

        if nextTargetSet <> invalid and carousel.currTargetSet <> invalid and nextTargetSet.focusIndex <> carousel.currTargetSet.focusIndex
            carousel.animateToTargetSet = nextTargetSet
            top().focusedTargetsetIndex = nextTargetSetIndex
        end if

        carousel.animateToItem = nextIndex
        top().focusedContentIndex = nextIndex

        return true
    end function, { key: key, press: press, carousel: m.carousel })
end function


sub onFocusTimerFired(options = {})
    finishTime = m.focusTimer.finishTime
    startTime = m.focusTimer.startTime
    currentTime = rodash.now()

    totalDuration! = finishTime - startTime
    if totalDuration! <= 0
        m.focusTimer.control = "stop"
        currentPercentage = m.focusTimer.focused ? 1 : 0
        m.carousel.focusPercent = currentPercentage
        return
    end if

    elapsedTime! = currentTime - startTime
    currentPercentage = elapsedTime! / totalDuration!

    if currentTime > finishTime
        m.focusTimer.control = "stop"
        currentPercentage = 1
    else if currentPercentage < 0
        currentPercentage = 0
    else if currentPercentage > 1
        currentPercentage = 1
    end if

    if not m.focusTimer.focused then currentPercentage = 1 - currentPercentage

    m.carousel.focusPercent = currentPercentage
end sub


sub onFocusedChildChange(options = {})
    node = options.data
    currentIndex = top().focusedContentIndex
    if m.content = invalid then return

    unfocused = node = invalid or not node.isSameNode(m.top) and not top().isInFocusChain()

    if not rodash.isNode(m.carousel.targetSet) then return

    m.focusTimer.focused = not unfocused

    currentTime = rodash.now()
    durationMs = m.carousel.duration * 1000
    finishTime = currentTime + durationMs
    m.focusTimer.startTime = currentTime
    m.focusTimer.finishTime = finishTime
    if m.focusTimer.control <> "start"
        m.focusTimer.control = "start"
    end if

    if unfocused
        unFocusedTargetSet = m.unFocusedTargetSet
        unFocusedTargetSet.focusIndex = m.carousel.targetSet.focusIndex
        rodash.delay(sub(args)
            args[0].animateToTargetSet = args[1]
        end sub, 100, [m.carousel, unFocusedTargetSet])
        m.carousel.animateToItem = currentIndex
        return
    end if

    if not rodash.isArray(m.targetSetArray) then return

    currentTargetSet = m.targetSetArray[top().focusedTargetsetIndex]
    m.carousel.animateToItem = currentIndex

    rodash.delay(sub(args)
        args[0].animateToTargetSet = args[1]
    end sub, 100, [m.carousel, currentTargetSet])

    m.carousel.setFocus(true)
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return

    data = options.data ?? {}
    content = data.content
    if not rodash.isNode(content) then return

    safeObserve("totalCount", onTotalCountChange, content)
    safeObserve("rectConfig", processConfig, content)

    m.content = content
    m.carousel.content = content
    m.carousel.itemComponentName = content.rectConfig.itemComponentName

    if rodash.isBoolean(content.rectConfig.dynamicWidth) and content.rectConfig.dynamicWidth
        rects = []
        for x = 0 to m.content.getChildCount() -1
            rects.push({
                height: 36,
                width: 12,
                x: 0,
                y: 0
            })
        end for
        unFocusedTargetSet = createTargetSet({
            focusIndex: 0,
            targetRects: rects
        })
        m.carousel.targetSet = unFocusedTargetSet
    else
        processConfig({ data: content.rectConfig })
    end if
end sub


sub onTotalCountChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    totalCarouselItems = options.data
    if rodash.isNumber(totalCarouselItems) then set({ totalCarouselItems: totalCarouselItems })
    processConfig()
end sub


sub onItemFocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    m.top.itemFocused = options.data
end sub


sub onItemSelected(options = {})
    if not rodash.isNonEmptyAA(options) then return
    m.top.itemSelected = options.data
end sub


sub onItemUnfocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    m.top.itemUnfocused = options.data
end sub


sub processConfig(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.content) then return

    defaultConfig = get("defaultConfig")
    config = {}
    config.append(defaultConfig)
    config.append(options.data ?? {})

    totalCarouselItems = m.content.totalCount ?? 0
    margins = calculate.margins({ squareMargins: config.squareMargins })
    squareTotalArea = calculate.squareTotalArea({
        bigSquare: config.bigSquare,
        margins: margins
    })
    maxVisibleTiles = calculate.maxVisibleTiles({
        visibleTiles: config.visibleTiles,
        totalCarouselItems: totalCarouselItems
    })
    extraRects = calculate.extraRectNumber({
        direction: config.direction,
        dynamicWidth: config.dynamicWidth,
        gutterSize: config.gutterSize,
        squareTotalArea: squareTotalArea
    })
    totalRects = calculate.totalRects({ visibleTiles: maxVisibleTiles, extraRects: extraRects })

    ' Calculate the first and last visible rects
    ' accounting for extra gutter rects
    visibleIndexArray = getVisibleIndices({
        defaultVisibleIndex: config.defaultVisibleIndex ?? 0,
        extraRects: extraRects,
        totalCarouselItems: totalCarouselItems,
        visibleTiles: maxVisibleTiles
    })

    firstVisibleIndex = visibleIndexArray[0]
    lastVisibleIndex = visibleIndexArray[1]

    set({
        lastVisibleIndex: lastVisibleIndex,
        wrap: config.wrap
    })

    generateRects({
        bigSquare: config.bigSquare,
        defaultVisibleIndex: config.defaultVisibleIndex,
        direction: config.direction,
        dynamicWidth: config.dynamicWidth,
        extraRects: extraRects,
        firstVisibleIndex: firstVisibleIndex,
        flushFocus: config.flushFocus,
        focusType: config.focusType,
        horizAlign: config.horizAlign,
        lastVisibleIndex: lastVisibleIndex,
        margins: margins,
        smallSquare: config.smallSquare,
        squareTotalArea: squareTotalArea,
        totalRects: totalRects,
        vertAlign: config.vertAlign
    })

    setListContent({
        animationDuration: config.animationDuration,
        itemComponentName: config.itemComponentName
    })

    top().width = calculate.carouselWidth({
        direction: config.direction,
        flushFocus: config.flushFocus,
        maxWidth: config.maxWidth,
        squareTotalArea: squareTotalArea,
        visibleTiles: maxVisibleTiles
    })

    top().height = calculate.carouselHeight({
        direction: config.direction,
        flushFocus: config.flushFocus,
        maxHeight: config.maxHeight,
        squareTotalArea: squareTotalArea,
        visibleTiles: maxVisibleTiles
    })

    if config.direction = "vertical"
        top().reverseKey = "up"
        top().advanceKey = "down"
    else
        top().reverseKey = "left"
        top().advanceKey = "right"
    end if

    if config.clip then clipCarousel()
end sub


sub clipCarousel()
    top().clippingRect = [0, 0, m.top.width, m.top.height]
    m.carousel.clippingRect = [0, 0, m.top.width, m.top.height]
end sub


sub registerChildRect(options = {})
    m.rectSizes[options.index] = {
        smallSquare: options.smallSquare,
        bigSquare: options.bigSquare
    }
    if m.rectSizes.count() = m.content.getChildCount()
        processConfig({ data: m.content.rectConfig })
    end if
end sub


sub setListContent(options = {})
    m.carousel.content = m.content
    m.carousel.itemComponentName = options.itemComponentName
    m.carousel.duration = options.animationDuration ?? 0.3
end sub


sub generateRects(options = {})
    defaultVisibleIndex = options.defaultVisibleIndex
    firstVisibleIndex = options.firstVisibleIndex
    lastVisibleIndex = options.lastVisibleIndex
    extraRects = options.extraRects
    flushFocus = options.flushFocus
    focusType = options.focusType

    targetsetRects = returnTargetsetRects(options)

    unfocusedRects = targetsetRects.shift()
    setUnfocusedTargetSet({
        defaultVisibleIndex: defaultVisibleIndex,
        extraRects: extraRects,
        flushFocus: flushFocus,
        unfocusedRects: unfocusedRects
    })

    ' Array of targetsets for each focused position in the list.
    m.targetSetArray = []

    if focusType = "fixed"
        index = defaultVisibleIndex + extraRects
        focusedTargetSet = createTargetSet({
            focusIndex: index,
            targetRects: targetsetRects[index]
        })
        m.targetSetArray.push(focusedTargetSet)
    else
        for index = 0 to targetsetRects.count() - 1
            focusedTargetSet = createObject("roSGNode", "TargetSet")

            if index >= firstVisibleIndex and index <= lastVisibleIndex
                focusedTargetSet = createTargetSet({
                    focusIndex: index,
                    targetRects: targetsetRects[index]
                })
                m.targetSetArray.push(focusedTargetSet)
            end if
        end for
    end if

    m.targetsetRects = targetsetRects
end sub


function getVisibleIndices(options = {})
    if not rodash.isNonEmptyAA(options) then return [0,0]
    defaultVisibleIndex = options.defaultVisibleIndex
    extraRects = options.extraRects

    numberOfContentItems = options.totalCarouselItems
    maxVisibleTiles = options.visibleTiles
    visibleTiles = numberOfContentItems < maxVisibleTiles ? numberOfContentItems : maxVisibleTiles

    firstVisibleIndex = defaultVisibleIndex + extraRects
    lastVisibleIndex = visibleTiles - 1 + extraRects

    return [firstVisibleIndex, lastVisibleIndex]
end function


sub setUnfocusedTargetSet(options = {})
    defaultVisibleIndex = options.defaultVisibleIndex
    extraRects = options.extraRects
    flushFocus = options.flushFocus
    unfocusedRects = options.unfocusedRects

    if flushFocus or not rodash.isNode(m.carousel.targetSet)

        ' Peel off the first array, which should always be for unfocused targetset
        unFocusedTargetSet = createTargetSet({
            focusIndex: defaultVisibleIndex + extraRects,
            targetRects: unfocusedRects
        })

        ' Set the initial targetset of the list to the unfocused one
        m.carousel.targetSet = unFocusedTargetSet
        m.unFocusedTargetSet = unFocusedTargetSet
    end if
end sub


function createTargetset(options = {})
    targetSet = createObject("roSGNode", "TargetSet")
    targetSet.update(options)
    return targetSet
end function


function returnTargetsetRects(options = {})
    bigSquare = options.bigSquare
    smallSquare = options.smallSquare
    extraRects = options.extraRects
    direction = options.direction
    dynamicWidth = options.dynamicWidth
    horizAlign = options.horizAlign
    flushFocus = options.flushFocus
    margins = options.margins
    squareTotalArea = options.squareTotalArea
    totalRects = options.totalRects
    vertAlign =  options.vertAlign

    targetsetRects = []

    ' -1 because we want to generate the unfocused state as first array
    for y = -1 to totalRects - 1
        focusedTile = y
        targetRects = []

        for x = 0 to totalRects - 1
            bigSquare = rectSquare({ type: "big", index: x })
            smallSquare = rectSquare({ type: "small", index: x })

            square = x = focusedTile ? bigSquare : smallSquare

            if horizAlign = "left"
                deltaX = 0
            else if horizAlign = "right"
                deltaX = (bigSquare[0] - smallSquare[0])
            else
                deltaX = (bigSquare[0] - smallSquare[0]) / 2
            end if

            if vertAlign = "top"
                deltaY = 0
            else if vertAlign = "bottom"
                deltaY = (bigSquare[1] - smallSquare[1])
            else
                deltaY = (bigSquare[1] - smallSquare[1]) / 2
            end if

            if dynamicWidth
                adjustedIndex = x + extraRects * -1
                listDirection = direction = "horizontal" ? 0 : 1
                rect = m.rectSizes[adjustedIndex]
                if not rodash.isNonEmptyAA(rect) then rect = {
                    bigSquare: [0, 0],
                    smallSquare: [0, 0]
                }

                ' If not focused OR
                ' if it is a row for unfocused state
                square = x <> y or y = -1 ? rect.smallSquare : rect.bigSquare

                coordinates = [0, 0]
                previousRect = targetRects[x - 1]
                if rodash.isNonEmptyAA(previousRect)
                    if direction = "horizontal"
                        coordinates[listDirection] = previousRect.x + previousRect.width + margins.left + margins.right
                    else
                        coordinates[listDirection] = previousRect.y + previousRect.height + margins.top + margins.bottom
                    end if
                end if

                if rodash.isNonEmptyArray(square)
                    targetRects.push({
                        height: square[1] ?? 0,
                        width: square[0] ?? 0,
                        x: coordinates[0],
                        y: coordinates[1]
                    })
                end if
            else if flushFocus
                containerPosition = calculate.rectFlushPosition({
                    bigSquare: bigSquare,
                    deltaX: deltaX,
                    deltaY: deltaY,
                    extraRects: extraRects,
                    horizontal: direction = "horizontal",
                    index: x,
                    focusedTile: focusedTile,
                    smallSquare: smallSquare
                })

                targetRects.push({
                    x: containerPosition[0],
                    y: containerPosition[1],
                    width: square[0],
                    height: square[1]
                })
            else
                containerPosition = calculate.rectStartingPosition({
                    extraRects: extraRects,
                    flushFocus: flushFocus,
                    horizontal: direction = "horizontal",
                    margins: margins,
                    smallSquare: smallSquare,
                    index: x,
                    square: squareTotalArea
                })

                offsetX = x = focusedTile ? margins.left : deltaX + margins.left
                offsetY = x = focusedTile ? margins.top : deltaY + margins.top

                targetRects.push({
                    x: containerPosition[0] + offsetX,
                    y: containerPosition[1] + offsetY,
                    width: square[0],
                    height: square[1]
                })
            end if
        end for

        targetsetRects.push(targetRects)
    end for

    return targetsetRects
end function


function rectSquare(options = {}) as object
    if rodash.isEmpty(options) then return [0, 0]

    squareKey = options.type = "small" ? "smallSquare" : "bigSquare"

    rectConfig = m.content.rectConfig
    dynamicWidth = rectConfig.dynamicWidth ?? false

    if dynamicWidth
        if rodash.isEmpty(m.rectSizes) then return [0, 0]

        index = options.index ?? 0
        squaresObj = m.rectSizes[index] ?? m.rectSizes[0]
        return squaresObj[squareKey] ?? [0, 0]
    end if

    return rectConfig[squareKey]
end function


namespace calculate
    function carouselHeight(options = {})
        if not rodash.isNonEmptyAA(options) then return 0

        direction = options.direction
        flushFocus = options.flushFocus
        maxHeight = options.maxHeight
        squareArea = options.squareTotalArea
        visibleTiles = options.visibleTiles

        if flushFocus
            firstSet = m.targetsetRects[0] ?? []
            lastItem = firstSet[firstSet.count() - 1] ?? { height: 0, width: 0, x: 0, y: 0}

            if direction = "horizontal"
                return lastItem.height
            else
                return maxHeight
            end if
        else
            if direction = "horizontal"
                return squareArea.height
            else
                return squareArea.height * visibleTiles
            end if
        end if
    end function


    function carouselWidth(options = {})
        if not rodash.isNonEmptyAA(options) then return 0

        direction = options.direction
        flushFocus = options.flushFocus
        maxWidth = options.maxWidth
        squareArea = options.squareTotalArea
        visibleTiles = options.visibleTiles

        if flushFocus
            if direction = "horizontal"
                return maxWidth ?? 0
            else
                return squareArea.width * visibleTiles
            end if
        else
            if direction = "horizontal"
                return squareArea.width * visibleTiles
            else
                return squareArea.width
            end if
        end if
    end function


    ' Get the number of extra hidden rects
    ' for *each side* of the carousel
    ' meaning ultimately it will be n*2
    function extraRectNumber(options = {})
        if not rodash.isNonEmptyAA(options) then return 0

        direction = options.direction
        dynamicWidth = options.dynamicWidth ?? false
        gutterSize = options.gutterSize
        squareArea = options.squareTotalArea
        defaultExtraRect = 1
        ' If there is a gutter, meaning partially visible rects
        ' on each side of the carousel,
        ' then we need to add an extra rects
        ' in order to smoothly load the partially visible rect.
        if not rodash.isNonEmptyAA(squareArea) then return 0
        if dynamicWidth then return 1

        gutterSize = gutterSize ?? 0
        if gutterSize <= 0 then return defaultExtraRect

        rectSize = squareTotalArea[direction = "horizontal" ? "width" : "height"]
        percentageOfSquareAsGutter = gutterSize / rectSize
        numberOfVisibleGutterSquares = int(percentageOfSquareAsGutter) + 1

        return numberOfVisibleGutterSquares + defaultExtraRect
    end function


    function floatMod(x as dynamic, y as dynamic)
        if y = 0 then return 0
        a = abs(x)
        b = abs(y)
        remainder = a - (int(a/b) * b)
        return remainder * sgn(x)
    end function


    function rectFlushPosition(options = {})
        coordinates = [0, 0]
        if not rodash.isNonEmptyAA(options) then return coordinates

        bigSquare = options.bigSquare
        deltaX = options.deltaX
        deltaY = options.deltaY
        extraRects = options.extraRects
        horizontal = options.horizontal
        index = options.index
        focusedTile = options.focusedTile
        smallSquare = options.smallSquare

        adjustedIndex = index + extraRects * -1

        primaryArrayIndex = horizontal ? 0 : 1
        secondryArrayIndex = horizontal ? 1 : 0
        deltaArray = [deltaX, deltaY]

        if focusedTile = -1
            coordinates[primaryArrayIndex] = adjustedIndex * smallSquare[primaryArrayIndex] + (deltaArray[primaryArrayIndex] / 2)
            coordinates[secondryArrayIndex] = deltaArray[secondryArrayIndex]
        else if index < focusedTile
            coordinates[primaryArrayIndex] = adjustedIndex * smallSquare[primaryArrayIndex]
            coordinates[secondryArrayIndex] = deltaArray[secondryArrayIndex]
        else if index = focusedTile
            coordinates[primaryArrayIndex] = adjustedIndex * smallSquare[primaryArrayIndex]
            coordinates[secondryArrayIndex] = 0
        else
            coordinates[primaryArrayIndex] = ((adjustedIndex - 1) * smallSquare[primaryArrayIndex]) + bigSquare[primaryArrayIndex]
            coordinates[secondryArrayIndex] = deltaArray[secondryArrayIndex]
        end if

        return coordinates
    end function


    function rectStartingPosition(options = {})
        coordinates = [0, 0]
        if not rodash.isNonEmptyAA(options) then return coordinates

        index = options.index ?? 0
        rect = options.square ?? {}
        horizontal = options.horizontal ?? false
        ' Because some of the tiles will be hidden
        extraRects = options.extraRects
        ' We need to adjust the index based on the extraRects
        adjustedIndex = index + extraRects * -1

        if rodash.isEmpty(rect) then return coordinates

        if horizontal
            coordinates[0] = adjustedIndex * rect.width
        else
            coordinates[1] = adjustedIndex * rect.height
        end if

        return coordinates
    end function


    function totalRects(options = {})
        if not rodash.isNonEmptyAA(options) then return 0
        visibleTiles = options.visibleTiles ?? {}
        extraRects = options.extraRects ?? 0
        return visibleTiles + (extraRects * 2)
    end function


    function margins(options = {})
        returnObj = {
            "left": 0,
            "top": 0,
            "right": 0,
            "bottom": 0
        }
        if not rodash.isNonEmptyAA(options) then return returnObj

        margin = options.squareMargins ?? 0

        if margin.count() = 1
            returnObj["left"] = margin[0]
            returnObj["top"] = margin[0]
            returnObj["right"] = margin[0]
            returnObj["bottom"] = margin[0]
        else if margin.count() = 2 or margin.count() = 3
            returnObj["left"] = margin[0]
            returnObj["top"] = margin[1]
            returnObj["right"] = margin[0]
            returnObj["bottom"] = margin[1]
        else if margin.count() = 4
            returnObj["left"] = margin[3]
            returnObj["top"] = margin[0]
            returnObj["right"] = margin[1]
            returnObj["bottom"] = margin[2]
        end if

        return returnObj
    end function


    function maxVisibleTiles(options = {})
        if not rodash.isNonEmptyAA(options) then return 0
        configMaxTiles = options.visibleTiles ?? 0
        numberOfItems = options.totalCarouselItems ?? 0
        return numberOfItems < configMaxTiles ? numberOfItems : configMaxTiles
    end function


    function squareTotalArea(options = {})
        if not rodash.isNonEmptyAA(options) then return 0

        bigSquare = options.bigSquare
        squareMargins = options.margins

        return {
            height: bigSquare[1] + squareMargins.top + squareMargins.bottom,
            width: bigSquare[0] + squareMargins.left + squareMargins.right
        }
    end function
end namespace


function CommonUtils_reduce(arr as object, func as function, args as object, initialValue=invalid as dynamic) as dynamic
    if not rodash.isArray(arr) then return invalid

    size = arr.count()
    startAt = 0
    accumulator = initialValue

    if size = 0 then return accumulator

    if accumulator = invalid
        accumulator = arr[0]
        startAt = 1
    end if

    for i = startAt to size - 1
        accumulator = func(accumulator, arr[i], i, arr, args)
    end for

    return accumulator
end function
