import "pkg:/components/_ord/wrappers.bs"

class NodeFunctions
    sub onInit(options = {})
        m.setupConfig()
    end sub


    sub setupConfig()
        m.defaultConfig = {
            animationDuration: 0.3,
            clip: true,
            componentName: "",
            defaultIndex: 0,
            direction: "horizontal",
            focusType: "floating"
            gutterWidth: 0,
            visibleTiles: 0,
            bigSquare: [0, 0],
            smallSquare: [0, 0],
            squareMargins: [0, 0]
        }

        safeObserve("config", "onConfigSet")
        safeObserve("data", "onDataSet")
    end sub


    sub onConfigChange(options = {})
        ?"onConfigChange " options
        config = options.data ?? {}
        if not rodash.isAA(config) then return
        fullConfig = {}
        fullConfig.append(m.defaultConfig)
        fullConfig.append(config)
        set({ config: fullConfig })
        ?"ASDDASSADASD"
    end sub


    sub onDataSet(options = {})
        if not rodash.isNonEmptyAA(options) then return
        ?"onDataSet " options
    end sub
end class
