import "pkg:/components/~boilerplate/azat.bs"


class NodeFunctions
    sub onInit(options = {})
        m.top.role = "Controller"

        m.socketTest = createObject("roSGNode", "WebsocketTest")
        m.socketTest.control = "RUN"

        subscribe({
            [events.TEST_EVENT]: "onTestEvent"
        })
    end sub

    sub onTestEvent(options = {}, msgInfo = {})
        ?"SocketController onTestEvent " options
    end sub
end class
