import "pkg:/components/_ord/wrappers.bs"


class NodeFunctions
    sub onInit(options = {})
        m.socketTest = createObject("roSGNode", "_ord_socketTask")
        m.socketTest.control = "RUN"

        subscribe({
            [events.TEST_EVENT]: "onTestEvent"
        })
    end sub

    sub onTestEvent(options = {}, msgInfo = {})
        ?"SocketController onTestEvent " options
    end sub
end class
