import "pkg:/components/_ord/wrappers.bs"


class NodeFunctions
    sub onInit(options = {})
        m.stylesTask = createObject("roSGNode", "StyleTask")

        subscribe({
            "STYLES_UPDATE": "onStylesUpdate"
            "REQUEST_STYLES": "requestStyles"
        })
    end sub

    sub onStylesUpdate(options = {})
        globeStyles = global()._ord_styles
        newStyles = options.STYLES ?? {}
        for each style in newStyles.items()
            globeStyles[style.key] = style.value
        end for
    end sub

    sub requestStyles(options = {})
        m.stylesTask.control = "RUN"
    end sub
end class



