import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runLoginUserTask)
    end sub)
end sub


function runLoginUserTask(options = {})
    options = top().options ?? {}
    model = options.model
    variables = options.variables ?? {}

    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Login) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>" })
    responseJSON = response.json ?? {}

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return true
    end if

    responseData = responseJSON.data ?? {}
    loginData = responseData.login ?? {}
    updateObject = loginData.user ?? {}
    updateObject.append({ jwt: loginData.jwt })

    publish(events.USER_LOGGED_IN, {
        model: model,
        updateObject: updateObject
    })
    return true
end function
