import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.gradient = top().findNode("gradient")
        m.list = top().findNode("topbarList")
        ' loadTopbar()
        safeObserve("data", onDataChange)
        safeObserve("focusedChild", onFocusedChildChange)
    end sub)
end sub


sub onDataChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    m.list.data = options.data
end sub


sub loadTopbar()
    list = top().findNode("topbarList")

    model = createObject("roSGNode", "TopbarModel")
    model.config = {
        carouselType: "dynamicSize",
        focusType: "floating",
        itemComponentName: "NavigationItem",
        maxWidth: 1800,
        visibleTiles: 999,
        useUnfocusedTargetSet: true,
        horizAlign: "left"
    }

    list.data = {
        content: model
    }

    m.list = list
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    m.list.setFocus(true)
end sub
