import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.scrubTrack = top().findNode("scrubTrack")
        m.progressBar = top().findNode("progressBar")
        m.scrubber = top().findNode("scrubber")

        safeFunctions({
            "updateProgress": updateProgress
        })
    end sub)
end sub


sub updateProgress(options = {})
    if rodash.isEmpty(options) then return
    position = options.position ?? 0
    duration = options.duration ?? 0

    if position = 0 or duration = 0
        redrawStyles()
        return
    end if

    totalWidth = top().width
    scrubberWidth = m.scrubber.width
    progressPercentage = position / duration
    progressWidth = totalWidth * progressPercentage
    m.progressBar.width = progressWidth
    m.scrubber.translation = [progressWidth - scrubberWidth, 0]
end sub
