function returnCarouselsArray(carouselsArray = [])
    if not rodash.isArray(carouselsArray) then return []

    updateObjArray = []

    for each carousel in carouselsArray

        updateObject = {
            carouselTitle: carousel.carouselTitle,
            carouselType: carousel.carouselType ?? "INDEX",
            id: carousel.documentId,
            subtype: "Collection",
            thumbnailType: carousel.thumbnailType ?? "LANDSCAPE"
        }

        updateObjArray.push(updateObject)
    end for

    updateObject = {
        children: updateObjArray
    }

    return updateObject
end function
