function getContentData(options = {})
    if not rodash.isNonEmptyAA(options) then return {}

    data = options.data
    if not rodash.isNonEmptyAA(data) then return {}

    contentImages = data.images ?? []
    imageFields = getImageFields(contentImages)

    updateObject = {
        bifs: data.bifs ?? [],
        credits: data.credits ?? [],
        complimentaryColor: data.complimentaryColor,
        copyrightYear: data.copyrightYear,
        description: data.description,
        duration: data.duration,
        genres: data.v2genres,
        id: data.documentId,
        rating: data.rating,
        playlistUrl: data.playlistUrl,
        position: data.position ?? 0,
        title: data.title,
        type: data.type,
        userItemId: data.userItemId
    }

    updateObject.append(imageFields)
    return updateObject
end function


function getImageFields(images)
    if not rodash.isNonEmptyArray(images) then return {}

    imageFields = rodash.reduce(images, function(acc, cv)
        imageType = lcase(cv.imageType ?? "")
        if rodash.isEmptyString(imageType) then return acc
        fieldName = imageType + "ImageUri"
        imageURL = cv.data?.url ?? ""
        serverPath = "<%- s(CONFIG.ENV.SERVER_URI) %>"
        acc[fieldName] = serverPath + imageURL
        return acc
    end function, {})

    if imageFields.landscapeImageUri <> invalid
        imageFields.thumbnailImageUri = imageFields.landscapeImageUri
    else if imageFields.portraitImageUri <> invalid
        imageFields.thumbnailImageUri = imageFields.portraitImageUri
    end if

    return imageFields
end function
