sub generateCarouselModel(options = {})
    model = options.model
    if not rodash.isNode(model) then return
    thumbnailType = options.thumbnailType

    fields = []
    if thumbnailType = "LANDSCAPE" or thumbnailType = "PORTRAIT"
        fields = ["id", "thumbnailImageUri"]
    end if

    carouselItemModel = model.carouselItemModel
    if not rodash.isNode(carouselItemModel) then carouselItemModel = createObject("roSGNode", "ContentModel")

    for each field in fields
        carouselItemModel[field] = model[field]
    end for

    model.carouselItemModel = carouselItemModel
end sub


function getImageFields(images)
    if not rodash.isNonEmptyArray(images) then return {}

    imageFields = rodash.reduce(images, function(acc, cv)
        imageType = lcase(cv.imageType ?? "")
        if rodash.isEmptyString(imageType) then return acc
        fieldName = imageType + "ImageUri"
        imageURL = cv.data?.url ?? ""
        serverPath = "<%- s(CONFIG.ENV.SERVER_URI) %>"
        acc[fieldName] = serverPath + imageURL
        return acc
    end function, {})

    if imageFields.landscapeImageUri <> invalid
        imageFields.thumbnailImageUri = imageFields.landscapeImageUri
    else if imageFields.portraitImageUri <> invalid
        imageFields.thumbnailImageUri = imageFields.portraitImageUri
    end if

    return imageFields
end function


sub processContent(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    if not rodash.isNode(model) then return

    data = options.data
    thumbnailType = options.thumbnailType ?? "LANDSCAPE"

    if not rodash.isNonEmptyAA(data) then return

    contentImages = data.images ?? []
    imageFields = getImageFields(contentImages)

    updateObject = {
        complimentaryColor: data.complimentaryColor,
        copyrightYear: data.copyrightYear,
        description: data.description,
        duration: data.duration,
        genres: data.v2genres,
        heroCTAsModel: returnHeroCTAsModel(),
        id: data.documentId,
        rating: data.rating,
        position: data.position ?? 0,
        title: data.title,
        type: data.type
    }

    updateObject.append(imageFields)
    model.update(updateObject, true)

    generateCarouselModel({ model: model, thumbnailType: thumbnailType })
    model.hydrated = true
end sub


function returnHeroCTAsModel()
    model = createObject("roSGNode", "CTAsModel")
    modelConfigArray = "<%- o(CONFIG.HeroCTAs) %>"
    updateObject = {
        children: []
    }

    for each item in modelConfigArray
        updateObject.children.push({
            id: item.id,
            dynamicWidth: item.dynamicWidth ?? false,
            iconText: item.iconText ?? "",
            title: (item.title ?? "").inStr("TKEY") <> -1 ? tr(item.title) : item.title,
            subtype: "Model"
        })
    end for

    model.update(updateObject, true)
    return model
end function


function returnTabsModel(carousels = [])
    if not rodash.isArray(carousels) then return invalid
    model = createObject("roSGNode", "Model")

    for each carousel in carousels
        carouselType = carousel.carouselType
        if rodash.isEmpty(carouselType) then continue for
        tabModel = createObject("roSGNode", "Model")
        tabModel.title = carouselType
        model.appendChild(tabModel)
    end for

    return model
end function
