function getContentData(options = {})
    data = options.data
    contentImages = data.images ?? []
    imageFields = getImageFields(contentImages)

    videoServerURI = "{{%- s(CONFIG.ENV.VIDEO_SERVER_URI) %}}"
    playlistUrl = data.playlistUrl ?? ""

    updateObject = {
        bifs: data.bifs ?? [],
        credits: data.credits ?? [],
        complimentaryColor: data.complimentaryColor,
        copyrightYear: data.copyrightYear,
        description: data.description,
        duration: data.duration,
        genres: data.v2genres,
        id: data.documentId,
        rating: data.rating,
        playlistUrl:  videoServerURI + playlistUrl,
        position: data.position ?? 0,
        subtype: "ContentModel",
        title: data.title,
        type: data.type,
        userItemId: data.userItemId
    }

    updateObject.append(imageFields)
    return updateObject
end function


function getImageFields(images)
    if not rodash.isNonEmptyArray(images) then return {}

    imageFields = rodash.reduce(images, function(acc, cv)
        imageType = lcase(cv.imageType ?? "")
        if rodash.isEmptyString(imageType) then return acc
        fieldName = imageType + "ImageUri"
        imageURL = cv.data?.url ?? ""
        serverPath = "{{%- s(CONFIG.ENV.SERVER_URI) %}}"
        acc[fieldName] = serverPath + imageURL
        return acc
    end function, {})

    if imageFields.landscapeImageUri <> invalid
        imageFields.thumbnailImageUri = imageFields.landscapeImageUri
    else if imageFields.portraitImageUri <> invalid
        imageFields.thumbnailImageUri = imageFields.portraitImageUri
    end if

    return imageFields
end function
