import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        m.container = top().findNode("container")
        m.contentLogo = top().findNode("contentLogo")
        m.metadata = top().findNode("metadata")
        m.description = top().findNode("description")
        m.ctas = top().findNode("ctas")

        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)
        setFocusMap({
            "default": m.ctas
        })
        safeObserve("ctaSelected", onCTASelected, m.ctas)
        redrawStyles()
    end sub)
end sub


sub onCTASelected(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.content) then return
    actionType = options.data
    if actionType = "PLAY"
        dispatch(events.PLAY_VIDEO, { content: m.content })
    else if actionType = "WATCHLIST"
        dispatch(events.TOGGLE_WATCHLIST, { content: m.content })
    else if actionType = "FAVORITE"
        dispatch(events.TOGGLE_FAVORITE, { content: m.content })
    else if actionType = "DETAILS"
        dispatch(events.NAVIGATE_TO, { slug: `/details/${m.content.id}`, content: m.content })
    end if
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    data = options.data
    content = data.content
    if rodash.isNode(m.content) and content.isSameNode(m.content) then return

    m.content = content
    ?"onDataSet " content

    onHydrated({ node: m.content })
    stackChildren({ node: m.container, direction: "vertical" })
    dispatch(events.HERO_ITEM_FOCUSED, { content: content, section: sections.DETAILS_HERO })
end sub


sub onHydrated(options = {})
    if not rodash.isNonEmptyAA(options) then return
    content = options.node

    setDescription(content.description)
    setLogoImage(content.logoImageUri)
    setCTAs(content.detailsCTAsModel)
    setMetadata(content)
end sub


sub setCTAs(detailsCTAsModel = {})
    if not rodash.isNode(detailsCTAsModel) then return
    m.ctas.data = { content: detailsCTAsModel }
end sub


sub setDescription(description = "")
    if rodash.isEmptyString(description) then return
    m.description.text = description
end sub


sub setLogoImage(logoImageUri = "")
    if rodash.isEmptyString(logoImageUri) then return
    m.contentLogo.uri = logoImageUri
end sub


sub setMetadata(content = {})
    if not rodash.isNode(content) then return
    metadataArray = []

    if rodash.isArray(content.genres)
        metadataArray.push({
            genres: content.genres
    })
    end if

    if rodash.isNonEmptyString(content.copyrightYear)
        metadataArray.push({
            copyrightYear: content.copyrightYear
        })
    end if

    if rodash.isNumber(content.duration)
        metadataArray.push({
            duration: content.duration
        })
    end if

    if rodash.isNonEmptyString(content.rating)
        metadataArray.push({
            rating: content.rating
        })
    end if

    m.metadata.data = {
        metadataArray: metadataArray
    }
end sub
