import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        safeObserve("config", onConfigChange)
    end sub)
end sub


sub onConfigChange(options = {})
    for each option in options.data
        controlItem = top().findNode(option.id)
        if not rodash.isNode(controlItem)
            controlItem = createObject("roSGNode", "ControlItem")
            controlItem.id = option.id
            top().appendChild(controlItem)
        end if

        controlItem.config = option
    end for

    redrawStyles()
    stackChildren({ direction: "horizontal" })
end sub
