import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        setupItem()
        styleHooks({
            after: afterStyling
        })
    end sub)
end sub


sub afterStyling(_options = {})
    onTextChange()
end sub

sub setupItem()
    m.label = top().findNode("label")
    m.icon = top().findNode("icon")
    m.container = top().findNode("textContainer")
    m.tabTop = top().findNode("tabTop")
    m.tabBottom = top().findNode("tabBottom")
    m.parentList = top().getParent()

    safeObserve("focusPercent", onFocusPercentChange)
    safeObserve("itemContent", itemContentChanged, top())
    safeObserve("currRect", onCurrRectChange, top())
    safeObserve("width", onCurrRectChange, top())
    safeObserve("height", onCurrRectChange, top())
    if rodash.isNode(m.parentList) then safeObserve("focusPercent", onGroupFocusPercentChange, m.parentList)
end sub


sub itemContentChanged(options = {})
    content = options.data
    m.label.text = ucase(content.title)
    m.icon.text = content.iconText ?? ""
    if not rodash.isEmpty(m.icon.text)
        m.icon.visible = true
    end if

    if top().index = top().getParent().itemFocused
        addClass("active", top())
    end if

    onTextChange()
end sub


sub onTextChange(_options = {})
    stackChildren({ node: m.container, direction: "horizontal" })
    tabWidth = m.container.boundingRect().width
    tabHeight = m.container.boundingRect().height
    m.container.width = tabWidth
    m.container.height = tabHeight
    top().width = tabWidth
    top().height = tabHeight

    if not rodash.isNode(m.parentList) then return

    exec("registerChildRect", {
        smallSquare: getFocusedRectSize(),
        bigSquare: getFocusedRectSize(),
        index: top().index
    }, m.parentList.getParent())
end sub


function getFocusedRectSize(_options = {})
    if not rodash.isNode(m.container) then return [0,0]

    return [getVisibleWidth(m.container), getVisibleHeight(m.container)]
end function


sub onCurrRectChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    field = options.field
    if field = "currRect"
        rect = options.data
    else
        rect = top()
    end if

    for each node in [m.container, m.tabTop, m.tabBottom]
        node.width = rect.width
        node.height = rect.height
    end for
end sub


sub onGroupFocusPercentChange(_options = {})
    ' percentage = options.data ?? {}
    ' labelSquare = get("labelSquare") ?? [0,0]
    ' labelWidth = labelSquare[0]
    ' labelHeight = labelSquare[1]
    ' if m.parentList.itemFocused = top().index then m.colorFieldInterpolator.fraction = percentage

    ' if m.parentList.itemFocused = top().index and get("dynamicWidth")
    '     m.label.clippingRect = [0, 0, labelWidth * percentage, labelHeight]
    ' end if
end sub


sub onFocusPercentChange(options = {})
    percentage = options.data ?? {}
    ' runFocusTransformation(percentage)
    ?"onFocusPercentageChange " percentage
end sub


sub runFocusTransformation(_percentage)
    ' labelSquare = get("labelSquare") ?? [0,0]
    ' labelWidth = labelSquare[0]
    ' labelHeight = labelSquare[1]

    ' if top().groupHasFocus then m.colorFieldInterpolator.fraction = percentage

    ' if get("dynamicWidth")
    '     m.label.clippingRect = [0, 0, labelWidth * percentage, labelHeight]
    ' end if
end sub

