import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        setTaskFunction(runQueue)
    end sub)
end sub


function runQueue(options = {})
    messagePort = createObject("roMessagePort")
    safeObserve("eventData", messagePort)

    while true
        msg = wait(1000, messagePort)
        if msg = invalid then continue while

        field = msg.getField()
        messageData = msg.getData()
        if rodash.isEmpty(messageData) then continue while

        eventId = messageData.id ?? ""
        eventOptions = messageData.options ?? {}

        if rodash.isEmpty(eventId) then continue while
        ?"PUBLISHING EVENT " eventId
        publish(eventId, eventOptions)
    end while

    return true
end function
