import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub()
        setupItem()
    end sub)
end sub


sub setupItem()
    m.indexLabel = m.top.findNode("label")
    m.container = m.top.findNode("container")
    m.container.opacity = 0.2
    safeObserve("currRect", onCurrentRectChange)
    safeObserve("focusPercent", onFocusPercentChange)
end sub


sub itemContentChanged(event)
    m.indexLabel.text = m.top.index
end sub


sub onCurrentRectChange(options = {})
    rect = options.data ?? {}
    ' ?"onCurrentRectChange " m.top.index

    if rodash.isNode(m.container)
        m.container.height = rect.height
        m.container.width = rect.width
    end if
end sub


sub onFocusPercentChange(options = {})
    focusPercentage = options.data ?? {}
    opacityPercentage = (0.5 * focusPercentage) * focusPercentage + 0.5
    m.container.opacity = opacityPercentage
end sub
