import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        setupItem()
    end sub)
end sub


sub setupItem()
    m.indexLabel = m.top.findNode("label")
    m.container = m.top.findNode("container")
    ' m.container.opacity = 0.5
    safeObserve("currRect", onCurrentRectChange)
    safeObserve("focusPercent", onFocusPercentChange)
end sub


sub itemContentChanged(event)
    content = event.getData()
    if content = invalid then return

    m.container.uri = content.HDPosterUrl
end sub


sub onCurrentRectChange(options = {})
    rect = options.data ?? {}

    if rodash.isNode(m.container)
        m.container.height = rect.height
        m.container.width = rect.width
    end if
end sub


sub onFocusPercentChange(options = {})
    focusPercentage = options.data ?? {}
    opacityPercentage = (0.5 * focusPercentage) * focusPercentage + 0.5
    m.container.opacity = opacityPercentage
end sub
