import "pkg:/components/_ord/init.bs"
import "pkg:/source/roku_modules/promises/promises.brs"

sub init()
    exec(sub(_options = {})
        safeObserve("data", onDataSet)
        m.title = top().findNode("title")
        onDataSet()
    end sub)
end sub


sub onDataSet(_options = {})
    content = createObject("roSGNode", "ContentModel")
    content.headerImageUri = "pkg:/static/images/WIP-screen.webp"
    content.complimentaryColor = "#075977"
    content.hydrated = true
    dispatch(events.SET_NEW_BACKGROUND, { content: content, replace: true, section: sections.HERO })
    m.title.text = "WORK IN PROGRESS"
end sub


' Methods exteded from sgRouter

function beforeViewSuspend(_options = {}) as dynamic
    suspendPromise = promises.create()
    fadeOut(top(), { callback: onViewFadedOut, callbackOptions: { promise: suspendPromise } })
    return suspendPromise
end function


sub onViewFadedOut(options = {})
    suspendPromise = options.promise
    promises.resolve(true, suspendPromise)
end sub


function onViewResume(_options = {})
    dispatch(events.SHOW_CATALOG_UI)
    fadeIn(top())
    return promises.resolve(invalid)
end function
