import "pkg:/components/_ord/init.bs"
import "bifTools.bs"

sub init()
    exec(sub(_options = {})
        m.videoOverlay = top().findNode("videoOverlay")
        m.trickplay = top().findNode("trickplay")
        m.video = top().findNode("video")
        m.video.enableUI = false
        m.video.notificationInterval = 1
        m.video.seekMode = "accurate"

        m.overlayTimer = createObject("roSGNode", "Timer")
        m.overlayTimer.duration = 5
        safeObserve("fire", hideOverlay, m.overlayTimer)

        m.scrubTimer = createObject("roSGNode", "Timer")
        m.scrubTimer.duration = 3
        safeObserve("fire", onScrubTimerFired, m.scrubTimer)

        m.seekTimer = createObject("roSGNode", "Timer")
        m.seekTimer.duration = 0.5
        m.seekTimer.repeat = true
        safeObserve("fire", onSeekTimerFired, m.seekTimer)

        m.controls = top().findNode("controls")
        controlsConfig = "{{%- o(CONFIG.DefaultControls) %}}"
        m.controls.config = controlsConfig

        activeControlsConfig = "{{%- o(CONFIG.ActiveControls) %}}"

        safeObserve("data", onDataSet)
        safeObserve("state", onVideoStateChange, m.video)
        safeObserve("position", onVideoPositionChange, m.video, ["duration"])
        safeObserve("duration", onVideoDurationChange, m.video)

        setFocusMap({
            "onFocus": m.videoOverlay,
            "onUnfocus": resetUI,
            "videoOverlay": {
                "left": [showOverlay, scrubLeft],
                "right": [showOverlay, scrubRight],
                "up": showOverlay,
                "ok": onSelection,
                "rewind": [showOverlay, seekRewind],
                "fastforward": [showOverlay, seekForward],
                "play": [showOverlay, togglePlayback],
                "back": onBackButton,
                "replay": [showOverlay, restartPlayback]
            }
        })

        set({
            "activeControlsConfig": activeControlsConfig,
            "controlsConfig": controlsConfig,
            "scrubInterval": 10,
            "scrubPosition": 0,
            "seekDirection": 0,
            "seeking": false,
            "seekIntervals": [30, 60, 120],
            "seekSpeed": 0,
            "overlayOpen": false
        })
    end sub)
end sub


sub onDataSet(options = {})
    data = options.data
    content = data.content
    m.content = content
    playerModel = exec("returnPlayerModel", {}, content)
    if not rodash.isNode(playerModel) then return
    m.video.content = playerModel
    m.video.seek = playerModel.position
    m.video.control = "play"
    m.videoOverlay.data = data
    showOverlay()
end sub


sub onScrubTimerFired(_options = {})
    m.video.control = "resume"
    set({ "scrubPosition": m.video.position })
    exec("hideTrickplay", {}, m.trickplay)
    resetControls()
end sub


sub onSeekTimerFired(_options = {})
    seeking = get("seeking")
    if not seeking then return

    seekSpeed = get("seekSpeed")
    seekIntervals = get("seekIntervals") ?? []
    scrubPosition = get("scrubPosition") ?? m.video.position
    seekDirection = get("seekDirection")
    duration = m.video.duration

    nextPosition = scrubPosition + (seekIntervals[seekSpeed] * seekDirection)
    if nextPosition >= duration then nextPosition = duration

    set({ "scrubPosition": nextPosition })
    sendTrickplayInfo({ trickplayPosition: nextPosition })

    if nextPosition = duration then m.seekTimer.control = "stop"
    if nextPosition <= 0 then m.seekTimer.control = "stop"

    showOverlay()
    updateControl({ controlId: "seekControl" })
end sub


function onSelection(_options = {})
    scrubbing = m.scrubTimer.control = "start"
    seeking = get("seeking") ?? false

    if m.scrubTimer.control = "start" then m.scrubTimer.control = "stop"
    if m.seekTimer.control = "start" then m.seekTimer.control = "stop"

    if seeking or scrubbing
        exec("hideTrickplay", {}, m.trickplay)
        m.video.seek = get("scrubPosition")
        set({
            "scrubPosition": m.video.position,
            "seekDirection": 0,
            "seeking": false,
            "seekSpeed": 0
        })
    else
        hideOverlay()
    end if

    return true
end function


sub onVideoDurationChange(options = {})
    position = m.video.position
    duration = options.data ?? 0
    exec("onPositionChange", { position: position, duration: duration }, m.videoOverlay)
end sub


sub onVideoPositionChange(options = {})
    position = options.data ?? 0
    set({ "scrubPosition": position })
    exec("onPositionChange", { position: position }, m.videoOverlay)

    options.append({ contentModel: m.content })
    dispatch(events.VIDEO_POSITION_CHANGE, options)
end sub


sub onVideoStateChange(options = {})
    state = options.data
    if state = "playing"
        resetControls()
        dispatch(events.VIDEO_PLAYING)
    else if state = "paused"
        updateControl({ controlId: "playControl" })
        dispatch(events.VIDEO_PAUSED)
    else if state = "buffering"
        dispatch(events.VIDEO_BUFFERING)
    else if state = "finished"
        dispatch(events.VIDEO_FINISHED)
    else if state = "error"
        dispatch(events.VIDEO_ERROR)
    else if state = "stopped"
        dispatch(events.VIDEO_STOPPED)
    end if
end sub


sub performScrub(options = {})
    if get("seeking") then return

    if m.video.state <> "playing" and m.video.state <> "paused" then return

    m.video.control = "pause"

    currentPosition = get("scrubPosition") ?? m.video.position
    positionDelta = options.positionDelta
    nextPosition = currentPosition + positionDelta

    set({ "scrubPosition": nextPosition })
    m.scrubTimer.control = "start"
    sendTrickplayInfo({ trickplayPosition: nextPosition })
    updateControl({ controlId: "scrubControl" })
end sub


sub resetUI(_options = {})
    exec("onPositionChange", { position: 0, duration: 0 }, m.videoOverlay)
    m.video.duration = 0
end sub


sub sendTrickplayInfo(options = {})
    options.trickplayFrame = getNearestFrameFromPosition(options.trickplayPosition ?? 0)
    options.duration = m.video.duration

    exec("setTrickplayInfo", options, m.trickplay)
    exec("setPositionLabel", { position: options.trickplayPosition }, m.videoOverlay)
end sub


function scrubLeft(_options = {})
    performScrub({ positionDelta: get("scrubInterval") * -1 })
    return true
end function


function scrubRight(_options = {})
    performScrub({ positionDelta: get("scrubInterval")})
    return true
end function


function onBackButton(_options = {})
    if get("seeking")
        return onSeekCancel()
    else if get("overlayOpen")
        return hideOverlay()
    end if

    m.video.control = "stop"
    return false
end function


sub onSeekCancel()
    if m.scrubTimer.control = "start" then m.scrubTimer.control = "stop"
    if m.seekTimer.control = "start" then m.seekTimer.control = "stop"
    m.video.control = "resume"
    set({
        "seekDirection": 0,
        "seeking": false,
        "seekSpeed": 0
    })
    exec("hideTrickplay", {}, m.trickplay)
end sub


function hideOverlay(_options = {})
    if not get("overlayOpen") then return true
    fadeOut(m.videoOverlay)
    set({ "overlayOpen": false })
    return true
end function


function showOverlay(_options = {})
    if get("overlayOpen")
        m.overlayTimer.control = "start"
        return true
    end if

    fadeIn(m.videoOverlay)
    set({ "overlayOpen": true })
    m.overlayTimer.control = "start"
    return true
end function


sub startSeek()
    if m.video.state <> "playing" and m.video.state <> "paused" then return

    if m.scrubTimer.control = "start"
        m.scrubTimer.control = "stop"
        resetControls()
    end if

    m.video.control = "pause"
    updateControl({ controlId: "playControl" })

    seekSpeed = get("seekSpeed")
    seeking = get("seeking")
    seekIntervals = get("seekIntervals") ?? []

    if seeking
        if seekSpeed > seekIntervals.count() - 1 then seekSpeed = seekIntervals.count() - 1
        set({ "seekSpeed": seekSpeed })
    else
        set({
            "scrubPosition": get("scrubPosition") ?? m.video.position,
            "seeking": true
        })
        m.seekTimer.control = "start"
        onSeekTimerFired()
    end if
end sub


function seekForward(_options = {})
    seekSpeed = get("seekSpeed")
    seekDirection = get("seekDirection")

    if seekDirection = -1 then seekSpeed = 0
    if seekDirection = 1 then seekSpeed += 1

    set({ "seekDirection": 1, "seekSpeed": seekSpeed })
    startSeek()
    return true
end function


function seekRewind(_options = {})
    seekSpeed = get("seekSpeed")
    seekDirection = get("seekDirection")
    if seekDirection = 1 then seekSpeed = 0
    if seekDirection = -1 then seekSpeed += 1

    set({ "seekDirection": -1, "seekSpeed": seekSpeed })
    startSeek()
    return true
end function


function togglePlayback(_options = {})
    if get("seeking")
        onSelection()
        return true
    end if

    if m.video.state = "paused"
        m.video.control = "resume"
    else if m.video.state = "playing"
        m.video.control = "pause"
    end if
    return true
end function


function restartPlayback(_options = {})
    dispatch(events.VIDEO_RESTARTING)
    m.video.seek = 0
    updateControl({ controlId: "restartControl" })

    rodash.delay(sub(_options = {})
        hideOverlay()
    end sub, 1000)

    return true
end function


sub resetControls(_options = {})
    m.controls.config = get("controlsConfig")
end sub


sub updateControl(options = {})
    controlId = options.controlId ?? ""
    if rodash.isEmpty(controlId) then return

    activeControls = get("activeControlsConfig") ?? {}
    newControlConfig = activeControls[controlId]
    if not rodash.isNonEmptyAA(newControlConfig) then return

    newControl = {}
    newControl.append(newControlConfig)

    m.controls.config = [newControl]
end sub
