import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.iconsContainer = top().findNode("iconsContainer")
        m.title = top().findNode("title")
        safeObserve("config", onConfigChange)
    end sub)
end sub


sub onConfigChange(options = {})
    config = options.data ?? {}
    if not rodash.isNonEmptyAA(config) then return
    if rodash.isNonEmptyArray(config.icons) then populateIcons(config.icons)
    m.title.text = ucase(tr(config.title))
    top().opacity = config.opacity ?? 1
    stackChildren({ direction: "horizontal" })
end sub


sub populateIcons(iconArray = [])
    rodash.removeNodeChildren(m.iconsContainer)
    for each icon in iconArray
        iconComponent = createObject("roSGNode", "Icon")
        iconComponent.text = icon
        m.iconsContainer.appendChild(iconComponent)
    end for
    redrawStyles()
    stackChildren({ direction: "horizontal" }, m.iconsContainer)
end sub

