import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        setupItem()
    end sub)
end sub


sub setupItem()
    m.label = m.top.findNode("label")
    m.icon = m.top.findNode("icon")
    m.container = m.top.findNode("textContainer")
    m.background = top().findNode("background")
    m.highlightTop = top().findNode("highlightTop")
    m.highlightBottom = top().findNode("highlightBottom")
    m.colorFieldInterpolator = top().findNode("focusColorInterpolator")
    m.parentList = top().getParent()
    m.flexList = m.parentList.getParent()

    safeObserve("focusPercent", onFocusPercentChange)
    safeObserve("itemContent", itemContentChanged, top())
    safeObserve("currRect", onCurrRectChange, top())
    safeObserve("focusPercent", onGroupFocusPercentChange, m.parentList)
end sub


sub itemContentChanged(options = {})
    content = options.data
    ?"itemContentChanged " content
    m.label.text = ucase(content.title)
    m.icon.text = content.iconText
    dynamicWidth = content.dynamicWidth ?? false
    set({ dynamicWidth: dynamicWidth })
    onTextChange()
end sub


sub onTextChange(_options = {})
    stackChildren({ node: m.container, direction: "horizontal" })
    m.container.width = m.container.boundingRect().width
    m.container.height = m.container.boundingRect().height

    exec("registerChildRect", {
        smallSquare: getUnFocusedRectSize(),
        bigSquare: getFocusedRectSize(),
        index: m.top.index
    }, top().getParent().getParent())

    if get("dynamicWidth") then m.label.clippingRect = [0,0,0,0]
end sub


sub onCurrRectChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    rect = options.data

    for each node in [m.background, m.highlightTop, m.highlightBottom]
        node.width = rect.width
        node.height = node.id = "highlightTop" ? (rect.height / 3) * 2 : rect.height
    end for
end sub


sub onGroupFocusPercentChange(options = {})
    percentage = options.data ?? {}
    labelSquare = get("labelSquare") ?? [0,0]
    labelWidth = labelSquare[0]
    labelHeight = labelSquare[1]
    if m.parentList.itemFocused = top().index then m.colorFieldInterpolator.fraction = percentage

    if m.parentList.itemFocused = top().index and get("dynamicWidth")
        m.label.clippingRect = [0, 0, labelWidth * percentage, labelHeight]
    end if
end sub


sub onFocusPercentChange(options = {})
    percentage = options.data ?? {}
    runFocusTransformation(percentage)
end sub


function getFocusedRectSize(_options = {})
    if not rodash.isNode(m.label) then return [0,0]

    m.label.text = ucase(top().itemContent.title)
    m.label.visible = true
    labelSquare = [getVisibleWidth(m.label), getVisibleHeight(m.label)]
    set({ "labelSquare": labelSquare })

    stackChildren({ node: m.container, direction: "horizontal" })
    return [getVisibleWidth(m.container), getVisibleHeight(m.container)]
end function


sub runFocusTransformation(percentage)
    labelSquare = get("labelSquare") ?? [0,0]
    labelWidth = labelSquare[0]
    labelHeight = labelSquare[1]

    if top().groupHasFocus then m.colorFieldInterpolator.fraction = percentage

    if get("dynamicWidth")
        m.label.clippingRect = [0, 0, labelWidth * percentage, labelHeight]
    end if
end sub


function getUnfocusedRectSize(_options = {})
    if not rodash.isNode(m.label) then return [0,0]

    if get("dynamicWidth")
        m.label.width = 0
        m.label.text = ""
        m.label.visible = false
    end if

    stackChildren({ node: m.container, direction: "horizontal" })
    return [getVisibleWidth(m.container), getVisibleHeight(m.container)]
end function
