import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        top().id = "carouselItem"
        setupItem()
    end sub)
end sub


sub setupItem()
    m.indexLabel = top().findNode("label")
    m.container = top().findNode("container")
    m.outline = top().findNode("outline")
    m.thumbnail = top().findNode("thumbnail")
    safeObserve("currRect", onCurrentRectChange)
    safeObserve("focusPercent", onFocusPercentChange)
    startLoadingAnimation()
end sub


sub startLoadingAnimation()
    if rodash.isNode(m.content) and m.content.hydrated
        fadeIn(m.container)
        return
    end if

    fadeOut(top(), { callback: onFadedOut, duration: 1 })
end sub


sub onFadedOut(options = {})
    fadeIn(top(), { callback: onFadedIn, duration: 1 })
end sub


sub onFadedIn(options = {})
    startLoadingAnimation()
    ' if not rodash.isNode(m.content) then return
    ' if rodash.isBoolean(m.content.hydrated) and not m.content.hydrated
    ' end if
end sub


sub itemContentChanged(event)
    content = event.getData()
    if content = invalid then return
    if rodash.isNode(m.content) then return

    m.content = content

    if rodash.isNonEmptyString(content.thumbnailImageUri)
        setThumbailImage({ data: content.thumbnailImageUri })
    else
        safeObserve("thumbnailImageUri", setThumbailImage, m.content)
    end if
end sub


sub onCurrentRectChange(options = {})
    rect = options.data ?? {}

    top().height = rect.height
    top().width = rect.width

    if rodash.isNode(m.container)
        m.container.height = rect.height
        m.container.width = rect.width
    end if

    if rodash.isNode(m.outline)
        m.outline.height = rect.height
        m.outline.width = rect.width
    end if

    if rodash.isNode(m.thumbnail)
        m.thumbnail.height = rect.height - 12
        m.thumbnail.width = rect.width - 12
    end if
end sub


sub onFocusPercentChange(options = {})
    focusPercentage = options.data ?? {}
    ' opacityPercentage = (0.5 * focusPercentage) * focusPercentage + 0.5
    ' m.container.opacity = opacityPercentage
end sub


sub setThumbailImage(options = {})
    thumbnailImageUrl = options.data ?? ""
    if rodash.isEmptyString(thumbnailImageUrl) then return
    m.thumbnail.uri = thumbnailImageUrl
end sub
