import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        setupItem()
    end sub)
end sub


sub setupItem()
    m.indexLabel = top().findNode("label")
    m.container = top().findNode("container")
    m.container.addField("loaded", "boolean", false)
    m.outline = top().findNode("outline")
    m.outline.visible = false
    m.thumbnail = top().findNode("thumbnail")
    m.defaultUnfocusedOpacity = 0.2
    setLoadable({ node: m.container, updateField: "loaded" })
    safeObserve("currRect", onCurrentRectChange)
    safeObserve("focusPercent", onFocusPercentChange)
    safeObserve("itemContent", itemContentChanged)
end sub


sub itemContentChanged(options = {})
    content = options.data
    if content = invalid then return
    setThumbailImage({ data: content.thumbnailImageUri })

    parentList = top().getParent() ?? {}

    if top().index < parentList.animateToItem ?? 0
        top().opacity = m.defaultUnfocusedOpacity
    else
        top().opacity = 1
    end if
end sub


sub onCurrentRectChange(options = {})
    rect = options.data ?? {}

    width = int(rect.width)
    height = int(rect.height)

    top().height = int(height / 3) * 3
    top().width = int(width / 3) * 3

    if rect.x + width < 0
        top().opacity = m.defaultUnfocusedOpacity
    else if rect.x > width
        top().opacity = 1
    end if

    if rodash.isNode(m.container)
        m.container.height = height
        m.container.width = width
    end if

    if rodash.isNode(m.outline)
        m.outline.height = height
        m.outline.width = width
    end if

    if rodash.isNode(m.thumbnail)
        m.thumbnail.height = height - 12
        m.thumbnail.width = width - 12
    end if

    loadingPoster = top().findNode("loadingPoster")
    if rodash.isNode(loadingPoster)
        loadingPoster.height = height
        loadingPoster.width = width
    end if
end sub


sub onFocusPercentChange(_options = {})
    parentList = top().getParent() ?? {}

    listCurrFocusIndex = parentList.currFocusItemIndex ?? 0
    modifiedFocusIndex = abs(top().index - listCurrFocusIndex)
    opacityPercentage = abs(1 - modifiedFocusIndex)
    changeOpacity(listCurrFocusIndex > top().index, opacityPercentage)
end sub


sub setThumbailImage(options = {})
    thumbnailImageUrl = options.data ?? ""
    if rodash.isEmptyString(thumbnailImageUrl) then return
    m.thumbnail.uri = thumbnailImageUrl
    m.container.loaded = true
    m.outline.visible = true
end sub


sub changeOpacity(hide = false, percentage = 0)
    if hide
        top().opacity = m.defaultUnfocusedOpacity + (percentage * (1 - m.defaultUnfocusedOpacity))
    else
        top().opacity = 1
    end if
end sub
