import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        ' top().id = "carouselItem"
        setupItem()
    end sub)
end sub


sub setupItem()
    m.indexLabel = top().findNode("label")
    m.container = top().findNode("container")
    m.container.addField("loaded", "boolean", false)
    m.outline = top().findNode("outline")
    m.outline.visible = false
    m.thumbnail = top().findNode("thumbnail")
    setLoadable({ node: m.container, updateField: "loaded" })
    safeObserve("currRect", onCurrentRectChange)
    safeObserve("focusPercent", onFocusPercentChange)
    safeObserve("itemContent", itemContentChanged)
end sub


sub itemContentChanged(options = {})
    content = options.data
    if content = invalid then return
    setThumbailImage({ data: content.thumbnailImageUri })
end sub


sub onCurrentRectChange(options = {})
    rect = options.data ?? {}

    width = int(rect.width)
    height = int(rect.height)

    top().height = int(height / 3) * 3
    top().width = int(width / 3) * 3

    if rodash.isNode(m.container)
        m.container.height = height
        m.container.width = width
    end if

    if rodash.isNode(m.outline)
        m.outline.height = height
        m.outline.width = width
    end if

    if rodash.isNode(m.thumbnail)
        m.thumbnail.height = height - 12
        m.thumbnail.width = width - 12
    end if
end sub


sub onFocusPercentChange(options = {})
    focusPercentage = options.data ?? {}
    ' opacityPercentage = (0.5 * focusPercentage) * focusPercentage + 0.5
    ' m.container.opacity = opacityPercentage
end sub


sub setThumbailImage(options = {})
    thumbnailImageUrl = options.data ?? ""
    if rodash.isEmptyString(thumbnailImageUrl) then return
    m.thumbnail.uri = thumbnailImageUrl
    m.container.loaded = true
    m.outline.visible = true
end sub
