import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.container = top().findNode("container")
        m.metadata = top().findNode("metadata")
        m.title = top().findNode("title")
        safeObserve("data", onDataSet)
    end sub)
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    data = options.data
    content = data.content
    if not rodash.isEmpty(content.title)
        m.title.visible = true
        setLogoTitle(content.title)
    end if

    setMetadata(content)
    stackChildren({ direction: "vertical" }, m.container)
end sub


sub setLogoTitle(title = "")
    if rodash.isEmptyString(title) then return
    m.title.text = title
end sub


sub setMetadata(content = {})
    if not rodash.isNode(content) then return
    metadataArray = []

    if rodash.isArray(content.genres)
        metadataArray.push({
            genres: content.genres
    })
    end if

    if rodash.isNonEmptyString(content.copyrightYear)
        metadataArray.push({
            copyrightYear: content.copyrightYear
        })
    end if

    if rodash.isNumber(content.duration)
        metadataArray.push({
            duration: content.duration
        })
    end if

    if rodash.isNonEmptyString(content.rating)
        metadataArray.push({
            rating: content.rating
        })
    end if

    m.metadata.data = {
        metadataArray: metadataArray
    }
end sub
