import "pkg:/components/_ord/wrappers.bs"
import "pkg:/components/tasks/shared/content.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runUserCarouselsTask)
    end sub)
end sub


function runUserCarouselsTask(options = {})
    options = top().options ?? {}
    if not rodash.isNonEmptyAA(options) then return true

    collectionTypes = options.collectionTypes
    userId = options.userId
    if rodash.isEmptyString(userId) then return true

    variables = {}
    variables.setModeCaseSensitive()
    variables = {
        "documentId": userId,
        "sort": "updatedAt:desc",
        "pagination": {
            "page": 1,
            "pageSize": 100
        }
    }

    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.UserCarousels) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>"})

    responseJSON = parseJSON(response.text)
    responseData = responseJSON.data ?? {}
    usersPermissionsUser = responseData.usersPermissionsUser ?? {}
    userCarouselsData = usersPermissionsUser.user_carousels ?? []

    carouselTypesArray = collectionTypes.keys() ?? []

    for each carousel in userCarouselsData
        updateObject = {
            children: [],
            id: carousel.documentId,
            type: carousel.type
        }

        userItems = carousel.user_items
        for each item in userItems
            content = item.content
            contentData = getContentData({ data: content })
            contentData.position = item.position
            contentData.userItemId = item.documentId
            updateObject.children.push(contentData)
        end for

        collectionTypes[carousel.type] = updateObject

        typeIndex = rodash.indexOf(carouselTypesArray, carousel.type)
        carouselTypesArray.delete(typeIndex)
    end for

    newCarouselIds = []

    for each carouselType in carouselTypesArray
        newCarouselId = createUserCarousel(carouselType)
        collectionTypes[carouselType] = {
            id: newCarouselId,
            type: carouselType
        }
        newCarouselIds.push(newCarouselId)
    end for

    if rodash.isNonEmptyArray(newCarouselIds) then attachCarouselsToUser({
        userId: userId,
        carouselIds: newCarouselIds
    })

    publish(events.USER_CAROUSELS_RECEIVED, {
        userCarouselsData: collectionTypes
    })
    return true
end function


function createUserCarousel(carouselType = "")
    variables = {}
    variables.setModeCaseSensitive()
    variables = {
        "carouselType": carouselType
    }

    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.CreateUserCarousel) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>"})

    responseJSON = parseJSON(response.text)
    responseData = responseJSON.data ?? {}
    carouselData = responseData.createUserCarousel ?? {}
    newCarouselId = carouselData.documentId

    return newCarouselId
end function


sub attachCarouselsToUser(options = {})
    if not rodash.isNonEmptyAA(options) then return

    variables = {}
    variables.setModeCaseSensitive()
    variables = {
        "userId": options.userId,
        "carouselIds": options.carouselIds
    }

    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.AttachCarouselToUser) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>"})

    ?"attachCarouselsToUser " response
end sub
