import "pkg:/components/_ord/init.bs"
import "pkg:/components/tasks/shared/content.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runUserItemTask)
    end sub)
end sub


function runUserItemTask(_options = {})
    options = top().options ?? {}
    collection = options.collection
    contentModel = options.contentModel
    existingUserItemIds = options.existingUserItemIds ?? []
    existingUserItemModel = collection.findNode(contentModel.id)

    if rodash.isNode(existingUserItemModel)
        if collection.type = carouselTypes.CONTINUE_WATCHING
            duration = options.duration ?? 0
            position = options.position ?? 0
            if rodash.isNumber(duration) and duration = 0 or rodash.isNumber(position) and position = 0 then return true

            if position > duration or duration - position <= 120
                deleteUserItemModel({
                    collection: collection,
                    contentModel: contentModel,
                    model: existingUserItemModel
                })
            else
                updateUserItemModel({
                    model: existingUserItemModel,
                    position: options.position ?? 0
                })
            end if
        else
            deleteUserItemModel({
                collection: collection,
                contentModel: contentModel,
                model: existingUserItemModel
            })
        end if
    else
        createUserItemModel({
            collection: collection,
            contentModel: contentModel,
            contentDocumentId: contentModel.id,
            existingUserItemIds: existingUserItemIds,
            position: options.position ?? 0
        })
    end if

    return true
end function


sub deleteUserItemModel(options = {})
    collection = options.collection
    model = options.model
    userItemId = model.userItemId

    variables = {}
    variables.setModeCaseSensitive()
    variables = {
        "documentId": userItemId
    }

    response = rokurequests_Requests().post("{{%- s(CONFIG.ENV.GRAPHQL_SERVER) %}}", { json: { query: "{{%- s(QUERY.DeleteUserItem) %}}", variables: variables }, headers: "{{%- o(CONFIG.Headers) %}}"})
    responseJSON = response.json

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return
    end if

    userItemType = returnUserItemType(collection.type)
    if rodash.isEmptyString(userItemType) then return

    collection.removeChild(model)

    contentModel = options.contentModel
    if not rodash.isNode(contentModel) then return

    if userItemType = userItemsTypes.CWITEM
        contentModel.position = 0
    else if userItemType = userItemsTypes.FAVORITE
        contentModel.favorited = false
    else if userItemType = userItemsTypes.WATCHLIST
        contentModel.watchlisted = false
    end if
end sub


sub updateUserItemModel(options = {})
    model = options.model
    userItemId = model.userItemId
    position = options.position

    variables = {}
    variables.setModeCaseSensitive()
    variables = {
        "documentId": userItemId,
        "position": position
    }
    response = rokurequests_Requests().post("{{%- s(CONFIG.ENV.GRAPHQL_SERVER) %}}", { json: { query: "{{%- s(QUERY.UpdateUserItem) %}}", variables: variables }, headers: "{{%- o(CONFIG.Headers) %}}"})
    responseJSON = response.json

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return
    end if

    model.position = position
end sub


sub createUserItemModel(options = {})
    collection = options.collection
    userItemType = returnUserItemType(collection.type)
    if rodash.isEmptyString(userItemType) then return

    contentModel = options.contentModel
    existingUserItemIds = options.existingUserItemIds ?? []

    contentDocumentId = options.contentDocumentId
    position = options.position

    variables = {}
    variables.setModeCaseSensitive()
    variables = {
        "contentDocumentId": contentDocumentId,
        "contentId": contentDocumentId,
        "position": position,
        "userItemType": userItemType
    }
    response = rokurequests_Requests().post("{{%- s(CONFIG.ENV.GRAPHQL_SERVER) %}}", { json: { query: "{{%- s(QUERY.CreateUserItem) %}}", variables: variables }, headers: "{{%- o(CONFIG.Headers) %}}"})
    responseJSON = response.json
    responseJSON = response.json

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return
    end if

    responseData = responseJSON.data ?? {}

    userItemData = responseData.createUserItem ?? {}
    content = userItemData.content ?? {}

    if not rodash.isNonEmptyAA(content) then return

    model = createObject("roSGNode", "ContentModel")

    updateObject = getContentData({ data: content })
    updateObject.userItemId = userItemData.documentId
    existingUserItemIds.unshift(userItemData.documentId)

    model.update(updateObject, true)

    attachUserItemModel({
        collection: collection,
        newUserItemModel: model,
        userItemIds: existingUserItemIds
    })

    if userItemType = userItemsTypes.CWITEM
        contentModel.position = position
    else if userItemType = userItemsTypes.FAVORITE
        contentModel.favorited = true
    else if userItemType = userItemsTypes.WATCHLIST
        contentModel.watchlisted = true
    end if
end sub


sub attachUserItemModel(options = {})
    collection = options.collection
    newUserItemModel = options.newUserItemModel
    if not rodash.isNode(newUserItemModel) then return

    userItemIds = options.userItemIds ?? []
    if not rodash.isNonEmptyArray(userItemIds) then return

    variables = {}
    variables.setModeCaseSensitive()
    variables = {
        "carouselDocumentId": collection.id,
        "userItemDocumentIds": userItemIds
    }
    response = rokurequests_Requests().post("{{%- s(CONFIG.ENV.GRAPHQL_SERVER) %}}", { json: { query: "{{%- s(QUERY.AttachUserItemToUserCarousel) %}}", variables: variables }, headers: "{{%- o(CONFIG.Headers) %}}"})
    responseJSON = response.json

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return
    end if

    collection.insertChild(newUserItemModel, 0)
end sub


function returnUserItemType(carouselType = "")
    if carouselType = carouselTypes.CONTINUE_WATCHING
        return userItemsTypes.CWITEM
    else if carouselType = carouselTypes.FAVORITES
        return userItemsTypes.FAVORITE
    else if carouselType = carouselTypes.WATCHLIST
        return userItemsTypes.WATCHLIST
    end if
    return ""
end function
