import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runSidebarTask)
    end sub)
end sub


function runSidebarTask(_options = {})
    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Sidebar) %>"}, headers: "<%- o(CONFIG.Headers) %>"})
    responseJSON = response.json ?? {}

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return true
    end if

    sidebarModel = returnSidebarModel(responseJSON)

    if rodash.isNode(sidebarModel)
        publish(events.SIDEBAR_RECEIVED, { content: sidebarModel })
    end if

    return true
end function


function returnSidebarModel(options = {})
    data = options.data ?? {}
    sidebarData = data.sidebar ?? {}
    screensData = sidebarData.screens ?? []
    updateObjArray = []

    for each screen in screensData
        updateObject = {
            documentId: screen.documentId,
            iconText: getIcon(screen.icon),
            id: screen.slug,
            title: screen.name ?? "",
            subtype: "ContentNode"
        }

        updateObjArray.push(updateObject)
    end for

    model = createObject("roSGNode", "SidebarModel")
    model.update(updateObjArray, true)
    model.defaultSlug = sidebarData.defaultSlug

    return model
end function


function getIcon(iconType)
    iconsDictionary = "<%- o(CONFIG.Icons) %>"
    return iconsDictionary[iconType] ?? ""
end function
