import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        setTaskFunction(runSidebarTask)
    end sub)
end sub


function runSidebarTask(options = {})
    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Sidebar) %>"}, headers: "<%- o(CONFIG.Headers) %>"})

    if rodash.isEmpty(response.text) then return true

    sidebarModel = returnSidebarModel(parseJSON(response.text))

    if rodash.isNode(sidebarModel)
        dispatch(events.SIDEBAR_RECEIVED, { content: sidebarModel })
    end if

    return true
end function


function returnSidebarModel(options = {})
    data = options.data ?? {}
    sidebarData = data.sidebar ?? {}
    screensData = sidebarData.screens ?? []
    updateObjArray = []

    for each screen in screensData
        updateObject = {
            documentId: screen.documentId,
            dynamicWidth: true,
            iconText: getIcon(screen.icon),
            id: screen.slug,
            title: screen.name ?? "",
            subtype: "ContentNode"
        }

        updateObjArray.push(updateObject)
    end for

    model = createObject("roSGNode", "SidebarModel")
    model.update(updateObjArray, true)
    model.defaultSlug = sidebarData.defaultSlug
    model.config = "<%- o(CONFIG.Sidebar) %>"

    return model
end function


function getIcon(iconType)
    iconsDictionary = "<%- o(CONFIG.Icons) %>"
    return iconsDictionary[iconType] ?? ""
end function
