import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.container = top().findNode("container")
        m.title = top().findNode("title")
        m.contentLogo = top().findNode("contentLogo")
        m.metadata = top().findNode("metadata")
        m.description = top().findNode("description")
        m.ctas = top().findNode("ctas")

        safeObserve("data", onDataSet)
        setFocusMap({
            "onFocus": m.ctas
        })
        safeObserve("ctaSelected", onCTASelected, m.ctas)
        redrawStyles()
    end sub)
end sub


sub onCTASelected(options = {})
    actionType = options.data
    if actionType = "CWITEM"
        dispatch(events.PLAY_VIDEO, { content: m.content })
    else if actionType = "WATCHLIST"
        dispatch(events.TOGGLE_WATCHLIST, { content: m.content })
    else if actionType = "FAVORITE"
        dispatch(events.TOGGLE_FAVORITE, { content: m.content })
    else if actionType = "DETAILS"
        dispatch(events.NAVIGATE_TO, { slug: `/details/${m.content.id}`, context: { content: m.content }})
    end if
end sub


sub onDataSet(options = {})
    data = options.data
    content = data.content
    if rodash.isNode(m.content) and content.isSameNode(m.content) then return

    m.content = content
    onHydrated({ node: m.content })
    stackChildren({ direction: "vertical" }, m.container)

    safeObserve("favorited", onFavoriteToggle, content)
    safeObserve("position", onPositionChange, content)
    safeObserve("watchlisted", onWatchlistToggle, content)
end sub


sub onFavoriteToggle(options = {})
    ctaItemModel = m.contentCTAsModel.findNode(userItemsTypes.FAVORITE)
    ctaItemModel.active = options.data
end sub


sub onPositionChange(options = {})
    ctaItemModel = m.contentCTAsModel.findNode(userItemsTypes.CWITEM)
    ctaItemModel.active = options.data <> 0
end sub


sub onWatchlistToggle(options = {})
    ctaItemModel = m.contentCTAsModel.findNode(userItemsTypes.WATCHLIST)
    ctaItemModel.active = options.data
end sub


sub onHydrated(options = {})
    content = options.node

    if not rodash.isEmpty(content.logoImageUri)
        m.contentLogo.visible = true
        m.title.visible = false
        setLogoImage(content.logoImageUri)
    else if not rodash.isEmpty(content.title)
        m.contentLogo.visible = false
        m.title.visible = true
        setLogoTitle(content.title)
    end if

    setDescription(content.description)
    setCTAs(content)
    setMetadata(content)
end sub


sub setCTAs(content = {})
    contentCTAsModel = exec("returnContentCTAsModel", {}, content)
    if not rodash.isNode(contentCTAsModel) then return
    m.contentCTAsModel = contentCTAsModel
    m.ctas.data = { content:  contentCTAsModel}
end sub


sub setDescription(description = "")
    if rodash.isEmptyString(description) then return
    m.description.text = description
end sub


sub setLogoImage(logoImageUri = "")
    if rodash.isEmptyString(logoImageUri) then return
    m.contentLogo.uri = logoImageUri
end sub


sub setLogoTitle(title = "")
    if rodash.isEmptyString(title) then return
    m.title.text = title
end sub


sub setMetadata(content = {})
    metadataArray = []

    if rodash.isArray(content.genres)
        metadataArray.push({
            genres: content.genres
    })
    end if

    if rodash.isNonEmptyString(content.copyrightYear)
        metadataArray.push({
            copyrightYear: content.copyrightYear
        })
    end if

    if rodash.isNumber(content.duration)
        metadataArray.push({
            duration: content.duration
        })
    end if

    if rodash.isNonEmptyString(content.rating)
        metadataArray.push({
            rating: content.rating
        })
    end if

    m.metadata.data = {
        metadataArray: metadataArray
    }
end sub
