import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.backgroundContainer = top().findNode("backgroundContainer")
        m.headerImage = top().findNode("headerImage")
        m.cornerGradient = top().findNode("cornerGradient")
        m.catalogGradientContainer = top().findNode("catalogGradientContainer")
        m.detailsGradientContainer = top().findNode("detailsGradientContainer")
        safeFunctions({
            hideBackground: hideBackground,
            hideCatalogGradients: hideCatalogGradients,
            hideDetailsGradients: hideDetailsGradients,
            hideHeaderImage: hideHeaderImage,
            showBackground: showBackground,
            showCatalogGradients: showCatalogGradients,
            showDetailsGradients: showDetailsGradients,
            showHeaderImage: showHeaderImage,
            updateAssets: updateAssets
        })
    end sub)
end sub


sub hideCatalogGradients(options = {})
    fadeOut(m.catalogGradientContainer, { duration: 1 })
end sub


sub showCatalogGradients(options = {})
    fadeIn(m.catalogGradientContainer, { duration: 1 })
end sub


sub showDetailsGradients(options = {})
    fadeIn(m.detailsGradientContainer, { duration: 1 })
end sub


sub hideDetailsGradients(options = {})
    fadeOut(m.detailsGradientContainer, { duration: 1 })
end sub


sub onBackgroundFadeOut(options = {})
    oldPoster = options.node
    if not rodash.isNode(oldPoster) then return
    m.backgroundContainer.removeChild(oldPoster)
end sub


sub setBackground(newUri = "")
    if rodash.isEmpty(newUri) then return
    newPoster = createObject("roSGNode", "Poster")
    newPoster.id = rodash.now().toStr()
    newPoster.opacity = 0
    newPoster.uri = newUri
    newPoster.width = "<%- s(STYLES.Dimensions.viewport.width) %>"
    newPoster.height = "<%- s(STYLES.Dimensions.viewport.height) %>"
    m.backgroundContainer.insertChild(newPoster, 0)
    if rodash.isInvalid(m.poster)
        m.poster = newPoster
        fadeIn(newPoster, { duration: 0.5 })
    else
        newPoster.opacity = 1
        oldPoster = m.poster
        m.poster = newPoster
        fadeOut(oldPoster, { callback: onBackgroundFadeOut, callbackOptions: { node: oldPoster }, duration: 0.5 })
    end if
end sub


sub updateAssets(options = {})
    if rodash.isEmpty(options) then return
    content = options.content
    if rodash.isEmpty(content) then return

    setComplimentaryColor(content.complimentaryColor)

    section = options.section
    if rodash.isEmpty(section) then return

    if section = sections.HERO
        setBackground(content.headerImageUri)
    else if section = sections.DETAILS_HERO
        setBackground(content.posterImageUri)
    else if section = sections.CAROUSEL
        m.headerImage.newUri = content.posterImageUri
    end if
end sub


sub setComplimentaryColor(newBlendColor = "")
    if rodash.isEmpty(newBlendColor) then return
    if not rodash.isNode(m.cornerGradient) then return
    if rodash.isEmpty(newBlendColor) then newBlendColor = "<%- s(STYLES.Palette.defaultCornerColor) %>"

    morphObject = {}
    morphObject[m.cornerGradient.id] = {
        fields: {
            blendColor: newBlendColor
        }
    }

    morph(morphObject)
end sub


sub hideBackground(options = {})
    fadeOut(m.backgroundContainer, { duration: 0.3 })
end sub


sub showBackground(options = {})
    fadeIn(m.backgroundContainer, { duration: 0.3 })
end sub


sub hideHeaderImage(options = {})
    fadeOut(m.headerImage, { duration: 0.3 })
end sub


sub showHeaderImage(options = {})
    fadeIn(m.headerImage, { duration: 0.3 })
end sub
