import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.backgroundContainer = top().findNode("backgroundContainer")
        m.cornerGradient = top().findNode("cornerGradient")
        m.catalogGradientContainer = top().findNode("catalogGradientContainer")
        m.contentGradientContainer = top().findNode("contentGradientContainer")
        m.headerImage = top().findNode("headerImage")

        safeFunctions({
            "hideBackground": hideBackground,
            "hideCatalogGradients": hideCatalogGradients,
            "hideContentGradients": hideContentGradients,
            "removeBackground": removeBackground,
            "setComplimentaryColor": setComplimentaryColor,
            "showBackground": showBackground,
            "showCatalogGradients": showCatalogGradients,
            "showContentGradients": showContentGradients,
            "updateBackgroundAssets": updateBackgroundAssets,
            "updateHeaderImage": updateHeaderImage
        })
    end sub)
end sub


sub hideCatalogGradients(_options = {})
    fadeOut(m.catalogGradientContainer, { duration: 0.5 })
end sub


sub showCatalogGradients(_options = {})
    fadeIn(m.catalogGradientContainer, { duration: 0.5 })
end sub


sub showContentGradients(_options = {})
    fadeIn(m.contentGradientContainer, { duration: 0.5 })
end sub


sub hideContentGradients(_options = {})
    fadeOut(m.contentGradientContainer, { duration: 0.5 })
end sub


sub onBackgroundFadeIn(options = {})
    oldPoster = options.node
    m.backgroundContainer.removeChild(oldPoster)
end sub


sub onBackgroundFadeOut(_options = {})
    for each child in m.backgroundContainer.getChildren(-1, 0)
        child.opacity = 0
    end for
end sub


sub removeBackground(options = {})
    content = options.content
    section = options.section ?? sections.CONTENT_HERO
    if not rodash.isNode(content) then return
    posterId = content.id + section
    poster = m.backgroundContainer.findNode(posterId)
    m.backgroundContainer.removeChild(poster)
end sub


sub setBackground(options = {})
    content = options.content
    if not rodash.isNode(content) then return
    if not content.hydrated then return

    section = options.section ?? ""
    posterId = content.id + section
    replaceCurrent = options.replace ?? false
    newUri = ""

    newPoster = m.backgroundContainer.findNode(posterId)

    if section = sections.HERO
        newUri = content.headerImageUri
    else if section = sections.CONTENT_HERO
        newUri = content.posterImageUri
    end if

    oldNode = not rodash.isNode(newPoster) and replaceCurrent ? m.backgroundContainer.getChild(0) : invalid

    if not rodash.isNode(newPoster)
        newPoster = createObject("roSGNode", "BackgroundImage")
        newPoster.id = posterId

        if rodash.isNonEmptyString(newUri)
            newPoster.blendColor = -1
            newPoster.uri = newUri
        end if

        m.backgroundContainer.appendChild(newPoster)
    end if

    fadeIn(newPoster, { callback: onBackgroundFadeIn, callbackOptions: { node: oldNode }, duration: 0.3 })
end sub


sub updateBackgroundAssets(options = {})
    setComplimentaryColor(options)
    showBackground()
    setBackground(options)
end sub


sub updateHeaderImage(options = {})
    m.headerImage.data = options
    showHeaderImage()
end sub


sub setComplimentaryColor(options = {})
    content = options.content
    newBlendColor = content.complimentaryColor

    if rodash.isEmpty(newBlendColor) then newBlendColor = "{{%- s(STYLES.Palette.defaultCornerColor) %}}"

    morphObject = {}
    morphObject[m.cornerGradient.id] = {
        fields: {
            blendColor: newBlendColor
        }
    }

    morph(morphObject)
end sub


sub hideBackground(_options = {})
    fadeOut(m.backgroundContainer, { callback: onBackgroundFadeOut, duration: 0.3 })
end sub


sub showBackground(_options = {})
    hideHeaderImage()
    fadeIn(m.backgroundContainer, { duration: 0.3 })
end sub


sub hideHeaderImage(_options = {})
    fadeOut(m.headerImage, { callback: clearHeaderImages, duration: 0.3 })
end sub


sub showHeaderImage(_options = {})
    hideBackground()
    fadeIn(m.headerImage, { duration: 0.3 })
end sub


sub clearHeaderImages(_options = {})
    exec("clearImages", {}, m.headerImage)
end sub
