import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.gradient = top().findNode("gradient")
        m.list = top().findNode("topbarList")
        m.overlay = top().findNode("overlay")
        m.userCarouselsContainer = top().findNode("userCarouselsContainer")
        m.userScrollGroup = top().findNode("userScrollGroup")
        liveConfig({ field: "config", keyPath: "ContentScrollGroup" }, m.userScrollGroup)

        safeObserve("itemFocused", onBarItemFocused, m.list)
        safeObserve("data", onDataChange)

        safeFunctions({
            "setUserCarousels": setUserCarousels
        })

        setFocusMap({
            "onFocus": onFocused,
            "onUnfocus": onUnfocused,
            "topbarList": {
                "default": false,
                "down": focusOnUserCarousel
            },
            "userScrollGroup": {
                "default": false,
                "up": m.list
            }
        })
    end sub)
end sub


function focusOnUserCarousel(_options = {})
    if not rodash.isNode(m.content) then return false

    currentNavFocus = m.list.itemFocused
    currentScrollItem = exec("getScrollItem", { itemIndex: currentNavFocus}, m.userScrollGroup)
    if not rodash.isNode(currentScrollItem) then return false
    carouselCollection = currentScrollItem.data?.content
    if not rodash.isNode(carouselCollection) then return false
    if carouselCollection.totalCount = 0 then return false

    setFocus(m.userScrollGroup)
    return true
end function

sub onBarItemFocused(options = {})
    m.userScrollGroup.animateToItem = options.data ?? 0
end sub


sub onDataChange(options = {})
    data = options.data
    content = data.content
    if not rodash.isNode(content) then return
    m.content = content
    liveConfig({ field: "config", keyPath: "Topbar" }, content)
    m.list.data = data
    fadeIn(top())
end sub


sub onFocused(_options = {})
    userCarouselsToggle(1)
    setFocus(m.list)
end sub


sub onUnfocused(_options = {})
    resetFocus()
    userCarouselsToggle(0)
end sub


sub processScrollItem(options = {})
    model = options.model
    component = createObject("roSGNode", "Carousel")

    liveConfig({ field: "config", keyPath: "UserCarousel" }, model)

    addClass("noTitle", component)
    component.data = { content: model }
    m.userScrollGroup.appendChild(component)
end sub


sub setUserCarousels(options = {})
    collections = options.collections

    for each collectionType in collections.items()
        collection = collectionType.value
        processScrollItem({ model: collection })
    end for
end sub


sub userCarouselsToggle(direction = 0)
    overlayOpacity = direction = 0 ? 0 : 0.6
    morphObject = {}
    morphObject[m.overlay.id] = {
        fields: {
            opacity: overlayOpacity
        }
    }
    morphObject[m.userCarouselsContainer.id] = {
        fields: {
            opacity: direction
        }
    }
    deferredAnimation = morph(morphObject, { deferred: true })

    floatFieldInterp = getFloatFieldInterpolator(deferredAnimation)
    if not rodash.isNode(floatFieldInterp) then return

    safeObserve("fraction", onAnimationFraction, floatFieldInterp)
    runAnimation(deferredAnimation.id)
end sub


sub onAnimationFraction(options = {})
    m.list.focusPercent = options.data
end sub
