import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.scrubBar = top().findNode("scrubBar")
        m.positionLabel = top().findNode("positionLabel")
        m.durationLabel = top().findNode("durationLabel")
        m.trickplay = top().findNode("trickplay")
        m.container = top().findNode("container")
        m.contentContainer = top().findNode("contentContainer")
        m.hideOverlay = top().findNode("hideOverlay")
        m.playerHeader = top().findNode("playerHeader")

        m.hideOverlay.config = "{{%- o(CONFIG.ControlItems.hideOverlay) %}}"

        safeObserve("data", onDataSet)

        safeFunctions({
            "onPositionChange": onPositionChange,
            "setPositionLabel": setPositionLabel
        })

        styleHooks({
            "after": afterStyling
        })

        afterStyling()
    end sub)
end sub


sub afterStyling(_options = {})
    stackChildren({ direction: "vertical" }, m.container)
    stackChildren({ direction: "vertical" }, m.contentContainer)
end sub


sub onDataSet(options = {})
    m.playerHeader.data = options.data
end sub


sub onPositionChange(options = {})
    position = options.position ?? 0
    duration = options.duration ?? get("duration") ?? 0
    exec("updateProgress", { position: position, duration: duration }, m.scrubBar)

    set({ duration: duration })

    setPositionLabel({ position: position })
    m.durationLabel.text = formatSeekText(duration)
end sub


sub setPositionLabel(options = {})
    position = options.position
    m.positionLabel.text = formatSeekText(position)
end sub


function formatSeekText(timeDelta = 0)
    if not rodash.isNumber(timeDelta) then return ""
    timeStr = ""
    iterationNumber = 0
    iterationDivisors = [3600, 60]
    template = ["00", "00", "00"]
    timeDelta% = timeDelta

    for each divisor in iterationDivisors
        modProduct = int(timeDelta%) \ divisor
        if modProduct <> 0
            timeStr = `0${modProduct}`
            template[iterationNumber] = right(timeStr, 2)
        end if

        timeDelta% = timeDelta% - (modProduct * divisor)
        iterationNumber++
    end for

    if timeDelta% <> 0
        timeStr = `0${timeDelta%}`
        template[2] = right(timeStr, 2)
    end if

    return template.join(":")
end function
