import "pkg:/components/_ord/wrappers.bs"
import "pkg:/source/roku_modules/promises/promises.brs"

sub init()
    exec(sub(_options = {})
        m.screenContainer = top().findNode("screenContainer")
        m.bottomContainer = top().findNode("bottomContainer")
        m.contentScrollGroup = top().findNode("contentScrollGroup")
        m.contentHero = top().findNode("contentHero")
        m.tabs = top().findNode("tabs")
        m.description = top().findNode("description")
        m.ctas = top().findNode("ctas")

        liveConfig({ field: "config", keyPath: "ContentScrollGroup" }, m.contentScrollGroup)
        safeObserve("data", onDataSet)
        safeObserve("itemFocused", onTabFocused, m.tabs)

        setFocusMap({
            "onFocus": m.contentHero,
            "contentHero": {
                "default": true,
                "back": false,
                "down": focusContentScrollGroup
            },
            "contentScrollGroup": {
                "back": false,
                "default": true,
                "up": focusContentHero
            },
            "tabs": {
                "back": false,
                "default": true,
                "down": m.contentScrollGroup,
                "up": sub(_options = {})
                    scrollPage(-1, onContentHeroFocused)
                end sub
            }
        })

        styleHooks({
            after: afterStyling
        })
    end sub)
end sub


sub onTabFocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.contentScrollGroup) then return

    m.contentScrollGroup.animateToItem = options.data ?? 0
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return

    data = options.data
    content = data.content
    if not rodash.isNode(content) then return

    m.content = content

    carousels = content.getChildren(-1, 0)
    for each model in carousels
        processScrollItem({ model: model })
    end for

    m.contentHero.data = { content: m.content }

    tabsModel = exec("returnTabsModel", { carousels: carousels }, content)

    if rodash.isNode(tabsModel)
        liveConfig({ field: "config", keyPath: "TabsCarousel" }, tabsModel)
        m.tabs.data = { content: tabsModel }
    end if

    afterStyling()
end sub


sub afterStyling(_options = {})
    if not rodash.isNode(m.screenContainer) then return
    if not rodash.isNode(m.bottomContainer) then return
    stackChildren({ node: m.screenContainer, direction: "vertical" })
    stackChildren({ node: m.bottomContainer, direction: "vertical" })
end sub


sub focusContentHero(_options = {})
    if not rodash.isNode(m.content) then return
    carouselCount = m.content.getChildCount()

    if carouselCount = 0 then return

    if carouselCount = 1
        scrollPage(-1, onContentHeroFocused)
    else
        setFocus(m.tabs)
    end if
end sub


sub focusContentScrollGroup(_options = {})
    if not rodash.isNode(m.content) then return
    scrollPage(1, onContentScrollGroupFocused)
end sub


sub onContentHeroFocused(_options = {})
    if not rodash.isNode(m.contentHero) then return
    setFocus(m.contentHero)
end sub


sub onContentScrollGroupFocused(_options = {})
    if not rodash.isNode(m.contentScrollGroup) then return
    if not rodash.isNode(m.content) then return

    carouselCount = m.content.getChildCount()

    if carouselCount = 0 then return

    if carouselCount = 1
        setFocus(m.contentScrollGroup)
    else
        setFocus(m.tabs)
    end if
end sub


sub processScrollItem(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    component = createObject("roSGNode", "Carousel")

    thumbnailType = model.thumbnailType
    configKey = thumbnailType = thumbnailTypes.LANDSCAPE ? "LandscapeCarousel" : "PortraitCarousel"
    liveConfig({ field: "config", keyPath: configKey }, model)

    addClass("noTitle", component)
    component.data = { content: model }
    m.contentScrollGroup.appendChild(component)
end sub


sub scrollPage(direction = 0, callbackFunc = invalid)
    if not rodash.isNode(m.bottomContainer) then return
    if not rodash.isNode(m.contentHero) then return
    if not rodash.isNode(m.description) then return
    if not rodash.isNode(m.ctas) then return

    morphObject = {}
    heightDelta = 393 * direction
    morphObject[m.bottomContainer.id] = {
        fields: {
            height: m.bottomContainer.height + heightDelta,
            translation: [
                0,
                m.contentHero.height - heightDelta
            ]
        }
    }

    morphObject[m.contentHero.id] = {
        fields: {
            height: m.contentHero.height - heightDelta
        }
    }

    morphObject[m.description.id] = {
        fields: {
            opacity: 0 - direction
        }
    }

    morphObject[m.ctas.id] = {
        fields: {
            opacity: 0 - direction
        }
    }

    morph(morphObject, { callback: callbackFunc, duration: 0.3 })
end sub


' Methods exteded from sgRouter

function beforeViewOpen(options = {}) as dynamic
    if not rodash.isNonEmptyAA(options) then return invalid
    routeData = options.route
    if not rodash.isNode(routeData) then return promises.resolve(invalid)
    context = routeData.context ?? {}
    content = context.content
    if not rodash.isNode(content) then return promises.resolve(invalid)

    top().opacity = 0.001
    fadeIn(top(), { duration: 0.5 })

    dispatch(events.SHOW_CONTENT_UI)
    dispatch(events.GET_CONTENT_DATA, { screenId: routeData.id, slug: routeData.path, content: content })
    return promises.resolve(invalid)
end function


function beforeViewSuspend(_options = {}) as dynamic
    fadeOut(top(), { duration: 0.5 })
    return promises.resolve(invalid)
end function


function onViewOpen(_options = {})
    return promises.resolve(invalid)
end function


function onViewResume(_options = {})
    dispatch(events.SHOW_CONTENT_UI)
    fadeIn(top(), { duration: 0.5 })
    return promises.resolve(invalid)
end function
