import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub()
        m.gradient = top().findNode("gradient")
        loadSidebar()
        safeObserve("focusedChild", onFocusedChildChange)
    end sub)
end sub


sub loadSidebar()
    list = top().findNode("sidebarList")

    model = createObject("roSGNode", "SidebarModel")
    model.rectConfig = {
        direction: "vertical",
        carouselType: "dynamicSize",
        focusType: "floating",
        itemComponentName: "NavigationItem",
        maxHeight: 1800,
        visibleTiles: 999,
        squareMargins: [0, 0, 0, 0],
        startingPositionOffsets: [0, 0, 0, 0, 0, 0, 0, 149, 0],
        uniformCrossAxisSize: true,
        useUnfocusedTargetSet: true,
        horizAlign: "left"
    }

    list.data = {
        content: model
    }

    m.list = list
    safeObserve("width", onListWidthChange, m.list)
    safeObserve("focusPercent", onFocusPercentChange, m.list)
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    m.list.setFocus(true)
end sub


sub onFocusPercentChange(options = {})
    focusPercent = options.data ?? 0
    sidebarColor = "<%- s(STYLES.Palette.sidebarColor) %>"
    maxSidebarColorOpacity = 0.8
    top().color = addOpacityToHexColor(sidebarColor, focusPercent * maxSidebarColorOpacity)

    minGradientOpacity = 0.7
    m.gradient.opacity = minGradientOpacity + ((1 - minGradientOpacity) * focusPercent)
end sub


sub onListWidthChange(options = {})
    if not rodash.isNonEmptyAA(options) then return

    listWidth = options.data
    if not rodash.isNumber(listWidth) then return

    m.gradient.width = listWidth + 3
    top().width = listWidth
end sub


function addOpacityToHexColor(color = "", opacity = 0) as string
    opacityHex = right("0" + stri(cint(opacity * 255), 16), 2)

    return left(color, 7) + opacityHex
end function
