import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.gradient = top().findNode("gradient")
        m.list = top().findNode("sidebarList")
        safeObserve("width", onListWidthChange, m.list)
        safeObserve("focusPercent", onFocusPercentChange, m.list)
        safeObserve("itemSelected", onItemSelected, m.list)
        safeObserve("itemFocused", onItemFocused, m.list)

        safeObserve("data", onDataChange)
        safeObserve("focusedChild", onFocusedChildChange)
    end sub)
end sub


sub onDataChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    data = options.data
    content = data.content
    if not rodash.isNode(content) then return

    m.content = content

    liveConfig({ field: "config", keyPath: "Sidebar" }, content)
    m.list.data = data

    defaultSlug = content.defaultSlug
    itemModel = content.findNode(defaultSlug)
    selectedItemIndex = rodash.indexOf(content.getChildren(-1, 0), itemModel)
    m.list.itemSelected = selectedItemIndex
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) or not top().isSameNode(focusedChild) then return
    m.list.setFocus(true)
end sub


sub onItemFocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    itemFocused = options.data
    ?"sidebar onItemFocused " itemFocused
end sub


sub onItemSelected(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.content) then return

    itemSelected = options.data
    itemModel = m.content.getChild(itemSelected)
    if not rodash.isNode(itemModel) then return

    dispatch(events.NAVIGATE_TO, { slug: itemModel.id, documentId: itemModel.documentId })
end sub


sub onFocusPercentChange(options = {})
    focusPercent = options.data ?? 0
    sidebarColor = top().openColor
    maxSidebarColorOpacity = 0.9
    top().color = addOpacityToHexColor(sidebarColor, focusPercent * maxSidebarColorOpacity)

    minGradientOpacity = 0.7
    m.gradient.opacity = minGradientOpacity + ((1 - minGradientOpacity) * focusPercent)
end sub


sub onListWidthChange(options = {})
    if not rodash.isNonEmptyAA(options) then return

    listWidth = options.data
    if not rodash.isNumber(listWidth) then return

    m.gradient.width = listWidth + 3
    top().width = listWidth
end sub


function addOpacityToHexColor(color = "", opacity = 0) as string
    opacityHex = right("0" + stri(cint(opacity * 255), 16), 2)

    return left(color, 7) + opacityHex
end function
