class Eventable extends onRokuDevInterface
    override sub initInterface()
        m.messageTask = createObject("roSGNode", "roMessageTask")
        m.messageTask.control = "RUN"
    end sub


    sub dispatch(eventId, options = {})
        if rodash.isEmpty(eventId) then return
        payload = {
            id: eventId
            options: options
        }
        m.messageTask.eventData = payload
    end sub
end class
