class Eventable
    subscriptions = {}
    publicFunctions = {}

    sub new(options = {})
        if not rodash.isNode(options.top) then return
        m.top = options.top

        componentRole = options.role ?? ""
        if rodash.isEmptyString(componentRole) then return

        if componentRole <> "Task"
            m.messageTask = createObject("roSGNode", "roMessageTask")
            m.messageTask.control = "RUN"
        end if

        m.top.addField("ordSubscriptions", "assocarray", false)

        ' m.setExportFunctions(componentRole)
    end sub

    ' sub setExportFunctions(role)
    '     if rodash.isEmptyString(role) then return

    '     if rodash.findIndex(["Scene", "View", "Model", "Controller", "Task"], role) <> -1
    '         m.publicFunctions.append({
    '             _dispatch: m.dispatch
    '         })
    '     end if

    '     if rodash.findIndex(["Scene", "Controller"], role) <> -1
    '         m.publicFunctions.append({
    '             _subscribe: m.subscribe
    '         })
    '     end if

    '     if rodash.findIndex(["Task"], role) <> -1
    '         m.publicFunctions.append({
    '             _publish: m.publish
    '         })
    '     end if
    ' end sub

    sub storeFunctions(options = {})
        subscriptions = m.top.getRef("ordSubscriptions") ?? {}

        name = options.name
        functions = options.functions
        functionArray = []

        if rodash.isArray(functions)
            functionArray.append(functions)
        else
            functionArray.push(functions)
        end if

        subscriptions[name] = functionArray
        m.top.setRef("ordSubscriptions", subscriptions)
    end sub


    sub subscribe(options = {})
        if rodash.isEmpty(options) then return

        for each event in options.items()
            eventName = event.key
            eventFunctions = event.value

            if rodash.isEmptyString(eventName) then continue for
            if not rodash.isString(eventFunctions) and not rodash.isArray(eventFunctions) then continue for

            m.storeFunctions({ name: eventName, functions: eventFunctions })

            messageQueue = getQueue()
            if messageQueue = invalid then return

            observeFunction = m.callEventFunctions
            observeFunctionName = rodash.getFunctionName(observeFunction)
            messageQueue.addMessageHandler(eventName, observeFunctionName)
        end for
    end sub

    sub callEventFunctions(data = {}, messageInfo = {})
        ?"callEventFunctions " data messageInfo
        if rodash.isEmpty(messageInfo) then return

        subscriptions = m.top.getRef("ordSubscriptions") ?? {}

        if rodash.isEmpty(subscriptions) then return

        eventId = messageInfo.message_id ?? ""
        eventFunctions = subscriptions[eventId]

        for each functionName in eventFunctions
            exec(functionName, data)
        end for
    end sub

    sub publish(name = "", options = {})
        messageQueue = getQueue()
        if messageQueue = invalid then return
        messageQueue.postMessage(name, options)
    end sub

    sub dispatch(eventId, options = {})
        if rodash.isEmpty(eventId) then return
        payload = {
            id: eventId
            options: options
        }
        m.messageTask.eventData = payload
    end sub
end class
