class Receivable extends onRokuDevInterface
    subscriptions = {}

    override sub initInterface(options = {})
        m.top.addField("ordSubscriptions", "assocarray", false)
    end sub


    sub storeFunctions(options = {})
        subscriptions = m.top.getRef("ordSubscriptions") ?? {}

        name = options.name
        functions = options.functions
        functionArray = []

        if rodash.isArray(functions)
            functionArray.append(functions)
        else
            functionArray.push(functions)
        end if

        subscriptions[name] = functionArray
        m.top.setRef("ordSubscriptions", subscriptions)
    end sub


    sub subscribe(options = {})
        if rodash.isEmpty(options) then return

        for each event in options.items()
            eventName = event.key
            eventFunctions = event.value

            if rodash.isEmptyString(eventName) then continue for
            if not rodash.isString(eventFunctions) and not rodash.isArray(eventFunctions) then continue for

            m.storeFunctions({ name: eventName, functions: eventFunctions })

            messageQueue = getQueue()
            if messageQueue = invalid then return

            observeFunction = m.callEventFunctions
            observeFunctionName = rodash.getFunctionName(observeFunction)
            messageQueue.addMessageHandler(eventName, observeFunctionName)
        end for
    end sub


    sub callEventFunctions(data = {}, messageInfo = {})
        if rodash.isEmpty(data) or rodash.isEmpty(messageInfo) then return

        subscriptions = m.top.getRef("ordSubscriptions") ?? {}

        if rodash.isEmpty(subscriptions) then return

        eventId = messageInfo.message_id ?? ""
        eventFunctions = subscriptions[eventId]

        for each functionName in eventFunctions
            exec(functionName, data)
        end for
    end sub
end class
