import "pkg:/components/_ord/wrappers.bs"
import "pkg:/source/roku_modules/sgrouter/router.brs"

sub init()
    exec(sub(options = {})
        sgRouter.initialize({ outlet: top().findNode("screenContainer") })

        sgRouter.addRoutes([
            { pattern: "/home", component: "CatalogScreen" },
            ' { pattern: "/shows", component: "CatalogScreen", clearStackOnResolve: true },
            ' { pattern: "/movies", component: "CatalogScreen", clearStackOnResolve: true },
            ' { pattern: "/details/series/:id", component: "DetailsScreen" },
            ' { pattern: "/details/series/:id/cast", component: "CastDetailsScreen" },
            ' { pattern: "/details/movies/:id", component: "DetailsScreen" },
            ' { pattern: "/details/movies/:id/cast", component: "CastDetailsScreen" },
            ' { pattern: "/:screenName", component: "DefaultScreen" }
        ])

        safeFunctions({
            "navigateTo": navigateTo
        })

        ' sgRouter.navigateTo("/home") ' Go to the welcome view

        ' set the focus to the router
        ' sgRouter.setFocus({ focus: true })

        safeObserve("routerState", onRouterStateChanged, sgRouter.getRouter())
        safeObserve("focusedChild", onFocusedChildChange)
    end sub)
end sub


sub navigateTo(options = {})
    if not rodash.isNonEmptyAA(options) then return

    slug = options.slug ?? ""
    if rodash.isEmptyString(slug) then return

    sgRouter.navigateTo(slug)
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) or not top().isSameNode(focusedChild) then return
    sgRouter.setFocus({ focus: true })
end sub


sub onRouterStateChanged(options = {})
    data = options.data
    if data.type <> "ActivationStart" then return

    dispatch(events.GET_SCREEN_DATA, { screenId: data.id, slug: data.url })
end sub
