import "pkg:/components/_ord/wrappers.bs"
import "pkg:/source/roku_modules/sgrouter/router.brs"

sub init()
    exec(sub(options = {})
        m.background = top().findNode("background")
        m.navigation = top().findNode("navigation")
        m.topbar = top().findNode("topbar")
        m.sidebar = top().findNode("sidebar")
        m.screenContainer = top().findNode("screenContainer")
        sgRouter.initialize({ outlet: m.screenContainer })

        sgRouter.addRoutes([
            { pattern: "/home", component: "CatalogScreen", keepVisible: true},
            ' { pattern: "/shows", component: "CatalogScreen", clearStackOnResolve: true },
            ' { pattern: "/movies", component: "CatalogScreen", clearStackOnResolve: true },
            ' { pattern: "/details/series/:id/cast", component: "CastDetailsScreen" },
            { pattern: "/details/:id", component: "DetailsScreen" },
            ' { pattern: "/details/movies/:id", component: "DetailsScreen" },
            ' { pattern: "/details/movies/:id/cast", component: "CastDetailsScreen" },
            ' { pattern: "/:screenName", component: "DefaultScreen" }
        ])

        safeFunctions({
            "showDetailsUI": showDetailsUI,
            "showCatalogUI": showCatalogUI,
            "navigateTo": navigateTo
        })

        setFocusMap({
            "default": m.screenContainer,
            "sidebar": {
                "right": focusOnScreen
            },
            "topbar": {
                "down": focusOnScreen,
                "left": m.sidebar
            }
        })

        set({
            catalogUIHidden: false,
            detailsUIHidden: true,
            navigationHidden: false
        })

        safeObserve("routerState", onRouterStateChanged, sgRouter.getRouter())
        safeObserve("focusedChild", onFocusedChildChange)
    end sub)
end sub


sub showCatalogUI(options = {})
    if get("navigationHidden")
        set({ navigationHidden: false })
        fadeIn(m.navigation, { duration: 1 })
    end if

    if get("catalogUIHidden")
        set({ catalogUIHidden: false, detailsUIHidden: true })
        exec("showCatalogGradients", options, m.background)
        exec("hideDetailsGradients", options, m.background)
    end if
end sub


sub showDetailsUI(options = {})
    if not get("navigationHidden")
        set({ navigationHidden: true })
        fadeOut(m.navigation, { duration: 1 })
    end if

    if get("detailsUIHidden")
        set({ catalogUIHidden: true, detailsUIHidden: false })
        exec("hideCatalogGradients", options, m.background)
        exec("showDetailsGradients", options, m.background)
    end if
end sub


sub navigateTo(options = {})
    if not rodash.isNonEmptyAA(options) then return

    slug = options.slug ?? ""
    if rodash.isEmptyString(slug) then return

    sgRouter.navigateTo(slug, { context: options })
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) or not top().isSameNode(focusedChild) then return
    focusOnScreen()
end sub


sub focusOnScreen(options = {})
    activeView = m.activeView
    if not rodash.isNode(activeView) then return
    setFocus(m.activeView)
end sub


sub onRouterStateChanged(options = {})
    data = options.data
    if data.type <> "NavigationEnd" then return
    setActiveView(data.id)
end sub


sub setActiveView(screenId = "")
    if rodash.isEmptyString(screenId) then return
    m.activeView = top().findNode(screenId)
    mapObject = {}

    viewMapObject = {
        "left": m.sidebar,
        "up": m.topbar
    }
    mapObject[screenId] = viewMapObject
    setFocusMap(mapObject)
    setFocus(m.activeView)
end sub


function onKeyEvent(key as string, press as boolean) as boolean
    return exec(function(options = {})
        key = options.key
        press = options.press
        if not press then return true
        handled = processFocus(key)
        ?"Layout onKeyEvent " key, handled
        return handled
    end function, { key: key, press: press })
end function
