import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runStyleTask)
    end sub)
end sub


function runStyleTask(_options = {})
    response = rokurequests_Requests().get("<%- s(CONFIG.ENV.LOCAL_DEV_SERVER) %>" + "/styles-update.json")
    responseJSON = response.json ?? {}

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return true
    end if

    publish(events.STYLES_UPDATE, responseJSON)

    return true
end function
