import "pkg:/components/_ord/wrappers.bs"
import "pkg:/source/roku_modules/promises/promises.brs"

sub init()
    exec(sub(options = {})
        m.screenContainer = top().findNode("screenContainer")
        m.catalogHero = top().findNode("catalogHero")
        m.scrollGroup = top().findNode("scrollGroup")

        liveConfig({ field: "config", keyPath: "CatalogScrollGroup" }, m.scrollGroup)

        safeObserve("data", onDataSet)

        styleHooks({
            after: afterStyling
        })
    end sub)
end sub


sub afterStyling(options = {})
    if not rodash.isNode(m.screenContainer) then return
    stackChildren({ node: m.screenContainer, direction: "vertical" })
end sub


function handleFocus(options = {})
    return exec(function(options = {})
        m.scrollGroup.setFocus(true)
        return true
    end function)
end function


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if rodash.isNode(m.content) then return

    data = options.data
    content = data.content
    m.content = content

    for each model in content.getChildren(-1, 0)
        processScrollItem({ model: model })
    end for
end sub


sub processScrollItem(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    carouselType = model.carouselType ?? "INDEX"

    if carouselType = "HERO"
        m.catalogHero.data = { content: model }
    else
        component = createObject("roSGNode", "Carousel")
        component.data = { content: model }
        m.scrollGroup.appendChild(component)
    end if

    afterStyling()
end sub
