import "pkg:/components/_ord/wrappers.bs"
import "pkg:/source/roku_modules/promises/promises.brs"

sub init()
    exec(sub(options = {})
        m.screenContainer = top().findNode("screenContainer")
        m.catalogHero = top().findNode("catalogHero")
        m.scrollGroup = top().findNode("scrollGroup")
        m.catalogHeader = top().findNode("catalogHeader")

        liveConfig({ field: "config", keyPath: "CatalogScrollGroup" }, m.scrollGroup)

        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)
        safeObserve("itemFocused", onScrollGroupItemFocused, m.scrollGroup)

        setFocusMap({
            "default": m.catalogHero,
            "catalogHero": {
                "down": focusScrollGroup
            },
            "scrollGroup": {
                "up": focusCatalogHero
            }
        })

        styleHooks({
            after: afterStyling
        })
    end sub)
end sub


sub focusCatalogHero(options = {})
    scrollPage(-1, onCatalogHeroFocused)
    dispatch(events.CATALOG_HERO_FOCUSED)
end sub


sub focusScrollGroup(options = {})
    scrollPage(1, onScrollGroupFocused)
    dispatch(events.SCROLL_GROUP_FOCUSED)
end sub


sub onCatalogHeroFocused(options = {})
    setFocus(m.catalogHero)
end sub


sub onScrollGroupFocused(options = {})
    if not rodash.isNode(m.scrollGroup) then return
    setFocus(m.scrollGroup)
end sub


sub onScrollGroupItemFocused(options = {})
    ?"onScrollGroupItemFocused " options
    if not rodash.isNonEmptyAA(options) then return
end sub


sub scrollPage(direction = 0, callbackFunc = invalid)
    morphObject = {}
    heightDelta = 195 * direction
    morphObject[m.scrollGroup.id] = {
        fields: {
            height: m.scrollGroup.height + heightDelta,
            translation: [
                0,
                m.catalogHero.height - heightDelta
            ]
        }
    }
    morphObject[m.catalogHero.id] = {
        fields: {
            height: m.catalogHero.height - heightDelta,
            opacity: 1 - direction
        }
    }

    morphObject[m.catalogHeader.id] = {
        fields: {
            height: direction = -1 ? m.catalogHero.height - heightDelta : 0,
            opacity: 0 + direction
        }
    }

    m.catalogHeader.visible = direction = 1 ? true : false

    morph(morphObject, { callback: callbackFunc, duration: 0.3 })
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub afterStyling(options = {})
    if not rodash.isNode(m.screenContainer) then return
    stackChildren({ node: m.screenContainer, direction: "vertical" })
end sub


function handleFocus(options = {})
    return exec(function(options = {})
        applyDefaultFocus()
        return true
    end function)
end function


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if rodash.isNode(m.content) then return

    data = options.data
    content = data.content
    m.content = content

    for each model in content.getChildren(-1, 0)
        processScrollItem({ model: model })
    end for
end sub


sub processScrollItem(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    carouselType = model.carouselType ?? "INDEX"

    if carouselType = "HERO"
        m.catalogHero.data = { content: model }
    else
        component = createObject("roSGNode", "Carousel")
        component.data = { content: model }
        m.scrollGroup.appendChild(component)
    end if

    afterStyling()
end sub


function onKeyEvent(key as string, press as boolean) as boolean
    return exec(function(options = {})
        key = options.key
        press = options.press
        if not press then return true
        handled = processFocus(key)
        ?"CatalogScreen onKeyEvent " key, handled
        return handled
    end function, { key: key, press: press })
end function
