import "pkg:/components/_ord/init.bs"
import "pkg:/source/roku_modules/promises/promises.brs"

sub init()
    exec(sub(_options = {})
        m.screenContainer = top().findNode("screenContainer")
        m.catalogHero = top().findNode("catalogHero")
        m.scrollGroup = top().findNode("scrollGroup")
        m.catalogHeader = top().findNode("catalogHeader")

        liveConfig({ field: "config", keyPath: "CatalogScrollGroup" }, m.scrollGroup)

        safeObserve("data", onDataSet)
        safeObserve("itemFocused", onScrollGroupItemFocused, m.scrollGroup)

        safeFunctions({
            "updateHeader": updateHeader
        })

        set({
            "dataSet": false,
            "hasHero": false
        })

        setFocusMap({
            "onFocus": focusScreen,
            "catalogHero": {
                "down": focusScrollGroup
            },
            "scrollGroup": {
                "up": focusCatalogHero
            }
        })

        styleHooks({
            "after": afterStyling
        })
    end sub)
end sub


sub checkPagination(options = {})
    if not rodash.isNode(m.content) then return
    itemFocused = options.itemFocused ?? 0
    lastPaginatedIndex = m.content.totalCount - 1
    paginationDelta = lastPaginatedIndex - itemFocused
    needsPaginating = paginationDelta <= 3 and m.content.canPaginate and not m.content.paginating
    if needsPaginating then dispatch(events.PAGINATE_SCREEN, { collection: m.content })
end sub


function focusCatalogHero(_options = {})
    if get("hasHero") ?? false
        scrollPage(-1, onCatalogHeroFocused)
        dispatch(events.CATALOG_HERO_FOCUSED)
        return true
    else
        return false
    end if
end function


sub focusScreen(_options = {})
    if not get("dataSet") ?? false then return

    if get("hasHero") ?? false
        setFocus(m.catalogHero)
    else
        setFocus(m.scrollGroup)
    end if
end sub


sub focusScrollGroup(_options = {})
    scrollPage(1, onScrollGroupFocused)
    dispatch(events.CATALOG_CAROUSELS_FOCUSED)
end sub


sub onCatalogHeroFocused(_options = {})
    setFocus(m.catalogHero)
end sub


sub onScrollGroupFocused(_options = {})
    if not rodash.isNode(m.scrollGroup) then return
    setFocus(m.scrollGroup)
end sub


sub onScrollGroupItemFocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if options.data = -1 then return
    if not rodash.isNonEmptyAA(options) then return
    checkPagination({ itemFocused: options.data })
end sub


sub scrollPage(direction = 0, callbackFunc = invalid)
    if not rodash.isNode(m.scrollGroup) then return
    if not rodash.isNode(m.catalogHero) then return
    if not rodash.isNode(m.catalogHeader) then return

    morphObject = {}
    heightDelta = 150 * direction

    morphObject[m.scrollGroup.id] = {
        fields: {
            height: m.scrollGroup.height + heightDelta,
            translation: [0, m.catalogHero.height - heightDelta]
        }
    }
    morphObject[m.catalogHero.id] = {
        fields: {
            height: m.catalogHero.height - heightDelta,
            opacity: 1 - direction
        }
    }

    morphObject[m.catalogHeader.id] = {
        fields: {
            height: direction = 1 ? m.catalogHero.height - heightDelta : 0,
            opacity: 0 + direction
        }
    }

    m.catalogHeader.visible = direction = 1 ? true : false

    morph(morphObject, { callback: callbackFunc })
end sub


sub afterStyling(_options = {})
    if not rodash.isNode(m.screenContainer) then return
    stackChildren({ direction: "vertical" }, m.screenContainer)
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if rodash.isNode(m.content) then return

    data = options.data
    content = data.content
    if not rodash.isNode(content) then return

    m.content = content
    hasHero = false

    for each model in content.getChildren(-1, 0)
        if not hasHero then hasHero = model.carouselType = carouselTypes.HERO
        processScrollItem({ model: model })
    end for

    set({ "dataSet": true, "hasHero": hasHero })
    if not hasHero then addClass("noHero", m.screenContainer)

    afterStyling()
    applyDefaultFocus()

    safeObserve("change", onCollectionChildChange, content)
end sub


sub onCollectionChildChange(options = {})
    changeData = options.data
    collection = options.node

    if rodash.isEmpty(changeData) then return
    operation = changeData.operation ?? ""
    if operation <> "add" and operation <> "remove" then return

    numberOfNewNodes = changeData.index2 - changeData.index1 + 1
    addedNodes = collection.getChildren(numberOfNewNodes, changeData.index1)
    if operation = "add"
        for each model in addedNodes
            processScrollItem({ model: model })
        end for
    end if
end sub


sub processScrollItem(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    carouselType = model.carouselType ?? "INDEX"

    if carouselType = "HERO"
        m.catalogHero.data = { content: model }
    else
        component = createObject("roSGNode", "Carousel")

        thumbnailType = model.thumbnailType
        configKey = thumbnailType = thumbnailTypes.LANDSCAPE ? "LandscapeCarousel" : "PortraitCarousel"
        liveConfig({ field: "config", keyPath: configKey }, model)

        component.data = { content: model }
        m.scrollGroup.appendChild(component)
    end if
end sub


sub updateHeader(options = {})
    if rodash.isEmpty(options) then return
    if not rodash.isNode(m.catalogHeader) then return
    m.catalogHeader.data = options
end sub


' Methods exteded from sgRouter

function beforeViewOpen(options = {}) as dynamic
    if rodash.isNonEmptyAA(options) then dispatch(events.GET_CATALOG_DATA, { screenId: options.route?.id, slug: options.route?.path })
    return promises.resolve(invalid)
end function


function beforeViewSuspend(_options = {}) as dynamic
    suspendPromise = promises.create()
    fadeOut(top(), { duration: 0.5, callback: onViewFadedOut, callbackOptions: { promise: suspendPromise } })
    return suspendPromise
end function


sub onViewFadedOut(options = {})
    if not rodash.isNonEmptyAA(options) then return
    suspendPromise = options.promise
    promises.resolve(true, suspendPromise)
end sub


function onViewResume(_options = {})
    dispatch(events.SHOW_CATALOG_UI)
    fadeIn(top(), { duration: 0.5 })
    return promises.resolve(invalid)
end function
