import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.list = top().findNode("ctasList")
        setFocusMap({
            "onFocus": m.list
        })
        safeObserve("data", onDataChange)
        safeObserve("itemSelected", onItemSelected, m.list)
    end sub)
end sub


sub onDataChange(options = {})
    data = options.data
    m.model = data.content

    liveConfig({ field: "config", keyPath: "CTACarousel" }, m.model)

    m.list.data = {
        content: m.model
    }
end sub


sub onItemSelected(options = {})
    itemSelected = options.data
    itemSelectedModel = m.model.getChild(itemSelected)
    top().ctaSelected = itemSelectedModel.id
end sub
