import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        m.list = top().findNode("ctasList")
        safeObserve("focusedChild", onFocusedChildChange)
        safeObserve("data", onDataChange)
        safeObserve("itemSelected", onItemSelected, m.list)
    end sub)
end sub


sub onDataChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.list) then return

    data = options.data
    m.model = data.content

    liveConfig({ field: "config", keyPath: "CTACarousel" }, m.model)

    m.list.data = {
        content: m.model
    }
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) or not top().isSameNode(focusedChild) then return
    if not rodash.isNode(m.list) then return
    m.list.setFocus(true)
end sub


sub onItemSelected(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.model) then return
    itemSelected = options.data
    itemSelectedModel = m.model.getChild(itemSelected)
    top().ctaSelected = itemSelectedModel.id
end sub
