class Animatable
    animations = {}
    publicFunctions = []
    defaultOptions = {
        "duration": 0.3,
        "easeFunction": "linear",
        "repeat": false,
        "optional": true,
        "options": []
    }

    sub new(_options = {})
        m.setExportFunctions(getGlobalAA().ord_role)
        if rodash.findIndex(["Scene", "View"], getGlobalAA().ord_role) = -1 then return
    end sub


    sub reset(_options = {})
        m.animations = {}
    end sub


    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(componentRole) then return

        if rodash.findIndex(["Scene", "View"], componentRole) = -1 then return

        m.publicFunctions = []
        m.publicFunctions.push("getFloatFieldInterpolator")
        m.publicFunctions.push("fadeIn")
        m.publicFunctions.push("fadeOut")
        m.publicFunctions.push("morph")
        m.publicFunctions.push("removeAnimation")
        m.publicFunctions.push("runAnimation")
    end sub


    sub runAnimation(options = {})
        id = options.id ?? ""
        if rodash.isEmptyString(id) then return

        animation = m.animations[id] ?? invalid
        if not rodash.isNode(animation) then return

        safeObserve("state", m.onAnimationComplete, animation)
        animation.control = "start"
    end sub


    function createAnimation(animationId = "", options = {})
        settings = {}
        settings.append(options)
        nodeId = settings.nodeId ?? ""
        animationOptions = settings.options ?? []
        settings.delete("options")

        animation = createObject("roSGNode", "Animation")
        animation.id = animationId
        animation.setFields(settings)

        for each option in animationOptions
            field = option.field ?? ""
            if rodash.isEmptyString(field) then continue for

            keyValue = option.keyValue ?? invalid
            if not rodash.isNonEmptyArray(keyValue) then continue for

            interpId = [nodeId, field].join(".")
            interpField = animation.findNode(interpId)

            if not rodash.isNode(interpField)
                interp = m.getInterpName(field)
                if rodash.isEmptyString(interp) then continue for
                interpField = createObject("roSGNode", interp)
                interpField.fieldToInterp = interpId
                interpField.id = interpId
            end if

            interpField.key = option.key ?? [0, 1]
            interpField.keyValue = keyValue
            animation.appendChild(interpField)
        end for

        return animation
    end function


    sub addAnimation(id = "", animations = [])
        if rodash.isEmptyString(id) then return
        if not rodash.isArray(animations) then return
        if m.animations = invalid then m.animations = {}

        animationCollection = []

        for each settings in animations
            animationId = m.constructAnimationId([settings])
            animation = m.createAnimation(animationId, settings)
            if rodash.isNode(animation) then animationCollection.push(animation)
        end for

        if animationCollection.count() = 0 then return

        if animationCollection.count() > 1

            animationShell = createObject("roSGNode", "ParallelAnimation")

            duration = 0

            for each item in animationCollection
                if item.duration > duration then duration = item.duration
                animationShell.appendChild(item)
            end for

            animationShell.update({ duration: duration }, true)
        else
            animationShell = animationCollection[0]
        end if

        animationShell.id = id

        if not rodash.isNode(animationShell) then return

        m.animations[id] = animationShell
    end sub


    sub removeAnimation(options = {})
        id = options.id ?? ""
        if rodash.isEmptyString(id) then return

        animationShell = m.animations[id] ?? invalid
        if not rodash.isNode(animationShell) then return

        safeUnobserve("state", animationShell)
        if animationShell.hasField("callback") then animationShell.setRef("callback", {})
        m.animations.delete(id)
    end sub


    function getFloatFieldInterpolator(options = {})
        node = options.node
        children = node.getChildren(-1, 0)
        for each child in children
            if child.subType() = "FloatFieldInterpolator" then return child
            return getFloatFieldInterpolator(child)
        end for
        return invalid
    end function


    function getInterpName(field = "") as Object
        if rodash.isEmptyString(field) then return ""

        fieldsMap = {
            "blendColor": "ColorFieldInterpolator",
            "color": "ColorFieldInterpolator",
            "height": "FloatFieldInterpolator",
            "opacity": "FloatFieldInterpolator",
            "scale": "Vector2DFieldInterpolator",
            "size": "FloatFieldInterpolator",
            "translation": "Vector2DFieldInterpolator",
            "width": "FloatFieldInterpolator"
        }

        if fieldsMap.doesExist(field) then return fieldsMap[field]
        return ""
    end function


    sub onAnimationComplete(options = {})
        state = options.data ?? ""
        animation = options.node

        if state <> "stopped" then return
        if not rodash.isNode(animation) then return

        safeUnobserve("state", animation)

        callback = animation.hasField("callback") ? animation.getRef("callback") : invalid
        if not rodash.isNonEmptyAA(callback) then return

        callbackFunction = callback.function
        callbackOptions = callback.options

        if animation.hasField("callback") then animation.setRef("callback", {})

        if rodash.isInvalid(callbackFunction) then return

        if rodash.isFunction(callbackFunction) or rodash.isNonEmptyString(callbackFunction)
            exec(callbackFunction, callbackOptions)
        end if
    end sub


    function returnAnimationOptions(options = {})
        nodeId = options.nodeId
        if rodash.isEmptyString(nodeId) then return invalid

        nodeFields = options.fields ?? {}
        if not rodash.isNonEmptyAA(nodeFields) then return invalid
        options.delete("fields")

        node = top().findNode(nodeId)
        if not rodash.isNode(node) then return invalid

        fieldOptionsArray = []

        for each field in nodeFields.items()
            fieldName = field.key
            oldValue = node[fieldName]
            newValue = field.value
            if rodash.isNumber(oldValue)
                oldValue = m.toFloatValue(oldValue)
            end if

            if rodash.isNumber(newValue)
                newValue = m.toFloatValue(newValue)
            end if

            if fieldName = "color" or fieldName = "blendColor"
                newValueClean = newValue.toStr().replace("#", "")
                newValue = val(newValueClean, 16)
                oldColorValue% = node[fieldName]
                oldValue = oldColorValue%
            end if

            if type(oldValue) <> type(newValue) and rodash.isEqual(oldValue, newValue) then return invalid

            animationOptionsObj = {
                field: fieldName,
                keyValue: [oldValue, newValue]
            }

            fieldOptionsArray.push(animationOptionsObj)
        end for

        options.options = fieldOptionsArray

        return options
    end function


    function morph(options = {})
        morphObject = options.morphObject ?? {}
        sharedOptions = options.sharedOptions ?? {}
        if not rodash.isNonEmptyAA(morphObject) then return invalid
        if m.animations = invalid then m.animations = {}

        animationOptionsArray = []
        animationCallback = invalid
        animationCallbackOptions = {}

        if rodash.isNotInvalid(sharedOptions.callback)
            animationCallback = sharedOptions.callback
            sharedOptions.delete("callback")
        end if

        if rodash.isNotInvalid(sharedOptions.callbackOptions)
            animationCallbackOptions = sharedOptions.callbackOptions
            sharedOptions.delete("callbackOptions")
        end if

        for each item in morphObject.items()
            nodeId = item.key
            options = item.value
            options.nodeId = nodeId
            options.append(m.defaultOptions)

            animationOptions = m.returnAnimationOptions(options)
            if not rodash.isNonEmptyAA(animationOptions) then continue for

            if rodash.isNonEmptyAA(sharedOptions) then animationOptions.append(sharedOptions)

            animationOptionsArray.push(animationOptions)
        end for

        animationId = m.constructAnimationId(animationOptionsArray)

        m.addAnimation(animationId, animationOptionsArray)

        animation = m.animations[animationId] ?? invalid

        if not rodash.isNode(animation) then return invalid

        if rodash.isNotInvalid(animationCallback) then m.setAnimationCallback({
            animation: animation,
            callback: animationCallback,
            options: animationCallbackOptions
        })

        deferred = sharedOptions.deferred ?? false

        if not deferred then m.runAnimation({ id: animationId })

        return animation
    end function


    function constructAnimationId(options = []) as String
        if not rodash.isNonEmptyArray(options) then return ""

        animationId = getNodeIdentifier(top())

        for each nodeOptions in options
            nodeId = nodeOptions.nodeId ?? ""
            animationId += nodeId

            fields = nodeOptions.options ?? []
            for each fieldObject in fields
                animationId += fieldObject.field ?? ""
            end for
        end for

        return animationId
    end function


    sub setAnimationCallback(options = {})
        animation = options.animation
        callback = options.callback
        options = options.options

        if rodash.isInvalid(animation.callback) then animation.addField("callback", "assocarray", false)

        animation.setRef("callback", {
            function: callback,
            options: options
        })
    end sub


    function fadeIn(options = {})
        node = options.node
        if not rodash.isNode(node) then return invalid
        return m.fade(node, { opacity: 1 }, options.options ?? {})
    end function


    function fadeOut(options = {})
        node = options.node
        if not rodash.isNode(node) then return invalid
        return m.fade(node, { opacity: 0 }, options.options ?? {})
    end function


    function fade(node = invalid, options = {}, sharedOptions = {})
        if not rodash.isNode(node) then return invalid

        nodeId = node.id ?? ""
        if rodash.isEmptyString(nodeId) then return invalid

        morphObject = {}

        morphObject[nodeId] = {
            fields: options
        }

        return m.morph({ morphObject: morphObject, sharedOptions: sharedOptions })
    end function


    function toFloatValue(value)
        if not rodash.isNumber(value) then return value
        floatValue! = value
        return floatValue!
    end function
end class


function getFloatFieldInterpolator(node = {})
    return interfaceFunction("getFloatFieldInterpolator", { node: node })
end function


function runAnimation(id = "")
    return interfaceFunction("runAnimation", { id: id })
end function


function removeAnimation(id = "")
    return interfaceFunction("removeAnimation", { id: id })
end function


function morph(morphObject = {}, sharedOptions = {})
    return interfaceFunction("morph", {
        morphObject: morphObject,
        sharedOptions: sharedOptions
    })
end function


function fadeIn(node = invalid, options = {})
    return interfaceFunction("fadeIn", { node: node, options: options })
end function


function fadeOut(node = invalid, options = {})
    return interfaceFunction("fadeOut", { node: node, options: options })
end function
