class Animatable
    animations = {}
    publicFunctions = []
    defaultOptions = {
        "duration": 0.3,
        "easeFunction": "linear",
        "repeat": false,
        "optional": true,
        "options": []
    }

    sub new(options = {})
        m.setExportFunctions(role())
        if rodash.findIndex(["Scene", "View"], role()) = -1 then return
    end sub


    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(componentRole) then return

        if rodash.findIndex(["Scene", "View"], componentRole) = -1 then return

        m.publicFunctions.push("animate")
        m.publicFunctions.push("reverse")
        m.publicFunctions.push("morph")
        m.publicFunctions.push("fadeIn")
        m.publicFunctions.push("fadeOut")
    end sub


    sub runAnimation(id = "", isReverse = false)
        if rodash.isEmptyString(id) then return

        animation = m.animations[id] ?? invalid
        if not rodash.isNode(animation) then return

        m.setReverse(animation.getChildren(-1, 0), isReverse)

        safeObserve("state", m.onAnimationComplete, animation)
        animation.control = "start"

        if rodash.isAA(m.continuousAnimations) and not m.continuousAnimations.doesExist(id)
            m.activeAnimations({ action: "add", id: id, node: animation })
        end if
    end sub


    sub finishAnimation(id = "" as String, shouldFinish = true as Boolean)
        if rodash.isEmptyString(id) then return

        animation = m.animations[id] ?? invalid
        if not rodash.isNode(animation) then return

        safeUnobserve("state", animation)

        if shouldFinish
            animation.control = "finish"
        else
            animation.control = "stop"
        end if
    end sub


    sub reverse(id = "")
        m.runAnimation(id, true)
    end sub


    function createAnimation(settings = {})
        nodeId = settings.nodeId ?? ""
        animationOptions = settings.options ?? []
        settings.delete("options")

        animation = createObject("roSGNode", "Animation")
        animation.setFields(settings)

        for each option in animationOptions
            field = option.field ?? ""
            if rodash.isEmptyString(field) then continue for

            keyValue = option.keyValue ?? invalid
            if not rodash.isNonEmptyArray(keyValue) then continue for

            interp = m.getInterpName(field)
            if rodash.isEmptyString(interp) then continue for

            interpField = createObject("roSGNode", interp)
            interpField.fieldToInterp = [nodeId, field].join(".")
            interpField.id = [nodeId, field].join(".")
            interpField.key = option.key ?? [0, 1]
            interpField.keyValue = keyValue
            animation.appendChild(interpField)
        end for

        return animation
    end function


    sub addAnimation(id = "", animations = [])
        if rodash.isEmptyString(id) then return
        if not rodash.isArray(animations) then return

        if m.animations = invalid then m.animations = {}
        if m.animations[id] <> invalid then return

        animationCollection = []

        for each settings in animations
            animation = m.createAnimation(settings)
            if rodash.isNode(animation) then animationCollection.push(animation)
        end for

        if animationCollection.count() = 0 then return

        if animationCollection.count() > 1
            animationShell = createObject("roSGNode", "ParallelAnimation")
            duration = 0

            for each item in animationCollection
                if item.duration > duration then duration = item.duration
                animationShell.appendChild(item)
            end for

            animationShell.update({ duration: duration }, true)
        else
            animationShell = animationCollection[0]
        end if

        if not rodash.isNode(animationShell) then return

        animationShell.id = id

        top().appendChild(animationShell)
        m.animations[id] = animationShell
    end sub


    sub removeAnimation(id = "")
        if rodash.isEmptyString(id) then return

        animationShell = m.animations[id] ?? invalid
        if not rodash.isNode(animationShell) then return

        safeUnobserve("state", animationShell)
        top().removeChild(animationShell)
        m.animations.delete(id)
    end sub


    function getInterpName(field = "") as Object
        if rodash.isEmptyString(field) then return ""

        fieldsMap = {
            "blendColor": "ColorFieldInterpolator",
            "color": "ColorFieldInterpolator",
            "height": "FloatFieldInterpolator",
            "opacity": "FloatFieldInterpolator",
            "scale": "Vector2DFieldInterpolator",
            "size": "FloatFieldInterpolator",
            "translation": "Vector2DFieldInterpolator",
            "width": "FloatFieldInterpolator"
        }

        if fieldsMap.doesExist(field) then return fieldsMap[field]
        return ""
    end function


    sub setReverse(animationChildren, isReverse = false as Boolean)
        for each child in animationChildren
            if child.subType() = "Animation" or child.subType() = "ParallelAnimation"
                m.setReverse(child.getChildren(-1, 0), isReverse)
            else if rodash.indexOf(["Vector2DFieldInterpolator", "FloatFieldInterpolator", "ColorFieldInterpolator"], child.subType()) <> -1
                child.reverse = isReverse
            end if
        end for
    end sub


    sub onAnimationComplete(options = {})
        state = options.data ?? ""
        animation = options.node

        if state <> "stopped" then return
        if not rodash.isNode(animation) then return

        safeUnobserve("state", animation)

        if rodash.isAA(m.continuousAnimations) and not m.continuousAnimations.doesExist(animation.id)
            m.activeAnimations({ action: "delete", id: animation.id })
        end if

        callback = animation.getRef("callback")
        callbackFunction = callback.function
        callbackOptions = callback.options

        if rodash.isInvalid(callbackFunction) then return

        if rodash.isFunction(callbackFunction)
            callbackFunction(callbackOptions)
        else if rodash.isNonEmptyString(callbackFunction)
            exec(callbackFunction, callbackOptions)
        end if
    end sub


    function returnAnimationOptions(options = {})
        nodeId = options.nodeId
        if rodash.isEmptyString(nodeId) then return invalid

        nodeFields = options.fields ?? {}
        if not rodash.isNonEmptyAA(nodeFields) then return invalid
        options.delete("fields")

        node = top().findNode(nodeId)
        if not rodash.isNode(node) then return invalid

        fieldOptionsArray = []

        for each field in nodeFields.items()
            fieldName = field.key
            oldValue = node[fieldName]
            newValue = field.value
            if rodash.isNumber(oldValue)
                oldValue = m.toFloatValue(oldValue)
            end if

            if rodash.isNumber(newValue)
                newValue = m.toFloatValue(newValue)
            end if

            if fieldName = "color" or fieldName = "blendColor"
                newValueClean = newValue.toStr().replace("#", "")
                newValue = val(newValueClean, 16)
                oldColorValue% = node[fieldName]
                oldValue = oldColorValue%
            end if

            if type(oldValue) <> type(newValue) and rodash.isEqual(oldValue, newValue) then return invalid

            animationOptionsObj = {
                field: fieldName,
                keyValue: [oldValue, newValue]
            }

            fieldOptionsArray.push(animationOptionsObj)
        end for

        options.options = fieldOptionsArray

        return options
    end function


    function morph(morphObject = {}, sharedOptions = {})
        if not rodash.isNonEmptyAA(morphObject) then return invalid
        if m.animations = invalid then m.animations = {}

        animationOptionsArray = []
        animationCallback = invalid
        animationCallbackOptions = {}

        if rodash.isNotInvalid(sharedOptions.callback)
            animationCallback = sharedOptions.callback
            sharedOptions.delete("callback")
        end if

        if rodash.isNotInvalid(sharedOptions.callbackOptions)
            animationCallbackOptions = sharedOptions.callbackOptions
            sharedOptions.delete("callbackOptions")
        end if

        for each item in morphObject.items()
            nodeId = item.key
            options = item.value
            options.nodeId = nodeId
            options.append(m.defaultOptions)

            animationOptions = m.returnAnimationOptions(options)
            if not rodash.isNonEmptyAA(animationOptions) then continue for

            if rodash.isNonEmptyAA(sharedOptions) then animationOptions.append(sharedOptions)

            animationOptionsArray.push(animationOptions)
        end for

        animationId = m.constructAnimationId(animationOptionsArray)
        animation = m.animations[animationId] ?? invalid

        if not rodash.isNode(animation)
            m.addAnimation(animationId, animationOptionsArray)
        end if

        animation = m.animations[animationId] ?? invalid
        if not rodash.isNode(animation) then return invalid

        if rodash.isNotInvalid(animationCallback)
            if rodash.isInvalid(animation.callback) then animation.addField("callback", "assocarray", false)
            if rodash.isInvalid(animation.callbackOptions) then animation.addField("callbackOptions", "assocarray", false)

            animation.setRef("callback", {
                function: animationCallback,
                options: animationCallbackOptions
            })

        end if

        m.runAnimation(animationId)

        return animationId
    end function


    function constructAnimationId(options = []) as String
        if not rodash.isNonEmptyArray(options) then return ""

        animationId = ""

        for each nodeOptions in options
            nodeId = nodeOptions.nodeId ?? ""
            animationId += nodeId

            fields = nodeOptions.options ?? []
            for each fieldObject in fields
                animationId += fieldObject.field ?? ""
            end for
        end for

        return animationId
    end function


    sub fadeIn(node = invalid, options = {})
        if not rodash.isNode(node) then return

        options.opacity = 1
        m.fade(node, options)
    end sub


    sub fadeOut(node = invalid, options = {})
        if not rodash.isNode(node) then return

        options.opacity = 0
        m.fade(node, options)
    end sub


    sub fade(node = invalid, options = {})
        if not rodash.isNode(node) then return
        ?"fade " options

        nodeId = node.id ?? ""
        if rodash.isEmptyString(nodeId) then return

        morphObject = {
            callbackFunc: options.callbackFunc ?? "",
            callbackOpts: options.callbackOpts ?? {}
        }
        morphObject[nodeId] = {
            delay: options.delay ?? 0,
            duration: options.duration ?? 0.3,
            opacity: options.opacity,
            callbackFunc: options.callbackFunc ?? ""
        }

        state = options.opacity = 0 ? "out" : "in"
        payloadObject = {}
        payloadObject[state] = morphObject

        m.morph(state, payloadObject)
    end sub


    function activeAnimations(options = {}) as Object
        if not rodash.isAA(options) then return invalid

        scene = app()
        if not rodash.isNode(scene) then return invalid
        if not scene.hasFunc("manageActiveAnimations") then return invalid

        payload = options
        payload.nodeId = m.getNodeId()
        return scene.callFunc("manageActiveAnimations", payload)
    end function


    function getNodeId() as String
        return `${top().subType()}_${top().id ?? ""}`
    end function


    function toFloatValue(value)
        if not rodash.isNumber(value) then return value
        floatValue! = value
        return floatValue!
    end function
end class
