class Configable
    appConfigs = "{{%- o(CONFIG) %}}"
    configPaths = {}

    sub new(_options = {})
        if getGlobalAA().ord_role = "Task" or getGlobalAA().ord_role = "Model" then return

        m.setExportFunctions(getGlobalAA().ord_role)

        if devMode() and not global().hasField("ord_configs")
            m.setupGlobalConfigs()
        end if
    end sub


    sub reset(_options = {})
        m.configPaths = {}
        if devMode() then global().removeField("ord_configs")
    end sub


    sub setupGlobalConfigs()
        global().addField("ord_configs", "node", true)
        global().ord_configs = createObject("roSGNode", "Node")
    end sub


    sub setExportFunctions(componentRole)
        if rodash.isEmptyString(componentRole) then return
        m.publicFunctions = []
        m.publicFunctions.push("liveConfig")
        m.publicFunctions.push("configUpdated")
    end sub


    sub liveConfig(options = {})
        field = options.field
        keyPath = options.keyPath
        node = options.node

        if rodash.isEmptyString(field) then return
        if rodash.isEmptyString(keyPath) then return
        if not rodash.isNode(node) then return

        config = rodash.get(m.appConfigs, keyPath)
        if rodash.isEmpty(config) then return

        updateObject = {}
        updateObject[field] = config
        node.update(updateObject, true)

        if not devMode() then return

        if not rodash.isNonEmptyAA(m.configPaths[keyPath])
            configsNode = global().ord_configs
            m.configPaths[keyPath] = {
                field: field,
                node: node
            }
            if configsNode[keyPath] = invalid
                nodeUpdateObj = {}
                nodeUpdateObj[keyPath] = config
                configsNode.update(nodeUpdateObj, true)
            end if

            safeObserve(keyPath, "configUpdated", configsNode)
        end if
    end sub


    sub configUpdated(options = {})
        field = options.field
        configObject = m.configPaths[field]
        if not rodash.isNonEmptyAA(configObject) then return

        configData = options.data ?? {}
        node = configObject.node
        nodeField = configObject.field ?? ""

        if not rodash.isNode(node) then return
        if rodash.isEmptyString(nodeField) then return

        node[nodeField] = configData
    end sub
end class


function liveConfig(options = {}, node = top())
    options.append({ node: node })
    return interfaceFunction("liveConfig", options)
end function
