class Configable
    publicFunctions = []
    appConfigs = "<%- o(CONFIG) %>"
    configPaths = {}

    sub new(_options = {})
        if getGlobalAA().ord_role = "Task" or getGlobalAA().ord_role = "Model" then return

        m.setExportFunctions(getGlobalAA().ord_role)

        if not global().hasField("ord_configs")
            m.setupGlobalConfigs()
        end if
    end sub


    sub setupGlobalConfigs()
        global().addField("ord_configs", "node", true)
        global().ord_configs = createObject("roSGNode", "Node")
    end sub


    sub setExportFunctions(componentRole)
        if rodash.isEmptyString(componentRole) then return
        m.publicFunctions.push("liveConfig")
        m.publicFunctions.push("configUpdated")
    end sub


    function liveConfig(options = {}, node = top())
        field = options.field
        keyPath = options.keyPath

        if rodash.isEmptyString(field) then return invalid
        if rodash.isEmptyString(keyPath) then return invalid
        if not rodash.isNode(node) then return invalid

        config = rodash.get(m.appConfigs, keyPath)
        if rodash.isEmpty(config) then return invalid

        updateObject = {}
        updateObject[field] = config
        node.update(updateObject, true)

        if not rodash.isNonEmptyAA(m.configPaths[keyPath])
            configsNode = global().ord_configs
            m.configPaths[keyPath] = {
                field: field,
                node: node
            }
            if configsNode[keyPath] = invalid
                nodeUpdateObj = {}
                nodeUpdateObj[keyPath] = config
                configsNode.update(nodeUpdateObj, true)
            end if
            safeObserve(keyPath, "configUpdated", configsNode)
        end if

        return config
    end function


    sub configUpdated(options = {})
        field = options.field
        configObject = m.configPaths[field]
        if not rodash.isNonEmptyAA(configObject) then return

        configData = options.data ?? {}
        node = configObject.node
        nodeField = configObject.field ?? ""

        if not rodash.isNode(node) then return
        if rodash.isEmptyString(nodeField) then return

        node[nodeField] = configData
    end sub
end class
