class Eventable
    subscriptions = {}
    publicFunctions = []

    sub new(options = {})
        if role() <> "Task" and global()._ord_eventQueue = invalid
            m.setupEventQueue()
        end if

        m.eventQueue = global()._ord_eventQueue

        'bs:disable-next-line
        m.renderQueue = createObject("roRenderThreadQueue")

        top().addField("_ord_subscriptions", "assocarray", false)

        m.setExportFunctions(role())
    end sub


    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(role) then return

        if rodash.findIndex(["Scene", "View", "Model", "Controller", "Task"], componentRole) <> -1
            m.publicFunctions.push("dispatch")
        end if

        if rodash.findIndex(["Scene", "Controller"], componentRole) <> -1
            m.publicFunctions.push("subscribe")
        end if

        if rodash.findIndex(["Task"], componentRole) <> -1
            m.publicFunctions.push("publish")
        end if
    end sub


    sub setupEventQueue()
        if rodash.isNode(global()._ord_eventQueue)
            m.eventQueue = global()._ord_eventQueue
        else
            eventQueue = createObject("roSGNode", "_ord_eventQueue")

            global().addField("_ord_eventQueue", "node", false)
            global()._ord_eventQueue = eventQueue
            m.eventQueue = eventQueue
        end if

        safeObserve("ready", m.onTaskReady, m.eventQueue)
        m.eventQueue.control = "RUN"
    end sub


    sub storeFunctions(options = {})
        subscriptions = top().getRef("_ord_subscriptions") ?? {}

        name = options.name
        functions = options.functions
        functionArray = []

        if rodash.isArray(functions)
            functionArray.append(functions)
        else
            functionArray.push(functions)
        end if

        subscriptions[name] = functionArray
        top().setRef("_ord_subscriptions", subscriptions)
    end sub

    sub onTaskReady(options = {})
        ?"onTaskReady " options.data
        dispatch(events.EVENT_TASK_READY)
    end sub

    sub subscribe(options = {})
        if rodash.isEmpty(options) then return

        for each event in options.items()
            eventName = event.key
            eventFunctions = event.value

            m.storeFunctions({ name: eventName, functions: eventFunctions })

            if m.renderQueue = invalid then return

            observeFunction = m.callEventFunctions
            observeFunctionName = rodash.getFunctionName(observeFunction)
            m.renderQueue.addMessageHandler(eventName, observeFunctionName)
        end for
    end sub


    sub callEventFunctions(data = {}, messageInfo = {})
        if rodash.isEmpty(messageInfo) then return

        subscriptions = top().getRef("_ord_subscriptions") ?? {}

        if rodash.isEmpty(subscriptions) then return

        eventId = messageInfo.message_id ?? ""
        eventFunctions = subscriptions[eventId]

        for each functionName in eventFunctions
            exec(functionName, data)
        end for
    end sub


    sub publish(options = {})
        if m.renderQueue = invalid then return
        m.renderQueue.postMessage(options.id, options.options)
    end sub


    sub dispatch(options = {})
        if not rodash.isNonEmptyAA(options) then return
        if m.eventQueue = invalid then return
        m.eventQueue.eventData = options
    end sub
end class
