class Eventable
    registrationsArray = []
    sub new(_options = {})
        m.renderQueue = createObject("roRenderThreadQueue")
        m.setExportFunctions(getGlobalAA().ord_role)

        if getGlobalAA().ord_role = "Task" or getGlobalAA().ord_role = "Model" then return

        if global().ord_eventQueue = invalid
            m.setupEventQueue()
        end if

        m.eventQueue = global().ord_eventQueue
        top().addField("ord_subscriptions", "assocarray", false)
    end sub


    sub reset(_options = {})
        m.unsubscribe()
        top().removeField("ord_subscriptions")
        safeUnobserve("ready", m.eventQueue)
        m.eventQueue = invalid
        if rodash.isNode(global().ord_eventQueue)
            global().ord_eventQueue.control = "STOP"
            global().removeField("ord_eventQueue")
        end if
    end sub


    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(componentRole) then return

        m.publicFunctions = []

        if rodash.findIndex(["Scene", "View", "Model", "Controller", "Task"], componentRole) <> -1
            m.publicFunctions.push("dispatch")
        end if

        if rodash.findIndex(["Scene", "Controller"], componentRole) <> -1
            m.publicFunctions.push("subscribe")
            m.publicFunctions.push("unsubscribe")
        end if

        if rodash.findIndex(["Task"], componentRole) <> -1
            m.publicFunctions.push("publish")
        end if
    end sub


    sub setupEventQueue()
        if rodash.isNode(global().ord_eventQueue)
            m.eventQueue = global().ord_eventQueue
        else
            eventQueue = createObject("roSGNode", "ord_eventQueue")
            global().addField("ord_eventQueue", "node", false)
            global().ord_eventQueue = eventQueue
            m.eventQueue = eventQueue
        end if

        safeObserve("ready", m.onTaskReady, m.eventQueue)
        m.eventQueue.control = "RUN"
    end sub


    sub storeFunctions(options = {})
        subscriptions = top().getRef("ord_subscriptions") ?? {}

        name = options.name
        functions = options.functions
        functionArray = []

        if rodash.isArray(functions)
            functionArray.append(functions)
        else
            functionArray.push(functions)
        end if

        subscriptions[name] = functionArray
        top().setRef("ord_subscriptions", subscriptions)
    end sub


    sub onTaskReady(_options = {})
        dispatch(events.EVENT_TASK_READY)
    end sub


    sub subscribe(options = {})
        for each event in options.items()
            eventName = event.key
            eventFunctions = event.value

            m.storeFunctions({ name: eventName, functions: eventFunctions })

            if m.renderQueue = invalid then return

            observeFunction = m.callEventFunctions
            observeFunctionName = rodash.getFunctionName(observeFunction)
            registration = m.renderQueue.addMessageHandler(eventName, observeFunctionName)
            m.registrationsArray.push(registration)
        end for

        if getGlobalAA().ord_role = "Controller"
            m.renderQueue.addMessageHandler(events.UNSUBSCRIBE_EVENTS, "ord_reset")
        end if
    end sub


    sub callEventFunctions(data = {}, messageInfo = {})
        if rodash.isEmpty(messageInfo) then return

        subscriptions = top().getRef("ord_subscriptions") ?? {}

        if rodash.isEmpty(subscriptions) then return

        eventId = messageInfo.message_id ?? ""
        eventFunctions = subscriptions[eventId]

        for each functionName in eventFunctions
            exec(functionName, data)
        end for
    end sub


    sub publish(options = {})
        if m.renderQueue = invalid then return
        'bs:disable-next-line
        if devMode() then ?"-=# EVENT: " options.id, rodash.now()
        m.renderQueue.postMessage(options.id, options.options)
    end sub


    sub dispatch(options = {})
        if m.eventQueue = invalid then return
        m.eventQueue.eventData = options
    end sub


    sub unsubscribe(_options = {})
        for each registration in m.registrationsArray
            registration.unregister()
        end for
        m.registrationsArray = []
    end sub
end class


function publish(name = "", options = {})
    return interfaceFunction("publish", { id: name, options: options })
end function


function subscribe(options)
    return interfaceFunction("subscribe", options)
end function


function dispatch(eventId, options = {})
    return interfaceFunction("dispatch", { id: eventId, options: options })
end function
