class Focusable
    publicFunctions = []
    focusMap = {}

    sub new(options = {})
        m.setExportFunctions(role())
    end sub


    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(role) then return

        if rodash.findIndex(["Scene", "View"], componentRole) = -1 then return

        m.publicFunctions.push("applyDefaultFocus")
        m.publicFunctions.push("setFocus")
        m.publicFunctions.push("processFocus")
        m.publicFunctions.push("setFocusMap")
    end sub


    sub applyDefaultFocus()
        defaultNode = m.focusMap.current ?? m.focusMap.default ?? ""
        if rodash.isFunction(defaultNode)
            exec(defaultNode)
            return
        end if

        if not rodash.isNode(defaultNode) and rodash.isString(defaultNode) then top().findNode(defaultNode)

        if not rodash.isNode(defaultNode) then defaultNode = top().getChild(0)

        if not rodash.isNode(defaultNode) then defaultNode = top()

        m.setFocus(defaultNode)
    end sub


    function getFocusedChild(node = {})
        if not rodash.isNode(node) then node = top()

        focusedNode = node.focusedChild
        if rodash.isNode(focusedNode.focusedChild) and not focusedNode.focusedChild.isSameNode(focusedNode)
            return m.getFocusedChild(focusedNode.focusedChild)
        else
            return rodash.isNode(focusedNode) ? focusedNode : node
        end if
    end function


    function processFocus(key as string)
        handled = false

        focusedChild = m.focusMap.current ?? m.focusMap.default ?? top()
        nodeMap = m.focusMap[focusedChild.id] ?? {}
        focusValue = nodeMap[key]

        if focusValue = invalid then return handled

        if rodash.isFunction(focusValue)
            exec(focusValue)
            handled = true
        else if rodash.isNode(focusValue)
            handled = true
        else if rodash.isNonEmptyString(focusValue)
            focusValue = top().findNode(focusValue)
            handled = true
        end if

        m.setFocus(focusValue)

        return handled
    end function


    sub setFocus(node = {})
        if not rodash.isNode(node) then return

        ' currentFocusedNode = m.focusMap.current
        ' if rodash.isNode(currentFocusedNode) and not node.isSameNode(currentFocusedNode)
        '     m.focusMap.current = node
        '     ?"setFocus " node
        '     node.setFocus(true)
        ' end if
        m.focusMap.current = node
        ?"setFocus " node
        node.setFocus(true)
    end sub


    sub setFocusMap(options = {})
        m.focusMap.append(options)
    end sub
end class
