class Focusable
    focusReady = false
    focusMap = {}
    focusNode = invalid
    focusFunction = invalid
    publicFunctions = []

    sub new(options = {})
        m.setExportFunctions(getGlobalAA().ord_role)
    end sub

    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(componentRole) then return

        if rodash.findIndex(["Scene", "View"], componentRole) = -1 then return

        m.publicFunctions.push("applyDefaultFocus")
        m.publicFunctions.push("setFocus")
        m.publicFunctions.push("processFocus")
        m.publicFunctions.push("readyToFocus")
        m.publicFunctions.push("setFocusMap")
        m.publicFunctions.push("waitToFocus")
    end sub


    sub applyDefaultFocus()
        defaultNode = m.focusMap.current ?? m.focusMap.default ?? ""
        if rodash.isFunction(defaultNode)
            exec(defaultNode)
            return
        end if

        if not rodash.isNode(defaultNode) and rodash.isString(defaultNode) then top().findNode(defaultNode)

        if not rodash.isNode(defaultNode) then defaultNode = top().getChild(0)

        if not rodash.isNode(defaultNode) then defaultNode = top()

        m.setFocus(defaultNode)
    end sub


    function getFocusedChild(node = {})
        if not rodash.isNode(node) then node = top()

        focusedNode = node.focusedChild
        if rodash.isNode(focusedNode.focusedChild) and not focusedNode.focusedChild.isSameNode(focusedNode)
            return m.getFocusedChild(focusedNode.focusedChild)
        else
            return rodash.isNode(focusedNode) ? focusedNode : node
        end if
    end function


    function processFocusFunction(focusFunction = {})
        if not rodash.isFunction(focusFunction) then return false

        functionHandled = exec(focusFunction)
        ' Supporting subs
        if functionHandled = invalid then return true
        if rodash.isBoolean(functionHandled) then return functionHandled
        return true
    end function


    function processFocus(key as string)
        handled = false

        focusTarget = m.focusMap.current ?? m.focusMap.default ?? top()
        if rodash.isFunction(focusTarget)
            handled = m.processFocusFunction(focusTarget)
            return handled
        end if

        nodeMap = m.focusMap[focusTarget.id] ?? {}
        focusArray = nodeMap[key]

        if rodash.isInvalid(focusArray) then return handled
        if not rodash.isArray(focusArray) then focusArray = [focusArray]

        for each target in focusArray
            if rodash.isFunction(target)
                functionHandled = m.processFocusFunction(target)
                if not handled then handled = functionHandled
                continue for
            end if

            if rodash.isInvalid(target) then continue for

            if not rodash.isNode(target) and rodash.isNonEmptyString(target)
                target = top().findNode(target)
            end if

            if not rodash.isNode(target) then continue for

            m.setFocus(target)
            if not handled then handled = true
        end for

        return handled
    end function


    sub setFocus(node = {})
        if not rodash.isNode(node) then return
        m.focusMap.current = node
        node.setFocus(true)
    end sub


    sub setFocusMap(options = {})
        if not rodash.isNonEmptyAA(options) then return
        m.focusMap.append(options)
    end sub


    sub waitToFocus(focusTarget)
        if rodash.isNode(focusTarget)
            if m.focusReady
                m.setFocus(focusTarget)
                return
            end if

            m.focusFunction = invalid
            m.focusNode = focusTarget
        else if rodash.isFunction(focusTarget)
            if m.focusReady
                exec(focusTarget)
                return
            end if

            m.focusFunction = focusTarget
            m.focusNode = invalid
        end if
    end sub


    sub readyToFocus()
        if m.focusReady then return
        m.focusReady = true

        focusFunction = m.focusFunction
        focusNode = m.focusNode

        if rodash.isNode(focusNode)
            m.setFocus(focusNode)
        else if rodash.isFunction(focusFunction)
            exec(focusFunction)
        end if
    end sub
end class
