class Loadable
    sub new(_options = {})
        m.setExportFunctions(getGlobalAA().ord_role)
    end sub


    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(componentRole) then return

        if rodash.findIndex(["Scene", "View"], componentRole) = -1 then return

        m.publicFunctions = []
        m.publicFunctions.push("onParentFadedIn")
        m.publicFunctions.push("setLoadable")
        m.publicFunctions.push("onWidthHeightChange")
    end sub


    sub onFieldUpdated(options = {})
        if not rodash.isNonEmptyAA(options) then return

        updatedField = options.field ?? ""
        if rodash.isEmpty(updatedField) then return

        node = options.node
        if not rodash.isNode(node) then return

        safeUnobserve(updatedField, node)
        safeUnobserve("width", node)
        ' Unobserving in case the node renders after update
        safeUnobserve("renderTracking", node)

        poster = node.findNode("loadingPoster")
        if rodash.isNode(poster) then poster.loading = false

        fadeIn(node, { callback: "onParentFadedIn", callbackOptions: { node: node }, duration: 0.5 })
    end sub


    sub onNodeRenderTracking(options = {})
        if not rodash.isNonEmptyAA(options) then return

        renderTracking = options.data ?? "none"
        node = options.node
        if not rodash.isNode(node) then return
        if renderTracking = "none" then return

        node.enableRenderTracking = false
        safeUnobserve("renderTracking", node)

        infoFields = options.info
        if not rodash.isNonEmptyAA(infoFields) then return

        updateField = infoFields.keys()?[0] ?? ""
        if rodash.isEmptyString(updateField) then return

        poster = node.findNode("loadingPoster")

        if not rodash.isNode(poster)
            poster = createObject("roSGNode", "LoadingPoster")
            poster.id = "loadingPoster"
            node.appendChild(poster)
            safeObserve("width", "onWidthHeightChange", node)
        end if

        poster.width = node.width
        poster.height = node.height
        poster.loading = true
    end sub


    sub onParentFadedIn(options = {})
        node = options.node
        if not rodash.isNode(node) then return
        poster = node.findNode("loadingPoster")
        if not rodash.isNode(poster) then return
        node.removeChild(poster)
    end sub


    sub onWidthHeightChange(options = {})
        if not rodash.isNonEmptyAA(options) then return

        node = options.node
        if not rodash.isNode(node) then return

        poster = node.findNode("loadingPoster")
        if not rodash.isNode(poster) then return

        poster.width = node.width
        poster.height = node.height
    end sub


    sub setLoadable(options = {})
        if not rodash.isNonEmptyAA(options) then return
        node = options.node
        updateField = options.updateField ?? ""
        if not rodash.isNode(node) then return
        if rodash.isEmptyString(updateField) then return
        if not rodash.isEmpty(node[updateField]) then return

        node.opacity = 0.001
        node.enableRenderTracking = true
        safeObserve("renderTracking", m.onNodeRenderTracking, node, [updateField])
        safeObserve(updateField, m.onFieldUpdated, node)
    end sub
end class


function setLoadable(options = {})
    return interfaceFunction("setLoadable", options)
end function
