class Safeable
    publicFunctions = []

    sub new(options = {})
        top().addField("_ord_proxyData", "assocarray", true)
        top().addField("_ord_callbacks", "assocarray", false)
        top().setRef("_ord_proxyData", {})

        m.setExportFunctions(role())
    end sub


    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(componentRole) then return

        m.publicFunctions.push("exec")
        m.publicFunctions.push("safeObserve")

        if rodash.findIndex(["Scene", "View", "Model"], componentRole) = -1 then return

        m.publicFunctions.push("safeFunc")

        if top().hasFunc("safeFunc") then return

        ?`

        WARNING: Please add
        <function name="safeFunc" />
        to ${top().subType()}.xml file

        `
    end sub


    function exec(options = {})
        if not rodash.isNonEmptyAA(options) then return invalid

        if devMode()
            return m.runFunc(options)
        else
            try
                return m.runFunc(options)
            catch e
                ?"Error: " e
            end try
        end if
    end function


    function runFunc(options = {})
        func = options.func
        functionArgument = options.options ?? {}
        node = options.node ?? top()
        externalInterface = options.externalInterface ?? {}

        if rodash.isFunction(func)
            try
                return func(functionArgument)
            catch e
                return func()
            end try
        end if

        if not node.isSameNode(top())
            return m.proxyFunc(func, functionArgument, node)
        end if

        if not rodash.isEmpty(externalInterface) and rodash.isFunction(externalInterface[func])
            return externalInterface[func](functionArgument)
        end if

        nodeSafeFunctions = top().getRef("_ord_safeFunctions")

        if not rodash.isFunction(nodeSafeFunctions[func]) then return invalid

        nodeFunction = nodeSafeFunctions[func]

        if rodash.isFunction(nodeFunction)
            try
                return nodeFunction(functionArgument)
            catch e
                return nodeFunction()
            end try
        end if

        return invalid
    end function


    function proxyFunc(functionName = "", options = {}, node = {})
        if not rodash.isNode(node) then return invalid

        proxyData = node.getRef("_ord_proxyData") ?? {}

        if not rodash.isEmpty(options)
            proxyData.input = options
        end if

        node.callFunc("safeFunc", functionName)

        return proxyData.output ?? invalid
    end function


    sub processSafeFunc(functionName)
        proxyData = top().getRef("_ord_proxyData") ?? {}
        options = proxyData.input
        returnData = exec(functionName, options, top(), getGlobalAA().interfaceFunctions[functionName])
        proxyData.input = invalid
        proxyData.output = rodash.isEmpty(returnData) ? invalid : returnData
    end sub


    sub safeObserve(fieldName = "", callbackFunc = "", node = getGlobalAA().top, infoFields = [])
        if rodash.isEmptyString(fieldName) then return

        if role() = "Task" and rodash.isMessagePort(callbackFunc)
            node.observeFieldScopedEx(fieldName, callbackFunc, infoFields)
            return
        end if

        if rodash.isEmptyString(callbackFunc) then return

        m.storeCallback({ field: fieldName, callback: callbackFunc })

        node.unObserveFieldScoped(fieldName)
        node.observeFieldScoped(fieldName, rodash.getFunctionName(m.safeCallback), infoFields)
    end sub


    sub safeCallback(event)
        fieldName = event.getField() ?? ""
        callbacks = top().getRef("_ord_callbacks") ?? {}
        functionName = callbacks[fieldName] ?? ""

        if rodash.isEmptyString(functionName) then return

        payload = {
            data: event.getData()
            info: event.getInfo()
            node: event.getRoSGNode()
            nodeId: event.getNode()
        }

        exec(functionName, payload)
    end sub


    function safeFunc(functionName = "")
        if devMode()
            return m.processSafeFunc(functionName)
        else
            try
                return m.processSafeFunc(functionName)
            catch e
                ?"Error: " e
            end try
        end if
    end function


    sub storeCallback(options = {})
        callbacks = top().getRef("_ord_callbacks") ?? {}

        field = options.field
        callback = options.callback

        callbacks[field] = callback
        top().setRef("_ord_callbacks", callbacks)
    end sub
end class
