class Safeable
    publicFunctions = []

    sub new(_options = {})
        top().addField("ord_proxyData", "assocarray", true)
        m.setExportFunctions(getGlobalAA().ord_role)
    end sub


    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(componentRole) then return

        m.publicFunctions.push("exec")
        m.publicFunctions.push("safeObserve")
        m.publicFunctions.push("safeUnobserve")
        m.publicFunctions.push("safeFunctions")

        if rodash.findIndex(["Task"], componentRole) <> -1
            m.publicFunctions.push("setTaskFunction")
        end if

        if rodash.findIndex(["Scene", "View", "Model"], componentRole) = -1 then return

        m.publicFunctions.push("safeFunc")

        if not devMode() then return
        if top().hasFunc("safeFunc") then return

        'bs:disable-next-line
        ?`

        WARNING: Please add
        <function name="safeFunc" />
        to ${top().subType()}.xml file

        `
    end sub


    function exec(options = {})
        if not rodash.isNonEmptyAA(options) then return invalid

        if devMode()
            return m.runFunc(options)
        else
            try
                return m.runFunc(options)
            catch e
                return onError(e)
            end try
        end if
    end function


    function runFunc(options = {})
        func = options.func
        functionArgument = options.options ?? {}
        node = options.node ?? top()

        if not top().isSameNode(node)
            return m.proxyFunc(func, functionArgument, node)
        end if

        targetFunction = invalid

        if rodash.isFunction(func)
            targetFunction = func
        end if

        if rodash.isString(func)
            nodeSafeFunctions = getGlobalAA().ord_safeFunctions ?? {}
            nodeFunction = nodeSafeFunctions[func]
            targetFunction = nodeFunction
        end if

        if rodash.isFunction(targetFunction)
            return targetFunction(functionArgument)
        end if

        internalFunctions = getGlobalAA().ord_interfaces ?? {}
        internalInterface = internalFunctions[func] ?? {}

        if rodash.isNonEmptyAA(internalInterface) then return internalInterface[func](functionArgument)

        return invalid
    end function


    function proxyFunc(functionName = "", options = {}, node = {})
        if not rodash.isNode(node) then return invalid

        if rodash.isNonEmptyAA(options)
            proxyData = {}

            if not rodash.isEmpty(options)
                proxyData.input = options
            end if

            node.moveIntoField("ord_proxyData", proxyData)
        end if

        node.callFunc("safeFunc", functionName)

        proxyData = node.moveFromField("ord_proxyData") ?? {}
        returnObj = proxyData.output ?? invalid

        return returnObj
    end function


    sub processSafeFunc(functionName)
        proxyData = top().ord_proxyData ?? {}
        options = proxyData.input ?? {}
        top().ord_proxyData = invalid
        returnData = m.exec({ func: functionName, options: options, node: top() })

        if returnData <> invalid
            proxyData.input = invalid
            proxyData.output = returnData
            top().ord_proxyData = proxyData
        end if
    end sub


    sub safeObserve(options = {})
        fieldName = options.fieldName ?? ""
        callbackFunc = options.callbackFunc ?? ""
        node = options.node ?? getGlobalAA().top
        infoFields = options.infoFields ?? []

        if rodash.isEmptyString(fieldName) then return
        if not rodash.isNode(node) then return

        if getGlobalAA().ord_role = "Task" and rodash.isMessagePort(callbackFunc)
            node.observeFieldScopedEx(fieldName, callbackFunc, infoFields)
            return
        end if

        if rodash.isEmptyString(callbackFunc) then return

        nodeIdentifier = getNodeIdentifier(node)
        uniqueFieldName = `${fieldName}${nodeIdentifier}`

        m.storeCallback({
            field: uniqueFieldName,
            callback: callbackFunc
        })

        node.unObserveFieldScoped(fieldName)
        node.observeFieldScoped(fieldName, rodash.getFunctionName(m.safeCallback), infoFields)
    end sub


    sub safeUnobserve(options = {})
        fieldName = options.fieldName ?? ""
        node = options.node ?? getGlobalAA().top

        if rodash.isEmptyString(fieldName) then return
        nodeIdentifier = getNodeIdentifier(node)
        uniqueFieldName = `${fieldName}${nodeIdentifier}`
        node.unObserveFieldScoped(fieldName)
        m.removeCallback({ field: uniqueFieldName })
    end sub


    ' This function runs on node's m context
    sub safeCallback(event)
        fieldName = event.getField() ?? ""

        if rodash.isEmptyString(fieldName) then return

        callbacks = getGlobalAA().ord_callbacks
        node = event.getRoSGNode()
        nodeIdentifier = getNodeIdentifier(node)
        uniqueFieldName = `${fieldName}${nodeIdentifier}`
        functionArrayName = callbacks[uniqueFieldName] ?? []

        for each functionName in functionArrayName
            if not rodash.isFunction(functionName) and rodash.isEmptyString(functionName) then continue for
            payload = {
                data: event.getData(),
                field: event.getField(),
                info: event.getInfo(),
                node: event.getRoSGNode(),
                nodeId: event.getNode()
            }

            exec(functionName, payload)
        end for
    end sub


    function safeFunc(options = {})
        functionName = options.functionName ?? ""

        if devMode()
            return m.processSafeFunc(functionName)
        else
            try
                return m.processSafeFunc(functionName)
            catch e
                return onError(e)
            end try
        end if
    end function


    sub safeFunctions(options = {})
        if not rodash.isAA(options) then return
        allFunctions = getGlobalAA().ord_safeFunctions ?? {}
        allFunctions.append(options)
        getGlobalAA().ord_safeFunctions = allFunctions
    end sub


    sub removeCallback(options = {})
        callbacks = getGlobalAA().ord_callbacks

        field = options.field
        callbacks.delete(field)
    end sub


    sub storeCallback(options = {})
        callbacks = getGlobalAA().ord_callbacks ?? {}

        field = options.field
        callback = options.callback
        if not rodash.isFunction(callback) and rodash.isEmptyString(callback) then return
        existingCallbacks = callbacks[field] ?? []
        existingCallbacks.push(callback)

        callbacks[field] = existingCallbacks

        getGlobalAA().ord_callbacks = callbacks
    end sub


    sub setTaskFunction(options = {})
        if not rodash.isNonEmptyAA(options) then return
        taskFunction = options.function
        if not rodash.isFunction(taskFunction) then return
        getGlobalAA().ord_taskFunction = taskFunction
    end sub
end class


function exec(func, options = {}, node = top())
    if m.ord_initiated = invalid then ord_init()
    return interfaceFunction("exec", { func: func, options: options, node: node })
end function


function safeFunctions(options = {})
    return interfaceFunction("safeFunctions", options)
end function


function safeFunc(functionName = "")
    return interfaceFunction("safeFunc", { functionName: functionName })
end function


function safeObserve(fieldName = "", callbackFunc = "", node = top(), infoFields = [])
    return interfaceFunction("safeObserve", {
        fieldName: fieldName,
        callbackFunc: callbackFunc,
        infoFields: infoFields,
        node: node
    })
end function


function safeUnobserve(fieldName = "", node = top())
    return interfaceFunction("safeUnobserve", { fieldName: fieldName, node: node })
end function


function setTaskFunction(taskFunction = invalid)
    return interfaceFunction("setTaskFunction", { function: taskFunction })
end function
