class Stateable
    sub new(_options = {})
        top().addField("ord_state", "assocarray", false)

        m.setExportFunctions(getGlobalAA().ord_role)
    end sub


    sub reset(_options = {})
        top().removeField("ord_state")
    end sub


    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(componentRole) then return

        if rodash.findIndex(["Scene", "View", "Model", "Controller"], componentRole) = -1 then return

        m.publicFunctions = []
        m.publicFunctions.push("get")
        m.publicFunctions.push("set")
    end sub


    function getStateValue(key = "", node = getGlobalAA().top)
        if rodash.isEmpty(key) then return invalid
        if not rodash.isInvalid(node[key]) then return node[key]

        nodeState = node.getRef("ord_state") ?? {}
        return nodeState[key]
    end function


    function get(options = {})
        stateOptions = options.options
        node = options.node

        if rodash.isString(stateOptions)
            return m.getStateValue(stateOptions, node)
        else if rodash.isArray(stateOptions)
            lookupObj = {}

            for each key in stateOptions
                lookupObj[key] = m.getStateValue(key, node)
            end for

            return lookupObj
        end if

        return invalid
    end function


    sub set(options = {})
        stateOptions = options.options
        node = options.node

        if not rodash.isNonEmptyAA(stateOptions) then return

        nodeState = node.getRef("ord_state") ?? {}

        for each item in stateOptions.items()
            key = item.key ?? ""
            value = item.value
            if rodash.isEmptyString(key) then continue for

            if node.hasField(key)
                node[key] = value
            else
                itemObj = {}
                itemObj[key] = value
                nodeState.append(itemObj)
            end if
        end for

        node.setRef("ord_state", nodeState)
    end sub
end class


function get(options, node = top())
    return interfaceFunction("get", { options: options, node: node })
end function


function set(options = {}, node = top())
    return interfaceFunction("set", { options: options, node: node })
end function
