class Stateable
    publicFunctions = []

    sub new(options = {})
        top().addField("_ord_State", "assocarray", false)

        m.setExportFunctions(getGlobalAA().ord_role)
    end sub

    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(componentRole) then return

        if rodash.findIndex(["Scene", "View", "Model", "Controller"], componentRole) = -1 then return

        m.publicFunctions.push("get")
        m.publicFunctions.push("set")
    end sub


    function getStateValue(key = "", node = getGlobalAA().top)
        if rodash.isEmpty(key) then return invalid
        if not rodash.isInvalid(node[key]) then return node[key]

        nodeState = node.getRef("_ord_State") ?? {}
        return nodeState[key]
    end function


    function get(options = {}, node = getGlobalAA().top)
        if rodash.isString(options)
            return m.getStateValue(options, node)
        else if rodash.isArray(options)
            lookupObj = {}

            for each key in options
                lookupObj[key] = m.getStateValue(key, node)
            end for

            return lookupObj
        end if

        return invalid
    end function


    sub set(options = {}, node = top())
        if not rodash.isNonEmptyAA(options) then return

        nodeState = node.getRef("_ord_State") ?? {}

        for each item in options.items()
            key = item.key ?? ""
            value = item.value
            if rodash.isEmptyString(key) then continue for

            if node.hasField(key)
                node[key] = value
            else
                itemObj = {}
                itemObj[key] = value
                nodeState.append(itemObj)
            end if
        end for

        node.setRef("_ord_State", nodeState)
    end sub
end class
