class Styleable
    publicFunctions = []

    sub new(options = {})
        m.setExportFunctions(role())

        if rodash.findIndex(["Scene", "View"], role()) = -1 then return

        if not global().hasField("_ord_styles")
            m.setupGlobalStyles()
        end if

        styleNode = global()._ord_styles

        appStyles = "<%- o(STYLES) %>"

        if not styleNode.hasField(top().subType())
            styleNode.addField(top().subType(), "assocarray", false)
            styleNode.setField(top().subType(), appStyles[top().subType()])
            styleNode.observeFieldScoped(top().subType(), rodash.getFunctionName(m.stylesUpdated))
        end if


        ' if role() = "Scene"
        '     m.setStyles(appStyles.App)
        ' end if


        m.setStyles(styleNode[top().subType()])

        if appStyles[top().subType()] <> invalid
        end if

        safeObserve("change", "onChildChange")
    end sub


    sub onChildChange(options = {})
        changeData = options.data
        if rodash.isEmpty(changeData) then return
        operation = changeData.operation ?? ""
        if operation = "add" or operation = "remove"
            m.redrawStyles()
        end if
    end sub


    sub redrawStyles()
        styleObject = global()._ord_styles.getField(top().subType())
        if rodash.isEmpty(styleObject) then return
        setStyles(styleObject)
    end sub


    sub stylesUpdated(event)
        styleObject = event.getData()
        if rodash.isEmpty(styleObject) then return
        setStyles(styleObject)
    end sub


    sub setupGlobalStyles()
        global().addField("_ord_styles", "node", true)
        global()._ord_styles = createObject("roSGNode", "Node")
    end sub


    sub setExportFunctions(componentRole)
        if rodash.isEmptyString(componentRole) then return

        if rodash.findIndex(["Scene", "View"], componentRole) = -1 then return
        m.publicFunctions.push("setStyles")
        m.publicFunctions.push("onChildChange")
    end sub


    function returnHandles(options = {})
        allNodeHandles = []

        node = options.node
        if not rodash.isNode(node) then return allNodeHandles

        nodeSubtype = node.subType()
        if not nodeSubtype = "Group" and not node.isSubtype("Group") then return allNodeHandles

        allNodeHandles.push(nodeSubtype)

        if rodash.isNonEmptyString(node.class) then allNodeHandles.push(`${nodeSubtype}.${node.class}`)

        if rodash.isNonEmptyString(node.id) then allNodeHandles.push(`${nodeSubtype}#${node.id}`)

        if rodash.isNonEmptyString(node.id) and rodash.isNonEmptyString(node.class) then allNodeHandles.push(`${nodeSubtype}#${node.id}.${node.class}`)

        return allNodeHandles
    end function


    sub setStyles(stylesheet, node = top())
        m.styleField(node, stylesheet)

        children = node.getChildren(-1, 0)
        if children.count() = 0 then return
        if not rodash.isNonEmptyAA(stylesheet) then return

        for each child in children
            elementhandles = m.returnHandles({ node: child })
            combinedNodeStyles = {}

            for each handle in elementhandles
                if rodash.isAA(stylesheet[handle]) then combinedNodeStyles.append(stylesheet[handle])
            end for

            if rodash.isEmpty(combinedNodeStyles) then continue for

            m.setStyles(combinedNodeStyles, child)
        end for
    end sub


    sub styleField(node, styles)
        if not rodash.isNonEmptyAA(styles) then return
        for each attribute in styles.items()
            attributeValue = attribute.value ?? ""
            if rodash.isString(attributeValue) and attributeValue.instr("TKEY") <> -1
                attributeValue = substitute(tr(attributeValue).trim(), chr(10))
            end if

            if node.hasField(attribute.key)
                node.setField(attribute.key, attributeValue)
            else if rodash.indexOf(["margin", "padding", "minWidth"], attribute.key) <> -1
                updateObject = {}
                updateObject[attribute.key] = attribute.value
                node.update(updateObject, true)
            end if
        end for
    end sub
end class
