class Styleable
    publicFunctions = []
    hookFunctions = {}

    sub new(_options = {})
        m.setExportFunctions(getGlobalAA().ord_role)

        if rodash.findIndex(["Scene", "View"], getGlobalAA().ord_role) = -1 then return

        if not top().hasField("class")
            top().addField("class", "string", true)
        end if

        if not global().hasField("_ord_styles")
            m.setupGlobalStyles()
        end if

        styleNode = global()._ord_styles
        appStyles = "<%- o(STYLES) %>"

        if not styleNode.hasField(top().subType())
            styleNode.addField(top().subType(), "assocarray", false)
            if rodash.isAA(appStyles) then styleNode.setField(top().subType(), appStyles[top().subType()])
        end if

        m.setStyles(styleNode[top().subType()])
        safeObserve(top().subType(), "stylesUpdated", styleNode)
        safeObserve("change", "onChildChange")
        safeObserve("id", "onIdClassChange")
        safeObserve("class", "onIdClassChange")
    end sub


    sub addClass(options = {})
        node = options.node ?? top()
        className = (options.class ?? "").trim()

        if not rodash.isNode(node) then return
        if rodash.isEmptyString(className) then return

        classNames = m.getClassNames(node)
        if rodash.indexOf(classNames, className) = -1 then classNames.push(className)

        m.setClassNames(node, classNames)
        m.redrawStyles()
    end sub


    sub removeClass(options = {})
        node = options.node ?? top()
        className = (options.class ?? "").trim()

        if not rodash.isNode(node) then return
        if rodash.isEmptyString(className) then return

        classNames = m.getClassNames(node)
        if rodash.indexOf(classNames, className) = -1 then return

        filteredClassNames = []
        for each existingClassName in classNames
            if existingClassName <> className then filteredClassNames.push(existingClassName)
        end for

        m.setClassNames(node, filteredClassNames)
        m.redrawStyles()
    end sub


    sub onChildChange(options = {})
        changeData = options.data
        if rodash.isEmpty(changeData) then return
        operation = changeData.operation ?? ""
        if operation = "add" or operation = "remove" or operation = "insert"
            m.redrawStyles()
        end if
    end sub


    sub onIdClassChange(options = {})
        if not rodash.isNonEmptyAA(options) then return

        field = options.field
        if rodash.isEmptyString(field) then return

        node = options.node
        if not rodash.isNode(node) then return

        styleObject = global()._ord_styles.getField(top().subType())

        if field = "id"
            m.setIdStyles(styleObject, node)
        else if field = "class"
            m.setClassStyles(styleObject, node)
        end if
    end sub


    sub redrawStyles()
        styleObject = global()._ord_styles.getField(top().subType())
        if rodash.isEmpty(styleObject) then return

        setStyles(styleObject)
    end sub


    sub stylesUpdated(options = {})
        styleObject = options.data
        if rodash.isEmpty(styleObject) then return

        if rodash.isFunction(m.hookFunctions.before)
            exec(m.hookFunctions.before, styleObject)
        end if

        setStyles(styleObject)

        if rodash.isAA(m.hookFunctions) and rodash.isFunction(m.hookFunctions.after)
            exec(m.hookFunctions.after, styleObject)
        end if
    end sub


    sub setupGlobalStyles()
        global().addField("_ord_styles", "node", true)
        global()._ord_styles = createObject("roSGNode", "Node")
    end sub


    sub setExportFunctions(componentRole)
        if rodash.isEmptyString(componentRole) then return

        if rodash.findIndex(["Scene", "View"], componentRole) = -1 then return
        m.publicFunctions.push("addClass")
        m.publicFunctions.push("removeClass")
        m.publicFunctions.push("redrawStyles")
        m.publicFunctions.push("setStyles")
        m.publicFunctions.push("styleHooks")
        m.publicFunctions.push("onChildChange")
        m.publicFunctions.push("onIdClassChange")
        m.publicFunctions.push("stylesUpdated")
    end sub


    function returnHandles(options = {})
        allNodeHandles = []

        node = options.node
        if not rodash.isNode(node) then return allNodeHandles

        nodeSubtype = node.subType()

        ' if not nodeSubtype = "Group" and not node.isSubtype("Group") then return allNodeHandles

        allNodeHandles.push(nodeSubtype)

        classNames = m.getClassNames(node)
        for each className in classNames
            allNodeHandles.push(`${nodeSubtype}.${className}`)
        end for

        if rodash.isNonEmptyString(node.id) then allNodeHandles.push(`${nodeSubtype}#${node.id}`)

        if rodash.isNonEmptyString(node.id)
            for each className in classNames
                allNodeHandles.push(`${nodeSubtype}#${node.id}.${className}`)
            end for
        end if

        return allNodeHandles
    end function


    sub setStyles(stylesheet, node = top())
        if not rodash.isNonEmptyAA(stylesheet) then return
        m.styleField(node, stylesheet)

        children = node.getChildren(-1, 0)

        for each child in children
            childStyles = stylesheet[child.subType()]
            if rodash.isEmpty(childStyles) then continue for
            m.setStyles(childStyles, child)
        end for

        m.setIdStyles(stylesheet, node)
        m.setClassStyles(stylesheet, node)
    end sub


    sub styleField(node, styles)
        if not rodash.isNonEmptyAA(styles) then return
        for each attribute in styles.items()
            attributeValue = attribute.value ?? ""
            if rodash.isString(attributeValue) and attributeValue.instr("TKEY") <> -1
                attributeValue = substitute(tr(attributeValue).trim(), chr(10))
            end if

            if node.hasField(attribute.key)
                node.setField(attribute.key, attributeValue)
            else if rodash.indexOf(["margin", "minHeight", "minWidth"], attribute.key) <> -1
                updateObject = {}
                updateObject[attribute.key] = attribute.value
                node.update(updateObject, true)
            end if
        end for
    end sub


    sub styleHooks(options = {})
        if not rodash.isNonEmptyAA(options) then return
        m.hookFunctions = options
    end sub


    sub setIdStyles(stylesheet = {}, node = top())
        if not rodash.isNonEmptyAA(stylesheet) then return
        idStyles = stylesheet[`&#${node.id ?? ""}`]
        if rodash.isNonEmptyAA(idStyles) then m.setStyles(idStyles, node)
    end sub


    sub setClassStyles(stylesheet = {}, node = top())
        classNames = m.getClassNames(node)
        for each className in classNames
            classStyles = stylesheet[`&.${className}`]
            if rodash.isNonEmptyAA(classStyles) then m.setStyles(classStyles, node)
        end for
    end sub


    function getClassNames(node)
        classNames = []

        if not rodash.isNode(node) then return classNames
        if not node.hasField("class") then return classNames

        rawClassNames = node.class ?? ""
        if not rodash.isNonEmptyString(rawClassNames) then return classNames

        for each className in rawClassNames.tokenize(" ")
            trimmedClassName = className.trim()
            if rodash.isEmptyString(trimmedClassName) then continue for
            if rodash.indexOf(classNames, trimmedClassName) = -1 then classNames.push(trimmedClassName)
        end for

        return classNames
    end function


    sub setClassNames(node, classNames = [])
        if not rodash.isNode(node) then return

        if not node.hasField("class")
            node.addField("class", "string", true)
        end if

        node.setField("class", rodash.join(classNames, " "))
    end sub
end class
