import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        m.paginationConfigs = "<%- o(CONFIG.Pagination) %>"
        safeFunctions({
            generateCarouselCollection: generateCarouselCollection,
            getVariables: getVariables,
            returnInitialPagination: returnInitialPagination
        })
    end sub)
end sub


sub generateCarouselCollection(_options = {})
    children = top().getChildren(-1, 0)
    carouselCollection = top().carouselCollection
    if not rodash.isNode(carouselCollection) then carouselCollection = createObject("roSGNode", "Collection")

    for each child in children
        existingModel = child.carouselItemModel
        if rodash.isNode(existingModel.getParent()) and existingModel.getParent().isSameNode(carouselCollection) then continue for
        carouselCollection.appendChild(existingModel)
    end for

    ' if carouselCollection.getChildCount() > top().getChildCount()
    '     numberOfChildren = carouselCollection.getChildCount() - top().getChildCount()
    '     ?"removing " numberOfChildren
    '     carouselCollection.removeChildrenIndex(numberOfChildren, top().getChildCount())
    ' end if

    top().carouselCollection = carouselCollection
end sub


function getPagination(_options = {})
    existingPagination = top().pagination
    if rodash.isNonEmptyAA(existingPagination)
        newPagination = returnSubsequentPagination()
        newPagination.start = top().totalCount
    else
        newPagination = returnInitialPagination()
    end if

    top().pagination = newPagination

    return newPagination
end function


function returnInitialPagination(_options = {})
    if m.top.carouselType = "HERO"
        return m.paginationConfigs["HeroInitial"]
    else
        return m.paginationConfigs["Initial"]
    end if
end function


function returnSubsequentPagination(_options = {})
    if m.top.carouselType = "HERO"
        return m.paginationConfigs["HeroSubsequent"]
    else
        return m.paginationConfigs["Subsequent"]
    end if
end function


function getVariables(_options = {})
    returnObj = {}
    returnObj.setModeCaseSensitive()
    returnObj["documentId"] = top().documentId
    returnObj["pagination"] = getPagination()
    return returnObj
end function
