import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        safeFunctions({
            getPagination: getPagination
        })
    end sub)
end sub


function getPagination(options = {})
    existingPagination = top().pagination
    if rodash.isNonEmptyAA(existingPagination)
        newPagination = "<%- o(CONFIG.Pagination.Subsequent) %>"
    else
        newPagination = "<%- o(CONFIG.Pagination.Initial) %>"
    end if

    return newPagination
end function
