import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        m.container = top().findNode("container")
        m.contentLogo = top().findNode("contentLogo")
        m.metadata = top().findNode("metadata")
        m.title = top().findNode("title")
        m.headerImage = top().findNode("headerImage")
        safeObserve("data", onDataSet)
    end sub)
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    data = options.data
    content = data.content
    if not rodash.isEmpty(content.logoImageUri)
        m.contentLogo.visible = true
        m.title.visible = false
        setLogoImage(content.logoImageUri)
    else if not rodash.isEmpty(content.title)
        m.contentLogo.visible = false
        m.title.visible = true
        setLogoTitle(content.title)
    end if

    ' if rodash.isNonEmptyString(content.posterImageUri)
    ' end if
    m.headerImage.newUri = content.posterImageUri

    setMetadata(content)

    stackChildren({ node: m.container, direction: "vertical" })
end sub


sub setLogoImage(logoImageUri = "")
    if rodash.isEmptyString(logoImageUri) then return
    m.contentLogo.uri = logoImageUri
end sub


sub setLogoTitle(title = "")
    if rodash.isEmptyString(title) then return
    m.title.text = title
end sub


sub setMetadata(content = {})
    if not rodash.isNode(content) then return
    metadataArray = []

    if rodash.isArray(content.genres)
        metadataArray.push({
            genres: content.genres
    })
    end if

    if rodash.isNonEmptyString(content.copyrightYear)
        metadataArray.push({
            copyrightYear: content.copyrightYear
        })
    end if

    if rodash.isNumber(content.duration)
        metadataArray.push({
            duration: content.duration
        })
    end if

    if rodash.isNonEmptyString(content.rating)
        metadataArray.push({
            rating: content.rating
        })
    end if

    m.metadata.data = {
        metadataArray: metadataArray
    }
end sub
