import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.heroScrollGroup = top().findNode("heroScrollGroup")
        liveConfig({ field: "config", keyPath: "HeroScrollGroup" }, m.heroScrollGroup)
        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)
        safeObserve("itemFocused", onHeroItemFocused, m.heroScrollGroup)
        setFocusMap({
            "default": m.heroScrollGroup
        })
    end sub)
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if rodash.isNode(m.content) then return

    data = options.data
    content = data.content
    m.content = content

    for each model in content.getChildren(-1, 0)
        processScrollItem({ model: model })
    end for

    safeObserve("hydrated", onCollectionHydrated, m.content)

    dispatch(events.PAGINATE_CAROUSEL, { collection: content })
end sub


sub onCollectionHydrated(options = {})
    if not rodash.isNonEmptyAA(options) then return
    onHeroItemFocused({ data: m.heroScrollGroup.itemFocused })
end sub


sub onHeroItemFocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.content) then return
    itemFocused = options.data
    itemFocusedModel = m.content.getChild(itemFocused)
    if not rodash.isNode(itemFocusedModel) then return

    dispatch(events.HERO_ITEM_FOCUSED, { content: itemFocusedModel, section: sections.HERO })
end sub


sub processScrollItem(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    if not rodash.isNode(model) then return

    component = createObject("roSGNode", "Hero")
    component.data = { content: model }
    m.heroScrollGroup.appendChild(component)
end sub
