import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.heroScrollGroup = top().findNode("heroScrollGroup")
        liveConfig({ field: "config", keyPath: "HeroScrollGroup" }, m.heroScrollGroup)
        safeObserve("data", onDataSet)
        safeObserve("itemFocused", onHeroItemFocused, m.heroScrollGroup)
        setFocusMap({
            "onFocus": m.heroScrollGroup
        })
    end sub)
end sub


sub onDataSet(options = {})
    data = options.data
    content = data.content
    m.content = content

    exec("generateDefaultModels", {}, content)

    for each model in content.getChildren(-1, 0)
        processScrollItem({ model: model })
    end for

    safeObserve("hydrated", onCollectionHydrated, content)
    safeObserve("change", onCollectionChildChange, content)

    dispatch(events.PAGINATE_CAROUSEL, { collection: content })
end sub



sub onCollectionChildChange(options = {})
    changeData = options.data
    collection = options.node
    operation = changeData.operation ?? ""
    if operation <> "add" and operation <> "remove" then return

    numberOfNewNodes = changeData.index2 - changeData.index1 + 1
    addedNodes = collection.getChildren(numberOfNewNodes, changeData.index1)
    if operation = "add"
        for each model in addedNodes
            processScrollItem({ model: model })
        end for
    end if
end sub


sub onCollectionHydrated(options = {})
    onHeroItemFocused({ data: m.heroScrollGroup.itemFocused })
end sub


sub onHeroItemFocused(options = {})
    itemFocused = options.data
    itemFocusedModel = m.content.getChild(itemFocused)
    if not rodash.isNode(itemFocusedModel) then return

    dispatch(events.HERO_ITEM_FOCUSED, { content: itemFocusedModel, section: sections.HERO })

    checkPagination({ itemFocused: options.data })
end sub


sub processScrollItem(options = {})
    model = options.model
    component = createObject("roSGNode", "Hero")
    component.data = { content: model }
    m.heroScrollGroup.appendChild(component)
end sub


sub checkPagination(options = {})
    itemFocused = options.itemFocused ?? 0
    lastPaginatedIndex = m.content.totalCount - 1
    paginationDelta = lastPaginatedIndex - itemFocused
    needsPaginating = paginationDelta <= 1 and m.content.canPaginate and not m.content.paginating
    if needsPaginating then dispatch(events.PAGINATE_CAROUSEL, { collection: m.content })
end sub

