class ImportsVsNoImports
    sub new()
        m.benchTimer = CreateObject("roTimespan")
        m.logText = []
        m.iterations = 999
    end sub


    sub start(options = {})

        for each item in options.items()
            m[item.key] = item.value
        end for

        m.test1()
    end sub


    sub end()
        m.top.resultsText = m.logText.join(chr(10))
    end sub


    sub test1()
        ?"Running Test 1"
        m.benchTimer.mark()

        for ix = 0 to m.iterations
            node = createObject("roSGNode", "NoImports")
        end for

        m.logText.push(`NoImports took ${m.benchTimer.totalMilliseconds().toStr()} ms`)
        m.test2()
    end sub


    sub test2()
        ?"Running Test 2"
        m.benchTimer.mark()


        for ix = 0 to m.iterations
            node = createObject("roSGNode", "Imports")
        end for

        m.logText.push(`Imports took ${m.benchTimer.totalMilliseconds().toStr()} ms`)
        m.end()
    end sub
end class
