import "pkg:/source/helpers/appUtils.bs"


sub init()
    m.queue = createObject("roSGNode", "roMessageTask")

    m.queue.observeField("state", "onStateChange")
    m.allEvents = "{{%- o(EVENT) %}}"
end sub


sub process(eventName, eventData = {} as dynamic)
    if not TypeGuard_isTruthy(m.allEvents[eventName]) then return
    processEvent("event", { type: eventName, data: eventData })
end sub


sub processEvent(key, value)
    if m.queue.state = "run"
        delayEvent(key, value)
        return
    end if

    m.queue.mutation = {
        key: key,
        value: value
    }
    m.queue.control = "RUN"
end sub


sub delayEvent(key, value)
    queueArray = m.queue.queue
    if queueArray = invalid then queueArray = []
    queueArray.push({ key: key, value: value})

    m.queue.queue = queueArray
end sub


sub onStateChange(event)
    queueState = event.getData()
    if queueState = "stop" or queueState = "done"

        m.queue.mutation = invalid

        if m.queue.queue.count() > 0
            queueArray = m.queue.queue
            if queueArray = invalid then queueArray = []
            data = queueArray.shift()
            if data = invalid then return

            m.queue.queue = queueArray
            processEvent(data.key, data.value)
        end if
    end if
end sub
