import "pkg:/source/helpers/dateTime.bs"
import "pkg:/source/helpers/commonUtils.bs"
import "pkg:/source/helpers/typeGuard.bs"

sub init()
    m.list = m.top.findNode("list")

    m.list.update({ focusPercent: 0.0 }, true)
    m.list.update({ childRect: {} }, true)
    m.list.showTargetRects = true
    m.list.observeFieldScoped("itemSelected", "onItemSelected")
    m.list.observeFieldScoped("itemFocused", "onItemFocused")
    m.list.observeFieldScoped("itemUnfocused", "onItemUnfocused")
    m.list.observeFieldScoped("childRect", "onChildRectChanged")

    m.top.observeFieldScoped("rectConfig", "onRectConfigSet")
    m.top.observeFieldScoped("content", "onContentChanged")
    m.top.observeFieldScoped("focusedChild", "onFocusedChildChange")
    m.top.observeFieldScoped("rectSizes", "onRectSizesChanged")

    m.top.focusedTargetsetIndex = 0
    m.childCount = 0
    m.initialFocusNode = m.list

    m.focusTimer = m.top.findNode("focusTimer")
    m.focusTimer.update({
        finishTime: DateTime_getTimestamp()
        focused: false
        startTime: DateTime_getTimestamp()
    }, true)

    m.focusTimer.duration = 0.016
    m.focusTimer.repeat = true
    CommonUtils_observeScoped(m.focusTimer, "fire", "onFocusTimerFired")

    m.totalRectDimensions = {
        height: 0
        width: 0
    }

    ' Default rect config
    m.rectConfig = {
        "autoclip": false,
        "bigSquare": [0, 0],
        "defaultVisibleIndex": 0,
        "direction": "horizontal",
        "duration": 0.01,
        "focusType": "floating",
        "gutterWidth": 0,
        "itemComponentName": "",
        "margin": [0, 0],
        "smallSquare": [0, 0],
        "visibleTiles": 0
    }

    m.lastVisibleIndex = 0
    m.targetSetArray = []
    m.totalRects = 0
    m.processedForRects = -1
    m.top.rectSizes = []
end sub


function createTargetset(options = {})
    targetSet = createObject("roSGNode", "TargetSet")
    targetSet.update(options)
    return targetSet
end function


sub generateDynamicRects()
    m.lastVisibleIndex = m.top.content.getChildCount() - 1
    targetsetRects = returnDynamicTargetsetRects(m.rectConfig)
    unfocusedRects = targetsetRects.shift()
    setUnfocusedTargetSet(unfocusedRects)

    ' Array of targetsets for each focused position in the list.
    m.targetSetArray = []

    for index = 0 to targetsetRects.count() - 1
        focusedTargetSet = createTargetSet({
            focusIndex: index
            targetRects: targetsetRects[index]
        })
        m.targetSetArray.push(focusedTargetSet)
    end for

    m.targetsetRects = targetsetRects
end sub


sub generateRects()
    ' Return all the arrays of rects for all the targetsets.
    ' TargetsetRects represent only the visible rectangles
    targetsetRects = returnTargetsetRects(m.rectConfig)
    unfocusedRects = targetsetRects.shift()
    setUnfocusedTargetSet(unfocusedRects)

    ' Calculate the first and last visible rects
    ' accounting for extra gutter rects
    visibleIndexArray = getVisibleIndices()
    m.firstVisibleIndex = visibleIndexArray[0]
    m.lastVisibleIndex = visibleIndexArray[1]

    ' Array of targetsets for each focused position in the list.
    m.targetSetArray = []

    for index = 0 to targetsetRects.count() - 1
        focusedTargetSet = createObject("roSGNode", "TargetSet")

        if index >= m.firstVisibleIndex and index <= m.lastVisibleIndex
            focusedTargetSet = createTargetSet({
                focusIndex: index
                targetRects: targetsetRects[index]
            })
            m.targetSetArray.push(focusedTargetSet)
        end if
    end for

    m.targetsetRects = targetsetRects
end sub


function getContentChildCount() as integer
    if not TypeGuard_isNode(m.top.content) then return 0
    return m.top.content.getChildCount()
end function


function getDynamicStartingPosition(options = {})
    focusedTile = options.focusedTile ?? 0
    coordinates = [0, 0]
    index = options.index ?? 0
    horizontal = options.horizontal ?? false

    if not TypeGuard_isArray(m.top.rectSizes) then return coordinates

    accumulator = 0

    for x = 0 to index
        rectSize = [0, 0]

        if x <= focusedTile or focusedTile < 0
            rectSize = (m.top.rectSizes[x - 1] ?? {}).smallSquare ?? [0, 0]
        else if x = focusedTile + 1
            rectSize = (m.top.rectSizes[x - 1] ?? {}).bigSquare ?? [0, 0]
        end if

        if horizontal
            accumulator += rectSize[0]
        else
            accumulator += rectSize[1]
        end if

    end for

    if horizontal
        coordinates[0] = accumulator
    else
        coordinates[1] = accumulator
    end if

    return coordinates
end function


' Get the number of extra hidden rects
' for *each side* of the carousel
' meaning ultimately it will be n*2
function getExtraRectNumber(options = {})
    extraRects = 1
    if TypeGuard_isEmptyAssocArray(m.rectConfig) then return extraRects
    ' If there is a gutter, meaning partially visible rects
    ' on each side of the carousel,
    ' then we need to add an extra rect
    ' in order to smoothly load the partially visible rect.
    gutterWidth = m.rectConfig.gutterWidth ?? 0
    if gutterWidth > 0 then extraRects = 2
    return extraRects
end function


function getHeight() as integer
    if TypeGuard_isEmptyAssocArray(m.rectConfig) then return 0

    if TypeGuard_isTruthy(m.rectConfig.flushFocus)
        firstSet = m.targetsetRects[0] ?? []
        lastItem = firstSet[firstSet.count() - 1] ?? { height: 0, width: 0, x: 0, y: 0}

        if m.rectConfig.direction = "horizontal"
            return lastItem.height
        else
            return m.rectConfig.maxHeight ?? 0
        end if
    else
        if m.rectConfig.direction = "horizontal"
            return m.totalRectDimensions.height
        else
            return m.totalRectDimensions.height * m.rectConfig.visibleTiles
        end if
    end if
end function


function getMargins()
    rectConfig = m.rectConfig ?? {}
    margin = rectConfig.margin ?? []

    returnObj = {
        "left": 0,
        "top": 0,
        "right": 0,
        "bottom": 0
    }

    if TypeGuard_isEmptyAssocArray(rectConfig) then return returnObj

    if margin.count() = 1
        returnObj["left"] = margin[0]
        returnObj["top"] = margin[0]
        returnObj["right"] = margin[0]
        returnObj["bottom"] = margin[0]
    else if margin.count() = 2 or margin.count() = 3
        returnObj["left"] = margin[0]
        returnObj["top"] = margin[1]
        returnObj["right"] = margin[0]
        returnObj["bottom"] = margin[1]
    else if margin.count() = 4
        returnObj["left"] = margin[3]
        returnObj["top"] = margin[0]
        returnObj["right"] = margin[1]
        returnObj["bottom"] = margin[2]
    end if

    return returnObj
end function


function getStartingPosition(options = {}) as object
    index = options.index ?? 0
    square = options.square ?? {}
    horizontal = options.horizontal ?? false
    ' Because some of the tiles will be hidden
    extraRects = options.extraRects
    ' We need to adjust the index based on the extraRects
    adjustedIndex = index + extraRects * -1
    coordinates = [0, 0]

    if TypeGuard_isEmptyAssocArray(square) then return coordinates

    if horizontal
        coordinates[0] = adjustedIndex * square.width
    else
        coordinates[1] = adjustedIndex * square.height
    end if

    return coordinates
end function


function getVisibleIndices(options = {})
    content = m.top.content
    if not TypeGuard_isNode(content) then return [0, 0]

    defaultVisibleIndex = m.rectConfig.defaultVisibleIndex ?? 0
    gutterWidth = m.rectConfig.gutterWidth ?? 0

    numberOfContentItems = content.getChildCount()
    maxVisibleTiles = m.rectConfig.visibleTiles ?? 0
    visibleTiles = numberOfContentItems < maxVisibleTiles ? numberOfContentItems : maxVisibleTiles

    ' By default the first visible rect will be index 1
    ' in order to allow a "staging" rect that is invisible behind the clippingrect
    gutterOffset = 1

    ' If there are gutter rects that act as semi-opaque tiles
    ' then we increase the default visible rect even further
    if gutterWidth > 0 then gutterOffset++

    firstVisibleIndex = defaultVisibleIndex + gutterOffset
    lastVisibleIndex = visibleTiles - 1 + gutterOffset

    return [firstVisibleIndex, lastVisibleIndex]
end function


function getWidth() as integer
    if TypeGuard_isEmptyAssocArray(m.rectConfig) then return 0

    if TypeGuard_isTruthy(m.rectConfig.flushFocus)
        if m.rectConfig.direction = "horizontal"
            return m.rectConfig.maxWidth ?? 0
        else

            reduction = function(acc, cv, index, arr, args)
                if TypeGuard_isArray(cv)
                    width = CommonUtils_reduce(cv, args.reduction, {reduction: args.reduction}, 0)
                else
                    width = cv.width
                end if

                if width > acc then acc = width
                return acc
            end function

            maxWidth = CommonUtils_reduce(m.targetsetRects, reduction, {reduction: reduction}, 0)

            return maxWidth
        end if
    else
        if m.rectConfig.direction = "horizontal"
            firstSet = m.targetsetRects[m.lastVisibleIndex] ?? []
            lastItem = firstSet[m.lastVisibleIndex]
            if not TypeGuard_isEmptyAssocArray(lastItem)
                return lastItem.width + lastItem.x
            end if
            return m.totalRectDimensions.width * m.rectConfig.visibleTiles
        else
            return m.totalRectDimensions.width
        end if
    end if
end function


sub onChildRectChanged(event)
    options = event.getData()
    index = options.index ?? 0
    bigSquare = options.bigSquare ?? []
    smallSquare = options.smallSquare ?? []

    rectSizes = m.top.rectSizes
    rectSizes[index] = { bigSquare: bigSquare, smallSquare: smallSquare }

    m.top.rectSizes = rectSizes
end sub


sub onContentChanged(event)
    content = event.getData()
    if not TypeGuard_isNode(content)
        m.list.content = invalid
        m.childCount = 0
        return
    end if

    if m.processedForRects <> m.totalRects or m.childCount <> content.getChildCount()
        processRects()
    end if
end sub


sub onFocusedChildChange(event)
    node = event.getData()
    currentIndex = m.top.focusedContentIndex
    if m.top.content = invalid then return

    unfocused = node = invalid or not node.isSameNode(m.top) and not m.top.isInFocusChain()

    if not TypeGuard_isNode(m.list.targetSet) then return

    m.focusTimer.focused = not unfocused

    currentTime = DateTime_getTimestamp()
    durationMs = m.list.duration * 1000
    finishTime = currentTime + durationMs
    m.focusTimer.startTime = currentTime
    m.focusTimer.finishTime = finishTime
    if m.focusTimer.control <> "start"
        m.focusTimer.control = "start"
    end if

    if unfocused
        unFocusedTargetSet = m.unFocusedTargetSet
        unFocusedTargetSet.focusIndex = m.list.targetSet.focusIndex
        m.list.animateToTargetSet = unFocusedTargetSet
        m.list.animateToItem = currentIndex
        return
    end if

    if not TypeGuard_isArray(m.targetSetArray) then return

    currentTargetSet = m.targetSetArray[m.top.focusedTargetsetIndex]

    m.list.animateToItem = currentIndex
    m.list.animateToTargetSet = currentTargetSet
    m.list.easeFunction = "linear"
end sub


sub onFocusTimerFired(event)
    finishTime = m.focusTimer.finishTime
    startTime = m.focusTimer.startTime
    currentTime = DateTime_getTimestamp()

    totalDuration! = finishTime - startTime
    if totalDuration! <= 0
        m.focusTimer.control = "stop"
        currentPercentage = m.focusTimer.focused ? 1 : 0
        m.list.focusPercent = currentPercentage
        return
    end if

    elapsedTime! = currentTime - startTime
    currentPercentage = elapsedTime! / totalDuration!

    if currentTime > finishTime
        m.focusTimer.control = "stop"
        currentPercentage = 1
    else if currentPercentage < 0
        currentPercentage = 0
    else if currentPercentage > 1
        currentPercentage = 1
    end if

    if not m.focusTimer.focused then currentPercentage = 1 - currentPercentage

    m.list.focusPercent = currentPercentage
end sub


sub onItemFocused(event)
    m.top.itemFocused = event.getData()
end sub


sub onItemSelected(event)
    m.top.itemSelected = event.getData()
end sub


sub onItemUnfocused(event)
    m.top.itemUnfocused = event.getData()
end sub


function onKeyEvent(key, press) as boolean
    if not press then return true

    if CommonUtils_floatMOD(m.list.currFocusItemIndex, 1) <> 0 then return true
    if key <> m.top.advanceKey and key <> m.top.reverseKey then return false

    direction = key = m.top.reverseKey ? -1 : 1

    currentIndex = m.top.focusedContentIndex
    nextIndex = currentIndex + direction

    currentTargetSetIndex = m.top.focusedTargetsetIndex
    nextTargetSetIndex = currentTargetSetIndex + direction
    if nextTargetSetIndex <= 0 then nextTargetSetIndex = 0
    if nextTargetSetIndex >= m.lastVisibleIndex then nextTargetSetIndex = m.lastVisibleIndex

    if m.list.content.getChild(nextIndex) = invalid
        if TypeGuard_isFalsey((m.rectConfig ?? {}).wrap) then return false

        if direction = 1
            nextIndex = 0
            nextTargetSetIndex = 0
        else
            profilesCollection = m.list.content
            if not TypeGuard_isNode(profilesCollection) then return true
            nextIndex = profilesCollection.getChildCount() - 1
            nextTargetSetIndex = nextIndex
        end if
    end if

    if not TypeGuard_isArray(m.targetSetArray) then return false

    nextTargetSet = m.targetSetArray[nextTargetSetIndex]

    if nextTargetSet <> invalid and m.list.currTargetSet <> invalid and nextTargetSet.focusIndex <> m.list.currTargetSet.focusIndex
        m.list.animateToTargetSet = nextTargetSet
        m.top.focusedTargetsetIndex = nextTargetSetIndex
    end if

    m.list.animateToItem = nextIndex
    m.top.focusedContentIndex = nextIndex

    return true
end function


sub onRectConfigSet(event)
    rectConfig = event.getData()
    m.rectConfig.append(rectConfig)

    if rectConfig.direction = "vertical"
        m.top.reverseKey = "up"
        m.top.advanceKey = "down"
    else
        m.top.reverseKey = "left"
        m.top.advanceKey = "right"
    end if

    processRects()
end sub


sub onRectSizesChanged(event)
    rectSizes = event.getData()
    if TypeGuard_isArray(rectSizes) and m.totalRects <> 0 and rectSizes.count() = m.totalRects
        processRects()
    end if
end sub


' Entry to generating TargetGroup rects
sub processRects()
    contentChildCount = getContentChildCount()
    if TypeGuard_isEmptyAssocArray(m.top.rectConfig) or contentChildCount = 0 then return

    rectConfig = m.rectConfig
    m.processedForRects = m.totalRects

    tilesOnScreen = rectConfig.visibleTiles ?? 0
    extraRects = getExtraRectNumber()
    flushFocus = rectConfig.flushFocus ?? false
    totalRects = flushFocus ? contentChildCount : tilesOnScreen + (extraRects * 2)
    m.totalRects = totalRects

    if TypeGuard_isTruthy(flushFocus)
        generateDynamicRects()
    else
        generateRects()
    end if

    setListContent()

    m.top.width = getWidth()
    m.top.height = getHeight()

    setAutoclip()
end sub


function rectSquare(options = {}) as object
    if TypeGuard_isEmptyAssocArray(m.rectConfig) then return [0, 0]
    if TypeGuard_isEmptyAssocArray(options) then return [0, 0]

    squareKey = options.type = "small" ? "smallSquare" : "bigSquare"

    if TypeGuard_isTruthy(m.rectConfig.flushFocus)
        if TypeGuard_isArrayEmpty(m.top.rectSizes) then return [0, 0]

        index = options.index ?? 0
        return (m.top.rectSizes[index] ?? {}).[squareKey] ?? [0, 0]
    end if

    return m.rectConfig[squareKey]
end function


function returnDynamicTargetsetRects(options = {})
    if TypeGuard_isEmptyAssocArray(options) then return []
    direction = options.direction ?? "horizontal"
    listDirection = direction = "horizontal" ? 0 : 1

    rectSizes = m.top.rectSizes ?? []
    margins = getMargins()
    targetsetRects = []

    ' y = -1 is for getting the unfocused targetset rects
    ' m.totalRects - 1 is to get the last index
    for y = -1 to m.totalRects -1
        rects = []
        for x = 0 to rectSizes.count()
            rect = rectSizes[x]
            if TypeGuard_isEmptyAssocArray(rect) then rect = rectSizes[x - 1] ?? {}

            ' If not focused OR
            ' if it is a row for unfocused state
            square = x <> y or y = -1 ? rect.smallSquare : rect.bigSquare

            coordinates = [0, 0]
            previousRect = rects[x - 1]
            if not TypeGuard_isEmptyAssocArray(previousRect)
                if direction = "horizontal"
                    coordinates[listDirection] = previousRect.x + previousRect.width + margins.left + margins.right
                else
                    coordinates[listDirection] = previousRect.y + previousRect.height + margins.top + margins.bottom
                end if
            end if

            if TypeGuard_isArrayNotEmpty(square)
                rects.push({
                    height: square[1] ?? 0
                    width: square[0] ?? 0
                    x: coordinates[0]
                    y: coordinates[1]
                })
            end if
        end for

        ' When the list initially loads,
        ' because we want dynamic width,
        ' we need to supply default values first
        ' so the list is drawn and each item can report its width
        if TypeGuard_isArrayEmpty(rects)
            for x = 0 to m.totalRects -1
                rects.push({
                    height: 36
                    width: 12
                    x: 0
                    y: 0
                })
            end for
        end if

        targetsetRects.push(rects)
    end for

    return targetsetRects
end function


function returnTargetsetRects(options = {})
    ' smallSquare = options.smallSquare ?? []
    bigSquare = options.bigSquare ?? []
    direction = options.direction ?? "horizontal"
    horizontal = direction = "horizontal"
    horizAlign = options.horizAlign ?? "center"
    vertAlign =  options.vertAlign ?? "center"

    margins = getMargins()

    targetsetRects = []

    extraRects = getExtraRectNumber()

    for y = -1 to m.totalRects - 1
        focusedTile = y
        targetRects = []

        for x = 0 to m.totalRects - 1
            bigSquare = rectSquare({ type: "big", index: x })
            smallSquare = rectSquare({ type: "small", index: x })

            m.totalRectDimensions = {
                height: bigSquare[1] + margins.top + margins.bottom
                width: bigSquare[0] + margins.left + margins.right
            }

            if horizAlign = "left"
                deltaX = 0
            else if horizAlign = "right"
                deltaX = (bigSquare[0] - smallSquare[0])
            else
                deltaX = (bigSquare[0] - smallSquare[0]) / 2
            end if

            if vertAlign = "top"
                deltaY = 0
            else if vertAlign = "bottom"
                deltaY = (bigSquare[1] - smallSquare[1])
            else
                deltaY = (bigSquare[1] - smallSquare[1]) / 2
            end if

            containerPosition = getStartingPosition({
                extraRects: extraRects
                horizontal: horizontal
                focusedTile: focusedTile
                index: x
                square: m.totalRectDimensions
            })

            square = x = focusedTile ? bigSquare : smallSquare
            offsetX = x = focusedTile ? margins.left : deltaX + margins.left
            offsetY = x = focusedTile ? margins.top : deltaY + margins.top

            targetRects.push({
                x: containerPosition[0] + offsetX,
                y: containerPosition[1] + offsetY,
                width: square[0],
                height: square[1]
            })
        end for

        targetsetRects.push(targetRects)
    end for

    return targetsetRects
end function


sub setAutoclip()
    if m.rectConfig.autoclip
        m.top.clippingRect = [0, 0, m.top.width, m.top.height]
        m.list.clippingRect = [0, 0, m.top.width, m.top.height]
    end if
end sub


sub setListContent()
    content = m.top.content
    if not TypeGuard_isNode(content)
        m.list.content = invalid
        m.childCount = 0
        return
    end if

    if not TypeGuard_isSameNode(m.list.content, content)
        m.list.content = content
    end if

    m.list.itemComponentName = m.rectConfig.itemComponentName
    m.list.duration = m.rectConfig.duration ?? 0.3
    m.childCount = content.getChildCount()
end sub


sub setUnfocusedTargetSet(unfocusedRects = [])
    rectConfig = m.top.rectConfig ?? {}

    if TypeGuard_isTruthy(rectConfig.flushFocus) or not TypeGuard_isNode(m.list.targetSet)
        defaultVisibleIndex = m.rectConfig.defaultVisibleIndex ?? 0
        extraRects = getExtraRectNumber()

        if TypeGuard_isTruthy(rectConfig.flushFocus) then extraRects = 0

        ' Peel off the first array, which should always be for unfocused targetset
        unFocusedTargetSet = createTargetSet({
            focusIndex: defaultVisibleIndex + extraRects
            targetRects: unfocusedRects
        })

        ' Set the initial targetset of the list to the unfocused one
        m.list.targetSet = unFocusedTargetSet
        m.unFocusedTargetSet = unFocusedTargetSet
    end if
end sub


function totalRectDimensions()
    return {}
end function
