import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        m.headerImageContainer = top().findNode("headerImageContainer")
        safeObserve("data", onDataSet)
        m.headerImageGradients = top().findNode("headerImageGradients")
        m.headerImageMask = top().findNode("headerImageMask")

        rokuDevice = createObject("roDeviceInfo")
        if rokuDevice.getGraphicsPlatform() <> "opengl"
            m.headerImageGradients.visible = true
            m.headerImageMask.maskuri = ""
        end if
        safeFunctions({
            "clearImages": clearImages
        })
    end sub)
end sub


sub clearImages(_options = {})
    if not rodash.isNode(m.headerImageContainer) then return
    m.headerImageContainer.removeChildren(m.headerImageContainer.getChildren(-1, 0))
    m.poster = invalid
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    data = options.data
    content = data.content
    m.content = content

    if content.hydrated ?? false
        onHydrated({ node: m.content })
    else
        safeObserve("hydrated", onHydrated, content)
    end if
end sub


sub onHydrated(options = {})
    if not rodash.isNonEmptyAA(options) then return
    content = options.node

    setImage(content.posterImageUri)
end sub


sub onImageFadeOut(options = {})
    oldPoster = options.node
    if not rodash.isNode(oldPoster) then return
    m.headerImageContainer.removeChild(oldPoster)
end sub


sub setImage(newUri = "")
    oldPoster = m.poster

    if rodash.isNode(oldPoster) and oldPoster.uri = newUri
        if oldPoster.opacity = 0 then fadeIn(oldPoster)
        return
    end if

    newPoster = createObject("roSGNode", "Poster")
    newPoster.id = rodash.now().toStr()
    newPoster.opacity = 0
    newPoster.uri = newUri
    newPoster.width = top().width
    newPoster.height = top().height
    m.headerImageContainer.appendChild(newPoster)

    if rodash.isNode(oldPoster) then fadeOut(oldPoster, { callback: onImageFadeOut, callbackOptions: { node: oldPoster }, duration: 0.3 })

    fadeIn(newPoster, { duration: 0.3 })
    m.poster = newPoster
end sub
