import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.headerImageContainer = top().findNode("headerImageContainer")

        safeObserve("data", onDataSet)

        safeFunctions({
            "clearImages": clearImages
        })
    end sub)
end sub


sub clearImages(_options = {})
    m.headerImageContainer.removeChildren(m.headerImageContainer.getChildren(-1, 0))
    m.poster = invalid
end sub


sub onDataSet(options = {})
    data = options.data
    content = data.content
    m.content = content

    if content.hydrated ?? false
        onHydrated({ node: m.content })
    else
        safeObserve("hydrated", onHydrated, content)
    end if
end sub


sub onHydrated(options = {})
    content = options.node
    setImage(content.posterImageUri)
end sub


sub onImageFadeOut(options = {})
    oldPoster = options.node
    if not rodash.isNode(oldPoster) then return
    m.headerImageContainer.removeChild(oldPoster)
end sub


sub setImage(newUri = "")
    oldPoster = m.poster

    if rodash.isNode(oldPoster) and oldPoster.uri = newUri
        if oldPoster.opacity = 0 then fadeIn(oldPoster)
        return
    end if

    newPoster = createObject("roSGNode", "Poster")
    newPoster.id = rodash.now().toStr()
    newPoster.opacity = 0
    newPoster.uri = newUri
    newPoster.width = top().width
    newPoster.height = top().height
    m.headerImageContainer.appendChild(newPoster)

    if rodash.isNode(oldPoster) then fadeOut(oldPoster, { callback: onImageFadeOut, callbackOptions: { node: oldPoster }})

    fadeIn(newPoster, { delay: 0.1 })
    m.poster = newPoster
end sub
