import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        m.leftLine = top().findNode("leftLine")
        m.tabItem = top().findNode("tabItem")
        m.rightLine = top().findNode("rightLine")

        tabModel = createObject("roSGNode", "Model")
        tabModel.update("<%- o(CONFIG.SeparatorTab) %>", true)
        tabModel.title = tr(tabModel.title)

        styleHooks({
            "after": afterStyling
        })

        afterStyling()
    end sub)
end sub


sub afterStyling(_options = {})
    stackChildren({ direction: "horizontal" })
end sub
