import "pkg:/components/_ord/wrappers.bs"
import "pkg:/source/roku_modules/promises/promises.brs"

sub init()
    exec(sub(_options = {})
        m.screenContainer = top().findNode("screenContainer")
        m.bottomContainer = top().findNode("bottomContainer")
        m.detailsScrollGroup = top().findNode("detailsScrollGroup")
        m.detailsHero = top().findNode("detailsHero")
        m.tabs = top().findNode("tabs")
        m.description = top().findNode("description")
        m.ctas = top().findNode("ctas")

        liveConfig({ field: "config", keyPath: "DetailsScrollGroup" }, m.detailsScrollGroup)
        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)
        safeObserve("itemFocused", onTabFocused, m.tabs)

        setFocusMap({
            "default": m.detailsHero,
            "detailsHero": {
                "default": true,
                "down": focusDetailsScrollGroup
            },
            "detailsScrollGroup": {
                "default": true,
                "up": focusDetailsHero
            },
            "tabs": {
                "back": false,
                "default": true,
                "down": m.detailsScrollGroup,
                "up": sub(_options = {})
                    scrollPage(-1, onDetailsHeroFocused)
                end sub
            }
        })

        styleHooks({
            after: afterStyling
        })
    end sub)
end sub


function beforeViewOpen(options = {}) as dynamic
    routeData = options.route
    if not rodash.isNode(routeData) then return promises.resolve(invalid)
    context = routeData.context ?? {}
    content = context.content
    if not rodash.isNode(content) then return promises.resolve(invalid)

    top().opacity = 0.001
    top().visible = true
    top().translation = [0, 0]
    fadeIn(top(), { duration: 1 })

    dispatch(events.SHOW_DETAILS_UI)
    dispatch(events.GET_DETAILS_DATA, { screenId: routeData.id, slug: routeData.path, content: content })
    return promises.resolve(invalid)
end function


sub onTabFocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.detailsScrollGroup) then return

    m.detailsScrollGroup.animateToItem = options.data ?? 0
end sub


function onViewOpen(_options = {})
    return promises.resolve(invalid)
end function


function onViewResume(_options = {})
    dispatch(events.SHOW_DETAILS_UI)
    return promises.resolve(invalid)
end function


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if rodash.isNode(m.content) then return

    data = options.data
    content = data.content
    m.content = content
    carousels = content.carousels
    m.detailsHero.data = { content: m.content }

    tabsModel = content.tabsModel

    liveConfig({ field: "config", keyPath: "TabsCarousel" }, tabsModel)
    m.tabs.data = { content: tabsModel }

    for each model in carousels
        processScrollItem({ model: model })
    end for

    afterStyling()
end sub


sub afterStyling(_options = {})
    if not rodash.isNode(m.screenContainer) then return
    if not rodash.isNode(m.bottomContainer) then return
    stackChildren({ node: m.screenContainer, direction: "vertical" })
    stackChildren({ node: m.bottomContainer, direction: "vertical" })
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub focusDetailsHero(_options = {})
    if not rodash.isNode(m.content) then return

    carousels = m.content.carousels ?? []
    carouselCount = carousels.count()

    if carouselCount = 0 then return

    if carouselCount = 1
        scrollPage(-1, onDetailsHeroFocused)
    else
        setFocus(m.tabs)
    end if
end sub


sub focusDetailsScrollGroup(_options = {})
    if not rodash.isNode(m.content) then return
    scrollPage(1, onDetailsScrollGroupFocused)
    ' dispatch(events.SCROLL_GROUP_FOCUSED)
end sub


sub onDetailsHeroFocused(_options = {})
    if not rodash.isNode(m.detailsHero) then return
    setFocus(m.detailsHero)
end sub


sub onDetailsScrollGroupFocused(_options = {})
    if not rodash.isNode(m.detailsScrollGroup) then return
    if not rodash.isNode(m.content) then return

    carousels = m.content.carousels ?? []
    carouselCount = carousels.count()

    if carouselCount = 0 then return

    if carouselCount = 1
        setFocus(m.detailsScrollGroup)
    else
        setFocus(m.tabs)
    end if
end sub


sub processScrollItem(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    component = createObject("roSGNode", "Carousel")

    addClass("noTitle", component)
    component.data = { content: model }
    m.detailsScrollGroup.appendChild(component)
end sub


sub scrollPage(direction = 0, callbackFunc = invalid)
    morphObject = {}
    heightDelta = 393 * direction
    morphObject[m.bottomContainer.id] = {
        fields: {
            height: m.bottomContainer.height + heightDelta,
            translation: [
                0,
                m.detailsHero.height - heightDelta
            ]
        }
    }

    morphObject[m.detailsHero.id] = {
        fields: {
            height: m.detailsHero.height - heightDelta
        }
    }

    morphObject[m.description.id] = {
        fields: {
            opacity: 0 - direction
        }
    }

    morphObject[m.ctas.id] = {
        fields: {
            opacity: 0 - direction
        }
    }

    morph(morphObject, { callback: callbackFunc, duration: 0.3 })
end sub


function onKeyEvent(key as string, press as boolean) as boolean
    return exec(function(options = {})
        if not options.press then return true
        handled = processFocus(options.key)
        ?"DetailsScreen onKeyEvent " options.key, handled
        return handled
    end function, { key: key, press: press })
end function
