import "pkg:/components/_ord/wrappers.bs"
import "pkg:/source/roku_modules/promises/promises.brs"

sub init()
    exec(sub(options = {})
        m.screenContainer = top().findNode("screenContainer")
        m.bottomContainer = top().findNode("bottomContainer")
        m.detailsScrollGroup = top().findNode("detailsScrollGroup")
        m.detailsHero = top().findNode("detailsHero")
        m.tabs = top().findNode("tabs")

        liveConfig({ field: "config", keyPath: "CatalogDetailsScrollGroup" }, m.detailsScrollGroup)
        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)

        setFocusMap({
            "default": m.detailsHero,
            "catalogHero": {
                "down": "focusDetailsScrollGroup"
            },
            "detailsScrollGroup": {
                "up": "focusCatalogHero"
            }
        })

        styleHooks({
            after: afterStyling
        })
    end sub)
end sub


function beforeViewOpen(options = {}) as dynamic
    ?"beforeViewOPen " options.route.context, options.route.queryParams, options.route.routeParams
    routeData = options.route
    if not rodash.isNode(routeData) then return promises.resolve(invalid)
    context = routeData.context ?? {}
    content = context.content
    if not rodash.isNode(content) then return promises.resolve(invalid)

    top().opacity = 0
    fadeIn(top(), { duration: 1 })

    dispatch(events.GET_DETAILS_DATA, { screenId: routeData.id, slug: routeData.path, content: content })
    return promises.resolve(invalid)
end function


function onViewOpen(options = {})
    ?"onViewOPen "  top().subtype()
    dispatch(events.SHOW_DETAILS_UI)

    return promises.resolve(invalid)
end function


function onViewResume(options = {})
    ?"onViewResume "  top().subtype()
    dispatch(events.SHOW_DETAILS_UI)
    return promises.resolve(invalid)
end function


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if rodash.isNode(m.content) then return

    data = options.data
    content = data.content
    m.content = content
    carousels = content.carousels
    m.detailsHero.data = { content: m.content }
    m.tabs.data = { content: content. tabsModel }

    for each model in carousels
        processScrollItem({ model: model })
    end for

    afterStyling()
end sub


sub afterStyling(options = {})
    if not rodash.isNode(m.screenContainer) then return
    if not rodash.isNode(m.bottomContainer) then return
    stackChildren({ node: m.bottomContainer, direction: "vertical" })
    stackChildren({ node: m.screenContainer, direction: "vertical" })
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub focusCatalogHero(options = {})
    ' scrollPage(-1, onCatalogHeroFocused)
    ' dispatch(events.CATALOG_HERO_FOCUSED)
end sub


sub focusDetailsScrollGroup(options = {})
    ' scrollPage(1, onDetailsScrollGroupFocused)
    ' onDetailsScrollGroupFocused()
    ' dispatch(events.SCROLL_GROUP_FOCUSED)
end sub


sub processScrollItem(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    component = createObject("roSGNode", "Carousel")
    addClass("noTitle", component)
    component.data = { content: model }
    m.detailsScrollGroup.appendChild(component)
end sub


sub scrollPage(direction = 0, callbackFunc = invalid)
    morphObject = {}
    heightDelta = 195 * direction
    morphObject[m.detailsScrollGroup.id] = {
        fields: {
            height: m.detailsScrollGroup.height + heightDelta,
            translation: [
                0,
                m.catalogHero.height - heightDelta
            ]
        }
    }
    morphObject[m.catalogHero.id] = {
        fields: {
            height: m.catalogHero.height - heightDelta,
            opacity: 1 - direction
        }
    }

    morphObject[m.catalogHeader.id] = {
        fields: {
            height: direction = -1 ? m.catalogHero.height - heightDelta : 0,
            opacity: 0 + direction
        }
    }

    m.catalogHeader.visible = direction = 1 ? true : false

    morph(morphObject, { callback: callbackFunc, duration: 0.3 })
end sub
