import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.container = top().findNode("container")
        m.scrolltrack = top().findNode("scrollTrack")
        m.scrollKnob = top().findNode("scrollKnob")

        defaultConfig = {
            advanceKey: "down",
            reverseKey: "up",
            direction: "vertical",
            flushEnd: false,
            maxSize: 0,
            showScrollbar: false,
            scrollbarPosition: "right",
            scrollSize: 0
        }

        set({
            defaultConfig: defaultConfig,
            focusedItem: 0
        })

        onConfigChange({ data: defaultConfig })

        safeObserve("config", onConfigChange)
        safeObserve("change", onChildChange)
        safeObserve("width", onConfigChange)
        safeObserve("height", onConfigChange)
    end sub)
end sub


function onKeyEvent(key as string, press as boolean) as boolean
    return exec(function(options = {})
        key = options.key
        press = options.press
        if not press then return true
        handled = rodash.indexOf([get("advanceKey"), get("reverseKey")], key) <> -1

        if handled then return performScroll(key)
        return handled
    end function, { key: key, press: press })
end function


sub onConfigChange(options = {})
    if not rodash.isNonEmptyAA(options) then return

    defaultConfig = get("defaultConfig") ?? {}
    config = {}
    config.append(defaultConfig)
    if rodash.isNonEmptyAA(options.data) then config.append(options.data)

    horizontal = config.direction = "horizontal"

    config.horizontal = horizontal
    config.axisIndex= horizontal ? 0 : 1
    config.crossAxisIndex= horizontal ? 1 : 0
    config.targetDimension = horizontal ? "width" : "height"
    config.crossAxisTargetDimension = horizontal ? "height" : "width"

    if config.direction = "vertical"
        config.reverseKey = "up"
        config.advanceKey = "down"
    else
        config.reverseKey = "left"
        config.advanceKey = "right"
    end if

    set(config)
    setGroupSizes()
end sub


sub onChildChange(options = {})
    changeData = options.data

    if rodash.isEmpty(changeData) then return
    operation = changeData.operation ?? ""
    if operation <> "add" and operation <> "remove" then return

    numberOfNewNodes = changeData.index2 - changeData.index1 + 1
    addedNodes = top().getChildren(numberOfNewNodes, changeData.index1)

    for each child in addedNodes
        if child.isSubtype("Group") then m.container.appendChild(child)
    end for

    setGroupSizes()
end sub


sub setGroupSizes()
    direction = get("direction") ?? "vertical"
    horizontal = get("horizontal") ?? false
    if rodash.isEmptyString(direction) then return

    stackChildren({ node: m.container, direction: direction })

    viewportDimensions = calculate.viewportSize({
        horizontal: horizontal,
        maxSize: get("maxSize")
    })

    scrollContainerDimensions = calculate.scrollContainerSize({
        node: m.container
    })

    set({
        scrollContainerDimensions: scrollContainerDimensions,
        viewportDimensions: viewportDimensions
    })

    setClippingRect()

    if not get("showScrollbar") then return

    setupScrollbar({
        axisIndex: get("axisIndex"),
        crossAxisIndex: get("crossAxisIndex"),
        crossAxisTargetDimension: get("crossAxisTargetDimension"),
        direction: direction,
        horizontal: horizontal,
        scrollbarPosition: get("scrollbarPosition"),
        scrollContainerDimensions: scrollContainerDimensions,
        targetDimension: get("targetDimension"),
        viewportDimensions: viewportDimensions
    })
end sub


function performScroll(key = "")
    if rodash.isEmptyString(key) then return false

    children = m.container.getChildren(-1, 0)
    if not rodash.isNonEmptyArray(children) then return false

    direction = get("direction")
    horizontal = direction = "horizontal"
    focusedItem = get("focusedItem")
    axisIndex = get("axisIndex")

    nextFocusedItem = calculate.nextIndex({
        focusedItem: focusedItem,
        key: key,
        maxIndex: children.count() - 1
    })

    if nextFocusedItem = focusedItem then return false

    scrollContainerDimensions = get("scrollContainerDimensions")
    viewportDimensions = get("viewportDimensions")

    maxTranslation = [0, 0]

    if get("flushEnd")
        maxTranslation[axisIndex] = scrollContainerDimensions[axisIndex] - viewportDimensions[axisIndex]
    else
        lastChild = rodash.last(children)
        if rodash.isNotInvalid(lastChild)
            lastChildSize = horizontal ? getVisibleWidth(lastChild) : getVisibleHeight(lastChild)
            maxTranslation[axisIndex] = scrollContainerDimensions[axisIndex] - lastChildSize
        end if
    end if

    trackTranslation = m.container.translation
    trackTranslation[axisIndex] = 0

    if nextFocusedItem > 0
        for index = 0 to nextFocusedItem - 1
            child = children[index]
            childSize = horizontal ? getVisibleWidth(child) : getVisibleHeight(child)
            trackTranslation[axisIndex] += childSize
        end for
    end if

    if trackTranslation[axisIndex] > maxTranslation[axisIndex]
        trackTranslation[axisIndex] = maxTranslation[axisIndex]
    end if

    scrollKnobTranslation = m.scrollKnob.translation
    scrollKnobTranslation[axisIndex] = 0

    scrollKnobTranslation[axisIndex] = calculate.scrollTranslation({
        axisIndex: axisIndex,
        targetDimension: get("targetDimension"),
        horizontal: horizontal,
        maxTranslation: maxTranslation,
        scrollKnob: m.scrollKnob,
        trackTranslation: trackTranslation,
        viewportDimensions: viewportDimensions
    })

    trackTranslation[axisIndex] = trackTranslation[axisIndex] * -1

    performMorph({
        scrollKnobTranslation: scrollKnobTranslation,
        trackTranslation: trackTranslation
    })

    children[nextFocusedItem].setFocus(true)

    set({
        focusedItem: nextFocusedItem
    })

    return true
end function


sub setClippingRect(options = {})
    top().clippingRect = [0, 0, top().width, top().height]
    m.container.clippingRect = [0, 0, m.container.width, m.container.height]
end sub


sub setupScrollbar(options = {})
    axisIndex = options.axisIndex
    horizontal = options.horizontal
    viewportDimensions = options.viewportDimensions
    scrollbarPosition = options.scrollbarPosition
    scrollContainerDimensions = options.scrollContainerDimensions
    targetDimension = options.targetDimension
    crossAxisTargetDimension = options.crossAxisTargetDimension
    crossAxisIndex = options.crossAxisIndex

    stackChildren({ node: m.scrollTrack })

    m.scrolltrack[targetDimension] = viewportDimensions[axisIndex]
    m.scrollKnob[targetDimension] = (viewportDimensions[axisIndex] / scrollContainerDimensions[axisIndex]) * viewportDimensions[axisIndex]

    if horizontal
        if scrollbarPosition <> "top" and scrollbarPosition <> "bottom"
            scrollbarPosition = "bottom"
        end if
    else
        if scrollbarPosition <> "left" and scrollbarPosition <> "right"
            scrollbarPosition = "right"
        end if
    end if

    scrolltrackTranslation = m.scrolltrack.translation
    containerTranslation = m.container.translation

    if scrollbarPosition = "right" or scrollbarPosition = "bottom"
        scrolltrackTranslation[crossAxisIndex] = viewportDimensions[crossAxisIndex] - m.scrolltrack[crossAxisTargetDimension]
        m.container[crossAxisTargetDimension] = viewportDimensions[crossAxisIndex] - m.scrolltrack[crossAxisTargetDimension]
    else if scrollbarPosition = "left" or scrollbarPosition = "top"
        containerTranslation[crossAxisIndex] = m.scrolltrack[crossAxisTargetDimension]
        m.container[crossAxisTargetDimension] = viewportDimensions[crossAxisIndex] - m.scrolltrack[crossAxisTargetDimension]
    end if

    m.scrolltrack.translation = scrolltrackTranslation
    m.container.translation = containerTranslation

    setClippingRect()
    m.scrolltrack.visible = true
end sub


sub performMorph(options = {})
    scrollKnobTranslation = options.scrollKnobTranslation ?? [0, 0]
    trackTranslation = options.trackTranslation ?? [0, 0]

    morphObject = {}

    if rodash.isNode(m.container) and rodash.isNonEmptyString(m.container.id)
        morphObject[m.container.id] = {
            fields: {
                translation: trackTranslation
            }
        }
    end if

    if rodash.isNode(m.scrollKnob) and rodash.isNonEmptyString(m.scrollKnob.id)
        morphObject[m.scrollKnob.id] = {
            fields: {
                translation: scrollKnobTranslation
            }
        }
    end if

    morph(morphObject)
end sub


namespace calculate
    function nextIndex(options = {})
        focusedItem = options.focusedItem
        key = options.key
        maxIndex = options.maxIndex
        nextFocusedItem = focusedItem

        if key = get("advanceKey")
            if focusedItem < maxIndex then nextFocusedItem = focusedItem + 1
        else if key = get("reverseKey")
            if focusedItem > 0 then nextFocusedItem = focusedItem - 1
        end if

        return nextFocusedItem
    end function


    function scrollContainerSize(options = {})
        node = options.node
        if not rodash.isNode(node) then return [0, 0]
        return [
            node.width,
            node.height
        ]
    end function


    function scrollTranslation(options = {})
        axisIndex = options.axisIndex
        horizontal = options.horizontal
        maxTranslation = options.maxTranslation
        scrollKnob = options.scrollKnob
        targetDimension = options.targetDimension
        trackTranslation = options.trackTranslation
        viewportDimensions = options.viewportDimensions

        scrollableSize = viewportDimensions[axisIndex] - m.scrollKnob[targetDimension]
        scrollPercentage = trackTranslation[axisIndex] / maxTranslation[axisIndex]
        scrollTrackTranslation = scrollPercentage * scrollableSize

        if rodash.isInvalid(scrollKnob.margin) then return scrollTrackTranslation

        if scrollPercentage <> 1 and scrollPercentage <> 0 then return scrollTrackTranslation

        margins = quadrupleMargins(scrollKnob.margin)

        if scrollPercentage = 0
            marginOffset = horizontal ? margins.left : margins.top
            scrollTrackTranslation += marginOffset
        else if scrollPercentage = 1
            marginOffset = horizontal ? margins.right : margins.bottom
            scrollTrackTranslation -= marginOffset
        end if

        return scrollTrackTranslation
    end function


    function viewportSize(options = {})
        horizontal = options.horizontal
        maxSize = options.maxSize ?? 0
        viewportHeight = top().height
        viewportWidth = top().width

        if maxSize > 0
            if horizontal
                viewportHeight = maxSize
            else
                viewportWidth = maxSize
            end if
        end if

        return [viewportWidth, viewportHeight]
    end function

end namespace
