module.exports = {
    "Icons": {
        "arrowDown": "2",
        "arrowLeft": "4",
        "arrowRight": "3",
        "arrowUp": "1",
        "caretDown": "D",
        "caretLeft": "L",
        "caretRight": "R",
        "caretUp": "U",
        "cc": "6",
        "continueWatching": "c",
        "documentaries": "d",
        "ellipsisV": "E",
        "ellipsisH": "e",
        "favorites": "f",
        "genres": "g",
        "home": "h",
        "info": "I",
        "liveTV": "t",
        "movies": "m",
        "pause": "P",
        "play": ">",
        "playSquare": "C",
        "podcasts": "p",
        "remote": "r",
        "replay": "@",
        "search": "s",
        "seekFF": "B",
        "seekRW": "A",
        "shows": "a",
        "sports": "b",
        "settings": "S",
        "user": "u",
        "watchLater": "l",
        "watchlist": "w"
    }
};
