import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.list = top().findNode("ctasList")

        safeObserve("focusedChild", onFocusedChildChange)
        safeObserve("data", onDataChange)
    end sub)
end sub


sub onDataChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.list) then return

    data = options.data
    ctasModel = data.content

    liveConfig({ field: "config", keyPath: "CTACarousel" }, ctasModel)

    m.list.data = {
        content: ctasModel
    }
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) or not top().isSameNode(focusedChild) then return
    if not rodash.isNode(m.list) then return
    m.list.setFocus(true)
end sub
