import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        loadList()
        safeObserve("focusedChild", onFocusedChildChange)
    end sub)
end sub


sub loadList()
    list = top().findNode("ctasList")

    ctasModel = createObject("roSGNode", "CTAsModel")
    liveConfig({ field: "config", keyPath: "CTACarousel" }, ctasModel)

    list.data = {
        content: ctasModel
    }

    m.list = list
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    m.list.setFocus(true)
end sub
