import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.container = top().findNode("container")
        m.contentLogo = top().findNode("contentLogo")
        m.metadata = top().findNode("metadata")
        m.description = top().findNode("description")
        m.ctas = top().findNode("ctas")

        setLoadable({ node: m.contentLogo, updateField: "uri" })
        setLoadable({ node: m.description, updateField: "text" })
        setLoadable({ node: m.metadata, updateField: "data" })
        setLoadable({ node: m.ctas, updateField: "data" })

        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)
        setFocusMap({
            "default": m.ctas
        })
        stackChildren({ node: m.container, direction: "vertical" })
        redrawStyles()
    end sub)
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    data = options.data
    content = data.content
    if rodash.isNode(m.content) and content.isSameNode(m.content) then return

    m.content = content

    if rodash.isEmptyString(content.description)
        safeObserve("description", setDescription, m.content)
    else
        setDescription({ data: content.description})
    end if

    if rodash.isEmptyString(content.logoImageUri)
        safeObserve("logoImageUri", setLogoImage, m.content)
    else
        setLogoImage({ data: content.logoImageUri})
    end if

    if not rodash.isArray(content.genres)
        safeObserve("hydrated", setMetadata, m.content)
    else
        setMetadata({ node: content })
    end if

    if not rodash.isArray(content.heroCTAsModel)
        safeObserve("heroCTAsModel", setCTAs, m.content)
    else
        setCTAs({ node: content })
    end if
end sub


sub setCTAs(options = {})
    if not rodash.isNonEmptyAA(options) then return
    node = options.node
    if not rodash.isNode(node) then return
    m.ctas.data = { content: node.heroCTAsModel }
end sub


sub setDescription(options = {})
    if not rodash.isNonEmptyAA(options) then return
    m.description.text = options.data ?? ""
end sub


sub setLogoImage(options = {})
    if not rodash.isNonEmptyAA(options) then return
    m.contentLogo.uri = options.data ?? ""
end sub


sub setMetadata(options = {})
    if not rodash.isNonEmptyAA(options) then return
    content = options.node
    metadataArray = []

    if rodash.isArray(content.genres)
        metadataArray.push({
            genres: content.genres
    })
    end if

    if rodash.isNonEmptyString(content.copyrightYear)
        metadataArray.push({
            copyrightYear: content.copyrightYear
        })
    end if

    if rodash.isNumber(content.duration)
        metadataArray.push({
            duration: content.duration
        })
    end if

    if rodash.isNonEmptyString(content.rating)
        metadataArray.push({
            rating: content.rating
        })
    end if

    m.metadata.data = {
        metadataArray: metadataArray
    }
end sub

