import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        m.container = top().findNode("container")
        m.contentLogo = top().findNode("contentLogo")
        m.metadata = top().findNode("metadata")
        m.description = top().findNode("description")
        m.ctas = top().findNode("ctas")

        setLoadable({ node: m.contentLogo, updateField: "uri" })
        setLoadable({ node: m.description, updateField: "text" })
        setLoadable({ node: m.metadata, updateField: "data" })
        setLoadable({ node: m.ctas, updateField: "data" })

        safeObserve("data", onDataSet)
        safeObserve("ctaSelected", onCTASelected, m.ctas)

        setFocusMap({
            "onFocus": onHeroFocus
        })
        stackChildren({ node: m.container, direction: "vertical" })
        redrawStyles()
    end sub)
end sub


function onHeroFocus(options = {})
    ?"onHeroFocus "
    return true
end function


sub onCTASelected(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.content) then return
    actionType = options.data
    if actionType = "PLAY"

    else if actionType = "MORE_INFO"
        dispatch(events.NAVIGATE_TO, { slug: `/content/${m.content.id}`, content: m.content })
    end if
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    data = options.data
    content = data.content
    if rodash.isNode(m.content) and content.isSameNode(m.content) then return

    m.content = content

    if content.hydrated ?? false
        onHydrated({ node: m.content })
    else
        safeObserve("hydrated", onHydrated, content)
    end if
end sub


sub onHydrated(options = {})
    if not rodash.isNonEmptyAA(options) then return
    content = options.node
    ?"onHydrated " top().id

    setDescription(content.description)
    setLogoImage(content.logoImageUri)
    setCTAs(content)
    setMetadata(content)
    ' applyDefaultFocus()
end sub


sub setCTAs(content = {})
    if not rodash.isNode(content) then return
    heroCTAsModel = exec("returnHeroCTAsModel", {}, content)
    if not rodash.isNode(heroCTAsModel) then return
    m.ctas.data = { content:  heroCTAsModel}
end sub


sub setDescription(description = "")
    if rodash.isEmptyString(description) then return
    m.description.text = description
end sub


sub setLogoImage(logoImageUri = "")
    if rodash.isEmptyString(logoImageUri) then return
    m.contentLogo.uri = logoImageUri
end sub


sub setMetadata(content = {})
    if not rodash.isNode(content) then return
    metadataArray = []

    if rodash.isArray(content.genres)
        metadataArray.push({
            genres: content.genres
    })
    end if

    if rodash.isNonEmptyString(content.copyrightYear)
        metadataArray.push({
            copyrightYear: content.copyrightYear
        })
    end if

    if rodash.isNumber(content.duration)
        metadataArray.push({
            duration: content.duration
        })
    end if

    if rodash.isNonEmptyString(content.rating)
        metadataArray.push({
            rating: content.rating
        })
    end if

    m.metadata.data = {
        metadataArray: metadataArray
    }
end sub
