import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        subscribe({
            [events.APP_STARTED]: loginUser,
            [events.GET_USER_CAROUSELS]: getUserCarousels,
            [events.USER_LOGGED_IN]: userLoggedIn,
            [events.USER_CAROUSELS_RECEIVED]: userCarouselsReceived
        })
    end sub)
end sub


sub getUserCarousels(_options = {})
    collections = {
        [carouselTypes.CONTINUE_WATCHING]: createObject("roSGNode", "Collection"),
        [carouselTypes.FAVORITES]: createObject("roSGNode", "Collection"),
        [carouselTypes.WATCHLIST]: createObject("roSGNode", "Collection")
    }
    set({
        collections: collections
    })

    userCarouselsTask = createObject("roSGNode", "UserCarouselsTask")
    userCarouselsTask.update({
        options: {
            collections: collections,
            userModel: get("userModel")
        }
    }, true)

    userCarouselsTask.control = "RUN"
end sub


sub loginUser(_options = {})
    loginUserTask = createObject("roSGNode", "LoginUserTask")
    loginUserTask.control = "RUN"
end sub


sub userCarouselsReceived(_options = {})
    ' collections = get("collections")
    ' ?"userCarouselsReceived " collections["CONTINUE_WATCHING"] collections["FAVORITES"] collections["WATCHLIST"]
end sub


sub userLoggedIn(options = {})
    if not rodash.isNonEmptyAA(options) then return
    userModel = options.userModel
    set({ userModel: userModel })
    dispatch(events.GET_USER_CAROUSELS)
end sub
