import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        subscribe({
            [events.APP_STARTED]: loginUser,
            [events.GET_USER_CAROUSELS]: getUserCarousels,
            [events.USER_LOGGED_IN]: userLoggedIn,
            [events.USER_CAROUSELS_RECEIVED]: userCarouselsReceived,
            [events.TOGGLE_FAVORITE]: toggleFavorite,
            [events.TOGGLE_WATCHLIST]: toggleWatchlist,
            [events.VIDEO_POSITION_CHANGE]: onVideoPositionChange
        })
    end sub)
end sub


sub getUserCarousels(_options = {})
    collectionTypes = {
        [carouselTypes.CONTINUE_WATCHING]: {},
        [carouselTypes.FAVORITES]: {},
        [carouselTypes.WATCHLIST]: {}
    }

    userModel = get("model")
    if not rodash.isNode(userModel) then return

    userCarouselsTask = createObject("roSGNode", "UserCarouselsTask")
    userCarouselsTask.update({
        options: {
            collectionTypes: collectionTypes,
            userId: userModel.documentId
        }
    }, true)

    userCarouselsTask.control = "RUN"
end sub


sub loginUser(_options = {})
    userModel = createObject("roSGNode", "UserModel")
    loginUserTask = createObject("roSGNode", "LoginUserTask")
    loginUserTask.update({
        options: {
            model: userModel,
            variables: exec("getVariables", {}, userModel)
        }
    }, true)
    loginUserTask.control = "RUN"
end sub


sub onVideoPositionChange(options = {})
    position = options.data ?? 0
    duration = options.info?.duration ?? 0
    contentModel = options.contentModel

    collections = get("collections") ?? {}
    if not rodash.isNonEmptyAA(collections) then return

    collection = collections[carouselTypes.CONTINUE_WATCHING]
    if not rodash.isNode(collection) then return

    prevPosition = get("prevPosition") ?? {}
    prevContentPosition = prevPosition[contentModel.id] ?? 0

    positionDelta = abs(position - prevContentPosition)
    if positionDelta < 15 then return

    prevPosition[contentModel.id] = position
    set({ prevPosition: prevPosition })

    userItemTask = createObject("roSGNode", "UserItemTask")
    userItemTask.update({
        options: {
            collection: collection,
            contentModel: contentModel,
            duration: duration,
            existingUserItemIds: exec("getChildIds", {}, collection),
            position: position
        }
    })

    userItemTask.control = "RUN"
end sub


sub toggleFavorite(options = {})
    if not rodash.isNonEmptyAA(options) then return
    contentModel = options.content
    if not rodash.isNode(contentModel) then return

    collections = get("collections")
    if not rodash.isNonEmptyAA(collections) then return

    collection = collections[carouselTypes.FAVORITES]
    if not rodash.isNode(collection) then return

    userItemTask = createObject("roSGNode", "UserItemTask")
    userItemTask.update({
        options: {
            collection: collection,
            contentModel: contentModel,
            existingUserItemIds: exec("getChildFields", { field: "userItemId" }, collection)
        }
    })
    userItemTask.control = "RUN"
end sub


sub toggleWatchlist(options = {})
    if not rodash.isNonEmptyAA(options) then return
    contentModel = options.content
    if not rodash.isNode(contentModel) then return

    collections = get("collections")
    if not rodash.isNonEmptyAA(collections) then return

    collection = collections[carouselTypes.WATCHLIST]
    if not rodash.isNode(collection) then return

    userItemTask = createObject("roSGNode", "UserItemTask")
    userItemTask.update({
        options: {
            collection: collection,
            contentModel: contentModel,
            existingUserItemIds: exec("getChildIds", {}, collection)
        }
    })
    userItemTask.control = "RUN"
end sub


sub userCarouselsReceived(options = {})
    collections = get("collections") ?? {}
    userCarouselsData = options.userCarouselsData ?? {}
    if not rodash.isNonEmptyAA(userCarouselsData) then return

    for each carouselData in userCarouselsData.items()
        carouselType = carouselData.key
        carouselData = carouselData.value
        if not rodash.isNonEmptyAA(carouselData) then continue for
        collection = collections[carouselType]
        if not rodash.isNode(collection) then collection = createObject("roSGNode", "Collection")
        collection.update(carouselData, true)
        collections[carouselType] = collection
    end for

    set({
        collections: collections
    })

    dispatch(events.SET_USER_CAROUSELS, { collections: collections })
end sub


sub userLoggedIn(options = {})
    if not rodash.isNonEmptyAA(options) then return

    userModel = options.model
    updateObject = options.updateObject ?? {}
    if not rodash.isNode(userModel) then return

    userModel.update(updateObject, true)
    set({ model: userModel })

    dispatch(events.GET_USER_CAROUSELS)
end sub
