import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.pill = top().findNode("pill")
        m.ratingText = top().findNode("ratingText")
        safeObserve("text", onTextSet)
    end sub)
end sub


sub onTextSet(options = {})
    rating = options.data
    m.ratingText.text = ucase("Rated " + rating.replace("_", "-"))
    stackChildren({ direction: "horizontal" }, m.pill)
end sub
