import "pkg:/source/roku_modules/rodash/rodash.brs"
import "styleable.bs"
import "wrapperFunctions.bs"


sub initFramework(options = {})
    m.scene = m.top.getScene()
    m.top.addField("safeFunctions", "assocarray", false)

    safeFunctions = {}
    ' if rodash.isFunction(options) then
    safeFunctions.append(new options({ m: m }))

    m.top.addField("state", "assocarray", false)
    m.top.setRef("safeFunctions", safeFunctions)

    initSafeFunctions()
    initStyles()
end sub


sub initSafeFunctions(options = {})
    try
        m.top.addField("azSafeFuncPayload", "assocarray", true)
        m.top.addField("azSafeFuncReturnObj", "assocarray", false)

        m.safeFunctions = options.safeFunctions
    catch e
        ?"Error: " e
    end try
end sub


sub azSafeFunc(event = {})
    devMode = true

    if devMode
        doRun(event)
    else
        try
            doRun(event)
        catch e
            ?"Error: " e
        end try
    end if
end sub


sub doRun(event)
    data = rodash.isNodeEvent(event) ? event.getData() : event ?? {}

    funcName = m.top.azTriggerSafeFunc ?? ""
    funcOptions = m.top.getRef("azSafeFuncPayload")

    safeFunctions = m.top.getRef("safeFunctions")

    returnObj = safeFunctions[funcName](funcOptions)
    if rodash.isNonEmptyAA(returnObj) then m.top.setRef("azSafeFuncReturnObj", returnObj)

    m.top.setRef("azSafeFuncPayload", {})
end sub

class privates
    sub new(options = {})
        if not rodash.isAA(options) then return
        if not rodash.isAA(options.m) then return

        m.append(options.m)
        ?"privateFunctions new "
    end sub
end class
