import "pkg:/components/_ord/init.bs"
import "pkg:/source/roku_modules/sgrouter/router.brs"

sub init()
    exec(sub(_options = {})
        m.background = top().findNode("background")
        m.navigation = top().findNode("navigation")
        m.topbar = top().findNode("topbar")
        m.sidebar = top().findNode("sidebar")
        m.screenContainer = top().findNode("screenContainer")
        m.videoPlayer = top().findNode("videoPlayer")

        sgrouter.initialize({ outlet: m.screenContainer })

        sgRouter.addRoutes([
            { pattern: "/home", component: "CatalogScreen", suspendMode: "show", clearStackOnResolve: true },
            { pattern: "/movies", component: "CatalogScreen", suspendMode: "show", clearStackOnResolve: true },
            { pattern: "/tv-shows", component: "CatalogScreen", suspendMode: "show", clearStackOnResolve: true },
            { pattern: "/documentaries", component: "CatalogScreen", suspendMode: "show", clearStackOnResolve: true },
            { pattern: "/content/:id", component: "ContentScreen", suspendMode: "show" },
            { pattern: "/details/:id", component: "DetailsModal", keepAlive: { enabled: false } },
            { pattern: "/:screenName", component: "WIPScreen" }
        ])

        safeFunctions({
            "catalogCarouselsFocused": catalogCarouselsFocused,
            "catalogHeroFocused": catalogHeroFocused,
            "goBack": goBack,
            "initiateCrash": initiateCrash,
            "showCatalogUI": showCatalogUI,
            "showContentUI": showContentUI,
            "navigateTo": navigateTo,
            "playVideo": playVideo,
            "setActiveView": setActiveView,
            "updateHeaderAssets": updateHeaderAssets,
            "updateBackgroundAssets": updateBackgroundAssets
        })

        setFocusMap({
            "onFocus": m.screenContainer,
            "onKey": {
                "default": true,
                "back": m.sidebar
            },
            "screenContainer": {
                "left": m.sidebar,
                "up": m.topbar
            },
            "sidebar": {
                "right": focusOnScreen
            },
            "topbar": {
                "back": focusOnScreen,
                "down": focusOnScreen,
                "left": m.sidebar
            },
            "videoPlayer": {
                "back": hideVideoPlayer
            }
        })

        set({
            "catalogUIHidden": false,
            "contentUIHidden": true,
            "navigationHidden": false,
            "videoActive": false
        })

        safeObserve("routerState", onRouterStateChanged, sgRouter.getRouter())
    end sub)
end sub


sub catalogCarouselsFocused(options = {})
    exec("hideBackground", options, m.background)
end sub


sub catalogHeroFocused(options = {})
    exec("showBackground", options, m.background)
end sub


sub initiateCrash(_options = {})
    fadeOut(top(), { callback: onLayoutFadedOut })
end sub


sub focusOnScreen(_options = {})
    activeView = getActiveView()
    if not rodash.isNode(activeView) then return
    setFocus(activeView, m.screenContainer)
end sub


sub goBack(options = {})
    if get("videoActive") then return
    wentBack = sgrouter.goBack()
    errorState = options.error ?? false

    if errorState and not wentBack then dispatch(events.NOTIFY_CRASH)
end sub


sub hideVideoPlayer(_options = {})
    toggleVideoPlayer(-1)
    set({ "videoActive": false })
    focusOnScreen()
end sub


sub toggleVideoPlayer(direction = 0)
    morphObject = {}
    morphObject[m.videoPlayer.id] = {
        fields: {
            opacity: 0 + direction
        }
    }
    morphObject[m.screenContainer.id] = {
        fields: {
            opacity: 1 - direction
        }
    }
    morphObject[m.background.id] = {
        fields: {
            opacity: 1 - direction
        }
    }
    if get("contentUIHidden")
        morphObject[m.navigation.id] = {
            fields: {
                opacity: 1 - direction
            }
        }
    end if

    morph(morphObject)
end sub


sub onLayoutFadedOut(_options = {})
    sgrouter.destroy()
    dispatch(events.APP_CRASH)
end sub


sub navigateTo(options = {})
    slug = options.slug ?? ""
    if rodash.isEmptyString(slug) then return

    setFocus(m.screenContainer)

    routeOptions = {}
    routeOptions.append(options)

    sgRouter.navigateTo(slug, routeOptions)
end sub


sub playVideo(options = {})
    m.videoPlayer.data = options
    toggleVideoPlayer(1)
    set({ "videoActive": true })
    setFocus(m.videoPlayer)
end sub


function getActiveView()
    return top().findNode(get("activeViewId") ?? "")
end function


sub setActiveView(options = {})
    screenId = options.screenId ?? ""
    if rodash.isEmptyString(screenId) then return

    set({ "activeViewId": screenId })
    focusOnScreen()
end sub


sub showCatalogUI(options = {})
    if get("navigationHidden")
        set({ "navigationHidden": false })
        fadeIn(m.navigation)
    end if

    if get("catalogUIHidden")
        set({ "catalogUIHidden": false, "contentUIHidden": true })
        exec("showCatalogGradients", options, m.background)
        exec("hideContentGradients", options, m.background)
    end if
end sub


sub showContentUI(options = {})
    if not get("navigationHidden")
        set({ "navigationHidden": true })
        fadeOut(m.navigation)
    end if

    if get("contentUIHidden")
        set({ "catalogUIHidden": true, "contentUIHidden": false })
        exec("hideCatalogGradients", options, m.background)
        exec("showContentGradients", options, m.background)
    end if
end sub


sub updateHeaderAssets(options = {})
    activeView = getActiveView()
    if not rodash.isNode(activeView) then return
    exec("updateHeader", options, activeView)
    exec("updateHeaderImage", options, m.background)
end sub


sub updateBackgroundAssets(options = {})
    exec("updateBackgroundAssets", options, m.background)
end sub


sub onRouterStateChanged(options = {})
    data = options.data
    if data.type <> "NavigationEnd" then return

    dispatch(events.SCREEN_ACTIVE, { screenId: data.id, slug: data.url })
end sub
