import "pkg:/components/_ord/wrappers.bs"


sub init()
    exec(sub(options = {})
        m.stylesTask = createObject("roSGNode", "StyleTask")

        subscribe({
            [events.STYLES_UPDATE]: onStylesUpdate,
            [events.REQUEST_STYLES]: requestStyles
        })
    end sub)
end sub


sub onStylesUpdate(options = {})
    globeStyles = global()._ord_styles
    newStyles = options.STYLES ?? {}
    for each style in newStyles.items()
        if globeStyles[style.key] <> invalid and formatJSON(globeStyles[style.key]) <> formatJSON(style.value)
            globeStyles[style.key] = style.value
        end if
    end for
end sub


sub requestStyles(options = {})
    m.stylesTask.control = "RUN"
end sub
