import "pkg:/components/_ord/wrappers.bs"


sub init()
    exec(sub(options = {})
        m.stylesTask = createObject("roSGNode", "StyleTask")

        subscribe({
            [events.STYLES_UPDATE]: onStylesUpdate,
            [events.REQUEST_STYLES]: requestStyles
        })
    end sub)
end sub


sub onStylesUpdate(options = {})
    globalStyles = global()._ord_styles
    newStyles = options.STYLES ?? {}
    if not rodash.isAA(newStyles) then return

    for each style in newStyles.items()
        globalStyles.setField(style.key, style.value)
    end for
end sub


sub requestStyles(options = {})
    m.stylesTask.control = "RUN"
end sub

