import "pkg:/components/_ord/init.bs"


sub init()
    exec(sub(_options = {})
        if not devMode() then return

        subscribe({
            [events.STYLES_UPDATE]: onStylesUpdate,
            [events.REQUEST_STYLES]: requestStyles
        })
    end sub)
end sub


sub onStylesUpdate(options = {})
    globalStyles = global().ord_styles
    newStyles = options.STYLES ?? {}
    if not rodash.isAA(newStyles) then return

    for each style in newStyles.items()
        globalStyles.setField(style.key, style.value)
    end for
end sub


sub requestStyles(_options = {})
    stylesTask = createObject("roSGNode", "StyleTask")
    stylesTask.control = "RUN"
end sub
