import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        subscribe({
            [events.CAROUSEL_FOCUSED]: navSound
            ' [events.CAROUSEL_ITEM_FOCUSED]: navSound
        })
    end sub)
end sub


sub endSound(_options = {})
    playSound(sounds.DEADEND)
end sub


sub ffSound(_options = {})
    playSound(sounds.NAVMULTI)
end sub


sub playSound(_name, _volume = 50)
    ' app().playSound = name
end sub


sub navSound(_options = {})
    playSound(sounds.NAVSINGLE)
end sub


sub selectSound(_options = {})
    ' playSound(sounds.SELECT)
end sub
