import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
    end sub)
end sub


function getItems() as object
    return [
        {
            iconText: Icons.play,
            title: "Play Now"
        },
        {
            dynamicWidth: true,
            iconText: Icons.watchlist,
            title: "Apdd to watchlist"
        },
        {
            dynamicWidth: true,
            iconText: Icons.favorites,
            title: "Add to favorites"
        },
        {
            dynamicWidth: true,
            iconText: Icons.ellipsisH,
            title: "Details"
        }
    ]
end function
