import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        m.gradient = top().findNode("gradient")
        m.list = top().findNode("topbarList")
        m.userCarouselsContainer = top().findNode("userCarouselsContainer")
        m.userScrollGroup = top().findNode("userScrollGroup")
        liveConfig({ field: "config", keyPath: "ContentScrollGroup" }, m.userScrollGroup)

        safeFunctions({
            "setUserCarousels": setUserCarousels
        })

        safeObserve("data", onDataChange)
        safeObserve("focusedChild", onFocusedChildChange)
    end sub)
end sub


sub onDataChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    data = options.data
    content = data.content
    if not rodash.isNode(content) then return
    liveConfig({ field: "config", keyPath: "Topbar" }, content)
    m.list.data = data
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) or not top().isSameNode(focusedChild) then return
    m.list.setFocus(true)
end sub


sub processScrollItem(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    component = createObject("roSGNode", "Carousel")

    addClass("noTitle", component)
    component.data = { content: model }
    m.userScrollGroup.appendChild(component)
end sub


sub setUserCarousels(options = {})
    if not rodash.isNonEmptyAA(options) then return
    collections = options.collections

    for each collectionType in collections.items()
        collection = collectionType.value
        processScrollItem({ model: collection })
    end for
end sub
