import "pkg:/components/_ord/init.bs"


sub init()
    exec(sub(_options = {})
        m.loadingTimer = createObject("roSGNode", "Timer")
        m.loadingTimer.duration = 1
        safeObserve("fire", onLoadingTimerFire, m.loadingTimer)

        subscribe({
            [events.API_ERROR]: onApiError,
            [events.APP_CRASH]: onAppCrash,
            [events.APP_ERROR]: onAppError,
            [events.APP_STARTED]: onAppStarted,
            [events.NOTIFY_CLOSE]: notifyClose,
            [events.NOTIFY_CRASH]: notifyCrash,
            [events.NOTIFY_EXCEPTION]: notifyException,
            [events.SCREEN_ACTIVE]: onScreenActive
        })
    end sub)
end sub


sub notifyClose(options = {})
    content = options.content
    if not rodash.isNode(content) then return

    toaster = top().getScene().findNode("toaster")
    if not rodash.isNode(toaster) then return

    collection = toaster.data?.content
    if not rodash.isNode(collection) then return

    modelIndex = rodash.indexOf(collection.getChildren(-1, 0), content)

    if modelIndex + 1 = collection.totalCount
        collection.removeChildren(collection.getChildren(-1, 0))
    end if

    if content.type = "warning"
        dispatch(events.ERROR_GO_BACK)
    else if content.type = "error"
        dispatch(events.ERROR_PREPARE_CRASH)
    end if
end sub


sub notifyException(_options = {})
    sendToaster({ title: "Exception occured, going back to the previous page", type: "warning" })
end sub


sub notifyCrash(_options = {})
    sendToaster({ title: "Unrecoverable error occurred.  Channel restarting.", type: "error" })
end sub


sub sendToaster(options = {})
    toaster = top().getScene().findNode("toaster")
    if not rodash.isNode(toaster) then return

    if rodash.isInvalid(toaster.data)
        toasterCollection = createObject("roSGNode", "Collection")
        toaster.data = { content: toasterCollection }
    else
        toasterCollection = toaster.data.content
    end if

    options.append({ subtype: "Model" })
    toasterCollection.update({
        children: [options]
    }, true)

    toasterCollection.totalCount = toasterCollection.getChildCount()
end sub


sub onApiError(options = {})
    ?"onApiError " options
end sub


sub onAppCrash(_options = {})
    dispatch(events.UNSUBSCRIBE_EVENTS)
    dispatch(events.RESTART_APP)
end sub


sub onAppError(options = {})
    'bs:disable-next-line
    ?"APP_ERROR: " formatJSON(options)
    layout = top().getScene().findNode("layout")
    if not rodash.isNode(layout) then return
    videoActive = get("videoActive", layout)
    if not videoActive then dispatch(events.NOTIFY_EXCEPTION)
end sub


sub onAppStarted(_options = {})
    m.loadingTimer.control = "start"
end sub


sub onLoadingTimerFire(_options = {})
    toggleLoadingOverlay({ toggle: true })
end sub


sub onScreenActive(_options = {})
    m.loadingTimer.control = "stop"
    toggleLoadingOverlay({ toggle: false })
end sub


sub toggleLoadingOverlay(options = {})
    layoutOverlay = top().getScene().findNode("loadingOverlay")
    if not rodash.isNode(layoutOverlay) then return
    exec("toggleOverlay", options, layoutOverlay)
end sub
