import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        if not devMode() then return

        m.socketTask = createObject("roSGNode", "ord_socketTask")
        m.socketTask.control = "RUN"

        subscribe({
            [events.UNSUBSCRIBE_EVENTS]: sub(_options = {})
                m.socketTask.control = "STOP"
                m.socketTask = invalid
            end sub
        })
    end sub)
end sub
