import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.heroScrollGroup = top().findNode("heroScrollGroup")
        safeObserve("data", onDataSet)
    end sub)
end sub


sub onDataSet(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if rodash.isNode(m.content) then return

    data = options.data
    content = data.content
    m.content = content

    for each model in content.getChildren(-1, 0)
        processScrollItem({ model: model })
    end for
end sub


sub processScrollItem(options = {})
    if not rodash.isNonEmptyAA(options) then return

    model = options.model
    if not rodash.isNode(model) then return

    component = createObject("roSGNode", "Hero")
    component.data = { content: model }
    m.heroScrollGroup.appendChild(component)

    ' afterStyling()
end sub
