import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        setTaskFunction(runTopbarTask)
    end sub)
end sub


function runTopbarTask(options = {})
    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Topbar) %>"}, headers: "<%- o(CONFIG.Headers) %>"})

    if rodash.isEmpty(response.text) then return true

    sidebarModel = returnTopbarModel(parseJSON(response.text))

    if rodash.isNode(sidebarModel)
        dispatch(events.TOPBAR_RECEIVED, { content: sidebarModel })
    end if

    return true
end function


function returnTopbarModel(options = {})
    data = options.data ?? {}
    topbarData = data.topbar ?? {}
    screensData = topbarData.screens ?? []
    updateObjArray = []

    for each screen in screensData
        updateObject = {
            iconText: getIcon(screen.icon),
            title: screen.name ?? "",
            subtype: "ContentNode"
        }

        updateObjArray.push(updateObject)
    end for

    model = createObject("roSGNode", "TopbarModel")
    model.update(updateObjArray, true)
    model.totalCount = model.getChildCount()
    model.config = "<%- o(CONFIG.Topbar) %>"

    return model
end function


function getIcon(iconType)
    iconsDictionary = "<%- o(CONFIG.Icons) %>"
    return iconsDictionary[iconType] ?? ""
end function
