import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(_options = {})
        setTaskFunction(runTopbarTask)
    end sub)
end sub


function runTopbarTask(_options = {})
    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Topbar) %>"}, headers: "<%- o(CONFIG.Headers) %>"})
    responseJSON = response.json ?? {}

    if not response.ok
        onError({
            failureReason: response.getfailurereason,
            errors: (responseJSON ?? {}).errors
        })
        return true
    end if

    topbarModel = returnTopbarModel(responseJSON)

    if rodash.isNode(topbarModel)
        publish(events.TOPBAR_RECEIVED, { content: topbarModel })
    end if

    return true
end function


function returnTopbarModel(options = {})
    data = options.data ?? {}
    topbarData = data.topbar ?? {}
    screensData = topbarData.screens ?? []
    updateObjArray = []

    for each screen in screensData
        updateObject = {
            iconText: getIcon(screen.icon),
            title: screen.name ?? "",
            subtype: "ContentNode"
        }

        updateObjArray.push(updateObject)
    end for

    model = createObject("roSGNode", "TopbarModel")
    model.update(updateObjArray, true)

    return model
end function


function getIcon(iconType)
    iconsDictionary = "<%- o(CONFIG.Icons) %>"
    return iconsDictionary[iconType] ?? ""
end function
