import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        setTaskFunction(runPaginationTask)
    end sub)
end sub


function runPaginationTask(options = {})
    options = top().options ?? {}
    if not rodash.isNonEmptyAA(options) then return true

    collection = options.collection
    if not rodash.isNode(collection) then return true

    variables = exec("getVariables", {}, collection)
    ?"runPaginationTask " formatJSON(variables)
    response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Carousel) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>"})

    responseJSON = parseJSON(response.text)
    responseData = responseJSON.data ?? {}
    carouselsData = responseData.carousel ?? {}
    contentsData = carouselsData.contents ?? []
    collectionChildren = collection.getChildren(-1, 0)

    for each content in contentsData
        documentId =  content.documentId ?? ""
        if rodash.isEmptyString(documentId) then continue for

        existingContentNode = collection.findNode(documentId)

        if rodash.isNode(existingContentNode)
            hydrateContentNode({ node: existingContentNode, data: content })
            continue for
        end if

        existingEmptyNode = rodash.find(collectionChildren, function(cv)
            return not cv.hydrated
        end function)

        if rodash.isNode(existingEmptyNode)
            hydrateContentNode({ node: existingEmptyNode, data: content })
            continue for
        end if

        newContentNode = createObject("roSGNode", "ContentModel")
        hydrateContentNode({ node: newContentNode, data: content, thumbnailType: collection.thumbnailType })
        collection.appendChild(newContentNode)
    end for

    collection.canPaginate = not rodash.isEmpty(contentsData)
    exec("generateCarouselCollection", {}, collection)
    collection.paginating = false
    collection.hydrated = true


    return true
end function


sub hydrateContentNode(options = {})
    if not rodash.isNonEmptyAA(options) then return

    node = options.node
    data = options.data
    thumbnailType = options.thumbnailType ?? "LANDSCAPE"

    if not rodash.isNode(node) then return
    if not rodash.isNonEmptyAA(data) then return

    contentImages = data.images ?? []
    imageFields = getImageFields(contentImages)

    updateObject = {
        complimentaryColor: data.complimentaryColor,
        copyrightYear: data.copyrightYear,
        description: data.description,
        duration: data.duration,
        genres: data.v2genres,
        heroCTAsModel: returnHeroCTAsModel(),
        id: data.documentId,
        rating: data.rating,
        title: data.title,
        type: data.type
    }

    updateObject.append(imageFields)
    node.update(updateObject, true)

    exec("generateCarouselModel", { thumbnailType: thumbnailType }, node)
    node.hydrated = true
end sub


function getImageFields(images)
    if not rodash.isNonEmptyArray(images) then return {}

    imageFields = rodash.reduce(images, function(acc, cv)
        imageType = lcase(cv.imageType ?? "")
        if rodash.isEmptyString(imageType) then return acc
        fieldName = imageType + "ImageUri"
        imageURL = cv.data?.url ?? ""
        serverPath = "<%- s(CONFIG.ENV.SERVER_URI) %>"
        acc[fieldName] = serverPath + imageURL
        return acc
    end function, {})

    if imageFields.landscapeImageUri <> invalid
        imageFields.thumbnailImageUri = imageFields.landscapeImageUri
    else if imageFields.portraitImageUri <> invalid
        imageFields.thumbnailImageUri = imageFields.portraitImageUri
    end if

    return imageFields
end function

function returnHeroCTAsModel()
    model = createObject("roSGNode", "CTAsModel")
    modelConfigArray = "<%- o(CONFIG.HeroCTAs) %>"
    updateObject = {
        children: []
    }

    for each item in modelConfigArray
        updateObject.children.push({
            dynamicWidth: item.dynamicWidth ?? false,
            iconText: item.iconText ?? "",
            title: (item.title ?? "").inStr("TKEY") <> -1 ? tr(item.title) : item.title,
            subtype: "Model"
        })
    end for

    model.update(updateObject, true)
    return model
end function
