import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        setTaskFunction(runPaginationTask)
    end sub)
end sub


function runPaginationTask(options = {})
    options = top().options ?? {}
    if not rodash.isNonEmptyAA(options) then return true

    collection = options.collection
    if not rodash.isNode(collection) then return true

    variables = {
        documentId: collection.documentId,
        pagination: exec("getPagination", { test: "Input" }, collection)
    }

    ?"variables " formatJSON(variables)

    ' response = rokurequests_Requests().post("<%- s(CONFIG.ENV.GRAPHQL_SERVER) %>", { json: { query: "<%- s(QUERY.Carousel) %>", variables: variables }, headers: "<%- o(CONFIG.Headers) %>"})

    ' ?"response " response.text

    ' ?"collection " collection
    return true
end function
