import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.iconsContainer = top().findNode("iconsContainer")
        m.title = top().findNode("title")
        safeObserve("config", onConfigChange)
    end sub)
end sub


sub onConfigChange(options = {})
    if rodash.isEmpty(options) then return
    config = options.data ?? {}
    if not rodash.isNonEmptyAA(config) then return
    if rodash.isNonEmptyArray(config.icons) then populateIcons(config.icons)
    m.title.text = ucase(tr(config.title))
    top().opacity = config.opacity ?? 1
    stackChildren({ node: top(), direction: "horizontal" })
end sub


sub populateIcons(iconArray = [])
    if not rodash.isNode(m.iconsContainer) then return
    rodash.removeNodeChildren(m.iconsContainer)
    for each icon in iconArray
        iconComponent = createObject("roSGNode", "Icon")
        iconComponent.text = icon
        m.iconsContainer.appendChild(iconComponent)
    end for
    redrawStyles()
    stackChildren({ node: m.iconsContainer, direction: "horizontal" })
end sub

