import "pkg:/source/roku_modules/rodash/rodash.brs"
import "pkg:/source/roku_modules/rokurequests/Requests.brs"

import "pkg:/source/plugins/logger.bs"
import "pkg:/components/constants.bs"

import "interfaces/safeable.bs"
import "interfaces/eventable.bs"
import "interfaces/stateable.bs"
import "interfaces/styleable.bs"

sub init()
    interfaces = [Safeable, Stateable]

    allFunctions = {}
    interfaceFunctions = {}

    for each interface in interfaces
        interfaceInstance = new interface()
        ' if rodash.isNonEmptyAA(interfaceInstance) then allFunctions.append(interfaceInstance)

        interfacePublicFunctions = interfaceInstance.publicFunctions ?? []
        for each functionName in interfacePublicFunctions
            interfaceFunctions[functionName] = interfaceInstance
        end for
    end for

    ' ?"allFunctions " allFunctions

    m.allFunctions = allFunctions
    m.interfaceFunctions = interfaceFunctions

    ' if componentRole = "Scene" then m.top.removeChild(m.top.getChild(0))

    '[Safeable, Eventable, Stateable, Styleable]

    m.interfaceFuncs = allFunctions

    exec("onInit")
end sub


sub registerControllers(controllers = [])
    if not rodash.isNonEmptyArray(controllers) then return
    if not m.top.isSubtype("Scene") then return

    m.controllers = []

    for each controllerName in controllers
        m.controllers.push(createObject("roSGNode", controllerName))
    end for
end sub


function app()
    return m.global.getScene()
end function


function exec(func = "", options = {}, node = m.top, externalInterface = {})
    interface = m.interfaceFunctions["exec"]
    if interface = invalid then return invalid
    return interface.exec(func, options, node, externalInterface)
end function


function safeFunc(functionName = "")
    interface = m.interfaceFunctions["safeFunc"]
    if interface = invalid then return invalid
    return interface.safeFunc(functionName)
end function


function safeObserve(fieldName = "", callbackFunc = "", node = m.top, infoFields = [])
    interface = m.interfaceFunctions["safeObserve"]
    if interface = invalid then return invalid
    return interface.safeObserve(fieldName, callbackFunc, node,infoFields)
end function


function get(options, node = m.top)
    interface = m.interfaceFunctions["get"]
    if interface = invalid then return invalid
    return exec("get", options, node, interface)
end function


function set(options = {}, node = m.top)
    interface = m.interfaceFunctions["set"]
    if interface = invalid then return invalid
    return exec("set", options, node, interface)
end function


function publish(name = "", options = {})
    return m.interfaceFuncs.publish(name, options)
end function


function subscribe(options = {})
    return m.interfaceFuncs.subscribe(options)
end function


function dispatch(event = "", options = {})
    return m.interfaceFuncs.dispatch(event, options)
end function


function getQueue()
    if m.messageQueue <> invalid return m.messageQueue
    'bs:disable-next-line
    m.messageQueue = createObject("roRenderThreadQueue")
    return m.messageQueue
end function

function top()
    return getGlobalAA().top
end function

function global()
    return getGlobalAA().global
end function

function role()
    componentRole = "Controller"

    if m.top.isSubtype("Group")
        componentRole = m.top.isSubtype("Scene") ? "Scene" : "View"
    else if m.top.isSubtype("Task")
        componentRole = "Task"
    else if m.top.isSubtype("ContentNode")
        componentRole = "Model"
    end if

    return componentRole
end function


function timer()
    if m.timer = invalid
        m.timer = createObject("roTimespan")
    end if

    return m.timer
end function
