import "pkg:/source/roku_modules/rodash/rodash.brs"
import "pkg:/source/plugins/logger.bs"
import "pkg:/components/constants.bs"

import "interfaces/eventable.bs"
import "interfaces/publishable.bs"
import "interfaces/receivable.bs"
import "interfaces/safeable.bs"
import "interfaces/sendable.bs"
import "interfaces/stateable.bs"
import "interfaces/styleable.bs"


sub init()
    m.top.removeChild(m.top.getChild(0))
    m.top.addField("role", "string", false)
    m.top.observeFieldScoped("role", "onRoleset")

    m.allInterfaces = {
        "Safeable": Safeable,
        "Stateable": Stateable,
        "Styleable": Styleable,
        "Eventable": Eventable,
        "Sendable": Sendable,
        "Receivable": Receivable,
        "Publishable": Publishable
    }

    m.roleInterfaces = {
        "Scene": [
            "Eventable",
            "Stateable",
            "Safeable",
            "Stateable",
            "Sendable",
            "Receivable",
            "Styleable"
        ],
        "Controller": [
            "Safeable",
            "Stateable",
            "Sendable",
            "Receivable",
        ],
        "View": [],
        "Model": [],
        "Repository": [],
        "Task": [
            "Safeable",
            "Publishable"
        ],
    }

    interfaceFuncs = {}
    m.azHasSafeFuncs = false

    try
        safeFunctions = new privateFunctions() ?? invalid
        if rodash.isAA(safeFunctions) then interfaceFuncs.append(safeFunctions)
        m.azHasSafeFuncs = true
    catch e
        ?"Private functions do not exist in " m.top.subType()
    end try

    m.azSafeable = m.top.hasFunc("safeFunc")

    if m.azHasSafeFuncs and not m.azSafeable
        xmlFilename = `${m.top.subType()}.xml`
        ?`

        WARNING: Please add
        <function name="safeFunc" />
        to ${xmlFilename} file

        `
    end if

    m.interfaceFuncs = interfaceFuncs

    onInit()
end sub


sub onRoleset(event)
    if not rodash.isNodeEvent(event) then return
    role = event.getData()
    roleInterfaces = m.roleInterfaces[role]
    implements(roleInterfaces)
end sub


sub registerControllers(controllers = [])
    if not rodash.isNonEmptyArray(controllers) then return
    if not m.top.isSubtype("Scene") then return

    m.controllers = []

    for each controllerName in controllers
        m.controllers.push(createObject("roSGNode", controllerName))
    end for
end sub


sub implements(interfaces = [])
    if rodash.isEmpty(interfaces) then return

    allInterfaceFunctions = m.interfaceFuncs ?? {}

    for each interfaceName in interfaces
        interfaceClass = m.allInterfaces[interfaceName]
        interfaceInstance = new interfaceClass({ top: m.top, global: m.global })
        interfaceInstance.initInterface()
        interfaceFunctions = interfaceInstance.returnInterfaceFunctions()

        for each interfaceFunction in interfaceFunctions.items()
            allInterfaceFunctions[interfaceFunction.key] = interfaceFunction.value
        end for
    end for

    m.interfaceFuncs = allInterfaceFunctions
end sub


function app()
    return m.global.getScene()
end function


function exec(func = "", options = {}, node = m.top)
    if rodash.isFunction(func) then return func(options)
    if not rodash.isFunction(m.interfaceFuncs["exec"]) then return invalid
    return m.interfaceFuncs.exec(func, options, node)
end function


function safeFunc(functionName = "")
    return m.interfaceFuncs.safeFunc(functionName)
end function


function publish(name = "", options = {})
    return m.interfaceFuncs.publish(name, options)
end function


function subscribe(options = {})
    return m.interfaceFuncs.subscribe(options)
end function


function get(options, node = m.top)
    return m.interfaceFuncs.getField(options, node)
end function


function dispatch(event = "", options = {})
    return m.interfaceFuncs.dispatch(event, options)
end function


function set(options = {}, node = m.top)
    return m.interfaceFuncs.setField(options, node)
end function


function getQueue()
    if m.messageQueue <> invalid return m.messageQueue
    'bs:disable-next-line
    m.messageQueue = createObject("roRenderThreadQueue")
    return m.messageQueue
end function


class onRokuDevInterface
    function new(options = {})
        for each item in options.items()
            m[item.key] = item.value
        end for
    end function

    sub initInterface()
    end sub

    function returnInterfaceFunctions(options = {})
        return m
    end function
end class
