import "pkg:/source/roku_modules/rodash/rodash.brs"
' import "pkg:/source/plugins/safeable.bs"
import "interfaces/safeable.bs"
import "interfaces/styleable.bs"
import "pkg:/source/plugins/stateable.bs"
import "pkg:/source/plugins/logger.bs"


sub init()
    m.top.removeChild(m.top.getChild(0))

    interfaceFuncs = {}

    m.interfaces = {
        "Stateable": Stateable
    }

    m.safeable = new Safeable({ node: m.top })
    ?m.safeable.returnInterfaceFunctions()

    m.styleable = new Styleable({ node: m.top })
    m.azHasSafeFuncs = false

    try
        safeFunctions = new privateFunctions() ?? invalid
        if rodash.isAA(safeFunctions) then interfaceFuncs.append(safeFunctions)
        m.azHasSafeFuncs = true
    catch e
        ?"Private functions do not exist in " m.top.subType()
    end try

    m.azSafeable = m.top.hasFunc("safeFunc")

    ?"m.azHasSafeFuncs " m.azHasSafeFuncs

    if m.azHasSafeFuncs and not m.azSafeable
        xmlFilename = `${m.top.subType()}.xml`
        ?`

        WARNING: Please add
        <function name="safeFunc" />
        to ${xmlFilename} file

        `
    end if

    m.top.setRef("interfaces_ref", interfaceFuncs)

    onInit()
end sub


sub implements(interfaces = [])
    if rodash.isEmpty(interfaces) then return

    allInterfaceFunctions = {}

    for each interfaceName in interfaces
        interfaceClass = m.interfaces[interfaceName]
        interfaceInstance = new interfaceClass()
        interfaceFunctions = interfaceInstance.getReferences()

        for each interfaceFunction in interfaceFunctions.items()
            functionArray = allInterfaceFunctions[interfaceFunction.key] ?? []
            functionArray.push(interfaceFunction.value)
            allInterfaceFunctions[interfaceFunction.key] = functionArray
        end for
    end for

    ?"allInterfaceFunctions " allInterfaceFunctions
    m.top.setRef("interfaces_ref", allInterfaceFunctions)
end sub

function exec(functionName = "", options = {}, node = m.top)
    return m.Safeable.exec(functionName, options, node)
end function

function safeFunc(functionName = "")
    return m.Safeable.safeFunc(functionName)
end function
