class Eventable
    subscriptions = {}
    publicFunctions = []

    sub new(options = {})

        if role() = "Scene" or global()._ord_eventQueue = invalid
            m.eventQueue = createObject("roSGNode", "_ord_eventQueue")
            m.eventQueue.control = "RUN"
            global().addField("_ord_eventQueue", "node", false)
            global()._ord_eventQueue = m.eventQueue
        end if

        top().addField("_ord_subscriptions", "assocarray", false)

        m.setExportFunctions(role())
    end sub

    sub setExportFunctions(componentRole = "")
        if rodash.isEmptyString(role) then return

        if rodash.findIndex(["Scene", "View", "Model", "Controller", "Task"], componentRole) <> -1
            m.publicFunctions.push("dispatch")
        end if

        if rodash.findIndex(["Scene", "Controller"], componentRole) <> -1
            m.publicFunctions.push("subscribe")
        end if

        if rodash.findIndex(["Task"], componentRole) <> -1
            m.publicFunctions.push("publish")
        end if
    end sub

    sub storeFunctions(options = {})
        subscriptions = top().getRef("_ord_subscriptions") ?? {}

        name = options.name
        functions = options.functions
        functionArray = []

        if rodash.isArray(functions)
            functionArray.append(functions)
        else
            functionArray.push(functions)
        end if

        subscriptions[name] = functionArray
        top().setRef("_ord_subscriptions", subscriptions)
    end sub


    sub subscribe(options = {})
        if rodash.isEmpty(options) then return

        for each event in options.items()
            eventName = event.key
            eventFunctions = event.value

            if rodash.isEmptyString(eventName) then continue for
            if not rodash.isString(eventFunctions) and not rodash.isArray(eventFunctions) then continue for

            m.storeFunctions({ name: eventName, functions: eventFunctions })

            messageQueue = getQueue()
            if messageQueue = invalid then return

            observeFunction = m.callEventFunctions
            observeFunctionName = rodash.getFunctionName(observeFunction)
            messageQueue.addMessageHandler(eventName, observeFunctionName)
        end for
    end sub

    sub callEventFunctions(data = {}, messageInfo = {})
        ?"callEventFunctions " data messageInfo
        if rodash.isEmpty(messageInfo) then return

        subscriptions = top().getRef("_ord_subscriptions") ?? {}

        if rodash.isEmpty(subscriptions) then return

        eventId = messageInfo.message_id ?? ""
        eventFunctions = subscriptions[eventId]

        for each functionName in eventFunctions
            exec(functionName, data)
        end for
    end sub

    sub publish(name = "", options = {})
        messageQueue = getQueue()
        if messageQueue = invalid then return
        messageQueue.postMessage(name, options)
    end sub

    sub dispatch(eventId, options = {})
        if rodash.isEmpty(eventId) then return
        payload = {
            id: eventId
            options: options
        }
        m.eventQueue.eventData = payload
    end sub
end class
