class Styleable
    publicFunctions = {}

    sub new(options = {})
        if not rodash.isNode(options.top) then return
        m.top = options.top

        componentRole = options.role ?? ""
        if rodash.isEmptyString(componentRole) then return

        ' m.setExportFunctions(componentRole)
    end sub


    ' sub setExportFunctions(role)
    '     if rodash.isEmptyString(role) then return

    '     if rodash.findIndex(["Scene", "View"], role) = -1 then return
    '     m.publicFunctions.append({
    '         _setStyles: m.setStyles
    '     })
    ' end sub


    function returnHandles(options = {})
        allNodeHandles = []

        node = options.node
        if not rodash.isNode(node) then return allNodeHandles

        nodeSubtype = node.subType()
        if not nodeSubtype = "Group" and not node.isSubtype("Group") then return allNodeHandles

        allNodeHandles.push(nodeSubtype)

        if rodash.isNonEmptyString(node.class) then allNodeHandles.push(`${nodeSubtype}.${node.class}`)

        if rodash.isNonEmptyString(node.id) then allNodeHandles.push(`${nodeSubtype}#${node.id}`)

        if rodash.isNonEmptyString(node.id) and rodash.isNonEmptyString(node.class) then allNodeHandles.push(`${nodeSubtype}#${node.id}.${node.class}`)

        return allNodeHandles
    end function


    ' Progammatically attach styles to the node's children and its grandchildren
    sub setStyles(stylesheet, node = m.top)
        m.styleField(node, stylesheet)

        children = node.getChildren(-1, 0)
        if children.count() = 0 then return
        if not rodash.isNonEmptyAA(stylesheet) then return

        for each child in children
            elementhandles = m.returnHandles({ node: child })
            combinedNodeStyles = {}

            for each handle in elementhandles
                if rodash.isAA(stylesheet[handle]) then combinedNodeStyles.append(stylesheet[handle])
            end for

            if rodash.isEmpty(combinedNodeStyles) then continue for

            childId = child.id.split("_")[0]

            m.setStyles(combinedNodeStyles, child)
        end for
    end sub


    sub styleField(node, styles)
        for each attribute in styles.items()
            attributeValue = attribute.value ?? ""
            if rodash.isString(attributeValue) and attributeValue.instr("TKEY") <> -1
                attributeValue = substitute(tr(attributeValue).trim(), chr(10))
            end if

            if node.hasField(attribute.key)
                node.setField(attribute.key, attributeValue)
            else if rodash.indexOf(["margin", "padding", "minWidth"], attribute.key) <> -1
                updateObject = {}
                updateObject[attribute.key] = attribute.value
                node.update(updateObject, true)
            end if
        end for
    end sub
end class
