import "pkg:/source/roku_modules/rodash/rodash.brs"
import "pkg:/source/roku_modules/rokurequests/Requests.brs"

import "pkg:/components/constants.bs"

import "traits/animatable.bs"
import "traits/configable.bs"
import "traits/eventable.bs"
import "traits/focusable.bs"
import "traits/loadable.bs"
import "traits/positionable.bs"
import "traits/safeable.bs"
import "traits/stateable.bs"
import "traits/styleable.bs"


sub ord_init()
    setRole()

    interfaces = [Safeable, Stateable, Eventable, Styleable, Animatable, Focusable, Configable, Loadable, Positionable]

    m.ord_allInterfaces = []
    m.ord_publicInterfaces = {}

    for each interface in interfaces
        interfaceInstance = new interface()
        m.ord_allInterfaces.push(interfaceInstance)
        interfacePublicFunctions = interfaceInstance.publicFunctions ?? []
        for each functionName in interfacePublicFunctions
            m.ord_publicInterfaces[functionName] = interfaceInstance
        end for
    end for

    if getGlobalAA().ord_role = "Task"
        top().functionName = "runTask"
    end if

    m.ord_initiated = true
end sub


sub ord_reset(_options = {}, _messageInfo = {})
    for each interfaceInstance in m.ord_allInterfaces
        interfaceInstance.reset()
    end for

    m.ord_initiated = invalid
end sub


function getNodeIdentifier(node)
    if not rodash.isNode(node) then return ""
    if rodash.isInvalid(node.ord_uuid) then setUUID(node)

    return node.ord_uuid
end function


function interfaceFunction(name = "", options = {})
    if rodash.isEmptyString(name) then return invalid
    interface = m.ord_publicInterfaces[name]
    if interface = invalid then return invalid
    return interface[name](options)
end function


function onError(options = {})
    threadInfo = top().threadInfo()
    options.threadType = threadInfo.currentThread.type
    options.nodeName = threadInfo.currentThread.name
    if options.threadType = "Task"
        publish(events.API_ERROR, options)
    else
        dispatch(events.APP_ERROR, options)
    end if
    return invalid
end function


sub registerControllers(controllers = [])
    if not rodash.isNonEmptyArray(controllers) then return
    if not top().isSubtype("Scene") then return

    for each controllerName in controllers
        updateObject = {}
        updateObject[controllerName] = createObject("roSGNode", controllerName)
        set(updateObject)
    end for
end sub


function runTask()
    if not rodash.isFunction(m.ord_taskFunction) then return invalid
    return exec(m.ord_taskFunction)
end function


sub setRole()
    componentRole = "Controller"

    if top().isSubtype("Group")
        componentRole = top().isSubtype("Scene") ? "Scene" : "View"
    else if top().isSubtype("Task")
        componentRole = "Task"
    else if top().isSubtype("ContentNode")
        componentRole = "Model"
    end if

    m.ord_role = componentRole
end sub


sub setUUID(node)
    if not rodash.isNode(node) then return
    node.addField("ord_uuid", "string", false)
    node.ord_uuid = createObject("roDeviceInfo").getRandomUUID()
end sub


' Helper functions.

function app()
    return m.global.getScene()
end function


function devMode()
    appIsDev = createObject("roAppInfo").isDev()
    devOverride = true
    return appIsDev ? devOverride : appIsDev
end function


function global()
    return getGlobalAA().global
end function


function top()
    return getGlobalAA().top
end function


function user()
    return get("UserController", app())
end function
