import "pkg:/source/roku_modules/rodash/rodash.brs"
import "pkg:/source/roku_modules/rokurequests/Requests.brs"

import "pkg:/components/constants.bs"

import "traits/animatable.bs"
import "traits/configable.bs"
import "traits/eventable.bs"
import "traits/focusable.bs"
import "traits/loadable.bs"
import "traits/positionable.bs"
import "traits/safeable.bs"
import "traits/stateable.bs"
import "traits/styleable.bs"


sub ord_init()
    setCreatedAt(top())
    setRole()

    interfaces = [Safeable, Stateable, Eventable, Styleable, Animatable, Focusable, Configable, Loadable, Positionable]

    m.ord_interfaces = {}

    for each interface in interfaces
        interfaceInstance = new interface()
        interfacePublicFunctions = interfaceInstance.publicFunctions ?? []
        for each functionName in interfacePublicFunctions
            m.ord_interfaces[functionName] = interfaceInstance
        end for
    end for

    if getGlobalAA().ord_role = "Task"
        top().functionName = "runTask"
    end if

    m.ord_initiated = true
end sub


function getNodeIdentifier(node)
    if not rodash.isNode(node) then return ""
    if rodash.isInvalid(node.ord_uuid) then setUUID(node)

    return node.ord_uuid
end function


function interfaceFunction(name = "", options = {})
    if rodash.isEmptyString(name) then return invalid
    if not rodash.isNonEmptyAA(options) then return invalid
    interface = m.ord_interfaces[name]
    if interface = invalid then return invalid
    return interface[name](options)
end function


function onError(e)
    'bs:disable-next-line
    ?"ERROR: " formatJSON(e)
    return invalid
end function


sub registerControllers(controllers = [])
    if not rodash.isNonEmptyArray(controllers) then return
    if not top().isSubtype("Scene") then return

    for each controllerName in controllers
        updateObject = {}
        updateObject[controllerName] = createObject("roSGNode", controllerName)
        set(updateObject)
    end for
end sub


function runTask()
    if not rodash.isFunction(m._ord_taskFunction) then return invalid
    return exec(m._ord_taskFunction)
end function


sub setCreatedAt(node)
    if not rodash.isNode(node) then return
    node.addField("createdAt", "longinteger", false)
    node.createdAt = rodash.now()
end sub


sub setRole()
    componentRole = "Controller"

    if top().isSubtype("Group")
        componentRole = top().isSubtype("Scene") ? "Scene" : "View"
    else if top().isSubtype("Task")
        componentRole = "Task"
    else if top().isSubtype("ContentNode")
        componentRole = "Model"
    end if

    m.ord_role = componentRole
end sub


sub setUUID(node)
    if not rodash.isNode(node) then return
    node.addField("ord_uuid", "string", false)
    node.ord_uuid = createObject("roDeviceInfo").getRandomUUID()
end sub


' Helper functions.

function app()
    return m.global.getScene()
end function


function devMode()
    return true
end function


function global()
    return getGlobalAA().global
end function


function top()
    return getGlobalAA().top
end function


function user()
    return get("UserController", app())
end function

