import "pkg:/source/roku_modules/rodash/rodash.brs"
import "pkg:/source/roku_modules/rokurequests/Requests.brs"

import "pkg:/components/constants.bs"

import "traits/animatable.bs"
import "traits/configable.bs"
import "traits/eventable.bs"
import "traits/focusable.bs"
import "traits/loadable.bs"
import "traits/safeable.bs"
import "traits/stateable.bs"
import "traits/styleable.bs"


sub ord_init()
    setCreatedAt(top())
    setRole()

    interfaces = [Safeable, Stateable, Eventable, Styleable, Animatable, Focusable, Configable, Loadable]

    m.ord_interfaces = {}

    for each interface in interfaces
        interfaceInstance = new interface()
        interfacePublicFunctions = interfaceInstance.publicFunctions ?? []
        for each functionName in interfacePublicFunctions
            m.ord_interfaces[functionName] = interfaceInstance
        end for
    end for

    if getGlobalAA().ord_role = "Task"
        top().functionName = "runTask"
    end if

    m.ord_initiated = true
end sub


sub setCreatedAt(node)
    if not rodash.isNode(node) then return
    node.addField("createdAt", "longinteger", false)
    node.createdAt = rodash.now()
end sub


sub setUUID(node)
    if not rodash.isNode(node) then return
    node.addField("ord_uuid", "string", false)
    node.ord_uuid = createObject("roDeviceInfo").getRandomUUID()
end sub


function getNodeIdentifier(node)
    if not rodash.isNode(node) then return ""
    if rodash.isInvalid(node.ord_uuid) then setUUID(node)

    return node.ord_uuid
end function


sub setRole()
    componentRole = "Controller"

    if m.top.isSubtype("Group")
        componentRole = m.top.isSubtype("Scene") ? "Scene" : "View"
    else if m.top.isSubtype("Task")
        componentRole = "Task"
    else if m.top.isSubtype("ContentNode")
        componentRole = "Model"
    end if

    m.ord_role = componentRole
end sub
