import "init.bs"

sub registerControllers(controllers = [])
    if not rodash.isNonEmptyArray(controllers) then return
    if not m.top.isSubtype("Scene") then return

    for each controllerName in controllers
        updateObject = {}
        updateObject[controllerName] = createObject("roSGNode", controllerName)
        set(updateObject)
    end for
end sub


function safeFunctions(options = {})
    interface = m.interfaceFunctions["safeFunctions"]
    if interface = invalid then return invalid
    return interface.safeFunctions(options)
end function


function devMode()
    return true
end function


function app()
    return m.global.getScene()
end function


function user()
    return get("UserController", app())
end function


function exec(func, options = {}, node = m.top, externalInterface = {})

    if not m.top.hasField("_ord_initiated") or not m.top._ord_initiated then ord_init()

    if not rodash.isNonEmptyAA(m.interfaceFunctions) then return invalid

    interface = m.interfaceFunctions["exec"]
    if interface = invalid then return invalid

    return interface.exec({
        func: func,
        options: options,
        node: node,
        externalInterface: externalInterface
    })
end function


function safeFunc(functionName = "")
    interface = m.interfaceFunctions["safeFunc"]
    if interface = invalid then return invalid
    return interface.safeFunc(functionName)
end function


function safeObserve(fieldName = "", callbackFunc = "", node = m.top, infoFields = [])
    interface = m.interfaceFunctions["safeObserve"]
    if interface = invalid then return invalid
    return interface.safeObserve(fieldName, callbackFunc, node, infoFields)
end function


function safeUnobserve(fieldName = "", node = m.top)
    interface = m.interfaceFunctions["safeUnobserve"]
    if interface = invalid then return invalid
    return interface.safeUnobserve(fieldName, node)
end function


function setTaskFunction(taskFunction = invalid)
    if not rodash.isFunction(taskFunction) then return invalid
    interface = m.interfaceFunctions["setTaskFunction"]
    return interface.setTaskFunction({ function: taskFunction })
end function



function get(options, node = m.top)
    interface = m.interfaceFunctions["get"]
    if interface = invalid then return invalid
    return interface.get(options, node)
end function


function set(options = {}, node = m.top)
    interface = m.interfaceFunctions["set"]
    if interface = invalid then return invalid
    return interface.set(options, node)
end function


function publish(name = "", options = {})
    interface = m.interfaceFunctions["publish"]
    if interface = invalid then return invalid
    return interface.publish({
        id: name,
        options: options
    })
end function


function subscribe(options)
    interface = m.interfaceFunctions["subscribe"]
    if interface = invalid then return invalid
    return interface.subscribe(options)
end function


function setStyles(options, node = m.top)
    interface = m.interfaceFunctions["setStyles"]
    if interface = invalid then return invalid
    return interface.setStyles(options, node)
end function


function addClass(className = "", node = m.top)
    interface = m.interfaceFunctions["addClass"]
    if interface = invalid then return invalid
    return interface.addClass({ class: className, node: node })
end function


function removeClass(className = "", node = m.top)
    interface = m.interfaceFunctions["removeClass"]
    if interface = invalid then return invalid
    return interface.removeClass({ class: className, node: node })
end function


function redrawStyles()
    interface = m.interfaceFunctions["redrawStyles"]
    if interface = invalid then return invalid
    return interface.redrawStyles()
end function


function styleHooks(options = {})
    interface = m.interfaceFunctions["styleHooks"]
    if interface = invalid then return invalid
    return interface.styleHooks(options)
end function


function animate(animation, options = {})
    interface = m.interfaceFunctions["animate"]
    if interface = invalid then return invalid
    return interface.animate(animation, options)
end function


function reverse(animation = "", options = {})
    interface = m.interfaceFunctions["reverse"]
    if interface = invalid then return invalid
    return interface.reverse(animation, options)
end function


function finishAnimation(id = "")
    interface = m.interfaceFunctions["reverse"]
    if interface = invalid then return invalid
    return interface.finishAnimation(id)
end function


function stopAnimation(id = "")
    interface = m.interfaceFunctions["stopAnimation"]
    if interface = invalid then return invalid
    return interface.stopAnimation(id)
end function


function removeAnimation(id = "")
    interface = m.interfaceFunctions["removeAnimation"]
    if interface = invalid then return invalid
    return interface.removeAnimation(id)
end function


function morph(morphObject = {}, sharedOptions = {})
    interface = m.interfaceFunctions["morph"]
    if interface = invalid then return invalid
    return interface.morph(morphObject, sharedOptions)
end function


function fadeIn(node = invalid, options = {})
    interface = m.interfaceFunctions["fadeIn"]
    if interface = invalid then return invalid
    return interface.fadeIn(node, options)
end function


function fadeOut(node = invalid, options = {})
    interface = m.interfaceFunctions["fadeOut"]
    if interface = invalid then return invalid
    return interface.fadeOut(node, options)
end function


function dispatch(eventId, options = {})
    interface = m.interfaceFunctions["dispatch"]
    if interface = invalid then return invalid
    return interface.dispatch({
        id: eventId,
        options: options
    })
end function


function setFocusMap(options = {})
    interface = m.interfaceFunctions["setFocusMap"]
    if interface = invalid then return invalid
    return interface.setFocusMap(options)
end function


function processFocus(key = "")
    interface = m.interfaceFunctions["processFocus"]
    if interface = invalid then return invalid
    return interface.processFocus(key)
end function


function waitToFocus(focusTarget)
    interface = m.interfaceFunctions["waitToFocus"]
    if interface = invalid then return invalid
    return interface.waitToFocus(focusTarget)
end function


function readyToFocus()
    interface = m.interfaceFunctions["readyToFocus"]
    if interface = invalid then return invalid
    return interface.readyToFocus()
end function


function setLoadable(options = {})
    interface = m.interfaceFunctions["setLoadable"]
    if interface = invalid then return invalid
    return interface.setLoadable(options)
end function


function applyDefaultFocus()
    interface = m.interfaceFunctions["applyDefaultFocus"]
    if interface = invalid then return invalid
    return interface.applyDefaultFocus()
end function


function setFocus(node)
    interface = m.interfaceFunctions["setFocus"]
    if interface = invalid then return invalid
    return interface.setFocus(node)
end function


function liveConfig(options = {}, node = top())
    interface = m.interfaceFunctions["liveConfig"]
    if interface = invalid then return invalid
    return interface.liveConfig(options, node)
end function


function top()
    return getGlobalAA().top
end function


function global()
    return getGlobalAA().global
end function


function runTask()
    if not rodash.isFunction(m._ord_taskFunction) then return invalid
    return exec(m._ord_taskFunction)
end function


sub onError(e)
    'bs:disable-next-line
    ?"ERROR: " formatJSON(e)
end sub


sub stackChildren(options = {})
    node = options.node ?? m.top
    children = node.getChildren(-1, 0)
    totalHeight = 0
    totalWidth = 0
    direction = options.direction ?? "horizontal"
    horizontal = direction = "horizontal"

    for each child in children
        if not child.isSubtype("Group") then continue for
        childMargins = quadrupleMargins(child.margin)

        topMargin = childMargins.top
        leftMargin = childMargins.left

        childHeight = getVisibleHeight(child)
        childWidth = getVisibleWidth(child)

        if horizontal
            if childWidth = 0 then continue for
            child.translation = [totalWidth + leftMargin, child.translation[1]]
            totalWidth += childWidth
        else
            if childHeight = 0 then continue for
            child.translation = [child.translation[0], totalHeight + topMargin]
            totalHeight += childHeight
        end if
    end for

    minWidth = node.minWidth ?? 0
    minHeight = node.minHeight ?? 0

    if horizontal
        node.width = totalWidth > minWidth ? totalWidth : minWidth
        node.height = node.boundingRect().height
    else
        node.height = totalHeight > minHeight ? totalHeight : minHeight
        node.width = node.boundingRect().width
    end if
end sub


function quadrupleMargins(margin)
    returnObj = {
        "left": 0,
        "top": 0,
        "right": 0,
        "bottom": 0
    }

    if margin = invalid then return returnObj

    if rodash.isNumber(margin) then margin = [margin]
    if rodash.isString(margin) then margin = [val(margin)]

    if margin.count() = 1
        returnObj["left"] = margin[0]
        returnObj["top"] = margin[0]
        returnObj["right"] = margin[0]
        returnObj["bottom"] = margin[0]
    else if margin.count() = 2 or margin.count() = 3
        returnObj["left"] = margin[0]
        returnObj["top"] = margin[1]
        returnObj["right"] = margin[0]
        returnObj["bottom"] = margin[1]
    else if margin.count() = 4
        returnObj["left"] = margin[3]
        returnObj["top"] = margin[0]
        returnObj["right"] = margin[1]
        returnObj["bottom"] = margin[2]
    end if

    return returnObj
end function


function getVisibleHeight(node)
    if not rodash.isNode(node) then return 0

    nodeHeight = 0
    clippingRect = node.clippingRect
    boundingRect = node.boundingRect()
    nodeMargins = quadrupleMargins(node.margin)

    if not node.visible then return 0
    if not rodash.isNonEmptyAA(clippingRect) then return 0

    if clippingRect.height > 0
        nodeHeight = clippingRect.height
    else if rodash.isNumber(node.height) and node.height > 0
        nodeHeight = node.height
    else if rodash.isNonEmptyAA(boundingRect)
        nodeHeight = boundingRect.height
    end if

    nodeHeight += nodeMargins.top
    nodeHeight += nodeMargins.bottom

    return nodeHeight
end function

function getVisibleWidth(node)
    if not rodash.isNode(node) then return 0

    nodeWidth = 0
    clippingRect = node.clippingRect
    boundingRect = node.boundingRect()
    nodeMargins = quadrupleMargins(node.margin)

    if not node.visible then return 0
    if not rodash.isNonEmptyAA(clippingRect) then return 0

    if clippingRect.width > 0
        nodeWidth = clippingRect.width
    else if rodash.isNumber(node.width) and node.width > 0
        nodeWidth = node.width
    else if rodash.isNonEmptyAA(boundingRect)
        nodeWidth = boundingRect.width
    end if

    nodeWidth += nodeMargins.left
    nodeWidth += nodeMargins.right

    return nodeWidth
end function
