import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub()
        loadList()
        safeObserve("focusedChild", onFocusedChildChange)
    end sub)
end sub


sub loadList()
    list = top().findNode("flushCarouselList")

    carouselModel = createObject("roSGNode", "FlushCarouselModel")
    carouselModel.rectConfig = {
        vertAlign: "bottom",
        clip: true,
        defaultVisibleIndex: 0,
        carouselType: "flushFocus",
        focusType: "floating",
        itemComponentName: "TestItem",
        visibleTiles: 14,
        wrap: true,
        bigSquare: [201, 300],
        smallSquare: [120, 180]
    }

    list.data = {
        content: carouselModel
    }

    m.list = list
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    m.list.setFocus(true)
end sub
