import "pkg:/components/constants.bs"

sub init()
    updateObjArray = []

    for each item in getItems()
        updateObject = { subtype: "ContentNode"}
        updateObject.append(item)
        updateObjArray.push(updateObject)
    end for

    m.top.update(updateObjArray, true)
end sub


function getItems() as object
    return [
        {
            iconText: Icons.search,
            title: "Search"
        },
        {
            iconText: Icons.genres,
            title: "Genres"
        },
        {
            iconText: Icons.favorites,
            title: "Favorites"
        },
        {
            iconText: Icons.watchlist,
            title: "Watchlist"
        }
    ]
end function
