import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options)
    end sub)
end sub


function getItems() as object
    return [
        {
            iconText: Icons.search,
            title: "Search"
        },
        {
            iconText: Icons.genres,
            title: "Genres"
        },
        {
            iconText: Icons.favorites,
            title: "Favorites"
        },
        {
            iconText: Icons.watchlist,
            title: "Watchlist"
        }
    ]
end function
