import "pkg:/components/_ord/wrappers.bs"


sub init()
    exec(sub(_options = {})
        subscribe({
            [events.APP_STARTED]: onAppStarted,
            [events.CATALOG_HERO_FOCUSED]: onCatalogHeroFocused,
            [events.CAROUSEL_ITEM_FOCUSED]: onCarouselItemFocused,
            [events.DETAILS_DATA_RECEIVED]: onScreenDataReceived,
            [events.GET_CATALOG_DATA]: getCatalogData,
            [events.GET_DETAILS_DATA]: getDetailsData,
            [events.GET_SIDEBAR]: getSidebar,
            [events.GET_TOPBAR]: getTopbar,
            [events.HERO_ITEM_FOCUSED]: updateBackgroundAssets,
            [events.NAVIGATE_TO]: navigateTo,
            [events.PAGINATE_CAROUSEL]: paginateCarousel,
            [events.PAGINATE_SCREEN]: getCatalogData,
            [events.SCREEN_DATA_RECEIVED]: [onScreenDataReceived],
            [events.SCROLL_GROUP_FOCUSED]: onScrollGroupFocused,
            [events.SHOW_CATALOG_UI]: showCatalogUI,
            [events.SHOW_DETAILS_UI]: showDetailsUI,
            [events.SIDEBAR_RECEIVED]: onSidebarReceived,
            [events.TOPBAR_RECEIVED]: onTopbarReceived
        })
    end sub)
end sub


sub onAppStarted(_options = {})
    dispatch(events.GET_SIDEBAR)
    dispatch(events.GET_TOPBAR)
end sub


sub onCarouselItemFocused(options = {})
    if not rodash.isNonEmptyAA(options) then return
    itemHeader = catalogHeader()
    if not rodash.isNode(itemHeader) then return
    itemHeader.data = options

    updateBackgroundAssets(options)
end sub


sub updateBackgroundAssets(options = {})
    if rodash.isEmpty(options) then return
    appBackground = background()
    if not rodash.isNode(appBackground) then return
    exec("updateAssets", options, background())
    content = options.content

    rodash.delay(sub(options = {})
        ' dispatch(events.PLAY_VIDEO, { content: options.content })
        dispatch(events.NAVIGATE_TO, { slug: `/details/${options.content.id}`, content: options.content })
    end sub, 1000, { content: content })
end sub


sub getCatalogData(options = {})
    if not rodash.isNonEmptyAA(options) then return
    slug = options.slug ?? ""
    screenId = options.screenId ?? ""
    collection = options.collection
    screenConfig = get(slug) ?? {}

    if not rodash.isNode(collection)
        documentId = screenConfig.documentId ?? ""
        collection = createObject("roSGNode", "Collection")
        collection.update({
            documentId: documentId,
            screenId: screenId,
            slug: slug
        }, true)
    end if

    collection.paginating = true

    screenConfig.collection = collection
    saveObject = {}
    saveObject[slug] = screenConfig
    set(saveObject)

    screenTask = createObject("roSGNode", "ScreenTask")
    screenTask.update({
        options: {
            collection: collection
        }
    }, true)

    screenTask.control = "RUN"
end sub


sub getDetailsData(options = {})
    if not rodash.isNonEmptyAA(options) then return
    slug = options.slug ?? ""
    screenId = options.screenId ?? ""
    content = options.content

    if not rodash.isNode(content)
        content = createObject("roSGNode", "ContentModel")
    end if

    content.update({
        screenId: screenId,
        slug: slug
    }, true)

    screenTask = createObject("roSGNode", "DetailsTask")
    screenTask.update({
        options: {
            content: content
        }
    }, true)

    screenTask.control = "RUN"
end sub


sub getSidebar(_options = {})
    sidebarTask = createObject("roSGNode", "SidebarTask")
    sidebarTask.control = "RUN"
end sub


sub getTopbar(_options = {})
    topbarTask = createObject("roSGNode", "TopbarTask")
    topbarTask.control = "RUN"
end sub


sub navigateTo(options = {})
    documentId = options.documentId
    slug = options.slug
    content = options.content

    screenConfig = get(slug) ?? {}
    screenConfig["documentId"] = documentId
    screenConfig["content"] = content

    saveObject = {}
    saveObject[slug] = screenConfig
    set(saveObject)

    exec("navigateTo", options, layout())
end sub


sub onCatalogHeroFocused(options = {})
    exec("showBackground", options, background())
    ' exec("hideHeaderImage", options, background())
end sub


sub onScrollGroupFocused(options = {})
    exec("hideBackground", options, background())
    ' exec("showHeaderImage", options, background())
end sub


sub onScreenDataReceived(options = {})
    if not rodash.isNonEmptyAA(options) then return

    screenModel = options.content
    if not rodash.isNode(screenModel) then return

    screenId = screenModel.screenId ?? ""
    if rodash.isEmpty(screenId) then return

    screen = layout().findNode(screenId)
    if not rodash.isNode(screen) then return

    if rodash.isEmpty(screen.data)
        screen.data = {
            content: screenModel
        }
    end if
end sub


sub showCatalogUI(_options = {})
    exec("showCatalogUi", {}, layout())
end sub


sub showDetailsUI(_options = {})
    exec("showDetailsUi", {}, layout())
end sub


sub onSidebarReceived(options = {})
    sidebar().data = options
end sub


sub onTopbarReceived(options = {})
    topbar().data = options
end sub


sub paginateCarousel(options = {})
    if not rodash.isNonEmptyAA(options) then return
    collection = options.collection
    collection.paginating = true

    carouselTask = createObject("roSGNode", "CarouselTask")

    carouselTask.update({
        options: {
            collection: collection
        }
    }, true)

    carouselTask.control = "RUN"
end sub


function background()
    return findNode("background")
end function


function catalogHeader()
    return findNode("catalogHeader")
end function


function layout()
    return findNode("layout")
end function


function sidebar()
    return findNode("sidebar")
end function


function topbar()
    return findNode("topbar")
end function


function findNode(nodeId)
    node = m[nodeId]
    if rodash.isInvalid(node) then node = app().findNode(nodeId)
    m[nodeId] = node
    return node
end function
