import "pkg:/components/_ord/wrappers.bs"


sub init()
    exec(sub(options = {})
        subscribe({
            [events.APP_STARTED]: onAppStarted,
            [events.GET_SCREEN_DATA]: getScreenData,
            [events.GET_SIDEBAR]: getSidebar,
            [events.GET_TOPBAR]: getTopbar,
            [events.NAVIGATE_TO]: navigateTo,
            [events.PAGINATE_CAROUSEL]: paginateCarousel,
            [events.SCREEN_DATA_RECEIVED]: onScreenDataReceived,
            [events.SIDEBAR_RECEIVED]: onSidebarReceived,
            [events.TOPBAR_RECEIVED]: onTopbarReceived
        })
    end sub)
end sub


sub onAppStarted(options = {})
    dispatch(events.GET_SIDEBAR)
    dispatch(events.GET_TOPBAR)
end sub


sub getScreenData(options = {})
    if not rodash.isNonEmptyAA(options) then return

    screenId = options.screenId
    slug = options.slug

    screenConfig = get(slug) ?? {}
    screenConfig.screenId = screenId

    screenVariables = screenConfig.variables ?? {}

    saveObject = {}
    saveObject[slug] = screenConfig
    set(saveObject)

    if rodash.isInvalid(m.screenTask) then m.screenTask = createObject("roSGNode", "ScreenTask")

    screenPagination = getScreenPagination(screenVariables)
    if not rodash.isNonEmptyAA(screenPagination) then return

    screenVariables.pagination = screenPagination
    m.screenTask.update({ screenVariables: screenVariables
    }, true)
    m.screenTask.control = "RUN"
end sub


function getScreenPagination(options = {})
    if not rodash.isNonEmptyAA(options) then return invalid

    paginationOptions = {}

    if rodash.isNonEmptyAA(options.pagination)

    else
        paginationOptions = "<%- o(CONFIG.Pagination.Initial) %>"
    end if

    return paginationOptions
end function


sub getSidebar(options = {})
    if rodash.isInvalid(m.sidebarTask) then m.sidebarTask = createObject("roSGNode", "SidebarTask")
    m.sidebarTask.control = "RUN"
end sub


sub getTopbar(options = {})
    if rodash.isInvalid(m.topbarTask) then m.topbarTask = createObject("roSGNode", "TopbarTask")
    m.topbarTask.control = "RUN"
end sub


sub navigateTo(options = {})
    ?"navigateTo " options

    documentId = options.documentId
    slug = options.slug

    screenConfig = get(slug) ?? {}
    screenVariables = screenConfig.variables ?? {}
    screenVariables.setModeCaseSensitive()
    screenVariables["documentId"] = documentId
    screenConfig.variables = screenVariables

    saveObject = {}
    saveObject[slug] = screenConfig
    set(saveObject)

    exec("navigateTo", options, layout())
end sub


sub onScreenDataReceived(options = {})
    if not rodash.isNonEmptyAA(options) then return

    data = options.content
    screenModel = data.getChild(0)
    slug = screenModel.slug ?? ""
    screenConfig = get(slug) ?? {}
    screenId = screenConfig.screenId
    screen = layout().findNode(screenId)
    if not rodash.isNode(screen) then return

    screenConfig.totalCount = screenModel.totalCount
    screen.data = {
        content: screenModel
    }

    screenModel.getChild(0).callFunc("testFunction")

    saveObject = {}
    saveObject[slug] = screenConfig
    set(saveObject)
end sub


sub onSidebarReceived(options = {})
    sidebar().data = options
end sub


sub onTopbarReceived(options = {})
    topbar().data = options
end sub


sub paginateCarousel(options = {})
    if not rodash.isNonEmptyAA(options) then return
    collection = options.collection
    paginationTask = createObject("roSGNode", "PaginationTask")

    paginationTask.update({
        options: {
            collection: collection
        }
    }, true)

    paginationTask.control = "RUN"
end sub


function layout()
    return findNode("layout")
end function


function sidebar()
    return findNode("sidebar")
end function


function topbar()
    return findNode("topbar")
end function


function findNode(nodeId)
    node = m[nodeId]
    if rodash.isInvalid(node) then node = app().findNode(nodeId)
    m[nodeId] = node
    return node
end function
