import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.videoControls = top().findNode("videoControls")
        m.video = top().findNode("video")
        m.video.enableUI = true
        m.video.notificationInterval = 1
        m.video.seekMode = "accurate"

        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)
        safeObserve("state", onVideoStateChange, m.video)
        safeObserve("position", onVideoPositionChange, m.video, ["duration"])

        setFocusMap({
            "default": m.videoControls,
            "videoControls": {
                "left": scrubLeft,
                "right": scrubRight,
                "up": showOverlay,
                "down": exitPlayer,
                "rewind": seekRewind,
                "fastforward": seekForward,
                "play": togglePlayback,
                "back": hideOverlay,
                "replay": restartPlayback
            }
        })

        set({
            overlayOpen: true
        })
    end sub)
end sub


sub onDataSet(options = {})
    if rodash.isEmpty(options) then return
    if not rodash.isNode(m.video) then return
    if not rodash.isNode(m.videoControls) then return

    data = options.data
    content = data.content
    playerModel = content.playerModel
    m.video.content = playerModel
    m.video.control = "play"
    m.videoControls.data = data
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub onVideoPositionChange(options = {})
    exec("onPositionChange", options, m.videoControls)
end sub


sub onVideoStateChange(options = {})
    if rodash.isEmpty(options) then return
    state = options.data
    if state = "playing"
        dispatch(events.VIDEO_PLAYING)
    else if state = "paused"
        dispatch(events.VIDEO_PAUSED)
    else if state = "buffering"
        dispatch(events.VIDEO_BUFFERING)
    else if state = "finished"
        dispatch(events.VIDEO_FINISHED)
    else if state = "error"
        dispatch(events.VIDEO_ERROR)
    end if
end sub


sub scrubLeft(options = {})
    if rodash.isEmpty(options) then return
end sub


sub scrubRight(options = {})
    if rodash.isEmpty(options) then return
end sub


sub hideOverlay(options = {})
    if not get("overlayOpen") then return
    fadeOut(m.videoControls)
    set({ overlayOpen: false })
end sub


sub showOverlay(options = {})
    if get("overlayOpen") then return
    fadeIn(m.videoControls)
    set({ overlayOpen: true })
end sub


sub exitPlayer(options = {})
    if rodash.isEmpty(options) then return
end sub


sub seekForward(options = {})
    if not rodash.isNode(m.video) then return
    ' m.video.control = "pause"
    m.video.seek = m.video.position + 30
end sub


sub seekRewind(options = {})
    if not rodash.isNode(m.video) then return
    m.video.seek = m.video.position - 30
end sub


sub togglePlayback(options = {})
    if not rodash.isNode(m.video) then return
    if m.video.state = "paused"
        m.video.control = "play"
    else if m.video.state = "playing"
        m.video.control = "pause"
    end if
end sub


sub restartPlayback(options = {})
    if not rodash.isNode(m.video) then return
    dispatch(events.VIDEO_RESTARTING)
    m.video.seek = 0
end sub


function onKeyEvent(key as string, press as boolean) as boolean
    return exec(function(options = {})
        if not options.press then return true
        handled = processFocus(options.key)
        ?"VideoPlayer onKeyEvent " options.key, handled
        return handled
    end function, { key: key, press: press })
end function
