import "pkg:/components/_ord/wrappers.bs"
import "bifTools.bs"

sub init()
    exec(sub(options = {})
        m.videoControls = top().findNode("videoControls")
        m.trickplay = top().findNode("trickplay")
        m.video = top().findNode("video")
        m.video.enableUI = true
        m.video.notificationInterval = 1
        m.video.seekMode = "accurate"

        m.overlayTimer = createObject("roSGNode", "Timer")
        m.overlayTimer.duration = 5
        safeObserve("fire", hideOverlay, m.overlayTimer)

        m.scrubTimer = createObject("roSGNode", "Timer")
        m.scrubTimer.duration = 3
        safeObserve("fire", onScrubTimerFired, m.scrubTimer)

        m.seekTimer = createObject("roSGNode", "Timer")
        m.seekTimer.duration = 0.5
        m.seekTimer.repeat = true
        safeObserve("fire", onSeekTimerFired, m.seekTimer)

        m.controls = top().findNode("controls")
        controlsConfig = "<%- o(CONFIG.DefaultControls) %>"
        m.controls.config = controlsConfig

        activeControlsConfig = "<%- o(CONFIG.ActiveControls) %>"

        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)
        safeObserve("state", onVideoStateChange, m.video)
        safeObserve("position", onVideoPositionChange, m.video, ["duration"])

        setFocusMap({
            "default": m.videoControls,
            "videoControls": {
                "left": [showOverlay, scrubLeft],
                "right": [showOverlay, scrubRight],
                "up": showOverlay,
                "down": exitPlayer,
                "ok": onSelection,
                "options": onOptions,
                "rewind": [showOverlay, seekRewind],
                "fastforward": [showOverlay, seekForward],
                "play": [showOverlay, togglePlayback],
                "back": onBackButton,
                "replay": [showOverlay, restartPlayback]
            }
        })

        set({
            activeControlsConfig: activeControlsConfig,
            controlsConfig: controlsConfig,
            scrubInterval: 10,
            scrubPosition: 0,
            seekDirection: 0,
            seeking: false,
            seekIntervals: [30, 60, 120],
            seekSpeed: 0,
            overlayOpen: true
        })
    end sub)
end sub


function onOptions(options = {})
    ?"onOptions "
    return false
end function


sub onDataSet(options = {})
    if rodash.isEmpty(options) then return
    if not rodash.isNode(m.video) then return
    if not rodash.isNode(m.videoControls) then return

    data = options.data
    content = data.content
    playerModel = content.playerModel
    m.video.content = playerModel
    m.video.control = "play"
    m.videoControls.data = data
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub onScrubTimerFired(options = {})
    if not rodash.isNode(m.trickplay) then return
    if not rodash.isNode(m.video) then return
    m.video.control = "resume"
    set({ scrubPosition: m.video.position })
    exec("hideTrickplay", {}, m.trickplay)
    resetControls()
end sub


sub onSeekTimerFired(options = {})
    if not rodash.isNode(m.seekTimer) then return
    if not rodash.isNode(m.video) then return
    seeking = get("seeking")
    if not seeking then return

    seekSpeed = get("seekSpeed")
    seekIntervals = get("seekIntervals") ?? []
    scrubPosition = get("scrubPosition") ?? m.video.position
    seekDirection = get("seekDirection")
    duration = m.video.duration

    nextPosition = scrubPosition + (seekIntervals[seekSpeed] * seekDirection)
    if nextPosition >= duration then nextPosition = duration

    set({ scrubPosition: nextPosition })
    sendTrickplayInfo({ trickplayPosition: nextPosition })

    if nextPosition = duration then m.seekTimer.control = "stop"
    if nextPosition <= 0 then m.seekTimer.control = "stop"

    updateControl({ controlId: "seekControl" })
end sub


sub onSelection(options = {})
    if not rodash.isNode(m.seekTimer) then return
    if not rodash.isNode(m.scrubTimer) then return

    scrubbing = m.scrubTimer.control = "start"
    seeking = get("seeking") ?? false

    if m.scrubTimer.control = "start" then m.scrubTimer.control = "stop"
    if m.seekTimer.control = "start" then m.seekTimer.control = "stop"

    if seeking or scrubbing
        exec("hideTrickplay", {}, m.trickplay)
        m.video.seek = get("scrubPosition")
        set({
            seekDirection: 0,
            seeking: false,
            seekSpeed: 0
        })
    else
        hideOverlay()
    end if
end sub


sub onVideoPositionChange(options = {})
    exec("onPositionChange", options, m.videoControls)
end sub


sub onVideoStateChange(options = {})
    if rodash.isEmpty(options) then return
    state = options.data
    if state = "playing"
        resetControls()
        dispatch(events.VIDEO_PLAYING)
    else if state = "paused"
        updateControl({ controlId: "playControl" })
        dispatch(events.VIDEO_PAUSED)
    else if state = "buffering"
        dispatch(events.VIDEO_BUFFERING)
    else if state = "finished"
        dispatch(events.VIDEO_FINISHED)
    else if state = "error"
        dispatch(events.VIDEO_ERROR)
    end if
end sub


sub performScrub(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.video) then return
    if not rodash.isNode(m.scrubTimer) then return
    if get("seeking") then return

    if m.video.state <> "playing" and m.video.state <> "paused" then return

    m.video.control = "pause"

    currentPosition = get("scrubPosition") ?? m.video.position
    positionDelta = options.positionDelta
    nextPosition = currentPosition + positionDelta

    set({ scrubPosition: nextPosition })
    m.scrubTimer.control = "start"
    sendTrickplayInfo({ trickplayPosition: nextPosition })
    updateControl({ controlId: "scrubControl" })
end sub


sub sendTrickplayInfo(options = {})
    if not rodash.isNonEmptyAA(options) then return
    if not rodash.isNode(m.trickplay) then return
    if not rodash.isNode(m.videoControls) then return

    options.trickplayFrame = getNearestFrameFromPosition(options.trickplayPosition ?? 0)
    options.duration = m.video.duration

    exec("setTrickplayInfo", options, m.trickplay)
    exec("setPositionLabel", { position: options.trickplayPosition }, m.videoControls)
end sub


sub scrubLeft(options = {})
    performScrub({ positionDelta: get("scrubInterval") * -1 })
end sub


sub scrubRight(options = {})
    performScrub({ positionDelta: get("scrubInterval")})
end sub


sub onBackButton(options = {})
    if get("seeking")
        onSeekCancel()
    else if get("overlayOpen")
        hideOverlay()
    end if
end sub


sub onSeekCancel()
    if not rodash.isNode(m.video) then return
    if not rodash.isNode(m.trickplay) then return
    if m.scrubTimer.control = "start" then m.scrubTimer.control = "stop"
    if m.seekTimer.control = "start" then m.seekTimer.control = "stop"
    m.video.control = "resume"
    set({
        seekDirection: 0,
        seeking: false,
        seekSpeed: 0
    })
    exec("hideTrickplay", {}, m.trickplay)
end sub


sub hideOverlay(options = {})
    if not get("overlayOpen") then return
    fadeOut(m.videoControls)
    set({ overlayOpen: false })
end sub


sub showOverlay(options = {})
    ?"showOverlay " get("overlayOpen")
    if get("overlayOpen") then return
    fadeIn(m.videoControls)
    set({ overlayOpen: true })
end sub


sub exitPlayer(options = {})
    if rodash.isEmpty(options) then return
end sub


sub startSeek()
    if not rodash.isNode(m.scrubTimer) then return
    if not rodash.isNode(m.seekTimer) then return
    if not rodash.isNode(m.video) then return
    if m.video.state <> "playing" and m.video.state <> "paused" then return

    m.video.control = "pause"

    if m.scrubTimer.control = "start" then m.scrubTimer.control = "stop"

    seekSpeed = get("seekSpeed")
    seeking = get("seeking")
    seekIntervals = get("seekIntervals") ?? []

    if seeking
        if seekSpeed > seekIntervals.count() - 1 then seekSpeed = seekIntervals.count() - 1
        set({ seekSpeed: seekSpeed })
    else
        set({
            scrubPosition: m.video.position,
            seeking: true
        })
        m.seekTimer.control = "start"
        onSeekTimerFired()
    end if
end sub


sub seekForward(options = {})
    seekSpeed = get("seekSpeed")
    seekDirection = get("seekDirection")

    if seekDirection = -1 then seekSpeed = 0
    if seekDirection = 1 then seekSpeed += 1

    set({ seekDirection: 1, seekSpeed: seekSpeed })
    startSeek()
end sub


sub seekRewind(options = {})
    seekSpeed = get("seekSpeed")
    seekDirection = get("seekDirection")
    if seekDirection = 1 then seekSpeed = 0
    if seekDirection = -1 then seekSpeed += 1

    set({ seekDirection: -1, seekSpeed: seekSpeed })
    startSeek()
end sub


sub togglePlayback(options = {})
    if not rodash.isNode(m.video) then return

    if get("seeking")
        onSelection()
        return
    end if

    if m.video.state = "paused"
        m.video.control = "resume"
    else if m.video.state = "playing"
        m.video.control = "pause"
    end if
end sub


sub restartPlayback(options = {})
    if not rodash.isNode(m.video) then return
    dispatch(events.VIDEO_RESTARTING)
    m.video.seek = 0
    updateControl({ controlId: "restartControl" })
end sub


sub resetControls(options = {})
    rodash.delay(sub(controls)
        if not rodash.isNode(controls) then return
        controls.config = get("controlsConfig")
    end sub, 500, m.controls)
end sub


sub updateControl(options = {})
    if not rodash.isNonEmptyAA(options) then return
    controlId = options.controlId ?? ""
    if rodash.isEmpty(controlId) then return

    activeControls = get("activeControlsConfig") ?? {}
    newControlConfig = activeControls[controlId]
    if not rodash.isNonEmptyAA(newControlConfig) then return

    newControl = {}
    newControl.append(newControlConfig)

    m.controls.config = [newControl]
end sub


function onKeyEvent(key as string, press as boolean) as boolean
    return exec(function(options = {})
        if not options.press then return true
        handled = processFocus(options.key)
        ?"VideoPlayer onKeyEvent " options.key, handled
        return handled
    end function, { key: key, press: press })
end function
