import "pkg:/components/_ord/wrappers.bs"

sub init()
    exec(sub(options = {})
        m.videoControls = top().findNode("videoControls")
        m.video = top().findNode("video")
        m.video.enableUI = false
        m.video.notificationInterval = 1
        safeFunctions({
            ' setStreamURL: setStreamURL
        })
        safeObserve("data", onDataSet)
        safeObserve("focusedChild", onFocusedChildChange)
        safeObserve("state", onVideoStateChange, m.video)
        safeObserve("position", onVideoPositionChange, m.video, ["duration"])
    end sub)
end sub


sub onDataSet(options = {})
    if rodash.isEmpty(options) then return
    data = options.data
    content = data.content
    playerModel = content.playerModel
    m.video.content = playerModel
    m.video.control = "play"
end sub


sub onFocusedChildChange(options = {})
    if not rodash.isNonEmptyAA(options) then return
    focusedChild = options.data
    if not rodash.isNode(focusedChild) then return
    if top().isSameNode(focusedChild) then applyDefaultFocus()
end sub


sub onVideoPositionChange(options = {})
    exec("onPositionChange", options, m.videoControls)
end sub


sub onVideoStateChange(options = {})
    if rodash.isEmpty(options) then return
    state = options.data
    if state = "playing"
        dispatch(events.VIDEO_PLAYING)
    end if
end sub
