import "pkg:/components/_ord/init.bs"

sub init()
    exec(sub(_options = {})
        m.gradient = top().findNode("gradient")
        m.list = top().findNode("sidebarList")
        safeFunctions({
            "setActiveSlug": setActiveSlug
        })
        setFocusMap({
            "onFocus": m.list
        })
        safeObserve("width", onListWidthChange, m.list)
        safeObserve("focusPercent", onFocusPercentChange, m.list)
        safeObserve("itemSelected", onItemSelected, m.list)

        safeObserve("data", onDataChange)
    end sub)
end sub


sub setActiveSlug(options = {})
    slug = options.slug ?? ""
    if rodash.isEmptyString(slug) then return

    itemModel = m.content.findNode(slug)
    selectedItemIndex = rodash.indexOf(m.content.getChildren(-1, 0), itemModel)
    if selectedItemIndex = m.list.itemSelected then return
    exec("setActiveItem", { activeIndex: selectedItemIndex }, m.list)
end sub


sub onDataChange(options = {})
    data = options.data
    content = data.content
    m.content = content

    liveConfig({ field: "config", keyPath: "Sidebar" }, content)
    if rodash.isNode(m.list) then m.list.data = data

    defaultSlug = content.defaultSlug
    setActiveSlug({ slug: defaultSlug })
end sub


sub onItemSelected(options = {})
    itemSelected = options.data
    itemModel = m.content.getChild(itemSelected)
    if not rodash.isNode(itemModel) then return

    dispatch(events.NAVIGATE_TO, {
        slug: itemModel.id,
        documentId: itemModel.documentId,
        outgoingRouteConfigOverrides: {
            suspendMode: "detach"
        }
    })
end sub


sub onFocusPercentChange(options = {})
    focusPercent = options.data ?? 0
    sidebarColor = top().openColor
    maxSidebarColorOpacity = 0.9
    top().color = addOpacityToHexColor(sidebarColor, focusPercent * maxSidebarColorOpacity)

    minGradientOpacity = 0.7
    m.gradient.opacity = minGradientOpacity + ((1 - minGradientOpacity) * focusPercent)
end sub


sub onListWidthChange(options = {})
    listWidth = options.data
    if not rodash.isNumber(listWidth) then return

    m.gradient.width = listWidth + 3
    top().width = listWidth
end sub


function addOpacityToHexColor(color = "", opacity = 0) as string
    opacityHex = right("0" + stri(cint(opacity * 255), 16), 2)

    return left(color, 7) + opacityHex
end function
